Repository fluentcms/FluentCMS, pull requests merged in 2023-12, with the labels that each got.

#267 262 develop edit mode for plugin
  src/FluentCMS.Web.UI/AppState.cs
  src/FluentCMS.Web.UI/Pages/Home.razor
  src/FluentCMS.Web.UI/Pages/PluginContainer.razor
  src/FluentCMS.Web.UI/Pages/Section.razor
  src/FluentCMS.Web.UI/Plugins/Counter/CounterEdit.razor
Labels: enhancement

#272 Issue on rendering dynamic layout by regex
  src/FluentCMS.Web.UI/FluentCMS.Web.UI.csproj
  src/FluentCMS.Web.UI/Pages/Home.razor
  src/FluentCMS.Web.UI/Pages/Home.razor.cs
  src/FluentCMS.Web.UI/Routes.razor
Labels: bug

#282 281 add layouts and sample auth pages
  src/FluentCMS.Web.UI/Layouts/AuthLayout.razor
  src/FluentCMS.Web.UI/Layouts/PanelLayout.razor
  src/FluentCMS.Web.UI/Pages/Auth/Login.razor
  src/FluentCMS.Web.UI/Pages/Auth/Register.razor
  src/FluentCMS.Web.UI/Pages/Auth/ResetPassword.razor
  src/FluentCMS.Web.UI/Pages/Home.razor
  src/FluentCMS.Web.UI/Pages/KitchenSink.razor
  src/FluentCMS.Web.UI/_Imports.razor
  src/FluentCMS.Web.UI/static/scss/app.css
  src/FluentCMS.Web.UI/static/scss/components/_layout.scss
  src/FluentCMS.Web.UI/static/tailwind.config.js
  src/FluentCMS.Web.UI/wwwroot/css/app.min.css
Labels: enhancement

#291 290 Add previews
  src/FluentCMS.Web.UI/Layouts/PanelLayout.razor
  src/FluentCMS.Web.UI/Pages/Home.razor
  src/FluentCMS.Web.UI/Previews/Pages/Auth/ForgotPassword.razor
  src/FluentCMS.Web.UI/Previews/Pages/Auth/Login.razor
  src/FluentCMS.Web.UI/Previews/Pages/Auth/Register.razor
  src/FluentCMS.Web.UI/Previews/Pages/Auth/ResetPassword.razor
  src/FluentCMS.Web.UI/Previews/Pages/CRUD/Details.razor
  src/FluentCMS.Web.UI/Previews/Pages/CRUD/Form.razor
  src/FluentCMS.Web.UI/Previews/Pages/CRUD/List.razor
  src/FluentCMS.Web.UI/Previews/Pages/CRUD/NativeExample.razor
  src/FluentCMS.Web.UI/Previews/Pages/Components.razor
  src/FluentCMS.Web.UI/wwwroot/css/app.min.css
Labels: enhancement

#299 298 enable dynamic layout rendering and remove html remarks from source
  src/FluentCMS.Api/Controllers/PageController.cs
  src/FluentCMS.Api/Controllers/UserController.cs
  src/FluentCMS.Api/DefaultData/DefaultData.cs
  src/FluentCMS.Api/DefaultData/DefaultDataLoaderExtensions.cs
  src/FluentCMS.Providers/Email/SmtpEmailProvider.cs
  src/FluentCMS.Repositories/Abstractions/IHostRepository.cs
  src/FluentCMS.Services/Identity/Stores/UserStore.cs
  src/FluentCMS.Shared/DictionaryStringObjectJsonConverter.cs
  src/FluentCMS.Shared/JsonContentConverter.cs
  src/FluentCMS.Shared/Models/Users/UserAuthenticateRequest.cs
  src/FluentCMS.Tests/DummyEntities/DummyEntity.cs
  src/FluentCMS.Tests/Services/PageService_Tests.cs
  src/FluentCMS.Tests/Services/SiteService_Tests.cs
  src/FluentCMS.Tests/Services/UserServiceTests.cs
  src/FluentCMS.Tests/TestApplicationContext.cs
  src/FluentCMS.Web.UI/ApiClients/ClientServiceExtensions.cs
  src/FluentCMS.Web.UI/DefaultData/AuthLayout.body.html
  src/FluentCMS.Web.UI/DefaultData/AuthLayout.head.html
  src/FluentCMS.Web.UI/DefaultData/AuthLayout.html
  src/FluentCMS.Web.UI/DefaultData/PanelLayout.body.html
  src/FluentCMS.Web.UI/DefaultData/PanelLayout.head.html
  src/FluentCMS.Web.UI/DefaultData/PanelLayout.html
  src/FluentCMS.Web.UI/DefaultData/default.json
  src/FluentCMS.Web.UI/DefaultData/layout.body.html
  src/FluentCMS.Web.UI/Layouts/PanelLayout.razor
  src/FluentCMS.Web.UI/Pages/Home.razor
  src/FluentCMS.Web.UI/Pages/Home.razor.cs
  src/FluentCMS.Web.UI/Pages/MainLayout.razor
  src/FluentCMS.Web.UI/Pages/PluginContainer.razor
  src/FluentCMS.Web.UI/Plugins/Admin/Auth/ForgotPasswordViewPlugin.razor
  src/FluentCMS.Web.UI/Plugins/Admin/Auth/LoginViewPlugin.razor
  src/FluentCMS.Web.UI/Plugins/Admin/Auth/RegisterViewPlugin.razor
  src/FluentCMS.Web.UI/Plugins/Admin/Auth/ResetPasswordViewPlugin.razor
  src/FluentCMS.Web.UI/Plugins/General/Counter/CounterEditPlugin.razor
  src/FluentCMS.Web.UI/Plugins/General/Counter/CounterViewPlugin.razor
  src/FluentCMS.Web.UI/Plugins/General/HelloWorld/HelloWorldEditPlugin.razor
  src/FluentCMS.Web.UI/Plugins/General/HelloWorld/HelloWorldViewPlugin.razor
  src/FluentCMS.Web.UI/Plugins/General/TextHtml/TextHtmlEditPlugin.razor
  src/FluentCMS.Web.UI/Plugins/General/TextHtml/TextHtmlViewPlugin.razor
  src/FluentCMS.Web.UI/Previews/Pages/Auth/ForgotPassword.razor
  src/FluentCMS.Web.UI/Previews/Pages/Auth/Login.razor
  src/FluentCMS.Web.UI/Previews/Pages/Auth/Register.razor
  src/FluentCMS.Web.UI/Previews/Pages/Auth/ResetPassword.razor
  src/FluentCMS.Web.UI/Program.cs
  src/FluentCMS.Web.UI/Routes.razor
Labels: enhancement

#301 300 razor application level component cleanup
  src/FluentCMS.Web.UI/Components/Application/PluginContainer.razor
  src/FluentCMS.Web.UI/Components/Application/Section.razor
  src/FluentCMS.Web.UI/Pages/BasePage.cs
  src/FluentCMS.Web.UI/Pages/Home.razor
  src/FluentCMS.Web.UI/Pages/Home.razor.cs
  src/FluentCMS.Web.UI/_Imports.razor
Labels: enhancement

#303 #302 major refactor on AppState (not completed)
  src/FluentCMS.Api/Controllers/PluginContentController.cs
  src/FluentCMS.Web.UI/ApiClients/BaseClient.cs
  src/FluentCMS.Web.UI/ApiClients/ClientServiceExtensions.cs
  src/FluentCMS.Web.UI/ApiClients/PluginContentClient.cs
  src/FluentCMS.Web.UI/App.razor
  src/FluentCMS.Web.UI/Components/Application/BaseAppComponent.cs
  src/FluentCMS.Web.UI/Components/Application/BasePluginComponent.cs
  src/FluentCMS.Web.UI/Components/Application/PluginContainer.razor
  src/FluentCMS.Web.UI/Components/Application/PluginContainer.razor.cs
  src/FluentCMS.Web.UI/Components/Application/Section.razor
  src/FluentCMS.Web.UI/Components/Application/Section.razor.cs
  src/FluentCMS.Web.UI/DefaultData/default.json
  src/FluentCMS.Web.UI/Pages/BasePage.cs
  src/FluentCMS.Web.UI/Pages/Home.razor
  src/FluentCMS.Web.UI/Plugins/General/Counter/CounterViewPlugin.razor
  src/FluentCMS.Web.UI/Plugins/General/TextHtml/TextHtmlContent.cs
  src/FluentCMS.Web.UI/Plugins/General/TextHtml/TextHtmlEditPlugin.razor
  src/FluentCMS.Web.UI/Plugins/General/TextHtml/TextHtmlViewPlugin.razor
  src/FluentCMS.Web.UI/Program.cs
  src/FluentCMS.Web.UI/Routes.razor
  src/FluentCMS.Web.UI/Services/AppState.cs
  src/FluentCMS.Web.UI/Services/AppStateService.cs
  src/FluentCMS.Web.UI/Services/UIServiceExtensions.cs
  src/FluentCMS.Web.UI/UIServiceExtensions.cs
Labels: enhancement, plugin

#322 #321 Add Icon component
  src/FluentCMS.Web.UI/Components/Core/Alert.razor
  src/FluentCMS.Web.UI/Components/Core/Icon.razor
  src/FluentCMS.Web.UI/Components/Enums/ColorEnum.cs
  src/FluentCMS.Web.UI/Components/Enums/IconNameEnum.cs
  src/FluentCMS.Web.UI/Components/Enums/SizeEnum.cs
  src/FluentCMS.Web.UI/Previews/Pages/Components.razor
  src/FluentCMS.Web.UI/Program.cs
  src/FluentCMS.Web.UI/Resources/Icons.cs
  src/FluentCMS.Web.UI/Resources/Icons.resx
  src/FluentCMS.Web.UI/_Imports.razor
  src/FluentCMS.Web.UI/static/scss/App.scss
  src/FluentCMS.Web.UI/static/scss/app.css
  src/FluentCMS.Web.UI/static/scss/app.css.map
  src/FluentCMS.Web.UI/static/scss/components/_icon.scss
  src/FluentCMS.Web.UI/wwwroot/css/app.min.css
Labels: enhancement

#325 314 add badge component
  src/FluentCMS.Web.UI/Components/Core/Badge.razor
  src/FluentCMS.Web.UI/Previews/Pages/Components.razor
  src/FluentCMS.Web.UI/static/scss/App.scss
  src/FluentCMS.Web.UI/static/scss/app.css
  src/FluentCMS.Web.UI/static/scss/app.css.map
  src/FluentCMS.Web.UI/static/scss/components/_badge.scss
  src/FluentCMS.Web.UI/wwwroot/css/app.min.css
Labels: enhancement

#324 #323 Add Button component
  src/FluentCMS.Web.UI/Components/Core/Button.razor
  src/FluentCMS.Web.UI/Components/Enums/ButtonTypeEnum.cs
  src/FluentCMS.Web.UI/Components/Enums/IconNameEnum.cs
  src/FluentCMS.Web.UI/Pages/Pages/PageEdit.razor
  src/FluentCMS.Web.UI/Pages/Pages/PageList.razor
  src/FluentCMS.Web.UI/Pages/Sites/SiteEdit.razor
  src/FluentCMS.Web.UI/Pages/Sites/SiteList.razor
  src/FluentCMS.Web.UI/Pages/Users/RoleEdit.razor
  src/FluentCMS.Web.UI/Pages/Users/UserEdit.razor
  src/FluentCMS.Web.UI/Plugins/General/TextHtml/TextHtmlEditPlugin.razor
  src/FluentCMS.Web.UI/Previews/Pages/Components.razor
  src/FluentCMS.Web.UI/static/scss/app.css
  src/FluentCMS.Web.UI/static/scss/app.css.map
  src/FluentCMS.Web.UI/static/scss/components/_button.scss
  src/FluentCMS.Web.UI/wwwroot/css/app.min.css
Labels: enhancement

#320 #249 Add Base Component
  src/FluentCMS.Shared/Extensions/StringExtensions.cs
  src/FluentCMS.Web.UI/Components/Attributes/CssPropertyAttribute.cs
  src/FluentCMS.Web.UI/Components/Core/Alert.razor
  src/FluentCMS.Web.UI/Components/Core/Badge.razor
  src/FluentCMS.Web.UI/Components/Core/Base/BaseComponent.cs
  src/FluentCMS.Web.UI/Components/Core/Base/BaseComponentHelpers.cs
  src/FluentCMS.Web.UI/Components/Core/Base/UISettings.cs
  src/FluentCMS.Web.UI/Components/Core/Button.razor
  src/FluentCMS.Web.UI/Components/Core/Icon.razor
  src/FluentCMS.Web.UI/Components/Enums/ButtonTypeEnum.cs
  src/FluentCMS.Web.UI/Components/Enums/ColorEnum.cs
  src/FluentCMS.Web.UI/Components/Enums/IconNameEnum.cs
  src/FluentCMS.Web.UI/Components/Enums/SizeEnum.cs
  src/FluentCMS.Web.UI/Pages/Pages/PageEdit.razor
  src/FluentCMS.Web.UI/Pages/Pages/PageList.razor
  src/FluentCMS.Web.UI/Pages/Sites/SiteEdit.razor
  src/FluentCMS.Web.UI/Pages/Sites/SiteList.razor
  src/FluentCMS.Web.UI/Pages/Users/RoleEdit.razor
  src/FluentCMS.Web.UI/Pages/Users/UserEdit.razor
  src/FluentCMS.Web.UI/Plugins/General/TextHtml/TextHtmlEditPlugin.razor
  src/FluentCMS.Web.UI/Previews/Pages/Components.razor
  src/FluentCMS.Web.UI/Program.cs
  src/FluentCMS.Web.UI/Resources/Icons.cs
  src/FluentCMS.Web.UI/Resources/Icons.resx
  src/FluentCMS.Web.UI/_Imports.razor
  src/FluentCMS.Web.UI/static/scss/App.scss
  src/FluentCMS.Web.UI/static/scss/app.css
  src/FluentCMS.Web.UI/static/scss/app.css.map
  src/FluentCMS.Web.UI/static/scss/components/_badge.scss
  src/FluentCMS.Web.UI/static/scss/components/_button.scss
  src/FluentCMS.Web.UI/static/scss/components/_icon.scss
  src/FluentCMS.Web.UI/wwwroot/css/app.min.css
Labels: enhancement

#327 306 text html refactor 1
  src/FluentCMS.Api/Controllers/ContentController.cs
  src/FluentCMS.Api/Controllers/PluginContentController.cs
  src/FluentCMS.Entities/Helpers.cs
  src/FluentCMS.Repositories/MongoDB/PluginContentRepository.cs
  src/FluentCMS.Repositories/MongoDb/ContentRepository.cs
  src/FluentCMS.Services/ContentService.cs
  src/FluentCMS.Services/PluginContentService.cs
  src/FluentCMS.Shared/Exceptions/ExceptionCodes.cs
  src/FluentCMS.Shared/JsonContentConverter.cs
  src/FluentCMS.Shared/Models/ApiPagingResult.cs
  src/FluentCMS.Web.UI/ApiClients/BaseClient.cs
  src/FluentCMS.Web.UI/ApiClients/ContentClient.cs
  src/FluentCMS.Web.UI/ApiClients/PageClient.cs
  src/FluentCMS.Web.UI/ApiClients/PluginContentClient.cs
  src/FluentCMS.Web.UI/ApiClients/SiteClient.cs
  src/FluentCMS.Web.UI/Components/Application/BaseAppComponent.cs
  src/FluentCMS.Web.UI/Components/Application/BasePage.cs
  src/FluentCMS.Web.UI/Components/Application/BasePluginComponent.cs
  src/FluentCMS.Web.UI/Components/Application/PluginContainer.razor
  src/FluentCMS.Web.UI/Components/Application/PluginContainer.razor.cs
  src/FluentCMS.Web.UI/Components/Application/Section.razor
  src/FluentCMS.Web.UI/Components/Application/Section.razor.cs
  src/FluentCMS.Web.UI/Pages/Home.razor
  src/FluentCMS.Web.UI/Pages/KitchenSink.razor
  src/FluentCMS.Web.UI/Plugins/General/Counter/CounterEditPlugin.razor
  src/FluentCMS.Web.UI/Plugins/General/Counter/CounterViewPlugin.razor
  src/FluentCMS.Web.UI/Plugins/General/HelloWorld/HelloWorldContent.cs
  src/FluentCMS.Web.UI/Plugins/General/HelloWorld/HelloWorldEditPlugin.razor
  src/FluentCMS.Web.UI/Plugins/General/HelloWorld/HelloWorldViewPlugin.razor
  src/FluentCMS.Web.UI/Plugins/General/TextHtml/TextHtmlContent.cs
  src/FluentCMS.Web.UI/Plugins/General/TextHtml/TextHtmlEditPlugin.razor
  src/FluentCMS.Web.UI/Plugins/General/TextHtml/TextHtmlViewPlugin.razor
  src/FluentCMS.Web.UI/Routes.razor
  src/FluentCMS.Web.UI/Services/AppState.cs
  src/FluentCMS.Web.UI/Services/AppStateService.cs
  src/FluentCMS.Web.UI/Services/UIServiceExtensions.cs
Labels: bug, enhancement

#329 #328 Button type removed, code formatting
  src/FluentCMS.Repositories/MongoDB/PluginContentRepository.cs
  src/FluentCMS.Web.UI/Plugins/General/HelloWorld/HelloWorldEditPlugin.razor
Labels: bug

#332 330 develop contenttype builder api
  src/FluentCMS.Api/Controllers/ContentTypeController.cs
  src/FluentCMS.Api/Controllers/PageController.cs
  src/FluentCMS.Entities/Content.cs
  src/FluentCMS.Entities/ContentType.cs
  src/FluentCMS.Entities/ContentTypeField.cs
  src/FluentCMS.Repositories/Abstractions/IContentTypeRepository.cs
  src/FluentCMS.Repositories/MongoDB/ContentTypeRepository.cs
  src/FluentCMS.Repositories/MongoDB/ServiceExtensions.cs
  src/FluentCMS.Services/ContentTypeService.cs
  src/FluentCMS.Shared/Exceptions/ExceptionCodes.cs
Labels: enhancement

#339 #338 TextHtml plugin cleanup
  src/FluentCMS.Web.UI/Plugins/General/TextHtml/TextHtmlEditPlugin.razor
Labels: enhancement

#345 fix component styles
  src/FluentCMS.Web.UI/App.razor
  src/FluentCMS.Web.UI/Layouts/PanelLayout.razor
  src/FluentCMS.Web.UI/Previews/Pages/Components.razor
Labels: enhancement

#354 #353auth plugin's issue resolved
  src/FluentCMS.Web.UI/Plugins/Admin/Auth/ForgotPasswordViewPlugin.razor
  src/FluentCMS.Web.UI/Plugins/Admin/Auth/LoginViewPlugin.razor
  src/FluentCMS.Web.UI/Plugins/Admin/Auth/RegisterViewPlugin.razor
  src/FluentCMS.Web.UI/Plugins/Admin/Auth/ResetPasswordViewPlugin.razor
Labels: bug

#355 #313 extract auth layout and update auth plugins
  src/FluentCMS.Web.UI/DefaultData/AuthLayout.body.html
  src/FluentCMS.Web.UI/Plugins/Admin/Auth/ForgotPasswordViewPlugin.razor
  src/FluentCMS.Web.UI/Plugins/Admin/Auth/LoginViewPlugin.razor
  src/FluentCMS.Web.UI/Plugins/Admin/Auth/RegisterViewPlugin.razor
  src/FluentCMS.Web.UI/Plugins/Admin/Auth/ResetPasswordViewPlugin.razor
Labels: enhancement

#351 #350 Add checkbox and InputBase components
  src/FluentCMS.Web.UI/Components/Core/Base/InputBaseComponent.cs
  src/FluentCMS.Web.UI/Components/Core/Form/Checkbox.razor
  src/FluentCMS.Web.UI/Previews/Pages/Components.razor
  src/FluentCMS.Web.UI/static/scss/components/_checkbox.scss
Labels: enhancement

#362 352 testing the usage of nswaggen app to generate api client layer to be used in blazor app
  src/FluentCMS.Api/Models/ApiPagingResult.cs
  src/FluentCMS.Api/Models/ApiResult.cs
  src/FluentCMS.Api/Models/BooleanResponse.cs
  src/FluentCMS.Api/Models/Error.cs
  src/FluentCMS.Api/Models/Host/HostResponse.cs
  src/FluentCMS.Api/Models/Host/HostUpdateRequest.cs
  src/FluentCMS.Api/Models/IdRequest.cs
  src/FluentCMS.Api/Models/Pages/PageCreateRequest.cs
  src/FluentCMS.Api/Models/Pages/PageResponse.cs
  src/FluentCMS.Api/Models/Pages/PageSearchRequest.cs
  src/FluentCMS.Api/Models/Pages/PageUpdateRequest.cs
  src/FluentCMS.Api/Models/PagingRequest.cs
  src/FluentCMS.Api/Models/PluginResponse.cs
  src/FluentCMS.Api/Models/Roles/RoleCreateRequest.cs
  src/FluentCMS.Api/Models/Roles/RoleDto.cs
  src/FluentCMS.Api/Models/Roles/RoleResponse.cs
  src/FluentCMS.Api/Models/Roles/RoleUpdateRequest.cs
  src/FluentCMS.Api/Models/Roles/RolesResponse.cs
  src/FluentCMS.Api/Models/SiteIdRequest.cs
  src/FluentCMS.Api/Models/Sites/SiteCreateRequest.cs
  src/FluentCMS.Api/Models/Sites/SiteResponse.cs
  src/FluentCMS.Api/Models/Sites/SiteUpdateRequest.cs
  src/FluentCMS.Api/Models/Users/RoleSearchRequest.cs
  src/FluentCMS.Api/Models/Users/UserAuthenticateDto.cs
  src/FluentCMS.Api/Models/Users/UserAuthenticateRequest.cs
  src/FluentCMS.Api/Models/Users/UserChangePasswordRequest.cs
  src/FluentCMS.Api/Models/Users/UserCreateRequest.cs
  src/FluentCMS.Api/Models/Users/UserDto.cs
  src/FluentCMS.Api/Models/Users/UserRegisterRequest.cs
  src/FluentCMS.Api/Models/Users/UserSearchRequest.cs
  src/FluentCMS.Api/Models/Users/UserUpdateRequest.cs
  src/FluentCMS.Web.UI/ApiClients/BaseClient.cs
  src/FluentCMS.Web.UI/ApiClients/ClientServiceExtensions.cs
  src/FluentCMS.Web.UI/ApiClients/ContentClient.cs
  src/FluentCMS.Web.UI/ApiClients/GeneratedApiClients.cs
  src/FluentCMS.Web.UI/ApiClients/HostClient.cs
  src/FluentCMS.Web.UI/ApiClients/IApiClient.cs
  src/FluentCMS.Web.UI/ApiClients/PageClient.cs
  src/FluentCMS.Web.UI/ApiClients/PluginContentClient.cs
  src/FluentCMS.Web.UI/ApiClients/SiteClient.cs
  src/FluentCMS.Web.UI/ApiClients/config.nswag
  src/FluentCMS.Web.UI/Components/Application/BasePluginComponent.cs
  src/FluentCMS.Web.UI/Pages/Default.razor
  src/FluentCMS.Web.UI/Pages/Default.razor.cs
  src/FluentCMS.Web.UI/Pages/Pages/PageEdit.razor
  src/FluentCMS.Web.UI/Pages/Pages/PageList.razor
  src/FluentCMS.Web.UI/Pages/Sites/SiteEdit.razor
  src/FluentCMS.Web.UI/Pages/Sites/SiteList.razor
  src/FluentCMS.Web.UI/Pages/Users/RoleEdit.razor
  src/FluentCMS.Web.UI/Pages/Users/RoleList.razor
  src/FluentCMS.Web.UI/Pages/Users/UserEdit.razor
  src/FluentCMS.Web.UI/Pages/Users/UserList.razor
  src/FluentCMS.Web.UI/Plugins/General/HelloWorld/HelloWorldEditPlugin.razor
  src/FluentCMS.Web.UI/Plugins/General/TextHtml/TextHtmlContent.cs
  src/FluentCMS.Web.UI/Plugins/General/TextHtml/TextHtmlEditPlugin.razor
  src/FluentCMS.Web.UI/Plugins/General/TextHtml/TextHtmlViewPlugin.razor
  src/FluentCMS.Web.UI/Services/AppState.cs
  src/FluentCMS.Web.UI/Services/AppStateService.cs
  src/FluentCMS.Web.UI/Services/UIServiceExtensions.cs
  src/FluentCMS.Web.UI/_Imports.razor
Labels: enhancement

#356 Fix styles of component examples page
  src/FluentCMS.Web.UI/Previews/Pages/Components.razor
Labels: enhancement

#385 #384 Identity store cleanup
  src/FluentCMS.Services/Identity/Stores/UserStore.cs
  src/FluentCMS.Services/Identity/Stores/UserStore_IQueryableUserStore.cs
  src/FluentCMS.Services/Identity/Stores/UserStore_IUserAuthenticationTokenStore.cs
  src/FluentCMS.Services/Identity/Stores/UserStore_IUserClaimStore.cs
  src/FluentCMS.Services/Identity/Stores/UserStore_IUserEmailStore.cs
  src/FluentCMS.Services/Identity/Stores/UserStore_IUserLoginStore.cs
  src/FluentCMS.Services/Identity/Stores/UserStore_IUserRoleStore.cs
Labels: enhancement

#387 386 repository layer code cleanup and xml documentation
  src/FluentCMS.Repositories/Abstractions/IAuditEntityRepository.cs
  src/FluentCMS.Repositories/Abstractions/IEntityRepository.cs
  src/FluentCMS.Repositories/Abstractions/ISiteAssociatedRepository.cs
  src/FluentCMS.Repositories/MongoDB/AuditEntityRepository.cs
  src/FluentCMS.Repositories/MongoDB/EntityRepository.cs
  src/FluentCMS.Repositories/MongoDB/HostRepository.cs
  src/FluentCMS.Repositories/MongoDB/LayoutRepository.cs
  src/FluentCMS.Repositories/MongoDB/PageRepository.cs
  src/FluentCMS.Repositories/MongoDB/PermissionRepository.cs
  src/FluentCMS.Repositories/MongoDB/PluginDefinitionRepository.cs
  src/FluentCMS.Repositories/MongoDB/PluginRepository.cs
  src/FluentCMS.Repositories/MongoDB/RoleRepository.cs
  src/FluentCMS.Repositories/MongoDB/ServiceExtensions.cs
  src/FluentCMS.Repositories/MongoDB/SiteAssociatedRepository.cs
  src/FluentCMS.Repositories/MongoDB/SiteRepository.cs
  src/FluentCMS.Repositories/MongoDB/UserRepository.cs
  src/FluentCMS.Repositories/MongoDb/MongoDbContext.cs
  src/FluentCMS.Repositories/MongoDb/MongoDbOptions.cs
Labels: documentation, enhancement

#390 388 coding enhancement for service layer
  src/FluentCMS.Api/ApiApplicationContext.cs
  src/FluentCMS.Providers/Identity/UserTokenProvider.cs
  src/FluentCMS.Services/Identity/IdentityResultExtensions.cs
  src/FluentCMS.Shared/IApplicationContext.cs
Labels: documentation, enhancement

#391 #389 removing Current from IApplicationContext
  src/FluentCMS.Api/ApiApplicationContext.cs
  src/FluentCMS.Api/DefaultData/DefaultDataLoaderExtensions.cs
  src/FluentCMS.Repositories/MongoDB/AuditEntityRepository.cs
  src/FluentCMS.Repositories/MongoDB/HostRepository.cs
  src/FluentCMS.Repositories/MongoDb/ContentRepository.cs
  src/FluentCMS.Services/AuthorizationProvider.cs
  src/FluentCMS.Services/HostService.cs
  src/FluentCMS.Services/UserService.cs
  src/FluentCMS.Shared/IApplicationContext.cs
  src/FluentCMS.Web.UI/Program.cs
Labels: enhancement

#393 392 simplify response models in api
  src/FluentCMS.Api/Controllers/ContentController.cs
  src/FluentCMS.Api/Controllers/ContentTypeController.cs
  src/FluentCMS.Api/Controllers/HostController.cs
  src/FluentCMS.Api/Controllers/PluginContentController.cs
  src/FluentCMS.Api/Controllers/RoleController.cs
  src/FluentCMS.Api/FluentCMS.Api.csproj
  src/FluentCMS.Api/MappingProfiles.cs
  src/FluentCMS.Api/Models/ApiPagingResult.cs
  src/FluentCMS.Api/Models/ApiResult.cs
  src/FluentCMS.Api/Models/BooleanResponse.cs
  src/FluentCMS.Api/Models/Error.cs
  src/FluentCMS.Api/Models/Host/HostResponse.cs
  src/FluentCMS.Api/Models/Host/HostUpdateRequest.cs
  src/FluentCMS.Api/Models/IdRequest.cs
  src/FluentCMS.Api/Models/PagingRequest.cs
  src/FluentCMS.Api/Models/Roles/RoleCreateRequest.cs
  src/FluentCMS.Api/Models/Roles/RoleDto.cs
  src/FluentCMS.Api/Models/Roles/RoleResponse.cs
  src/FluentCMS.Api/Models/Roles/RoleUpdateRequest.cs
  src/FluentCMS.Api/Models/Roles/RolesResponse.cs
  src/FluentCMS.Api/Models/SiteIdRequest.cs
  src/FluentCMS.Api/Models/Sites/SiteCreateRequest.cs
  src/FluentCMS.Api/Models/Sites/SiteResponse.cs
  src/FluentCMS.Api/Models/Sites/SiteUpdateRequest.cs
  src/FluentCMS.Api/Models/Users/UserChangePasswordRequest.cs
  src/FluentCMS.Api/Models/Users/UserDetailResponse.cs
  src/FluentCMS.Api/Models/Users/UserLoginRequest.cs
  src/FluentCMS.Api/Models/Users/UserLoginResponse.cs
  src/FluentCMS.Api/Models/Users/UserRegisterRequest.cs
  src/FluentCMS.Api/Models/Users/UserUpdateRequest.cs
  src/FluentCMS.Api/SwaggerServiceExtensions.cs
  src/FluentCMS.Entities/FluentCMS.Entities.csproj
  src/FluentCMS.Web.UI/ApiClients/GeneratedApiClients.cs
  src/FluentCMS.Web.UI/ApiClients/config.nswag
  src/FluentCMS.Web.UI/FluentCMS.Web.UI.csproj
  src/FluentCMS.Web.UI/Plugins/General/HelloWorld/HelloWorldEditPlugin.razor
Labels: documentation

#368 #317 add input component
  src/FluentCMS.Web.UI/Components/Core/Base/InputBaseComponent.cs
  src/FluentCMS.Web.UI/Components/Core/Form/Input.razor
  src/FluentCMS.Web.UI/Previews/Pages/Components.razor
  src/FluentCMS.Web.UI/static/scss/components/_input.scss
Labels: enhancement

#370 #347 add name of icon in error message
  src/FluentCMS.Web.UI/Components/Core/Icon.razor
Labels: enhancement

#371 #349 add size css for button
  src/FluentCMS.Web.UI/Previews/Pages/Components.razor
  src/FluentCMS.Web.UI/static/scss/components/_button.scss
Labels: enhancement

#403 402 content should not inherit from dictionarystring object directly it should have a property for the content
  src/FluentCMS.Api/Controllers/BaseController.cs
  src/FluentCMS.Api/Controllers/ContentController.cs
  src/FluentCMS.Api/Controllers/PluginContentController.cs
  src/FluentCMS.Api/Controllers/PluginController.cs
  src/FluentCMS.Api/Models/Content/ContentCreateRequest.cs
  src/FluentCMS.Api/Models/Content/ContentUpdateRequest.cs
  src/FluentCMS.Api/Models/PluginContent/PluginContentCreateRequest.cs
  src/FluentCMS.Api/Models/PluginContent/PluginContentUpdateRequest.cs
  src/FluentCMS.Entities/Content.cs
  src/FluentCMS.Entities/Helpers.cs
  src/FluentCMS.Repositories/Abstractions/IContentRepository.cs
  src/FluentCMS.Repositories/Abstractions/IPluginContentRepository.cs
  src/FluentCMS.Repositories/MongoDB/PluginContentRepository.cs
  src/FluentCMS.Repositories/MongoDb/ContentRepository.cs
  src/FluentCMS.Services/ContentService.cs
  src/FluentCMS.Services/PluginContentService.cs
  src/FluentCMS.Shared/DictionaryStringObjectJsonConverter.cs
  src/FluentCMS.Shared/JsonContentConverter.cs
  src/FluentCMS.Web.UI/ApiClients/GeneratedApiClients.cs
  src/FluentCMS.Web.UI/ApiClients/config.nswag
  src/FluentCMS.Web.UI/Plugins/General/HelloWorld/HelloWorldContent.cs
  src/FluentCMS.Web.UI/Plugins/General/HelloWorld/HelloWorldEditPlugin.razor
  src/FluentCMS.Web.UI/Plugins/General/TextHtml/TextHtmlContent.cs
  src/FluentCMS.Web.UI/Plugins/General/TextHtml/TextHtmlEditPlugin.razor
  src/FluentCMS.Web.UI/Plugins/General/TextHtml/TextHtmlViewPlugin.razor
  src/FluentCMS.Web.UI/Program.cs
Labels: enhancement

#405 404 refactor api controllers based on meetings decision
  src/FluentCMS.Api/ApiApplicationContext.cs
  src/FluentCMS.Api/ConfigurationExtensions.cs
  src/FluentCMS.Api/Controllers/AccountController.cs
  src/FluentCMS.Api/Controllers/ContentTypeController.cs
  src/FluentCMS.Api/Controllers/HostController.cs
  src/FluentCMS.Api/Controllers/PageController.cs
  src/FluentCMS.Api/Controllers/RoleController.cs
  src/FluentCMS.Api/Controllers/SiteController.cs
  src/FluentCMS.Api/DefaultData/DefaultDataLoaderExtensions.cs
  src/FluentCMS.Api/Filters/DecodeQueryParamAttribute.cs
  src/FluentCMS.Api/JwtServiceExtensions.cs
  src/FluentCMS.Api/MappingExtensions.cs
  src/FluentCMS.Api/MappingProfiles.cs
  src/FluentCMS.Api/Models/Pages/PageCreateRequest.cs
  src/FluentCMS.Api/Models/Pages/PageResponse.cs
  src/FluentCMS.Api/Models/Pages/PageSearchRequest.cs
  src/FluentCMS.Api/Models/Pages/PageUpdateRequest.cs
  src/FluentCMS.Api/Models/PluginResponse.cs
  src/FluentCMS.Api/Models/Sites/SiteUpdateRequest.cs
  src/FluentCMS.Api/SwaggerServiceExtensions.cs
  src/FluentCMS.Services/RoleService.cs
  src/FluentCMS.Web.UI/ApiClients/GeneratedApiClients.cs
  src/FluentCMS.Web.UI/ApiClients/config.nswag
  src/FluentCMS.Web.UI/Services/AppStateService.cs
Labels: documentation, enhancement

#399 #398 Add Dropdown Component
  src/FluentCMS.Web.UI/Components/Core/Dropdown.razor
  src/FluentCMS.Web.UI/Components/Core/DropdownButton.razor
  src/FluentCMS.Web.UI/Components/Core/DropdownItem.razor
  src/FluentCMS.Web.UI/Components/Core/DropdownMenu.razor
  src/FluentCMS.Web.UI/Components/Enums/DropdownPlacementEnum.cs
  src/FluentCMS.Web.UI/Components/Enums/IconNameEnum.cs
  src/FluentCMS.Web.UI/Previews/Pages/Components.razor
  src/FluentCMS.Web.UI/Resources/Icons.resx
  src/FluentCMS.Web.UI/static/scss/components/_dropdown.scss
Labels: enhancement

#409 #407 fix style of icon inside button and remove git related text from…
  src/FluentCMS.Web.UI/Previews/Pages/Components.razor
  src/FluentCMS.Web.UI/static/scss/components/_button.scss
Labels: enhancement

#422 #421 change the base api path for app based controllers
  src/New/FluentCMS/Web/Api/Controllers/AppController.cs
  src/New/FluentCMS/Web/Api/Controllers/ContentController.cs
  src/New/FluentCMS/Web/Api/Controllers/ContentTypeController.cs
  src/New/FluentCMS/Web/Api/Controllers/RoleController.cs
Labels: enhancement

#429 #425 Entities extracted
  src/FluentCMS.sln
  src/New/FluentCMS.Entities/App.cs
  src/New/FluentCMS.Entities/AppAssociatedEntity.cs
  src/New/FluentCMS.Entities/AuditableEntity.cs
  src/New/FluentCMS.Entities/Content.cs
  src/New/FluentCMS.Entities/ContentType.cs
  src/New/FluentCMS.Entities/ContentTypeField.cs
  src/New/FluentCMS.Entities/Entity.cs
  src/New/FluentCMS.Entities/FluentCMS.Entities.csproj
  src/New/FluentCMS.Entities/Role.cs
  src/New/FluentCMS.Entities/SystemSettings.cs
  src/New/FluentCMS.Entities/User.cs
  src/New/FluentCMS.Entities/UserTwoFactorRecoveryCode.cs
  src/New/FluentCMS/FluentCMS.csproj
Labels: enhancement

#430 #426 extracting repository abstractions
  src/FluentCMS.sln
  src/New/FluentCMS.Repositories.Abstraction/FluentCMS.Repositories.Abstraction.csproj
  src/New/FluentCMS.Repositories.Abstraction/IAppAssociatedRepository.cs
  src/New/FluentCMS.Repositories.Abstraction/IAppRepository.cs
  src/New/FluentCMS.Repositories.Abstraction/IAuditableEntityRepository.cs
  src/New/FluentCMS.Repositories.Abstraction/IContentRepository.cs
  src/New/FluentCMS.Repositories.Abstraction/IContentTypeRepository.cs
  src/New/FluentCMS.Repositories.Abstraction/IEntityRepository.cs
  src/New/FluentCMS.Repositories.Abstraction/IQueryableRepository.cs
  src/New/FluentCMS.Repositories.Abstraction/IRoleRepository.cs
  src/New/FluentCMS.Repositories.Abstraction/ISystemSettingsRepository.cs
  src/New/FluentCMS.Repositories.Abstraction/IUserRepository.cs
  src/New/FluentCMS/FluentCMS.csproj
Labels: enhancement

#431 #427 MongoDB Repository extraction
  src/FluentCMS.sln
  src/New/FluentCMS.Repositories.MongoDB/AppAssociatedRepository.cs
  src/New/FluentCMS.Repositories.MongoDB/AppRepository.cs
  src/New/FluentCMS.Repositories.MongoDB/AuditableEntityRepository.cs
  src/New/FluentCMS.Repositories.MongoDB/ContentRepository.cs
  src/New/FluentCMS.Repositories.MongoDB/ContentTypeRepository.cs
  src/New/FluentCMS.Repositories.MongoDB/EntityRepository.cs
  src/New/FluentCMS.Repositories.MongoDB/FluentCMS.Repositories.MongoDB.csproj
  src/New/FluentCMS.Repositories.MongoDB/MongoDBContext.cs
  src/New/FluentCMS.Repositories.MongoDB/MongoDBOptions.cs
  src/New/FluentCMS.Repositories.MongoDB/MongoDBServiceExtensions.cs
  src/New/FluentCMS.Repositories.MongoDB/RoleRepository.cs
  src/New/FluentCMS.Repositories.MongoDB/SystemSettingsRepository.cs
  src/New/FluentCMS.Repositories.MongoDB/UserRepository.cs
  src/New/FluentCMS.Shared/Exceptions/AppApiClientException.cs
  src/New/FluentCMS.Shared/Exceptions/AppError.cs
  src/New/FluentCMS.Shared/Exceptions/AppException.cs
  src/New/FluentCMS.Shared/Exceptions/ExceptionCodes.cs
  src/New/FluentCMS.Shared/FluentCMS.Shared.csproj
  src/New/FluentCMS.Shared/IApplicationContext.cs
  src/New/FluentCMS/FluentCMS.csproj
Labels: enhancement

#432 428 refactor services to new project
  src/FluentCMS.sln
  src/New/FluentCMS.Identity/FluentCMS.Identity.csproj
  src/New/FluentCMS.Identity/IdentityResultExtensions.cs
  src/New/FluentCMS.Identity/UserStore.cs
  src/New/FluentCMS.Identity/UserStore_IQueryableUserStore.cs
  src/New/FluentCMS.Identity/UserStore_IUserAuthenticationTokenStore.cs
  src/New/FluentCMS.Identity/UserStore_IUserAuthenticatorKeyStore.cs
  src/New/FluentCMS.Identity/UserStore_IUserClaimStore.cs
  src/New/FluentCMS.Identity/UserStore_IUserEmailStore.cs
  src/New/FluentCMS.Identity/UserStore_IUserLockoutStore.cs
  src/New/FluentCMS.Identity/UserStore_IUserLoginStore.cs
  src/New/FluentCMS.Identity/UserStore_IUserPasswordStore.cs
  src/New/FluentCMS.Identity/UserStore_IUserPhoneNumberStore.cs
  src/New/FluentCMS.Identity/UserStore_IUserRoleStore.cs
  src/New/FluentCMS.Identity/UserStore_IUserSecurityStampStore.cs
  src/New/FluentCMS.Identity/UserStore_IUserTwoFactorRecoveryCodeStore.cs
  src/New/FluentCMS.Identity/UserStore_IUserTwoFactorStore.cs
  src/New/FluentCMS.Services/AppService.cs
  src/New/FluentCMS.Services/ContentService.cs
  src/New/FluentCMS.Services/ContentTypeService.cs
  src/New/FluentCMS.Services/FluentCMS.Services.csproj
  src/New/FluentCMS.Services/RoleService.cs
  src/New/FluentCMS.Services/ServiceExtensions.cs
  src/New/FluentCMS.Services/SystemSettingsService.cs
  src/New/FluentCMS.Services/UserService.cs
  src/New/FluentCMS.Services/UserTokenProvider.cs
  src/New/FluentCMS/FluentCMS.csproj
Labels: enhancement

#435 #434 extract Web.Api project
  src/FluentCMS.sln
  src/New/FluentCMS.Web.Api/Controllers/AccountController.cs
  src/New/FluentCMS.Web.Api/Controllers/AppController.cs
  src/New/FluentCMS.Web.Api/Controllers/BaseController.cs
  src/New/FluentCMS.Web.Api/Controllers/ContentController.cs
  src/New/FluentCMS.Web.Api/Controllers/ContentTypeController.cs
  src/New/FluentCMS.Web.Api/Controllers/RoleController.cs
  src/New/FluentCMS.Web.Api/Controllers/SystemSettingsController.cs
  src/New/FluentCMS.Web.Api/Controllers/UserController.cs
  src/New/FluentCMS.Web.Api/Extentions/SwaggerServiceExtensions.cs
  src/New/FluentCMS.Web.Api/Filters/DecodeQueryParamAttribute.cs
  src/New/FluentCMS.Web.Api/FluentCMS.Web.Api.csproj
  src/New/FluentCMS.Web.Api/Models/ApiPagingResult.cs
  src/New/FluentCMS.Web.Api/Models/ApiResult.cs
  src/New/FluentCMS.Web.Api/Models/App/AppCreateRequest.cs
  src/New/FluentCMS.Web.Api/Models/App/AppResponse.cs
  src/New/FluentCMS.Web.Api/Models/App/AppUpdateRequest.cs
  src/New/FluentCMS.Web.Api/Models/BaseAuditableResponse.cs
  src/New/FluentCMS.Web.Api/Models/Content/ContentCreateRequest.cs
  src/New/FluentCMS.Web.Api/Models/Content/ContentResponse.cs
  src/New/FluentCMS.Web.Api/Models/Content/ContentUpdateRequest.cs
  src/New/FluentCMS.Web.Api/Models/ContentType/ContentTypeCreateRequest.cs
  src/New/FluentCMS.Web.Api/Models/ContentType/ContentTypeResponse.cs
  src/New/FluentCMS.Web.Api/Models/ContentType/ContentTypeUpdateRequest.cs
  src/New/FluentCMS.Web.Api/Models/Error.cs
  src/New/FluentCMS.Web.Api/Models/Roles/RoleCreateRequest.cs
  src/New/FluentCMS.Web.Api/Models/Roles/RoleResponse.cs
  src/New/FluentCMS.Web.Api/Models/Roles/RoleUpdateRequest.cs
  src/New/FluentCMS.Web.Api/Models/SystemSettings/SystemSettingsUpdateRequest.cs
  src/New/FluentCMS.Web.Api/Models/Users/UserChangePasswordRequest.cs
  src/New/FluentCMS.Web.Api/Models/Users/UserCreateRequest.cs
  src/New/FluentCMS.Web.Api/Models/Users/UserDetailResponse.cs
  src/New/FluentCMS.Web.Api/Models/Users/UserLoginRequest.cs
  src/New/FluentCMS.Web.Api/Models/Users/UserLoginResponse.cs
  src/New/FluentCMS.Web.Api/Models/Users/UserRegisterRequest.cs
  src/New/FluentCMS.Web.Api/Models/Users/UserResponse.cs
  src/New/FluentCMS.Web.Api/Models/Users/UserUpdateRequest.cs
  src/New/FluentCMS/FluentCMS.csproj
  src/New/FluentCMS/Program.cs
  src/New/FluentCMS/Properties/launchSettings.json
  src/New/FluentCMS/appsettings.Development.json
Labels: enhancement

#437 #437 extract config folder
  src/New/FluentCMS.Shared/IApplicationContext.cs
  src/New/FluentCMS.Web.Api/ApiApplicationContext.cs
  src/New/FluentCMS.Web.Api/Extentions/ApiServiceExtensions.cs
  src/New/FluentCMS.Web.Api/Extentions/ConfigurationExtensions.cs
  src/New/FluentCMS/Config/appsettings.json
  src/New/FluentCMS/Program.cs
  src/New/FluentCMS/appsettings.json
Labels: enhancement

#439 #438 change `GetBySlug` to `Get` AppController
  src/New/FluentCMS.Web.Api/Controllers/AppController.cs
Labels: enhancement

#444 #443 rename `IApplicationContext to IAuthContext
  src/New/FluentCMS.Repositories.MongoDB/AppAssociatedRepository.cs
  src/New/FluentCMS.Repositories.MongoDB/AppRepository.cs
  src/New/FluentCMS.Repositories.MongoDB/AuditableEntityRepository.cs
  src/New/FluentCMS.Repositories.MongoDB/ContentRepository.cs
  src/New/FluentCMS.Repositories.MongoDB/ContentTypeRepository.cs
  src/New/FluentCMS.Repositories.MongoDB/EntityRepository.cs
  src/New/FluentCMS.Repositories.MongoDB/RoleRepository.cs
  src/New/FluentCMS.Repositories.MongoDB/SystemSettingsRepository.cs
  src/New/FluentCMS.Repositories.MongoDB/UserRepository.cs
  src/New/FluentCMS.Services/SystemSettingsService.cs
  src/New/FluentCMS.Services/UserService.cs
  src/New/FluentCMS.Shared/IAuthContext.cs
  src/New/FluentCMS.Web.Api/AuthContext.cs
  src/New/FluentCMS.Web.Api/Extentions/ApiServiceExtensions.cs
Labels: enhancement

#446 #445 rename SystemSettings to Global settings and applying some enhan…
  src/New/FluentCMS.Entities/GlobalSettings.cs
  src/New/FluentCMS.Repositories.Abstraction/IGlobalSettingsRepository.cs
  src/New/FluentCMS.Repositories.Abstraction/ISystemSettingsRepository.cs
  src/New/FluentCMS.Repositories.MongoDB/GlobalSettingsRepository.cs
  src/New/FluentCMS.Repositories.MongoDB/SystemSettingsRepository.cs
  src/New/FluentCMS.Services/GlobalSettingsService.cs
  src/New/FluentCMS.Services/ServiceExtensions.cs
  src/New/FluentCMS.Services/SystemSettingsService.cs
  src/New/FluentCMS.Services/UserService.cs
  src/New/FluentCMS.Shared/Exceptions/ExceptionCodes.cs
  src/New/FluentCMS.Web.Api/Controllers/AppController.cs
  src/New/FluentCMS.Web.Api/Controllers/BaseController.cs
  src/New/FluentCMS.Web.Api/Controllers/GlobalSettingsController.cs
  src/New/FluentCMS.Web.Api/Controllers/SetupController.cs
  src/New/FluentCMS.Web.Api/Controllers/SystemSettingsController.cs
  src/New/FluentCMS.Web.Api/Extentions/ApiServiceExtensions.cs
  src/New/FluentCMS.Web.Api/Models/GlobalSettings/GlobalSettingsUpdateRequest.cs
  src/New/FluentCMS.Web.Api/Models/Setup/SetupSettings.cs
  src/New/FluentCMS/Config/setup.json
  src/New/FluentCMS/Program.cs
Labels: enhancement

#448 447 add auto reset feature to repository while developing
  src/New/FluentCMS.Repositories.Abstraction/IGlobalSettingsRepository.cs
  src/New/FluentCMS.Repositories.MongoDB/GlobalSettingsRepository.cs
  src/New/FluentCMS.Services/GlobalSettingsService.cs
  src/New/FluentCMS.Web.Api/Controllers/SetupController.cs
  src/New/FluentCMS/Config/appsettings.json
  src/New/FluentCMS/Program.cs
Labels: enhancement

#450 #449 apis and swagger route naming enhancement
  src/New/FluentCMS.Web.Api/Controllers/AccountController.cs
  src/New/FluentCMS.Web.Api/Controllers/AppController.cs
  src/New/FluentCMS.Web.Api/Controllers/BaseController.cs
  src/New/FluentCMS.Web.Api/Controllers/ContentController.cs
  src/New/FluentCMS.Web.Api/Controllers/ContentTypeController.cs
  src/New/FluentCMS.Web.Api/Controllers/GlobalSettingsController.cs
  src/New/FluentCMS.Web.Api/Controllers/RoleController.cs
  src/New/FluentCMS.Web.Api/Controllers/SetupController.cs
  src/New/FluentCMS.Web.Api/Controllers/UserController.cs
  src/New/FluentCMS.Web.Api/Extentions/SwaggerServiceExtensions.cs
  src/New/FluentCMS/Properties/launchSettings.json
Labels: enhancement

#452 #451 add SetupManager and auto-reset db in DEV mode
  src/New/FluentCMS.Web.Api/Controllers/SetupController.cs
  src/New/FluentCMS.Web.Api/FluentCMS.Web.Api.csproj
  src/New/FluentCMS.Web.Api/SetupManager.cs
  src/New/FluentCMS.Web.Api/SetupSettings.cs
  src/New/FluentCMS/Program.cs
Labels: enhancement

#454 #453 develop AppController (initial version)
  src/New/FluentCMS.Web.Api/Controllers/AppController.cs
  src/New/FluentCMS.Web.Api/Models/App/AppUpdateRequest.cs
Labels: enhancement

#457 #433 AppTemplate implementation including Templates initial data
  src/New/FluentCMS.Entities/Templates/AppTemplate.cs
  src/New/FluentCMS.Entities/Templates/ContentTemplate.cs
  src/New/FluentCMS.Entities/Templates/ContentTypeFieldTemplate.cs
  src/New/FluentCMS.Entities/Templates/ContentTypeTemplate.cs
  src/New/FluentCMS.Repositories.Abstraction/IAppTemplateRepository.cs
  src/New/FluentCMS.Repositories.MongoDB/AppTemplateRepository.cs
  src/New/FluentCMS.Services/AppTemplateService.cs
  src/New/FluentCMS.Services/ServiceExtensions.cs
  src/New/FluentCMS.Shared/Exceptions/ExceptionCodes.cs
  src/New/FluentCMS.Web.Api/Controllers/AccountController.cs
  src/New/FluentCMS.Web.Api/Controllers/AppController.cs
  src/New/FluentCMS.Web.Api/Controllers/AppTemplateController.cs
  src/New/FluentCMS.Web.Api/Controllers/BaseController.cs
  src/New/FluentCMS.Web.Api/Controllers/GlobalSettingsController.cs
  src/New/FluentCMS.Web.Api/Controllers/SetupController.cs
  src/New/FluentCMS.Web.Api/Controllers/UserController.cs
  src/New/FluentCMS.Web.Api/Extentions/ApiServiceExtensions.cs
  src/New/FluentCMS.Web.Api/Models/AppTemplate/AppTemplateResponse.cs
  src/New/FluentCMS.Web.Api/SetupManager.cs
  src/New/FluentCMS.Web.Api/SetupSettings.cs
  src/New/FluentCMS/Config/setup.json
  src/New/FluentCMS/Program.cs
  src/New/FluentCMS/Templates/Blank/app-template.json
  src/New/FluentCMS/Templates/Blog/app-template.json
  src/New/FluentCMS/wwwroot/default.html
Labels: enhancement

#459 #458 service auto-registration for DI
  src/New/FluentCMS.Services/AppService.cs
  src/New/FluentCMS.Services/AppTemplateService.cs
  src/New/FluentCMS.Services/ContentService.cs
  src/New/FluentCMS.Services/ContentTypeService.cs
  src/New/FluentCMS.Services/GlobalSettingsService.cs
  src/New/FluentCMS.Services/IService.cs
  src/New/FluentCMS.Services/RoleService.cs
  src/New/FluentCMS.Services/ServiceExtensions.cs
  src/New/FluentCMS.Services/UserService.cs
Labels: enhancement

#461 456 rename fluentcmsrepositoriesabstraction to fluentcmsrepositoriesabstractions namespace and project name
  src/FluentCMS.sln
  src/New/FluentCMS.Identity/FluentCMS.Identity.csproj
  src/New/FluentCMS.Repositories.Abstractions/FluentCMS.Repositories.Abstractions.csproj
  src/New/FluentCMS.Repositories.Abstractions/IAppAssociatedRepository.cs
  src/New/FluentCMS.Repositories.Abstractions/IAppRepository.cs
  src/New/FluentCMS.Repositories.Abstractions/IAppTemplateRepository.cs
  src/New/FluentCMS.Repositories.Abstractions/IAuditableEntityRepository.cs
  src/New/FluentCMS.Repositories.Abstractions/IContentRepository.cs
  src/New/FluentCMS.Repositories.Abstractions/IContentTypeRepository.cs
  src/New/FluentCMS.Repositories.Abstractions/IEntityRepository.cs
  src/New/FluentCMS.Repositories.Abstractions/IGlobalSettingsRepository.cs
  src/New/FluentCMS.Repositories.Abstractions/IQueryableRepository.cs
  src/New/FluentCMS.Repositories.Abstractions/IRoleRepository.cs
  src/New/FluentCMS.Repositories.Abstractions/IUserRepository.cs
  src/New/FluentCMS.Repositories.MongoDB/FluentCMS.Repositories.MongoDB.csproj
Labels: enhancement

#465 #464 update Nuget packages
  src/FluentCMS.Api/FluentCMS.Api.csproj
  src/FluentCMS.Repositories/FluentCMS.Repositories.csproj
  src/FluentCMS.Tests/FluentCMS.Tests.csproj
  src/FluentCMS.Web.UI/FluentCMS.Web.UI.csproj
  src/New/FluentCMS.Repositories.MongoDB/FluentCMS.Repositories.MongoDB.csproj
Labels: enhancement

#462 346 develop e2e tests for host apis
  src/FluentCMS.sln
  src/New/FluentCMS.Services/Extensions/Extensions.cs
  src/New/FluentCMS.Services/UserService.cs
  src/New/FluentCMS.Web.Api/Controllers/SetupController.cs
  src/New/FluentCMS.Web.Api/Extentions/AutoMapperServiceExtensions.cs
  src/New/FluentCMS.Web.Api/MappingProfile.cs
  src/New/FluentCMS.Web.Api/SetupManager.cs
  src/New/FluentCMS/Program.cs
  src/New/Tests/FluentCMS.E2eTests/ApiClients/ClientServiceExtensions.cs
  src/New/Tests/FluentCMS.E2eTests/ApiClients/GeneratedApiClients.cs
  src/New/Tests/FluentCMS.E2eTests/ApiClients/IApiClient.cs
  src/New/Tests/FluentCMS.E2eTests/ApiClients/config.nswag
  src/New/Tests/FluentCMS.E2eTests/Extensions.cs
  src/New/Tests/FluentCMS.E2eTests/Features/SetupClient.feature
  src/New/Tests/FluentCMS.E2eTests/Features/SetupClient.feature.cs
  src/New/Tests/FluentCMS.E2eTests/Features/UserClient.feature
  src/New/Tests/FluentCMS.E2eTests/Features/UserClient.feature.cs
  src/New/Tests/FluentCMS.E2eTests/FluentCMS.E2eTests.csproj
  src/New/Tests/FluentCMS.E2eTests/ImplicitUsings.cs
  src/New/Tests/FluentCMS.E2eTests/StepDefinitions/DictionaryExtensions.cs
  src/New/Tests/FluentCMS.E2eTests/StepDefinitions/SetupStepDefinition.cs
  src/New/Tests/FluentCMS.E2eTests/StepDefinitions/UserStepDefinitions.cs
  src/New/Tests/FluentCMS.E2eTests/appsettings.json
Labels: enhancement

#488 #487 extension cleanup
  src/New/FluentCMS.Web.Api/Extentions/ApiServiceExtensions.cs
  src/New/FluentCMS.Web.Api/Extentions/AutoMapperServiceExtensions.cs
  src/New/FluentCMS/FluentCMS.csproj
  src/New/FluentCMS/Program.cs
  src/New/FluentCMS/SiteServiceExtensions.cs
Labels: enhancement

#491 #490 manual setting for Guid in MongoDB removed
  src/New/FluentCMS.Repositories.MongoDB/EntityRepository.cs
  src/New/FluentCMS.Repositories.MongoDB/MongoDBServiceExtensions.cs
Labels: enhancement

#492 #497 add FormField component to support required indicator in labels
  src/FluentCMS.Web.UI/Components/Core/Form/FormField.razor
  src/FluentCMS.Web.UI/Components/Core/Form/FormInput.razor
  src/FluentCMS.Web.UI/Components/Core/Form/Label.razor
  src/FluentCMS.Web.UI/Previews/Pages/Components.razor
  src/FluentCMS.Web.UI/static/scss/components/_form.scss
Labels: enhancement

#494 #493 set default type of input to text instead of date
  src/FluentCMS.Web.UI/Components/Enums/InputTypeEnum.cs
Labels: bug

#496 add size example for button
  src/FluentCMS.Web.UI/Previews/Pages/Components.razor
Labels: documentation

#503 #502 Add initial pages for crud with components
  src/FluentCMS.Web.UI/Previews/Pages/CRUD/DetailWithComponents.razor
  src/FluentCMS.Web.UI/Previews/Pages/CRUD/FormWithComponents.razor
  src/FluentCMS.Web.UI/Previews/Pages/CRUD/ListWithComponents.razor
  src/FluentCMS.Web.UI/Previews/Pages/Examples.razor
Labels: panel

#504 #500 add class prop for baseComponent
  src/FluentCMS.Web.UI/Components/Core/Base/BaseComponent.cs
  src/FluentCMS.Web.UI/Components/Core/Base/BaseComponentHelpers.cs
  src/FluentCMS.Web.UI/Previews/Pages/Components.razor
Labels: bug, component

#512 #511 add and cleanup card components
  src/FluentCMS.Web.UI/Components/Core/Card.razor
  src/FluentCMS.Web.UI/Components/Core/CardBody.razor
  src/FluentCMS.Web.UI/Components/Core/CardTitle.razor
  src/FluentCMS.Web.UI/Previews/Pages/Components.razor
  src/FluentCMS.Web.UI/static/scss/components/_card.scss
Labels: enhancement, component

#514 #513 Cleanup Alert component
  src/FluentCMS.Web.UI/Components/Core/Alert.razor
  src/FluentCMS.Web.UI/Components/Core/AlertContainer.razor
  src/FluentCMS.Web.UI/Components/Enums/AlertTypeEnum.cs
  src/FluentCMS.Web.UI/Previews/Pages/Components.razor
  src/FluentCMS.Web.UI/static/scss/components/_alert.scss
Labels: component

#520 483 refactor blazor admin panel in separate project
  src/New/FluentCMS.Entities/Site/Layout.cs
  src/New/FluentCMS.Repositories.Abstractions/IContentTypeRepository.cs
  src/New/FluentCMS.Repositories.Abstractions/ILayoutRepository.cs
  src/New/FluentCMS.Repositories.Abstractions/IPluginDefinitionRepository.cs
  src/New/FluentCMS.Repositories.Abstractions/IPluginRepository.cs
  src/New/FluentCMS.Repositories.MongoDB/ContentTypeRepository.cs
  src/New/FluentCMS.Repositories.MongoDB/LayoutRepository.cs
  src/New/FluentCMS.Repositories.MongoDB/PluginDefinitionRepository.cs
  src/New/FluentCMS.Repositories.MongoDB/PluginRepository.cs
  src/New/FluentCMS.Services/ContentTypeService.cs
  src/New/FluentCMS.Services/LayoutService.cs
  src/New/FluentCMS.Services/PluginDefinitionService.cs
  src/New/FluentCMS.Services/PluginService.cs
  src/New/FluentCMS.Shared/Exceptions/ExceptionCodes.cs
  src/New/FluentCMS.Web.Api/Controllers/GlobalSettingsController.cs
  src/New/FluentCMS.Web.Api/Controllers/PluginController.cs
  src/New/FluentCMS.Web.Api/Models/Plugin/PluginCreateRequest.cs
  src/New/FluentCMS.Web.Api/Models/Plugin/PluginDetailResponse.cs
  src/New/FluentCMS.Web.Api/Models/Plugin/PluginUpdateRequest.cs
  src/New/FluentCMS.Web.ApiClients/GeneratedApiClients.cs
  src/New/FluentCMS.Web.ApiClients/config.nswag
  src/New/FluentCMS.Web.UI/App.razor
  src/New/FluentCMS.Web.UI/Page.razor
  src/New/FluentCMS.Web.UI/_Imports.razor
Labels: enhancement

#523 #521 add super admin credentials to Setup process
  src/New/FluentCMS.Shared/Exceptions/ExceptionCodes.cs
  src/New/FluentCMS.Web.Api/AuthContext.cs
  src/New/FluentCMS.Web.Api/Controllers/SetupController.cs
  src/New/FluentCMS.Web.Api/Models/Setup/SetupRequest.cs
  src/New/FluentCMS.Web.Api/SetupManager.cs
  src/New/FluentCMS.Web.Api/SetupSettings.cs
  src/New/FluentCMS/Config/setup.json
  src/New/FluentCMS/Program.cs
Labels: enhancement

#525 #524 Api DI cleanup
  src/New/FluentCMS.Web.Api/Extentions/ApiServiceExtensions.cs
  src/New/FluentCMS.Web.Api/Extentions/SwaggerServiceExtensions.cs
  src/New/FluentCMS.Web.Api/Models/Setup/SetupRequest.cs
  src/New/FluentCMS/Program.cs
Labels: enhancement

#528 fix: #527 fix pageHeader actions
  src/FluentCMS.Web.UI/Components/Core/PageHeader.razor
Labels: bug

#369 #348 add button group component
  src/FluentCMS.Web.UI/Components/Core/ButtonGroup.razor
  src/FluentCMS.Web.UI/Previews/Pages/Components.razor
  src/FluentCMS.Web.UI/static/scss/app.css
  src/FluentCMS.Web.UI/static/scss/app.css.map
  src/FluentCMS.Web.UI/static/scss/components/_button.scss
  src/FluentCMS.Web.UI/wwwroot/css/app.min.css
Labels: enhancement

#501 #499 fix static width of dropdown menu
  src/FluentCMS.Web.UI/Previews/Pages/Components.razor
  src/FluentCMS.Web.UI/static/scss/components/_dropdown.scss
Labels: bug

#538 #537 code cleanup
  src/FluentCMS.Web.UI/Components/Core/Base/BaseComponent.cs
  src/FluentCMS.Web.UI/Components/Core/Base/BaseComponentHelpers.cs
  src/FluentCMS.Web.UI/Components/Enums/AlertTypeEnum.cs
  src/FluentCMS.Web.UI/Components/Enums/FormFieldStatusEnum.cs
Labels: enhancement

#542 #541 apiclient code cleanup
  src/New/FluentCMS.Web.ApiClients/ClientServiceExtensions.cs
Labels: enhancement

#546 #545 add plugin template to setup
  src/New/FluentCMS.Web.Api/Setup/AdminTemplate.cs
  src/New/FluentCMS.Web.Api/Setup/Models/AdminTemplate.cs
  src/New/FluentCMS.Web.Api/Setup/Models/LayoutTemplate.cs
  src/New/FluentCMS.Web.Api/Setup/Models/PageTemplate.cs
  src/New/FluentCMS.Web.Api/Setup/Models/PluginDefinitionTemplate.cs
  src/New/FluentCMS.Web.Api/Setup/Models/PluginTemplate.cs
  src/New/FluentCMS.Web.Api/Setup/SetupManager.cs
  src/New/FluentCMS/Templates/Admin/manifest.json
Labels: enhancement

#548 547 review pagecontroller
  src/New/FluentCMS.Web.Api/Controllers/PageController.cs
  src/New/FluentCMS.Web.Api/MappingProfile.cs
  src/New/FluentCMS.Web.Api/Models/BaseAuditableResponse.cs
  src/New/FluentCMS.Web.Api/Models/Pages/PageFullDetailResponse.cs
  src/New/FluentCMS.Web.Api/Models/Plugin/PluginDetailResponse.cs
  src/New/FluentCMS.Web.ApiClients/GeneratedApiClients.cs
  src/New/FluentCMS.Web.ApiClients/config.nswag
  src/New/FluentCMS.Web.UI/Page.razor
  src/New/FluentCMS.Web.UI/Pages/Error.razor
  src/New/FluentCMS.Web.UI/Pages/Setup.razor
  src/New/FluentCMS.Web.UI/Services/SiteState.cs
Labels: enhancement

#540 move component examples to separate files
  src/FluentCMS.Web.UI/Layouts/ComponentsLayout.razor
  src/FluentCMS.Web.UI/Layouts/PanelLayout.razor
  src/FluentCMS.Web.UI/Previews/Pages/CRUD/DetailWithComponents.razor
  src/FluentCMS.Web.UI/Previews/Pages/CRUD/FormWithComponents.razor
  src/FluentCMS.Web.UI/Previews/Pages/CRUD/ListWithComponents.razor
  src/FluentCMS.Web.UI/Previews/Pages/Components.razor
  src/FluentCMS.Web.UI/Previews/Pages/Components/AlertPage.razor
  src/FluentCMS.Web.UI/Previews/Pages/Components/BadgePage.razor
  src/FluentCMS.Web.UI/Previews/Pages/Components/ButtonPage.razor
  src/FluentCMS.Web.UI/Previews/Pages/Components/CardPage.razor
  src/FluentCMS.Web.UI/Previews/Pages/Components/ConfirmPage.razor
  src/FluentCMS.Web.UI/Previews/Pages/Components/DropdownPage.razor
  src/FluentCMS.Web.UI/Previews/Pages/Components/IconPage.razor
  src/FluentCMS.Web.UI/Previews/Pages/Components/InputPage.razor
  src/FluentCMS.Web.UI/Previews/Pages/Components/ModalPage.razor
  src/FluentCMS.Web.UI/Previews/Pages/Components/PaginationPage.razor
  src/FluentCMS.Web.UI/Previews/Pages/Components/SelectPage.razor
  src/FluentCMS.Web.UI/Previews/Pages/Components/SpinnerPage.razor
  src/FluentCMS.Web.UI/Previews/Pages/Components/TablePage.razor
  src/FluentCMS.Web.UI/Previews/Pages/Components/TextareaPage.razor
  src/FluentCMS.Web.UI/Previews/Pages/Components1.razor
  src/FluentCMS.Web.UI/Previews/Pages/Examples.razor
  src/FluentCMS.Web.UI/Previews/Pages/FormComponents.razor
Labels: documentation, component

#550 335 implement exception handling middleware for api layer
  src/New/FluentCMS.Shared/Exceptions/AppError.cs
  src/New/FluentCMS.Web.Api/ApiExecutionContext.cs
  src/New/FluentCMS.Web.Api/AuthContext.cs
  src/New/FluentCMS.Web.Api/Controllers/AccountController.cs
  src/New/FluentCMS.Web.Api/Controllers/BaseController.cs
  src/New/FluentCMS.Web.Api/Extentions/ApiServiceExtensions.cs
  src/New/FluentCMS.Web.Api/Extentions/SwaggerServiceExtensions.cs
  src/New/FluentCMS.Web.Api/Filters/ApiResultActionFilter.cs
  src/New/FluentCMS.Web.Api/Filters/ApiResultExceptionFilter.cs
  src/New/FluentCMS.Web.Api/Filters/Helper.cs
  src/New/FluentCMS.Web.Api/Middlware/ApplicationExecutionContextMiddleware.cs
  src/New/FluentCMS.Web.Api/Models/ApiPagingResult.cs
  src/New/FluentCMS.Web.Api/Models/ApiResult.cs
  src/New/FluentCMS.Web.Api/Models/Error.cs
  src/New/FluentCMS.Web.UI/Page.razor
  src/New/FluentCMS.Web.UI/Pages/Setup.razor
  src/New/FluentCMS.Web.UI/Services/SetupManager.cs
  src/New/FluentCMS.Web.UI/Services/SiteState.cs
  src/New/FluentCMS.Web.UI/_Imports.razor
  src/New/FluentCMS/Program.cs
Labels: enhancement

#552 #551 remove dependency to NavigationManager in Page
  src/New/FluentCMS.Web.UI/Page.razor
  src/New/FluentCMS.Web.UI/Services/SetupManager.cs
Labels: enhancement

#554 #553 Routes component extraction
  src/New/FluentCMS.Web.UI/App.razor
  src/New/FluentCMS.Web.UI/Page.razor
  src/New/FluentCMS.Web.UI/Pages/Counter.razor
  src/New/FluentCMS.Web.UI/Pages/Setup.razor
  src/New/FluentCMS.Web.UI/Routes.razor
Labels: enhancement

#559 555 refactor sitestate in blazor UI
  src/New/FluentCMS.Shared/Exceptions/ExceptionCodes.cs
  src/New/FluentCMS.Web.UI/Page.razor
  src/New/FluentCMS.Web.UI/Pages/Setup.razor
  src/New/FluentCMS.Web.UI/Services/AdminUIServiceExtensions.cs
  src/New/FluentCMS.Web.UI/Services/SetupManager.cs
  src/New/FluentCMS.Web.UI/Services/SiteState.cs
Labels: enhancement

#561 560 add cms dynamic UI engine
  src/New/FluentCMS.Web.UI.Components/BaseSiteComponent.cs
  src/New/FluentCMS.Web.UI/Components/BasePluginComponent.cs
  src/New/FluentCMS.Web.UI/Components/BaseSiteComponent.cs
  src/New/FluentCMS.Web.UI/Components/PluginContainer.razor
  src/New/FluentCMS.Web.UI/Components/Section.razor
  src/New/FluentCMS.Web.UI/Default.razor
  src/New/FluentCMS.Web.UI/Default.razor.cs
  src/New/FluentCMS.Web.UI/FluentCMS.Web.UI.csproj
  src/New/FluentCMS.Web.UI/Page.razor
  src/New/FluentCMS.Web.UI/Plugins/Auth/ForgotPasswordViewPlugin.razor
  src/New/FluentCMS.Web.UI/Plugins/Auth/LoginViewPlugin.razor
  src/New/FluentCMS.Web.UI/Plugins/Auth/RegisterViewPlugin.razor
  src/New/FluentCMS.Web.UI/Plugins/Auth/ResetPasswordViewPlugin.razor
  src/New/FluentCMS.Web.UI/_GlobalUsings.cs
  src/New/FluentCMS.Web.UI/_Imports.razor
  src/New/FluentCMS/Templates/Admin/AdminLayout.body.html
  src/New/FluentCMS/wwwroot/css/app.min.css
  src/New/FluentCMS/wwwroot/default.html
  src/New/FluentCMS/wwwroot/favicon.png
  src/New/FluentCMS/wwwroot/js/flowbite.min.js
Labels: enhancement

#567 565 clean up unused models for user
  src/New/FluentCMS.Web.Api/Controllers/UserController.cs
  src/New/FluentCMS.Web.Api/MappingProfile.cs
  src/New/FluentCMS.Web.Api/Models/Users/UserDetailResponse.cs
  src/New/FluentCMS.Web.Api/Models/Users/UserResponse.cs
Labels: enhancement

#569 refactor: update UserTokenProvider
  src/New/FluentCMS.Services/UserTokenProvider.cs
Labels: enhancement

#516 chore: remove old unused test project
  src/FluentCMS.Tests/DummyEntities/AuditedDummyEntity.cs
  src/FluentCMS.Tests/DummyEntities/DummyEntity.cs
  src/FluentCMS.Tests/FluentCMS.Tests.csproj
  src/FluentCMS.Tests/GlobalUsings.cs
  src/FluentCMS.Tests/Helpers/ApplicationContext/ApplicationContextDefaults.Admins.cs
  src/FluentCMS.Tests/Helpers/ApplicationContext/ApplicationContextDefaults.NonAdmins.cs
  src/FluentCMS.Tests/Helpers/ApplicationContext/ApplicationContextDefaults.SuperAdmins.cs
  src/FluentCMS.Tests/Helpers/ApplicationContext/ApplicationContextDefaults.cs
  src/FluentCMS.Tests/Helpers/ApplicationContext/ApplicationContextTestUtilExtensions.cs
  src/FluentCMS.Tests/Repositories/LiteDb/LiteDbAuditRepository_Tests.cs
  src/FluentCMS.Tests/Repositories/LiteDb/LiteDbRepository_Tests.cs
  src/FluentCMS.Tests/Repositories/MongoDb/Base_MongoDb_Repository_Tests.cs
  src/FluentCMS.Tests/Repositories/MongoDb/MongoDb_AuditedGenericRepository_Tests.cs
  src/FluentCMS.Tests/Repositories/MongoDb/MongoDb_GenericRepository_Tests.cs
  src/FluentCMS.Tests/Services/HostService_Tests.cs
  src/FluentCMS.Tests/Services/PageService_Tests.cs
  src/FluentCMS.Tests/Services/SiteService_Tests.cs
  src/FluentCMS.Tests/Services/UserServiceTests.cs
  src/FluentCMS.Tests/TestApplicationContext.cs
  src/FluentCMS.sln
Labels: enhancement
