Repository fluentcms/FluentCMS, pull requests merged in 2024-03, with the labels that each got.

#810 feat: add Home Page and display version in home
  src/FluentCMS.Web.UI.Components/Components/Icon/Icon.razor.cs
  src/FluentCMS.Web.UI.Components/Components/Typography/Typography.razor
  src/FluentCMS.Web.UI.Components/Components/Typography/Typography.razor.cs
  src/FluentCMS.Web.UI.Components/Resources/Icons.resx
  src/FluentCMS.Web.UI.Components/Static/dist/app.css
  src/FluentCMS.Web.UI.Components/Static/dist/app.css.map
  src/FluentCMS.Web.UI.Components/Static/scss/components/_button.scss
  src/FluentCMS.Web.UI.Components/Static/scss/components/_typography.scss
  src/FluentCMS.Web.UI.Components/wwwroot/css/app.min.css
  src/FluentCMS.Web.UI.Components/wwwroot/css/app.min.css.map
  src/FluentCMS.Web.UI.ComponentsDocs/Pages/Components/TextPage.razor
  src/FluentCMS.Web.UI/Plugins/Home/HomeViewPlugin.razor
  src/FluentCMS/Templates/Admin/manifest.json
Labels: panel

#821 feat: handle empty states
  src/FluentCMS.Web.UI/Components/EmptyTable.razor
  src/FluentCMS.Web.UI/Plugins/AppManagement/AppListPlugin.razor
  src/FluentCMS.Web.UI/Plugins/ContentManagement/ContentCreatePlugin.razor
  src/FluentCMS.Web.UI/Plugins/ContentManagement/ContentListPlugin.razor
  src/FluentCMS.Web.UI/Plugins/ContentManagement/ContentUpdatePlugin.razor
  src/FluentCMS.Web.UI/Plugins/ContentTypeManagement/ContentTypeCreatePlugin.razor
  src/FluentCMS.Web.UI/Plugins/ContentTypeManagement/ContentTypeListPlugin.razor
  src/FluentCMS.Web.UI/Plugins/UserManagement/UserListPlugin.razor
Labels: enhancement

#822 feat: add Edit and Delete button in detail page
  src/FluentCMS.Web.UI.Components/Static/scss/components/_button.scss
  src/FluentCMS.Web.UI/Plugins/AppManagement/AppDetailPlugin.razor
  src/FluentCMS.Web.UI/Plugins/ContentTypeManagement/ContentTypeDetailPlugin.razor
  src/FluentCMS.Web.UI/Plugins/UserManagement/UserDetailPlugin.razor
Labels: enhancement

#830 713 password reset flow api implementation
  src/FluentCMS.Services/ServiceExtensions.cs
  src/FluentCMS.Services/UserService.cs
  src/FluentCMS.Web.Api/Controllers/AccountController.cs
  src/FluentCMS.Web.Api/Models/Users/UserSendPasswordResetTokenRequest.cs
  src/FluentCMS.Web.Api/Models/Users/UserValidatePasswordResetTokenRequest.cs
Labels: enhancement

#831 823 in contenttype create api backend doesnt validate duplicate slugs
  src/FluentCMS.Services/ContentTypeService.cs
  src/FluentCMS.Shared/Exceptions/ExceptionCodes.cs
Labels: enhancement

#835 feat: add target=_blank for links of Home page
  src/FluentCMS.Web.UI/Plugins/Home/HomeViewPlugin.razor
Labels: enhancement

#844 818 add autofocus and tab navigation feature for form pages
  src/FluentCMS.Web.UI.Components/Components/Page/PageBackButton.razor
  src/FluentCMS.Web.UI.Components/Static/dist/app.css
  src/FluentCMS.Web.UI.Components/Static/dist/app.css.map
  src/FluentCMS.Web.UI.Components/Static/scss/components/_page.scss
  src/FluentCMS.Web.UI.Components/wwwroot/css/app.min.css
  src/FluentCMS.Web.UI.Components/wwwroot/css/app.min.css.map
  src/FluentCMS.Web.UI/Components/ExtendedFocusOnNavigate.razor
  src/FluentCMS.Web.UI/Plugins/AppManagement/AppListPlugin.razor
  src/FluentCMS.Web.UI/Plugins/Auth/LoginViewPlugin.razor
  src/FluentCMS.Web.UI/Plugins/Auth/RegisterViewPlugin.razor
  src/FluentCMS.Web.UI/Plugins/Auth/ResetPasswordViewPlugin.razor
  src/FluentCMS.Web.UI/Plugins/ContentManagement/ContentCreatePlugin.razor
  src/FluentCMS.Web.UI/Plugins/ContentManagement/ContentListPlugin.razor
  src/FluentCMS.Web.UI/Plugins/ContentTypeManagement/ContentTypeCreatePlugin.razor
  src/FluentCMS.Web.UI/Plugins/ContentTypeManagement/ContentTypeFieldModal.razor
  src/FluentCMS.Web.UI/Plugins/ContentTypeManagement/ContentTypeListPlugin.razor
  src/FluentCMS.Web.UI/Plugins/MediaLibrary/MediaListPlugin.razor
  src/FluentCMS.Web.UI/Plugins/Setup/SetupViewPlugin.razor
  src/FluentCMS.Web.UI/Plugins/UserManagement/UserDetailPlugin.razor
  src/FluentCMS.Web.UI/Plugins/UserManagement/UserListPlugin.razor
  src/FluentCMS.Web.UI/Routes.razor
Labels: enhancement

#849 style: remove shadow of table
  src/FluentCMS.Web.UI.Components/Static/scss/components/_table.scss
Labels: style

#850 fix: don't show empty table while loading content types
  src/FluentCMS.Web.UI/Plugins/ContentTypeManagement/ContentTypeListPlugin.razor
Labels: bug

#842 feat: add size and missing styles for Inputs.
  src/FluentCMS.Web.UI.Components/Components/Form/Input.razor
  src/FluentCMS.Web.UI.Components/Components/Form/Input.razor.cs
  src/FluentCMS.Web.UI.Components/Components/Form/Select.razor
  src/FluentCMS.Web.UI.Components/Static/scss/components/_form-field.scss
  src/FluentCMS.Web.UI.Components/Static/scss/components/_input.scss
  src/FluentCMS.Web.UI.Components/Static/scss/components/_select.scss
  src/FluentCMS.Web.UI.Components/Static/scss/components/_textarea.scss
  src/FluentCMS.Web.UI.ComponentsDocs/Pages/Components/InputPage.razor
  src/FluentCMS.Web.UI.ComponentsDocs/Pages/Components/SelectPage.razor
  src/FluentCMS.Web.UI/Plugins/ContentTypeManagement/ContentTypeListPlugin.razor
Labels: style

#853 Add Detail page for content
  src/FluentCMS.Web.UI/Plugins/ContentManagement/ContentDetailPlugin.razor
  src/FluentCMS.Web.UI/Plugins/ContentManagement/ContentListPlugin.razor
  src/FluentCMS.Web.UI/Plugins/ContentManagement/ContentUpdatePlugin.razor
Labels: enhancement

#816 789 fix failing tests
  src/FluentCMS.E2E.UI/config.js
  src/FluentCMS.E2E.UI/cypress/commands/admin-layout.js
  src/FluentCMS.E2E.UI/cypress/commands/apps.js
  src/FluentCMS.E2E.UI/cypress/commands/auth.js
  src/FluentCMS.E2E.UI/cypress/commands/content-type.js
  src/FluentCMS.E2E.UI/cypress/commands/content.js
  src/FluentCMS.E2E.UI/cypress/e2e/apps.e2e.js
  src/FluentCMS.E2E.UI/cypress/e2e/content-type.e2e.js
  src/FluentCMS.E2E.UI/cypress/e2e/content.e2e.js
  src/FluentCMS.E2E.UI/cypress/support/commands.js
Labels: test

#864 feat: add html report, video and screenshot for cypress
  src/FluentCMS.E2E.UI/.gitignore
  src/FluentCMS.E2E.UI/cypress.config.js
  src/FluentCMS.E2E.UI/cypress/commands/auth.js
  src/FluentCMS.E2E.UI/cypress/commands/setup.js
  src/FluentCMS.E2E.UI/cypress/e2e/admin-layout.e2e.js
  src/FluentCMS.E2E.UI/cypress/e2e/apps.e2e.js
  src/FluentCMS.E2E.UI/cypress/e2e/content-type.e2e.js
  src/FluentCMS.E2E.UI/cypress/e2e/content.e2e.js
  src/FluentCMS.E2E.UI/cypress/support/commands.js
  src/FluentCMS.E2E.UI/cypress/support/e2e.js
  src/FluentCMS.E2E.UI/package-lock.json
  src/FluentCMS.E2E.UI/package.json
Labels: test

#868 feat: add sidebar toggler component
  src/FluentCMS.Web.UI.Components/Components/Sidebar/SidebarToggler.razor
  src/FluentCMS.Web.UI.Components/Components/Sidebar/SidebarToggler.razor.js
  src/FluentCMS.Web.UI.Components/Layouts/PanelLayout.razor
  src/FluentCMS.Web.UI.Components/Static/scss/components/_sidebar.scss
  src/FluentCMS/wwwroot/js/admin-sidebar.js
Labels: enhancement

#881 878 fix e2e tests after adding contenttype fields
  src/FluentCMS.E2E.UI/config.js
  src/FluentCMS.E2E.UI/cypress/commands/admin-layout.js
  src/FluentCMS.E2E.UI/cypress/commands/apps.js
  src/FluentCMS.E2E.UI/cypress/commands/auth.js
  src/FluentCMS.E2E.UI/cypress/commands/content-type.js
  src/FluentCMS.E2E.UI/cypress/e2e/basic.e2e.js
  src/FluentCMS.E2E.UI/cypress/support/commands.js
  src/FluentCMS.Web.UI/Plugins/ContentTypeManagement/ContentTypeFields/Base/FieldAdvancedSettings.razor
  src/FluentCMS.Web.UI/Plugins/ContentTypeManagement/ContentTypeListPlugin.razor
Labels: test

#877 feat: add date field type
  src/FluentCMS.Web.UI/Plugins/ContentTypeManagement/ContentTypeFields/Base/FieldAdvancedSettings.razor
  src/FluentCMS.Web.UI/Plugins/ContentTypeManagement/ContentTypeFields/Date/Date.cs
  src/FluentCMS.Web.UI/Plugins/ContentTypeManagement/ContentTypeFields/Date/DateAdvancedSettings.razor
  src/FluentCMS.Web.UI/Plugins/ContentTypeManagement/ContentTypeFields/Date/DateBasicSettings.razor
Labels: enhancement

#887 Enable tests for mobile
  src/FluentCMS.E2E.UI/cypress.config.js
  src/FluentCMS.E2E.UI/cypress/commands/admin-layout.js
  src/FluentCMS.E2E.UI/cypress/commands/apps.js
  src/FluentCMS.E2E.UI/cypress/commands/content-type.js
  src/FluentCMS.E2E.UI/cypress/commands/content.js
  src/FluentCMS.E2E.UI/cypress/e2e/basic.e2e.js
  src/FluentCMS.E2E.UI/package.json
  src/FluentCMS.Web.UI/Plugins/ContentManagement/ContentIndexPlugin.razor
  src/FluentCMS.Web.UI/Plugins/ContentManagement/ContentLayout.razor
  src/FluentCMS/Templates/Admin/AdminLayout.body.html
Labels: test

#886 fix: enable page refresh after delete content
  src/FluentCMS.E2E.UI/cypress/commands/content.js
  src/FluentCMS.Web.UI/Plugins/ContentManagement/ContentListPlugin.razor
Labels: bug

#888 feat: add some padding in bottom of page
  src/FluentCMS.Web.UI.Components/Static/scss/components/_page.scss
Labels: enhancement, style

#901 fix: #899 fix e2e tests
  src/FluentCMS.E2E.UI/cypress/commands/admin-layout.js
  src/FluentCMS.E2E.UI/cypress/commands/auth.js
  src/FluentCMS.E2E.UI/cypress/commands/content-type.js
  src/FluentCMS.E2E.UI/cypress/commands/content.js
  src/FluentCMS.E2E.UI/cypress/e2e/basic.e2e.js
  src/FluentCMS.E2E.UI/cypress/support/commands.js
  src/FluentCMS.Web.UI.Components/Static/dist/app.css
  src/FluentCMS.Web.UI.Components/Static/dist/app.css.map
  src/FluentCMS.Web.UI.Components/wwwroot/css/app.min.css
  src/FluentCMS.Web.UI.Components/wwwroot/css/app.min.css.map
Labels: bug, test

#900 feat: add Change Password template
  src/FluentCMS.Web.UI/Plugins/Auth/ChangePasswordViewPlugin.razor
  src/FluentCMS/Templates/Admin/manifest.json
Labels: enhancement

#918 917 failing delete field api test
  src/Tests/FluentCMS.E2eTests/Features/AppClient.feature
  src/Tests/FluentCMS.E2eTests/Features/ContentTypeClient.feature
  src/Tests/FluentCMS.E2eTests/Features/RoleClient.feature
  src/Tests/FluentCMS.E2eTests/Features/UserClient.feature
  src/Tests/FluentCMS.E2eTests/StepDefinitions/Given/GivenIHaveAService.cs
  src/Tests/FluentCMS.E2eTests/StepDefinitions/Tags/RequiresAuthenticatedAdmin.cs
  src/Tests/FluentCMS.E2eTests/StepDefinitions/Then/ThenResponseErrorsShouldNotBeEmpty.cs
  src/Tests/FluentCMS.E2eTests/StepDefinitions/When/WhenIAuthenticateAsync.cs
Labels: bug

#920 Update README.md
  README.md
Labels: documentation

#922 #921 removing unused usings and clean up
  src/FluentCMS.Web.Api/Controllers/AccountController.cs
  src/FluentCMS.Web.Api/Controllers/SetupController.cs
  src/FluentCMS.Web.Api/Extentions/ApiServiceExtensions.cs
  src/FluentCMS.Web.Api/Models/App/AppCreateRequest.cs
  src/FluentCMS.Web.Api/Models/App/AppUpdateRequest.cs
  src/FluentCMS.Web.Api/Models/Content/ContentDetailResponse.cs
  src/FluentCMS.Web.Api/Models/ContentType/ContentTypeCreateRequest.cs
  src/FluentCMS.Web.Api/Models/ContentType/ContentTypeUpdateRequest.cs
  src/FluentCMS.Web.Api/Models/Setup/SetupRequest.cs
  src/FluentCMS.Web.Api/Models/Users/UserCreateRequest.cs
  src/FluentCMS.Web.Api/Models/Users/UserRegisterRequest.cs
  src/FluentCMS.Web.ApiClients/ClientServiceExtensions.cs
  src/FluentCMS.Web.UI.Components/Components/Form/Form.razor.cs
  src/FluentCMS.Web.UI.Components/Components/Table/Table.razor.cs
  src/FluentCMS.Web.UI.Components/Components/Toast/ToastModel.cs
  src/FluentCMS.Web.UI.Components/Components/Typography/Typography.razor.cs
  src/FluentCMS.Web.UI/Default.razor.cs
  src/FluentCMS.Web.UI/Plugins/Auth/ProfileViewPlugin.razor.cs
  src/FluentCMS.Web.UI/Services/AuthStateProvider.cs
  src/FluentCMS.Web.UI/Services/ErrorMessageExtension.cs
  src/FluentCMS/SiteServiceExtensions.cs
  src/Tests/FluentCMS.E2eTests/Features/AccountClient.feature.cs
  src/Tests/FluentCMS.E2eTests/Features/AppClient.feature.cs
  src/Tests/FluentCMS.E2eTests/Features/ContentTypeClient.feature.cs
  src/Tests/FluentCMS.E2eTests/Features/RoleClient.feature.cs
  src/Tests/FluentCMS.E2eTests/Features/SetupClient.feature.cs
  src/Tests/FluentCMS.E2eTests/Features/UserClient.feature.cs
  src/Tests/FluentCMS.E2eTests/StepDefinitions/Given/GivenIHaveAService.cs
Labels: enhancement

#924 #923 Nuget packages update
  src/FluentCMS.Entities/FluentCMS.Entities.csproj
  src/FluentCMS.Repositories.MongoDB/FluentCMS.Repositories.MongoDB.csproj
  src/FluentCMS.Services/FluentCMS.Services.csproj
  src/FluentCMS.Web.Api/FluentCMS.Web.Api.csproj
  src/FluentCMS.Web.ApiClients/FluentCMS.Web.ApiClients.csproj
  src/FluentCMS.Web.UI.Components/FluentCMS.Web.UI.Components.csproj
  src/FluentCMS.Web.UI/FluentCMS.Web.UI.csproj
  src/Tests/FluentCMS.E2eTests/FluentCMS.E2eTests.csproj
Labels: enhancement
