Repository fluentcms/FluentCMS, pull requests merged in 2024-08, with the labels that each got.

#1829 #1828 add admin toolbar for page and plugin
  src/Backend/FluentCMS.Web.Api/Setup/Models/PluginTemplate.cs
  src/Backend/FluentCMS.Web.Api/Setup/SetupManager.cs
  src/FluentCMS/Template/AdminLayout.body.html
  src/FluentCMS/Template/manifest.json
  src/Frontend/FluentCMS.Web.UI/Default.razor
  src/Frontend/FluentCMS.Web.UI/PageToolbar.razor
  src/Frontend/FluentCMS.Web.UI/PageToolbar.razor.cs
  src/Frontend/FluentCMS.Web.UI/PluginContainerActions.razor
  src/Frontend/FluentCMS.Web.UI/wwwroot/css/plugin-actions.css
  src/Frontend/FluentCMS.Web.UI/wwwroot/css/sitebuilder.css
  src/Frontend/FluentCMS.Web.UI/wwwroot/css/sitebuilder.default.css
  src/Frontend/FluentCMS.Web.UI/wwwroot/css/sitebuilder.preview.css
  src/Frontend/FluentCMS.Web.UI/wwwroot/css/toolbar.css
  src/Frontend/FluentCMS.Web.UI/wwwroot/images/logo.svg
  src/Frontend/FluentCMS.Web.UI/wwwroot/js/plugin-actions.js
  src/Frontend/FluentCMS.Web.UI/wwwroot/js/sitebuilder.default.js
  src/Frontend/FluentCMS.Web.UI/wwwroot/js/sitebuilder.js
  src/Frontend/Plugins/FluentCMS.Web.Plugins.Contents.TextHTML/TextHTMLEditPlugin.razor.cs
  src/Frontend/Plugins/FluentCMS.Web.Plugins.Contents.TextHTML/TextHTMLViewPlugin.razor
Labels: enhancement

#1838 #1837 move scss files to Flowbite folder
  src/FluentCMS/Template/AdminLayout.head.html
  src/FluentCMS/Template/AuthLayout.head.html
  src/FluentCMS/Template/DefaultLayout.head.html
  src/Frontend/FluentCMS.Web.UI.Components/Styles/App.scss
  src/Frontend/FluentCMS.Web.UI.Components/Styles/Flowbite/App.scss
  src/Frontend/FluentCMS.Web.UI.Components/Styles/Flowbite/Components/Accordion.scss
  src/Frontend/FluentCMS.Web.UI.Components/Styles/Flowbite/Components/Alert.scss
  src/Frontend/FluentCMS.Web.UI.Components/Styles/Flowbite/Components/Avatar.scss
  src/Frontend/FluentCMS.Web.UI.Components/Styles/Flowbite/Components/Badge.scss
  src/Frontend/FluentCMS.Web.UI.Components/Styles/Flowbite/Components/Breadcrumb.scss
  src/Frontend/FluentCMS.Web.UI.Components/Styles/Flowbite/Components/Button.scss
  src/Frontend/FluentCMS.Web.UI.Components/Styles/Flowbite/Components/Card.scss
  src/Frontend/FluentCMS.Web.UI.Components/Styles/Flowbite/Components/CloseButton.scss
  src/Frontend/FluentCMS.Web.UI.Components/Styles/Flowbite/Components/Confirm.scss
  src/Frontend/FluentCMS.Web.UI.Components/Styles/Flowbite/Components/DataTable.scss
  src/Frontend/FluentCMS.Web.UI.Components/Styles/Flowbite/Components/Divider.scss
  src/Frontend/FluentCMS.Web.UI.Components/Styles/Flowbite/Components/Dropdown.scss
  src/Frontend/FluentCMS.Web.UI.Components/Styles/Flowbite/Components/Form/FormAutocomplete.scss
  src/Frontend/FluentCMS.Web.UI.Components/Styles/Flowbite/Components/Form/FormCheckbox.scss
  src/Frontend/FluentCMS.Web.UI.Components/Styles/Flowbite/Components/Form/FormCheckboxGroup.scss
  src/Frontend/FluentCMS.Web.UI.Components/Styles/Flowbite/Components/Form/FormDateInput.scss
  src/Frontend/FluentCMS.Web.UI.Components/Styles/Flowbite/Components/Form/FormField.scss
  src/Frontend/FluentCMS.Web.UI.Components/Styles/Flowbite/Components/Form/FormFileUpload.scss
  src/Frontend/FluentCMS.Web.UI.Components/Styles/Flowbite/Components/Form/FormInput.scss
  src/Frontend/FluentCMS.Web.UI.Components/Styles/Flowbite/Components/Form/FormLabel.scss
  src/Frontend/FluentCMS.Web.UI.Components/Styles/Flowbite/Components/Form/FormMarkdownEditor.scss
  src/Frontend/FluentCMS.Web.UI.Components/Styles/Flowbite/Components/Form/FormNumberInput.scss
  src/Frontend/FluentCMS.Web.UI.Components/Styles/Flowbite/Components/Form/FormRadioGroup.scss
  src/Frontend/FluentCMS.Web.UI.Components/Styles/Flowbite/Components/Form/FormRichTextEditor.scss
  src/Frontend/FluentCMS.Web.UI.Components/Styles/Flowbite/Components/Form/FormSelect.scss
  src/Frontend/FluentCMS.Web.UI.Components/Styles/Flowbite/Components/Form/FormSwitch.scss
  src/Frontend/FluentCMS.Web.UI.Components/Styles/Flowbite/Components/Form/FormTextarea.scss
  src/Frontend/FluentCMS.Web.UI.Components/Styles/Flowbite/Components/Grid.scss
  src/Frontend/FluentCMS.Web.UI.Components/Styles/Flowbite/Components/Icon.scss
  src/Frontend/FluentCMS.Web.UI.Components/Styles/Flowbite/Components/Indicator.scss
  src/Frontend/FluentCMS.Web.UI.Components/Styles/Flowbite/Components/Modal.scss
  src/Frontend/FluentCMS.Web.UI.Components/Styles/Flowbite/Components/Pagination.scss
  src/Frontend/FluentCMS.Web.UI.Components/Styles/Flowbite/Components/Spacer.scss
  src/Frontend/FluentCMS.Web.UI.Components/Styles/Flowbite/Components/Spinner.scss
  src/Frontend/FluentCMS.Web.UI.Components/Styles/Flowbite/Components/Stack.scss
  src/Frontend/FluentCMS.Web.UI.Components/Styles/Flowbite/Components/Stepper.scss
  src/Frontend/FluentCMS.Web.UI.Components/Styles/Flowbite/Components/Tabs.scss
  src/Frontend/FluentCMS.Web.UI.Components/Styles/Flowbite/Components/Toast.scss
  src/Frontend/FluentCMS.Web.UI.Components/Styles/Flowbite/Components/Tooltip.scss
  src/Frontend/FluentCMS.Web.UI.Components/Styles/Flowbite/Components/Typography.scss
  src/Frontend/FluentCMS.Web.UI.Components/Styles/package.json
  src/Frontend/FluentCMS.Web.UI.Components/wwwroot/css/app.min.css
  src/Frontend/FluentCMS.Web.UI.Components/wwwroot/css/app.min.css.map
  src/Frontend/FluentCMS.Web.UI.Components/wwwroot/css/flowbite.min.css
  src/Frontend/FluentCMS.Web.UI.Components/wwwroot/css/flowbite.min.css.map
Labels: enhancement

#1841 Update README.md
  README.md
Labels: documentation

#1842 #1839 Fix TextEditor issue and remove usused files
  src/Frontend/FluentCMS.Web.UI.Components/Components/Accordion/Accordion.razor.scss
  src/Frontend/FluentCMS.Web.UI.Components/Components/Alert/Alert.razor.scss
  src/Frontend/FluentCMS.Web.UI.Components/Components/Avatar/Avatar.razor.scss
  src/Frontend/FluentCMS.Web.UI.Components/Components/Badge/Badge.razor.scss
  src/Frontend/FluentCMS.Web.UI.Components/Components/Breadcrumb/Breadcrumb.razor.scss
  src/Frontend/FluentCMS.Web.UI.Components/Components/Button/Button.razor.scss
  src/Frontend/FluentCMS.Web.UI.Components/Components/Card/Card.razor.scss
  src/Frontend/FluentCMS.Web.UI.Components/Components/CloseButton/CloseButton.razor.scss
  src/Frontend/FluentCMS.Web.UI.Components/Components/Confirm/Confirm.razor.scss
  src/Frontend/FluentCMS.Web.UI.Components/Components/DataTable/DataTable.razor.scss
  src/Frontend/FluentCMS.Web.UI.Components/Components/Divider/Divider.razor.scss
  src/Frontend/FluentCMS.Web.UI.Components/Components/Dropdown/Dropdown.razor.scss
  src/Frontend/FluentCMS.Web.UI.Components/Components/Form/FormAutocomplete/FormAutocomplete.razor.scss
  src/Frontend/FluentCMS.Web.UI.Components/Components/Form/FormCheckbox/FormCheckbox.razor.scss
  src/Frontend/FluentCMS.Web.UI.Components/Components/Form/FormDateInput/FormDateInput.razor.scss
  src/Frontend/FluentCMS.Web.UI.Components/Components/Form/FormField/FormField.razor.scss
  src/Frontend/FluentCMS.Web.UI.Components/Components/Form/FormFileUpload/FormFileUpload.razor.scss
  src/Frontend/FluentCMS.Web.UI.Components/Components/Form/FormInput/FormInput.razor.scss
  src/Frontend/FluentCMS.Web.UI.Components/Components/Form/FormLabel/FormLabel.razor.scss
  src/Frontend/FluentCMS.Web.UI.Components/Components/Form/FormMarkdownEditor/FormMarkdownEditor.razor.scss
  src/Frontend/FluentCMS.Web.UI.Components/Components/Form/FormNumberInput/FormNumberInput.razor.scss
  src/Frontend/FluentCMS.Web.UI.Components/Components/Form/FormRadioGroup/FormRadioGroup.razor.scss
  src/Frontend/FluentCMS.Web.UI.Components/Components/Form/FormRichTextEditor/FormRichTextEditor.razor.scss
  src/Frontend/FluentCMS.Web.UI.Components/Components/Form/FormSelect/FormSelect.razor.scss
  src/Frontend/FluentCMS.Web.UI.Components/Components/Form/FormSwitch/FormSwitch.razor.scss
  src/Frontend/FluentCMS.Web.UI.Components/Components/Form/FormTextarea/FormTextarea.razor.scss
  src/Frontend/FluentCMS.Web.UI.Components/Components/Grid/Grid.razor.scss
  src/Frontend/FluentCMS.Web.UI.Components/Components/Icon/Icon.razor.scss
  src/Frontend/FluentCMS.Web.UI.Components/Components/Indicator/Indicator.razor.scss
  src/Frontend/FluentCMS.Web.UI.Components/Components/Modal/Modal.razor.scss
  src/Frontend/FluentCMS.Web.UI.Components/Components/Pagination/Pagination.razor.scss
  src/Frontend/FluentCMS.Web.UI.Components/Components/Spacer/Spacer.razor.scss
  src/Frontend/FluentCMS.Web.UI.Components/Components/Spinner/Spinner.razor.scss
  src/Frontend/FluentCMS.Web.UI.Components/Components/Stack/Stack.razor.scss
  src/Frontend/FluentCMS.Web.UI.Components/Components/Stepper/Stepper.razor.scss
  src/Frontend/FluentCMS.Web.UI.Components/Components/Tabs/Tabs.razor.scss
  src/Frontend/FluentCMS.Web.UI.Components/Components/Toast/Toast.razor.scss
  src/Frontend/FluentCMS.Web.UI.Components/Components/Tooltip/Tooltip.razor.scss
  src/Frontend/FluentCMS.Web.UI.Components/Components/Typography/Typography.razor.scss
  src/Frontend/FluentCMS.Web.UI.Components/Styles/Flowbite/App.scss
  src/Frontend/FluentCMS.Web.UI.Components/Styles/Flowbite/Components/Form/FormAutocomplete.core.css
  src/Frontend/FluentCMS.Web.UI.Components/Styles/Flowbite/Components/Form/FormMarkdownEditor.core.css
  src/Frontend/FluentCMS.Web.UI.Components/Styles/Flowbite/Components/Form/FormRichTextEditor.core.css
  src/Frontend/FluentCMS.Web.UI.Components/wwwroot/css/flowbite.min.css
  src/Frontend/FluentCMS.Web.UI.Components/wwwroot/css/flowbite.min.css.map
Labels: bug

#1844 #1843 add initial docs
  README.md
  docs/Architecture.md
  docs/Page.md
  docs/PluginDefinition.md
  docs/README.md
  docs/Role.md
  docs/Site.md
  docs/User.md
  docs/resources/Architecture.png
Labels: documentation

#1849 #1848 remove warnings of RichTextEditor component
  src/Frontend/FluentCMS.Web.UI.Components/Components/Form/FormRichTextEditor/FormRichTextEditor.razor
  src/Frontend/FluentCMS.Web.UI.Components/Components/Form/FormRichTextEditor/FormRichTextEditor.razor.cs
Labels: enhancement, component

#1847 Refactor site builder javascript code
  src/Frontend/FluentCMS.Web.UI/App.razor
  src/Frontend/FluentCMS.Web.UI/Components/PageEditorSidebar.razor
  src/Frontend/FluentCMS.Web.UI/Components/PageEditorSidebar.razor.cs
  src/Frontend/FluentCMS.Web.UI/Components/PageToolbar.razor
  src/Frontend/FluentCMS.Web.UI/Components/PageToolbar.razor.cs
  src/Frontend/FluentCMS.Web.UI/Components/PluginActionsForms.razor
  src/Frontend/FluentCMS.Web.UI/Components/PluginActionsForms.razor.cs
  src/Frontend/FluentCMS.Web.UI/Components/PluginContainer.razor
  src/Frontend/FluentCMS.Web.UI/Components/PluginContainer.razor.cs
  src/Frontend/FluentCMS.Web.UI/Components/PluginContainerActions.razor
  src/Frontend/FluentCMS.Web.UI/Components/PluginContainerActions.razor.cs
  src/Frontend/FluentCMS.Web.UI/Components/SiteBuilder.razor
  src/Frontend/FluentCMS.Web.UI/Components/SiteBuilder.razor.cs
  src/Frontend/FluentCMS.Web.UI/Components/SiteBuilderForms.razor
  src/Frontend/FluentCMS.Web.UI/Components/SiteBuilderForms.razor.cs
  src/Frontend/FluentCMS.Web.UI/Default.razor
  src/Frontend/FluentCMS.Web.UI/PageEditorForms.razor
  src/Frontend/FluentCMS.Web.UI/PageEditorForms.razor.cs
  src/Frontend/FluentCMS.Web.UI/PageEditorHeader.razor
  src/Frontend/FluentCMS.Web.UI/PageEditorSidebar.razor
  src/Frontend/FluentCMS.Web.UI/PageEditorSidebar.razor.cs
  src/Frontend/FluentCMS.Web.UI/PluginContainerActions.razor
  src/Frontend/FluentCMS.Web.UI/PluginLoader/PluginLoadContext.cs
  src/Frontend/FluentCMS.Web.UI/wwwroot/css/confirm.css
  src/Frontend/FluentCMS.Web.UI/wwwroot/css/sitebuilder.editor.css
  src/Frontend/FluentCMS.Web.UI/wwwroot/css/sitebuilder.preview.css
  src/Frontend/FluentCMS.Web.UI/wwwroot/js/actions.js
  src/Frontend/FluentCMS.Web.UI/wwwroot/js/api.js
  src/Frontend/FluentCMS.Web.UI/wwwroot/js/columns.js
  src/Frontend/FluentCMS.Web.UI/wwwroot/js/request.js
  src/Frontend/FluentCMS.Web.UI/wwwroot/js/responsive.js
  src/Frontend/FluentCMS.Web.UI/wwwroot/js/sitebuilder.editor.js
  src/Frontend/FluentCMS.Web.UI/wwwroot/js/sitebuilder.js
  src/Frontend/FluentCMS.Web.UI/wwwroot/js/sitebuilder.preview.js
  src/Frontend/Plugins/FluentCMS.Web.Plugins.Contents.TextHTML/TextHTMLViewPlugin.razor
Labels: enhancement

#1861 Update Features Page.md
  docs/Page.md
Labels: documentation

#1860 Update Page.md
  docs/Page.md
Labels: documentation

#1852 #1467 Implement Page management
  src/Backend/FluentCMS.Services/PageService.cs
  src/Backend/FluentCMS.Web.Api/Controllers/PageController.cs
  src/Backend/FluentCMS.Web.Api/Models/Pages/PageCreateRequest.cs
  src/Backend/FluentCMS.Web.Api/Models/Pages/PageDetailResponse.cs
  src/FluentCMS/Template/AdminLayout.body.html
  src/FluentCMS/Template/manifest.json
  src/Frontend/FluentCMS.Web.ApiClients/GeneratedApiClients.cs
  src/Frontend/FluentCMS.Web.ApiClients/MappingProfile.cs
  src/Frontend/FluentCMS.Web.UI/Default.razor
  src/Frontend/Plugins/FluentCMS.Web.Plugins.Admin/PageManagement/PageCreatePlugin.razor
  src/Frontend/Plugins/FluentCMS.Web.Plugins.Admin/PageManagement/PageCreatePlugin.razor.cs
  src/Frontend/Plugins/FluentCMS.Web.Plugins.Admin/PageManagement/PageListPlugin.razor
  src/Frontend/Plugins/FluentCMS.Web.Plugins.Admin/PageManagement/PageListPlugin.razor.cs
  src/Frontend/Plugins/FluentCMS.Web.Plugins.Admin/PageManagement/PageUpdatePlugin.razor
  src/Frontend/Plugins/FluentCMS.Web.Plugins.Admin/PageManagement/PageUpdatePlugin.razor.cs
  src/Frontend/Plugins/FluentCMS.Web.Plugins.Admin/PageManagement/SelectOption.cs
  src/Shared/ViewState.cs
Labels: enhancement

#1857 #1854 add page update plugin orders api
  src/Backend/FluentCMS.Web.Api/Controllers/PageController.cs
  src/Backend/FluentCMS.Web.Api/Models/Pages/PageUpdatePluginOrdersRequest.cs
  src/Frontend/FluentCMS.Web.ApiClients/GeneratedApiClients.cs
  src/Frontend/FluentCMS.Web.ApiClients/config.nswag
  src/Frontend/FluentCMS.Web.UI.Components/Components/Form/FormRichTextEditor/FormRichTextEditor.razor.cs
  src/Frontend/FluentCMS.Web.UI/Components/PluginContainer.razor
  src/Frontend/FluentCMS.Web.UI/Components/SiteBuilderForms.razor
  src/Frontend/FluentCMS.Web.UI/Components/SiteBuilderForms.razor.cs
  src/Frontend/FluentCMS.Web.UI/wwwroot/js/api.js
  src/Frontend/FluentCMS.Web.UI/wwwroot/js/columns.js
  src/Frontend/FluentCMS.Web.UI/wwwroot/js/request.js
  src/Frontend/Plugins/FluentCMS.Web.Plugins.Admin/ContentTypeManagement/Components/SingleFile/SingleFileFieldFormFilePicker.razor.cs
  src/Frontend/Plugins/FluentCMS.Web.Plugins.Admin/FileManagement/FileListPlugin.razor.cs
  src/Frontend/Plugins/FluentCMS.Web.Plugins.Admin/FileManagement/Files/FileUploadModal.razor.cs
  src/Frontend/Plugins/FluentCMS.Web.Plugins.Admin/PageManagement/PageCreatePlugin.razor.cs
  src/Frontend/Plugins/FluentCMS.Web.Plugins.Admin/PageManagement/PageListPlugin.razor.cs
  src/Frontend/Plugins/FluentCMS.Web.Plugins.Admin/PageManagement/PageUpdatePlugin.razor.cs
  src/Frontend/Plugins/FluentCMS.Web.Plugins.Admin/PageManagement/SelectOption.cs
Labels: enhancement

#1858 #1853 Implement Edit and Detail Layouts for site and page
  src/Backend/FluentCMS.Entities/Sites/Page.cs
  src/Backend/FluentCMS.Entities/Sites/Site.cs
  src/Backend/FluentCMS.Web.Api/Controllers/PageController.cs
  src/Backend/FluentCMS.Web.Api/Models/Pages/PageCreateRequest.cs
  src/Backend/FluentCMS.Web.Api/Models/Pages/PageDetailResponse.cs
  src/Backend/FluentCMS.Web.Api/Models/Pages/PageFullDetailResponse.cs
  src/Backend/FluentCMS.Web.Api/Models/Site/SiteCreateRequest.cs
  src/Backend/FluentCMS.Web.Api/Models/Site/SiteDetailResponse.cs
  src/Backend/FluentCMS.Web.Api/Setup/Models/AdminTemplate.cs
  src/Backend/FluentCMS.Web.Api/Setup/Models/PageTemplate.cs
  src/Backend/FluentCMS.Web.Api/Setup/Models/SiteTemplate.cs
  src/Backend/FluentCMS.Web.Api/Setup/SetupManager.cs
  src/FluentCMS/Template/EditLayout.body.html
  src/FluentCMS/Template/EditLayout.head.html
  src/FluentCMS/Template/EditLayout.html
  src/FluentCMS/Template/SingleLayout.body.html
  src/FluentCMS/Template/SingleLayout.head.html
  src/FluentCMS/Template/SingleLayout.html
  src/FluentCMS/Template/manifest.json
  src/Frontend/FluentCMS.Web.ApiClients/GeneratedApiClients.cs
  src/Frontend/FluentCMS.Web.UI/Default.razor
  src/Frontend/FluentCMS.Web.UI/PluginsSection.razor
  src/Frontend/FluentCMS.Web.UI/ServiceExtensions.cs
  src/Frontend/Plugins/FluentCMS.Web.Plugins.Admin/SiteManagement/SiteCreatePlugin.razor
  src/Frontend/Plugins/FluentCMS.Web.Plugins.Admin/SiteManagement/SiteUpdatePlugin.razor
  src/Shared/ViewState.cs
Labels: enhancement

#1864 Add Settings property to Plugin classes; update SetupManager
  src/Backend/FluentCMS.Entities/Sites/Plugin.cs
  src/Backend/FluentCMS.Web.Api/Controllers/PluginController.cs
  src/Backend/FluentCMS.Web.Api/Models/Plugin/PluginCreateRequest.cs
  src/Backend/FluentCMS.Web.Api/Models/Plugin/PluginDetailResponse.cs
  src/Backend/FluentCMS.Web.Api/Models/Plugin/PluginUpdateRequest.cs
  src/Backend/FluentCMS.Web.Api/Setup/SetupManager.cs
  src/Frontend/FluentCMS.Web.ApiClients/GeneratedApiClients.cs
  src/Frontend/FluentCMS.Web.ApiClients/config.nswag
  src/Frontend/FluentCMS.Web.UI/Components/SiteBuilderForms.razor.cs
  src/Frontend/FluentCMS.Web.UI/ServiceExtensions.cs
Labels: enhancement

#1866 1820 api authorizatrion by babak
  src/Backend/FluentCMS.Entities/ApiToken.cs
  src/Backend/FluentCMS.Services/ApiTokenProvider.cs
  src/Backend/FluentCMS.Services/ApiTokenService.cs
  src/Backend/FluentCMS.Services/Providers/ApiTokenProviders/ApiTokenProvider.cs
  src/Backend/FluentCMS.Services/Providers/ApiTokenProviders/IApiTokenProvider.cs
  src/Backend/FluentCMS.Web.Api/Attributes/PolicyAttribute.cs
  src/Backend/FluentCMS.Web.Api/Controllers/AccountController.cs
  src/Backend/FluentCMS.Web.Api/Controllers/ApiTokenController.cs
  src/Backend/FluentCMS.Web.Api/Controllers/BaseController.cs
  src/Backend/FluentCMS.Web.Api/Controllers/FileController.cs
  src/Backend/FluentCMS.Web.Api/Controllers/PageController.cs
  src/Backend/FluentCMS.Web.Api/Controllers/PluginContentController.cs
  src/Backend/FluentCMS.Web.Api/Controllers/RoleController.cs
  src/Backend/FluentCMS.Web.Api/Controllers/SetupController.cs
  src/Backend/FluentCMS.Web.Api/Controllers/SiteController.cs
  src/Backend/FluentCMS.Web.Api/Extentions/ConfigurationExtensions.cs
  src/Backend/FluentCMS.Web.Api/Filters/ApiTokenAuthorizeFilter.cs
  src/Backend/FluentCMS.Web.Api/Filters/PolicyAuthorizeFiler.cs
  src/Backend/FluentCMS.Web.Api/MappingProfile.cs
  src/Backend/FluentCMS.Web.Api/Models/ApiToken/ApiTokenDetailResponse.cs
  src/Backend/FluentCMS.Web.Api/Models/ApiToken/ApiTokenUpdateRequest.cs
  src/Backend/FluentCMS.Web.Api/Setup/ISetupManager.cs
  src/Backend/FluentCMS.Web.Api/Setup/SetupManager.cs
  src/Backend/Repositories/FluentCMS.Repositories.Abstractions/IApiTokenRepository.cs
  src/Backend/Repositories/FluentCMS.Repositories.LiteDb/ApiTokenRepository.cs
  src/Backend/Repositories/FluentCMS.Repositories.MongoDB/ApiTokenRepository.cs
  src/FluentCMS/Config/appsettings.json
  src/FluentCMS/Program.cs
  src/FluentCMS/appsettings.json
  src/Frontend/FluentCMS.Web.ApiClients/ApiClientServiceExtensions.cs
  src/Frontend/FluentCMS.Web.ApiClients/ApiSettings.cs
  src/Frontend/FluentCMS.Web.ApiClients/GeneratedApiClients.cs
  src/Frontend/FluentCMS.Web.ApiClients/config.nswag
  src/Frontend/Plugins/FluentCMS.Web.Plugins.Admin/ApiTokenManagement/ApiTokenListPlugin.razor
  src/Frontend/Plugins/FluentCMS.Web.Plugins.Admin/ContentTypeManagement/Components/SingleFile/SingleFileFieldFormFilePicker.razor.cs
  src/Shared/Exceptions/ExceptionCodes.cs
Labels: enhancement

#1874 1806 refactor role management by babak
  src/Backend/FluentCMS.Entities/Role.cs
  src/Backend/FluentCMS.Entities/Sites/Role.cs
  src/Backend/FluentCMS.Services/RoleService.cs
  src/Backend/FluentCMS.Services/SiteService.cs
  src/Backend/FluentCMS.Web.Api/Controllers/ApiTokenController.cs
  src/Backend/FluentCMS.Web.Api/Controllers/RoleController.cs
  src/Backend/FluentCMS.Web.Api/Controllers/SiteController.cs
  src/Backend/FluentCMS.Web.Api/Models/Roles/RoleCreateRequest.cs
  src/Backend/FluentCMS.Web.Api/Models/Roles/RoleDetailResponse.cs
  src/Backend/FluentCMS.Web.Api/Setup/Models/AdminTemplate.cs
  src/Backend/FluentCMS.Web.Api/Setup/SetupManager.cs
  src/Backend/Repositories/FluentCMS.Repositories.Abstractions/IRoleRepository.cs
  src/Backend/Repositories/FluentCMS.Repositories.LiteDb/RoleRepository.cs
  src/Backend/Repositories/FluentCMS.Repositories.MongoDB/RoleRepository.cs
  src/FluentCMS/Template/manifest.json
  src/Frontend/FluentCMS.Web.ApiClients/GeneratedApiClients.cs
  src/Frontend/FluentCMS.Web.ApiClients/config.nswag
  src/Frontend/Plugins/FluentCMS.Web.Plugins.Admin/ApiTokenManagement/ApiTokenCreatePlugin.razor.cs
  src/Frontend/Plugins/FluentCMS.Web.Plugins.Admin/ApiTokenManagement/ApiTokenUpdatePlugin.razor.cs
  src/Frontend/Plugins/FluentCMS.Web.Plugins.Admin/RoleManagement/RoleCreatePlugin.razor
  src/Frontend/Plugins/FluentCMS.Web.Plugins.Admin/RoleManagement/RoleCreatePlugin.razor.cs
  src/Frontend/Plugins/FluentCMS.Web.Plugins.Admin/RoleManagement/RoleListPlugin.razor.cs
  src/Frontend/Plugins/FluentCMS.Web.Plugins.Admin/RoleManagement/RoleUpdatePlugin.razor
  src/Frontend/Plugins/FluentCMS.Web.Plugins.Admin/RoleManagement/RoleUpdatePlugin.razor.cs
  src/Shared/Exceptions/ExceptionCodes.cs
Labels: enhancement

#1879 #1878 Remove unused component and set OnClose event handler for modals
  src/Frontend/Plugins/FluentCMS.Web.Plugins.Admin/ContentTypeManagement/Components/FieldSettingForm.razor
  src/Frontend/Plugins/FluentCMS.Web.Plugins.Admin/ContentTypeManagement/Components/SingleFile/SingleFilePickerModal.razor
  src/Frontend/Plugins/FluentCMS.Web.Plugins.Admin/ContentTypeManagement/Components/SingleFile/SingleFilePickerModal.razor.cs
  src/Frontend/Plugins/FluentCMS.Web.Plugins.Admin/ContentTypeManagement/ContentType/Components/ContentTypeFieldSelector.razor
  src/Frontend/Plugins/FluentCMS.Web.Plugins.Admin/FileManagement/Files/FileUpdateModal.razor
  src/Frontend/Plugins/FluentCMS.Web.Plugins.Admin/FileManagement/Files/FileUploadModal.razor
  src/Frontend/Plugins/FluentCMS.Web.Plugins.Admin/FileManagement/Folders/FolderCreateModal.razor
  src/Frontend/Plugins/FluentCMS.Web.Plugins.Admin/FileManagement/Folders/FolderUpdateModal.razor
Labels: bug

#1880 #1704 implement redirectTo query parameter
  src/Frontend/FluentCMS.Web.UI/Components/PluginActionsForms.razor
  src/Frontend/FluentCMS.Web.UI/Components/PluginActionsForms.razor.cs
  src/Frontend/FluentCMS.Web.UI/Components/SiteBuilder.razor
  src/Frontend/FluentCMS.Web.UI/Default.razor
  src/Frontend/FluentCMS.Web.UI/Default.razor.cs
  src/Frontend/Plugins/FluentCMS.Web.Plugins.Admin/Componenets/BasePlugin.cs
  src/Frontend/Plugins/FluentCMS.Web.Plugins.Admin/Componenets/FormActions.razor.cs
  src/Frontend/Plugins/FluentCMS.Web.Plugins.Admin/PageManagement/PageListPlugin.razor.cs
  src/Frontend/Plugins/FluentCMS.Web.Plugins.Contents.TextHTML/TextHTMLEditPlugin.razor.cs
Labels: enhancement

#1876 #1865 add enability field to apitoken creation and update form front
  src/Backend/FluentCMS.Web.Api/Controllers/ApiTokenController.cs
  src/Backend/FluentCMS.Web.Api/Models/ApiToken/ApiTokenCreateRequest.cs
  src/FluentCMS/wwwroot/css/app.css
  src/Frontend/FluentCMS.Web.ApiClients/GeneratedApiClients.cs
  src/Frontend/FluentCMS.Web.ApiClients/config.nswag
  src/Frontend/FluentCMS.Web.UI.Components/Components/Icon/Icon.cs
  src/Frontend/FluentCMS.Web.UI.Components/Components/Icon/IconResource.resx
  src/Frontend/FluentCMS.Web.UI.Components/Styles/Flowbite/Components/DataTable.scss
  src/Frontend/FluentCMS.Web.UI.Components/wwwroot/css/flowbite.min.css
  src/Frontend/FluentCMS.Web.UI.Components/wwwroot/css/flowbite.min.css.map
  src/Frontend/Plugins/FluentCMS.Web.Plugins.Admin/ApiTokenManagement/ApiTokenCreatePlugin.razor
  src/Frontend/Plugins/FluentCMS.Web.Plugins.Admin/ApiTokenManagement/ApiTokenListPlugin.razor
  src/Frontend/Plugins/FluentCMS.Web.Plugins.Admin/ApiTokenManagement/ApiTokenListPlugin.razor.cs
  src/Frontend/Plugins/FluentCMS.Web.Plugins.Admin/ApiTokenManagement/ApiTokenUpdatePlugin.razor
  src/Frontend/Plugins/FluentCMS.Web.Plugins.Admin/RoleManagement/RoleCreatePlugin.razor.cs
  src/Frontend/Plugins/FluentCMS.Web.Plugins.Admin/RoleManagement/RoleUpdatePlugin.razor.cs
Labels: enhancement

#1882 #1861 run code analyzer
  src/Backend/FluentCMS.Web.Api/Models/ApiToken/ApiTokenUpdateRequest.cs
  src/Frontend/FluentCMS.Web.UI/Components/SiteBuilderForms.razor.cs
  src/Frontend/FluentCMS.Web.UI/Default.razor.cs
  src/Frontend/FluentCMS.Web.UI/_GlobalUsings.cs
  src/Frontend/Plugins/FluentCMS.Web.Plugins.Admin/ApiTokenManagement/ApiTokenListPlugin.razor.cs
  src/Frontend/Plugins/FluentCMS.Web.Plugins.Admin/Componenets/BasePlugin.cs
  src/Frontend/Plugins/FluentCMS.Web.Plugins.Admin/Componenets/FormActions.razor.cs
  src/Frontend/Plugins/FluentCMS.Web.Plugins.Contents.TextHTML/TextHTMLEditPlugin.razor.cs
Labels: enhancement

#1883 MessageBus Concept And Primary Roles Creation Per Site Is Added
  src/Backend/FluentCMS.Services/ActionNames.cs
  src/Backend/FluentCMS.Services/Providers/MessageBusProviders/IMessageBus.cs
  src/Backend/FluentCMS.Services/Providers/MessageBusProviders/IMessagePublisher.cs
  src/Backend/FluentCMS.Services/Providers/MessageBusProviders/IMessageSubscriber.cs
  src/Backend/FluentCMS.Services/Providers/MessageBusProviders/MessageBus.cs
  src/Backend/FluentCMS.Services/Providers/MessageBusProviders/MessagePublisher.cs
  src/Backend/FluentCMS.Services/Providers/MessageBusProviders/MessageSubscriber.cs
  src/Backend/FluentCMS.Services/RoleService.cs
  src/Backend/FluentCMS.Services/ServiceExtensions.cs
  src/Backend/FluentCMS.Services/SiteService.cs
  src/Backend/FluentCMS.Web.Api/Setup/Models/AdminTemplate.cs
  src/Backend/FluentCMS.Web.Api/Setup/SetupManager.cs
  src/Backend/Repositories/FluentCMS.Repositories.Abstractions/IEntityRepository.cs
  src/Backend/Repositories/FluentCMS.Repositories.LiteDb/EntityRepository.cs
  src/Backend/Repositories/FluentCMS.Repositories.MongoDB/EntityRepository.cs
  src/FluentCMS/Template/manifest.json
Labels: enhancement

#1890 #1877 secret-key-regeneration-generates-same-secret
  src/Backend/FluentCMS.Services/ApiTokenService.cs
  src/Backend/FluentCMS.Services/Providers/ApiTokenProviders/ApiTokenProvider.cs
  src/Backend/FluentCMS.Services/Providers/ApiTokenProviders/DefaultApiTokenProvider.cs
  src/Backend/FluentCMS.Services/Providers/ApiTokenProviders/IApiTokenProvider.cs
  src/Backend/FluentCMS.Web.Api/Controllers/ApiTokenController.cs
  src/Backend/FluentCMS.Web.Api/Filters/ApiTokenAuthorizeFilter.cs
  src/Backend/FluentCMS.Web.Api/Setup/SetupManager.cs
  src/Backend/Repositories/FluentCMS.Repositories.Abstractions/IApiTokenRepository.cs
  src/Backend/Repositories/FluentCMS.Repositories.LiteDb/ApiTokenRepository.cs
  src/Backend/Repositories/FluentCMS.Repositories.MongoDB/ApiTokenRepository.cs
  src/Frontend/Plugins/FluentCMS.Web.Plugins.Admin/ApiTokenManagement/ApiTokenListPlugin.razor
  src/Shared/Exceptions/ExceptionCodes.cs
Labels: enhancement

#1895 Update token provider and fix typo in method name
  src/Backend/FluentCMS.Services/ServiceExtensions.cs
  src/Backend/FluentCMS.Web.Api/Filters/ApiTokenAuthorizeFilter.cs
Labels: bug

#1910 #1909 run analyzer
  src/Frontend/Plugins/FluentCMS.Web.Plugins.Contents.TextHTML/RichText/RichTextEditPlugin.razor.cs
  src/Frontend/Plugins/FluentCMS.Web.Plugins.Contents.TextHTML/TextHTML/TextHTMLEditPlugin.razor.cs
Labels: enhancement

#1912 #1911 update Nuget packages
  src/Backend/FluentCMS.Entities/FluentCMS.Entities.csproj
  src/Backend/FluentCMS.Services/FluentCMS.Services.csproj
  src/Backend/FluentCMS.Web.Api/FluentCMS.Web.Api.csproj
  src/Backend/Repositories/FluentCMS.Repositories.LiteDb/FluentCMS.Repositories.LiteDb.csproj
  src/Backend/Repositories/FluentCMS.Repositories.MongoDB/FluentCMS.Repositories.MongoDB.csproj
  src/Frontend/FluentCMS.Web.UI.Components/FluentCMS.Web.UI.Components.csproj
  src/Frontend/FluentCMS.Web.UI/FluentCMS.Web.UI.csproj
  src/Frontend/Plugins/FluentCMS.Web.Plugins.Admin/FluentCMS.Web.Plugins.Admin.csproj
Labels: enhancement

#1914 #1900 implement message bus using MediatR
  src/Backend/FluentCMS.Services/ApiTokenService.cs
  src/Backend/FluentCMS.Services/FileService.cs
  src/Backend/FluentCMS.Services/FluentCMS.Services.csproj
  src/Backend/FluentCMS.Services/Providers/MessageBusProviders/IMessageBus.cs
  src/Backend/FluentCMS.Services/Providers/MessageBusProviders/IMessageHandler.cs
  src/Backend/FluentCMS.Services/Providers/MessageBusProviders/IMessagePublisher.cs
  src/Backend/FluentCMS.Services/Providers/MessageBusProviders/IMessageSubscriber.cs
  src/Backend/FluentCMS.Services/Providers/MessageBusProviders/InMemoryMessagePublisher.cs
  src/Backend/FluentCMS.Services/Providers/MessageBusProviders/Message.cs
  src/Backend/FluentCMS.Services/Providers/MessageBusProviders/MessageBus.cs
  src/Backend/FluentCMS.Services/Providers/MessageBusProviders/MessageBusServiceExtensions.cs
  src/Backend/FluentCMS.Services/Providers/MessageBusProviders/MessagePublisher.cs
  src/Backend/FluentCMS.Services/Providers/MessageBusProviders/MessageSubscriber.cs
  src/Backend/FluentCMS.Services/RoleService.cs
  src/Backend/FluentCMS.Services/ServiceExtensions.cs
  src/Backend/FluentCMS.Services/SiteService.cs
  src/Backend/FluentCMS.Services/UserService.cs
  src/Backend/FluentCMS.Services/_GlobalUsings.cs
Labels: enhancement

#1917 1885 role feature enhancement amir
  src/Backend/FluentCMS.Entities/Sites/UserRole.cs
  src/Backend/FluentCMS.Entities/User.cs
  src/Backend/FluentCMS.Identity/UserStore_IUserRoleStore.cs
  src/Backend/FluentCMS.Services/ActionNames.cs
  src/Backend/FluentCMS.Services/RoleService.cs
  src/Backend/FluentCMS.Services/UserRoleService.cs
  src/Backend/FluentCMS.Services/UserService.cs
  src/Backend/FluentCMS.Services/UserTokenProvider.cs
  src/Backend/FluentCMS.Web.Api/Controllers/AccountController.cs
  src/Backend/FluentCMS.Web.Api/Controllers/PageController.cs
  src/Backend/FluentCMS.Web.Api/Controllers/RoleController.cs
  src/Backend/FluentCMS.Web.Api/Controllers/UserController.cs
  src/Backend/FluentCMS.Web.Api/Controllers/UserRoleController.cs
  src/Backend/FluentCMS.Web.Api/MappingProfile.cs
  src/Backend/FluentCMS.Web.Api/Models/Pages/PageFullDetailResponse.cs
  src/Backend/FluentCMS.Web.Api/Models/Site/SiteDetailResponse.cs
  src/Backend/FluentCMS.Web.Api/Models/UserRoles/UserRoleDetailResponse.cs
  src/Backend/FluentCMS.Web.Api/Models/UserRoles/UserRoleUpdateRequest.cs
  src/Backend/FluentCMS.Web.Api/Models/Users/UserCreateRequest.cs
  src/Backend/FluentCMS.Web.Api/Models/Users/UserDetailResponse.cs
  src/Backend/FluentCMS.Web.Api/Models/Users/UserLoginResponse.cs
  src/Backend/FluentCMS.Web.Api/Models/Users/UserUpdateRequest.cs
  src/Backend/Repositories/FluentCMS.Repositories.Abstractions/IRoleRepository.cs
  src/Backend/Repositories/FluentCMS.Repositories.Abstractions/IUserRepository.cs
  src/Backend/Repositories/FluentCMS.Repositories.Abstractions/IUserRoleRepository.cs
  src/Backend/Repositories/FluentCMS.Repositories.LiteDb/RoleRepository.cs
  src/Backend/Repositories/FluentCMS.Repositories.LiteDb/UserRepository.cs
  src/Backend/Repositories/FluentCMS.Repositories.LiteDb/UserRoleRepository.cs
  src/Backend/Repositories/FluentCMS.Repositories.MongoDB/RoleRepository.cs
  src/Backend/Repositories/FluentCMS.Repositories.MongoDB/UserRepository.cs
  src/Backend/Repositories/FluentCMS.Repositories.MongoDB/UserRoleRepository.cs
  src/Frontend/FluentCMS.Web.ApiClients/ApiClientFactory.cs
  src/Frontend/FluentCMS.Web.ApiClients/GeneratedApiClients.cs
  src/Frontend/FluentCMS.Web.ApiClients/Services/AuthManager.cs
  src/Frontend/FluentCMS.Web.ApiClients/config.nswag
  src/Frontend/FluentCMS.Web.UI/MappingProfile.cs
  src/Frontend/FluentCMS.Web.UI/ServiceExtensions.cs
  src/Frontend/Plugins/FluentCMS.Web.Plugins.Admin/Componenets/BasePlugin.cs
  src/Frontend/Plugins/FluentCMS.Web.Plugins.Admin/FileManagement/FileListPlugin.razor
  src/Frontend/Plugins/FluentCMS.Web.Plugins.Admin/RoleManagement/RoleListPlugin.razor
  src/Frontend/Plugins/FluentCMS.Web.Plugins.Admin/UserManagement/UserCreatePlugin.razor
  src/Frontend/Plugins/FluentCMS.Web.Plugins.Admin/UserManagement/UserCreatePlugin.razor.cs
  src/Frontend/Plugins/FluentCMS.Web.Plugins.Admin/UserManagement/UserListPlugin.razor
  src/Frontend/Plugins/FluentCMS.Web.Plugins.Admin/UserManagement/UserUpdatePlugin.razor
  src/Frontend/Plugins/FluentCMS.Web.Plugins.Admin/UserManagement/UserUpdatePlugin.razor.cs
  src/Shared/Exceptions/ExceptionCodes.cs
  src/Shared/ViewState.cs
Labels: enhancement

#1919 1885 role feature enhancement amir
  src/Backend/FluentCMS.Web.Api/Controllers/PageController.cs
  src/Backend/FluentCMS.Web.Api/Models/Users/UserCreateRequest.cs
  src/Backend/Repositories/FluentCMS.Repositories.MongoDB/RoleRepository.cs
  src/Frontend/FluentCMS.Web.ApiClients/GeneratedApiClients.cs
  src/Frontend/Plugins/FluentCMS.Web.Plugins.Admin/UserManagement/UserCreatePlugin.razor.cs
Labels: bug

#1920 #1915 permission implementation
  src/Backend/FluentCMS.Entities/Sites/Permission.cs
  src/Backend/FluentCMS.Services/ActionNames.cs
  src/Backend/FluentCMS.Services/PageService.cs
  src/Backend/FluentCMS.Services/PermissionService.cs
  src/Backend/FluentCMS.Services/Permissions/IPermissionManager.cs
  src/Backend/FluentCMS.Services/Permissions/PermissionActionNames.cs
  src/Backend/FluentCMS.Services/Permissions/PermissionManager.cs
  src/Backend/FluentCMS.Services/Permissions/PermissionServiceExtensions.cs
  src/Backend/FluentCMS.Services/ServiceExtensions.cs
  src/Backend/FluentCMS.Services/_GlobalUsings.cs
  src/Backend/FluentCMS.Web.Api/Controllers/PageController.cs
  src/Backend/FluentCMS.Web.Api/Models/Pages/PageCreateRequest.cs
  src/Backend/FluentCMS.Web.Api/Models/Pages/PageDetailResponse.cs
  src/Backend/Repositories/FluentCMS.Repositories.Abstractions/IPermissionRepository.cs
  src/Backend/Repositories/FluentCMS.Repositories.LiteDb/PermissionRepository.cs
  src/Backend/Repositories/FluentCMS.Repositories.MongoDB/PermissionRepository.cs
  src/Frontend/FluentCMS.Web.ApiClients/GeneratedApiClients.cs
  src/Frontend/FluentCMS.Web.ApiClients/config.nswag
  src/Frontend/Plugins/FluentCMS.Web.Plugins.Admin/PageManagement/PageCreatePlugin.razor
  src/Frontend/Plugins/FluentCMS.Web.Plugins.Admin/PageManagement/PageCreatePlugin.razor.cs
  src/Frontend/Plugins/FluentCMS.Web.Plugins.Admin/PageManagement/PageUpdatePlugin.razor
  src/Frontend/Plugins/FluentCMS.Web.Plugins.Admin/PageManagement/PageUpdatePlugin.razor.cs
  src/Shared/Exceptions/ExceptionCodes.cs
Labels: enhancement

#1925 #1923 use separate project for RichText plugin
  src/FluentCMS.sln
  src/FluentCMS/FluentCMS.csproj
  src/FluentCMS/Template/manifest.json
  src/Frontend/FluentCMS.Web.UI/wwwroot/js/request.js
  src/Frontend/Plugins/FluentCMS.Web.Plugins.Contents.RichText/FluentCMS.Web.Plugins.Contents.RichText.csproj
  src/Frontend/Plugins/FluentCMS.Web.Plugins.Contents.RichText/RichText/RichTextContent.cs
  src/Frontend/Plugins/FluentCMS.Web.Plugins.Contents.RichText/RichText/RichTextEditPlugin.razor
  src/Frontend/Plugins/FluentCMS.Web.Plugins.Contents.RichText/RichText/RichTextEditPlugin.razor.cs
  src/Frontend/Plugins/FluentCMS.Web.Plugins.Contents.RichText/RichText/RichTextViewPlugin.razor
  src/Frontend/Plugins/FluentCMS.Web.Plugins.Contents.RichText/RichText/RichTextViewPlugin.razor.cs
  src/Frontend/Plugins/FluentCMS.Web.Plugins.Contents.RichText/_GlobalUsings.cs
  src/Frontend/Plugins/FluentCMS.Web.Plugins.Contents.RichText/_Imports.razor
Labels: enhancement

#1941 #1921 Setup Manager is moved to service layer
  src/Backend/FluentCMS.Services/ServiceExtensions.cs
  src/Backend/FluentCMS.Services/Setup/ISetupManager.cs
  src/Backend/FluentCMS.Services/Setup/Models/AdminTemplate.cs
  src/Backend/FluentCMS.Services/Setup/Models/ContentTypeTemplate.cs
  src/Backend/FluentCMS.Services/Setup/Models/LayoutTemplate.cs
  src/Backend/FluentCMS.Services/Setup/Models/PageTemplate.cs
  src/Backend/FluentCMS.Services/Setup/Models/PluginDefinitionTemplate.cs
  src/Backend/FluentCMS.Services/Setup/Models/PluginTemplate.cs
  src/Backend/FluentCMS.Services/Setup/Models/SetupModel.cs
  src/Backend/FluentCMS.Services/Setup/Models/SiteTemplate.cs
  src/Backend/FluentCMS.Services/Setup/SetupManager.cs
  src/Backend/FluentCMS.Web.Api/Controllers/PageController.cs
  src/Backend/FluentCMS.Web.Api/Controllers/SetupController.cs
  src/Backend/FluentCMS.Web.Api/Extentions/ApiServiceExtensions.cs
  src/Backend/FluentCMS.Web.Api/MappingProfile.cs
  src/Backend/FluentCMS.Web.Api/Setup/ISetupManager.cs
  src/Backend/FluentCMS.Web.Api/Setup/Models/ContentTypeTemplate.cs
  src/FluentCMS/Program.cs
Labels: enhancement

#1947 Restore FluentCMS.Entities namespace and class definitions
  src/Backend/FluentCMS.Entities/SiteAssociatedEntities/Page.cs
  src/Backend/FluentCMS.Entities/SiteAssociatedEntities/Permission.cs
  src/Backend/FluentCMS.Entities/SiteAssociatedEntities/Plugin.cs
  src/Backend/FluentCMS.Entities/SiteAssociatedEntities/PluginContent.cs
  src/Backend/FluentCMS.Entities/SiteAssociatedEntities/Role.cs
  src/Backend/FluentCMS.Entities/SiteAssociatedEntities/Site.cs
  src/Backend/FluentCMS.Entities/SiteAssociatedEntities/SiteAssociatedEntity.cs
  src/Backend/FluentCMS.Entities/SiteAssociatedEntities/UserRole.cs
Labels: enhancement

#1950 #1949 Remove bootstrap page and layout
  src/FluentCMS/Template/Bootstrap.body.html
  src/FluentCMS/Template/Bootstrap.head.html
  src/FluentCMS/Template/manifest.json
Labels: bug

#1948 #1928 implement content list viewer plugin
  src/FluentCMS.sln
  src/FluentCMS/FluentCMS.csproj
  src/FluentCMS/Template/DefaultLayout.body.html
  src/FluentCMS/Template/manifest.json
  src/Frontend/FluentCMS.Web.UI.Components/Components/Stack/Stack.razor.cs
  src/Frontend/FluentCMS.Web.UI.Components/Styles/Flowbite/Components/Badge.scss
  src/Frontend/FluentCMS.Web.UI.Components/Styles/Flowbite/Components/Stack.scss
  src/Frontend/FluentCMS.Web.UI.Components/wwwroot/css/flowbite.min.css
  src/Frontend/FluentCMS.Web.UI.Components/wwwroot/css/flowbite.min.css.map
  src/Frontend/FluentCMS.Web.UI/Components/PageEditorSidebar.razor
  src/Frontend/Plugins/FluentCMS.Web.Plugins.Contents.ContentViewer/ContentListSettingsPlugin.razor
  src/Frontend/Plugins/FluentCMS.Web.Plugins.Contents.ContentViewer/ContentListSettingsPlugin.razor.cs
  src/Frontend/Plugins/FluentCMS.Web.Plugins.Contents.ContentViewer/ContentListViewPlugin.razor
  src/Frontend/Plugins/FluentCMS.Web.Plugins.Contents.ContentViewer/ContentListViewPlugin.razor.cs
  src/Frontend/Plugins/FluentCMS.Web.Plugins.Contents.ContentViewer/FluentCMS.Web.Plugins.Contents.ContentViewer.csproj
  src/Frontend/Plugins/FluentCMS.Web.Plugins.Contents.ContentViewer/_GlobalUsings.cs
  src/Frontend/Plugins/FluentCMS.Web.Plugins.Contents.ContentViewer/_Imports.razor
Labels: enhancement

#1944 Refactor: Introduce new provider architecture
  src/Backend/FluentCMS.Entities/GlobalSettings.cs
  src/Backend/FluentCMS.Services/ApiTokenService.cs
  src/Backend/FluentCMS.Services/FileService.cs
  src/Backend/FluentCMS.Services/FluentCMS.Services.csproj
  src/Backend/FluentCMS.Services/PageService.cs
  src/Backend/FluentCMS.Services/PermissionService.cs
  src/Backend/FluentCMS.Services/Providers/FileStorageProviders/LocalFileStorageProvider.cs
  src/Backend/FluentCMS.Services/Providers/MessageBusProviders/MessageBusServiceExtensions.cs
  src/Backend/FluentCMS.Services/RoleService.cs
  src/Backend/FluentCMS.Services/ServiceExtensions.cs
  src/Backend/FluentCMS.Services/SiteService.cs
  src/Backend/FluentCMS.Services/UserRoleService.cs
  src/Backend/FluentCMS.Services/UserService.cs
  src/Backend/FluentCMS.Services/_GlobalUsings.cs
  src/Backend/FluentCMS.Web.Api/Filters/ApiTokenAuthorizeFilter.cs
  src/Backend/FluentCMS.Web.Api/Models/GlobalSettings/GlobalSettingsUpdateRequest.cs
  src/FluentCMS.sln
  src/FluentCMS/FluentCMS.csproj
  src/FluentCMS/Program.cs
  src/FluentCMS/Template/manifest.json
  src/FluentCMS/appsettings.json
  src/Providers/ApiTokenProviders/FluentCMS.Providers.ApiTokenProviders.Abstractions/FluentCMS.Providers.ApiTokenProviders.Abstractions.csproj
  src/Providers/ApiTokenProviders/FluentCMS.Providers.ApiTokenProviders.Abstractions/IApiTokenProvider.cs
  src/Providers/ApiTokenProviders/FluentCMS.Providers.ApiTokenProviders/FluentCMS.Providers.ApiTokenProviders.csproj
  src/Providers/ApiTokenProviders/FluentCMS.Providers.ApiTokenProviders/JwtApiTokenConfig.cs
  src/Providers/ApiTokenProviders/FluentCMS.Providers.ApiTokenProviders/JwtApiTokenProvider.cs
  src/Providers/ApiTokenProviders/FluentCMS.Providers.ApiTokenProviders/ServiceExtensions.cs
  src/Providers/EmailProviders/FluentCMS.Providers.EmailProviders.Abstractions/FluentCMS.Providers.EmailProviders.Abstractions.csproj
  src/Providers/EmailProviders/FluentCMS.Providers.EmailProviders.Abstractions/IEmailProvider.cs
  src/Providers/EmailProviders/FluentCMS.Providers.EmailProviders/FluentCMS.Providers.EmailProviders.csproj
  src/Providers/EmailProviders/FluentCMS.Providers.EmailProviders/ServiceExtensions.cs
  src/Providers/EmailProviders/FluentCMS.Providers.EmailProviders/SmtpEmailProvider.cs
  src/Providers/EmailProviders/FluentCMS.Providers.EmailProviders/SmtpServerConfig.cs
  src/Providers/FileStorageProviders/FluentCMS.Providers.FileStorageProviders.Abstractions/FluentCMS.Providers.FileStorageProviders.Abstractions.csproj
  src/Providers/FileStorageProviders/FluentCMS.Providers.FileStorageProviders.Abstractions/IFileStorageProvider.cs
  src/Providers/FileStorageProviders/FluentCMS.Providers.FileStorageProviders/FileStorageConfig.cs
  src/Providers/FileStorageProviders/FluentCMS.Providers.FileStorageProviders/FluentCMS.Providers.FileStorageProviders.csproj
  src/Providers/FileStorageProviders/FluentCMS.Providers.FileStorageProviders/LocalFileStorageProvider.cs
  src/Providers/FileStorageProviders/FluentCMS.Providers.FileStorageProviders/ServiceExtensions.cs
  src/Providers/MessageBusProviders/FluentCMS.Providers.MessageBusProviders.Abstractions/FluentCMS.Providers.MessageBusProviders.Abstractions.csproj
  src/Providers/MessageBusProviders/FluentCMS.Providers.MessageBusProviders.Abstractions/IMessageHandler.cs
  src/Providers/MessageBusProviders/FluentCMS.Providers.MessageBusProviders.Abstractions/IMessagePublisher.cs
  src/Providers/MessageBusProviders/FluentCMS.Providers.MessageBusProviders.Abstractions/Message.cs
  src/Providers/MessageBusProviders/FluentCMS.Providers.MessageBusProviders/FluentCMS.Providers.MessageBusProviders.csproj
  src/Providers/MessageBusProviders/FluentCMS.Providers.MessageBusProviders/InMemoryMessagePublisher.cs
  src/Providers/MessageBusProviders/FluentCMS.Providers.MessageBusProviders/ServiceExtensions.cs
Labels: enhancement

#1952 Add TemplateRenderingProviders and update project references
  src/FluentCMS.sln
  src/FluentCMS/FluentCMS.csproj
  src/FluentCMS/Program.cs
  src/FluentCMS/Template/DefaultLayout.body.html
  src/FluentCMS/Template/manifest.json
  src/Frontend/FluentCMS.Web.UI.Components/Components/Form/FormFileUpload/FormFileUpload.razor.cs
  src/Frontend/FluentCMS.Web.UI/DynamicRendering/LayoutProcessor.cs
  src/Frontend/FluentCMS.Web.UI/FluentCMS.Web.UI.csproj
  src/Frontend/Plugins/FluentCMS.Web.Plugins.Contents.ContentViewer/ContentListViewPlugin.razor.cs
  src/Frontend/Plugins/FluentCMS.Web.Plugins.Contents.ContentViewer/FluentCMS.Web.Plugins.Contents.ContentViewer.csproj
  src/Providers/TemplateRenderingProviders/FluentCMS.Providers.TemplateRenderingProviders.Abstractions/FluentCMS.Providers.TemplateRenderingProviders.Abstractions.csproj
  src/Providers/TemplateRenderingProviders/FluentCMS.Providers.TemplateRenderingProviders.Abstractions/ITemplateRenderingProvider.cs
  src/Providers/TemplateRenderingProviders/FluentCMS.Providers.TemplateRenderingProviders/FluentCMS.Providers.TemplateRenderingProviders.csproj
  src/Providers/TemplateRenderingProviders/FluentCMS.Providers.TemplateRenderingProviders/ScribanTemplateRenderingProvider.cs
  src/Providers/TemplateRenderingProviders/FluentCMS.Providers.TemplateRenderingProviders/ServiceExtensions.cs
Labels: enhancement

#1954 #1953 regenerate api clients
  src/Frontend/FluentCMS.Web.ApiClients/GeneratedApiClients.cs
  src/Frontend/FluentCMS.Web.ApiClients/config.nswag
Labels: enhancement

#1956 Improve code readability and formatting
  src/Frontend/Plugins/FluentCMS.Web.Plugins.Contents.ContentViewer/ContentListSettingsPlugin.razor.cs
  src/Providers/TemplateRenderingProviders/FluentCMS.Providers.TemplateRenderingProviders/ScribanTemplateRenderingProvider.cs
Labels: enhancement

#1959 #1918 Seperate UserRoleDelete from UserDelete method in UserService
  src/Backend/FluentCMS.Services/ActionNames.cs
  src/Backend/FluentCMS.Services/UserRoleService.cs
  src/Backend/FluentCMS.Services/UserService.cs
Labels: enhancement
