Repository fluentcms/FluentCMS, pull requests merged in 2024-06, with the labels that each got.

#1555 1554 review conform component
  src/FluentCMS.Web.UI.Components/Components/Confirm/Confirm.razor
  src/FluentCMS.Web.UI.Components/Components/Confirm/Confirm.razor.cs
  src/FluentCMS.Web.UI.Components/Components/Confirm/Confirm.razor.js
  src/FluentCMS.Web.UI.Components/Components/Confirm/Confirm.razor.scss
  src/FluentCMS.Web.UI.Components/Components/Confirm/ConfirmProvider.razor
  src/FluentCMS.Web.UI.Components/Components/Confirm/ConfirmProvider.razor.cs
  src/FluentCMS.Web.UI.Components/Components/Confirm/ConfirmService.cs
  src/FluentCMS.Web.UI.Components/Extensions/UIServiceExtensions.cs
  src/FluentCMS.Web.UI.Components/Styles/App.scss
  src/FluentCMS.Web.UI.Components/wwwroot/css/app.min.css
  src/FluentCMS.Web.UI.Components/wwwroot/css/app.min.css.map
  src/FluentCMS.Web.UI/Plugins/FileManagement/FileManagementListPlugin.razor
  src/FluentCMS.Web.UI/Plugins/RoleManagement/RoleListPlugin.razor
  src/FluentCMS.Web.UI/Plugins/RoleManagement/RoleListPlugin.razor.cs
Labels: enhancement

#1570 #1569 build styles
  src/FluentCMS.Web.UI.Components/wwwroot/css/app.min.css
  src/FluentCMS.Web.UI.Components/wwwroot/css/app.min.css.map
Labels: style

#1568 1424 develop site management plugins
  src/FluentCMS.Web.Api/Controllers/SiteController.cs
  src/FluentCMS.Web.Api/Models/Site/SiteCreateRequest.cs
  src/FluentCMS.Web.ApiClients/GeneratedApiClients.cs
  src/FluentCMS.Web.ApiClients/config.nswag
  src/FluentCMS.Web.UI.Components/wwwroot/css/app.min.css
  src/FluentCMS.Web.UI.Components/wwwroot/css/app.min.css.map
  src/FluentCMS.Web.UI/MappingProfile.cs
  src/FluentCMS.Web.UI/Plugins/SiteManagement/SiteCreatePlugin.razor
  src/FluentCMS.Web.UI/Plugins/SiteManagement/SiteCreatePlugin.razor.cs
  src/FluentCMS.Web.UI/Plugins/SiteManagement/SiteListPlugin.razor
  src/FluentCMS.Web.UI/Plugins/SiteManagement/SiteListPlugin.razor.cs
  src/FluentCMS.Web.UI/Plugins/SiteManagement/SiteUpdatePlugin.razor
  src/FluentCMS.Web.UI/Plugins/SiteManagement/SiteUpdatePlugin.razor.cs
  src/FluentCMS/Template/AdminLayout.body.html
  src/FluentCMS/Template/manifest.json
Labels: enhancement

#1579 Update README.md
  README.md
Labels: documentation

#1580 #1534 resolve user roles issue in User/GetAll
  src/FluentCMS.Web.Api/Controllers/UserController.cs
Labels: bug

#1581 #1549 rename urls to ApiServer
  src/FluentCMS.Web.ApiClients/ApiClientServiceExtensions.cs
  src/FluentCMS/Config/appsettings.json
Labels: enhancement

#1584 #1588 refactor Shred project
  src/Backend/FluentCMS.Common/Exceptions/AppApiClientException.cs
  src/Backend/FluentCMS.Common/Exceptions/AppError.cs
  src/Backend/FluentCMS.Common/Exceptions/AppException.cs
  src/Backend/FluentCMS.Common/Exceptions/ExceptionCodes.cs
  src/Backend/FluentCMS.Common/FluentCMS.Common.csproj
  src/Backend/FluentCMS.Common/IAuthContext.cs
  src/Backend/FluentCMS.Identity/FluentCMS.Identity.csproj
  src/Backend/Repositories/FluentCMS.Repositories.Abstractions/FluentCMS.Repositories.Abstractions.csproj
  src/Backend/Repositories/FluentCMS.Repositories.LiteDb/FluentCMS.Repositories.LiteDb.csproj
  src/Backend/Repositories/FluentCMS.Repositories.MongoDB/FluentCMS.Repositories.MongoDB.csproj
  src/FluentCMS.Web.UI/FluentCMS.Web.UI.csproj
  src/FluentCMS.sln
Labels: enhancement

#1585 Update README.md
  README.md
Labels: documentation

#1587 #1586 refactor `SiteServiceExtensions` extension
  src/FluentCMS.Web.UI.Components/Extensions/UIComponentServiceExtensions.cs
  src/FluentCMS.Web.UI/Services/CmsServiceExtensions.cs
  src/FluentCMS/Program.cs
  src/FluentCMS/SiteServiceExtensions.cs
Labels: enhancement

#1589 #1573 Cleanup modal component
  src/FluentCMS.Web.UI.Components/Components/Modal/Modal.razor
  src/FluentCMS.Web.UI.Components/Components/Modal/Modal.razor.cs
  src/FluentCMS.Web.UI.Components/Components/Modal/Modal.razor.scss
  src/FluentCMS.Web.UI.Components/Components/Modal/ModalContent.razor
  src/FluentCMS.Web.UI.Components/Components/Modal/ModalContent.razor.cs
Labels: enhancement, component

#1591 #1590 build styles
  src/FluentCMS.Web.UI.Components/wwwroot/css/app.min.css
  src/FluentCMS.Web.UI.Components/wwwroot/css/app.min.css.map
Labels: style

#1593 #1592 add meta to content type field
  src/Backend/FluentCMS.Entities/ContentTypeField.cs
  src/Backend/FluentCMS.Entities/ContentTypeFieldSettings.cs
Labels: enhancement

#1594 #1571 add Gutter prop for stack and remove ButtonGroup
  src/FluentCMS.Web.UI.Components/Components/Button/Button.razor.scss
  src/FluentCMS.Web.UI.Components/Components/Button/ButtonGroup.razor
  src/FluentCMS.Web.UI.Components/Components/Button/ButtonGroup.razor.cs
  src/FluentCMS.Web.UI.Components/Components/Confirm/Confirm.razor
  src/FluentCMS.Web.UI.Components/Components/Stack/Stack.cs
  src/FluentCMS.Web.UI.Components/Components/Stack/Stack.razor
  src/FluentCMS.Web.UI.Components/Components/Stack/Stack.razor.cs
  src/FluentCMS.Web.UI.Components/Components/Stack/Stack.razor.scss
  src/FluentCMS.Web.UI.Components/Components/Tabs/TabItem.razor.cs
  src/FluentCMS.Web.UI.Components/Components/Tabs/Tabs.razor.cs
  src/FluentCMS.Web.UI.Components/wwwroot/css/app.min.css
  src/FluentCMS.Web.UI.Components/wwwroot/css/app.min.css.map
  src/FluentCMS.Web.UI/Components/EmptyState.razor
  src/FluentCMS.Web.UI/Components/Form/FormActions.razor
  src/FluentCMS.Web.UI/Plugins/FileManagement/FileManagementEditModal.razor
  src/FluentCMS.Web.UI/Plugins/FileManagement/FileManagementTile.razor
  src/FluentCMS.Web.UI/Plugins/FileManagement/FileManagementUploadModal.razor
  src/FluentCMS.Web.UI/Plugins/Home/AdminHomeViewPlugin.razor
Labels: enhancement

#1561 #1558 Add Type selector and refactor ContentType detail page
  src/FluentCMS.Web.ApiClients/GeneratedApiClients.cs
  src/FluentCMS.Web.ApiClients/config.nswag
  src/FluentCMS.Web.UI.Components/Components/Confirm/Confirm.razor
  src/FluentCMS.Web.UI.Components/Components/Confirm/Confirm.razor.scss
  src/FluentCMS.Web.UI.Components/Components/Form/FormSelect/FormSelect.razor
  src/FluentCMS.Web.UI.Components/Components/Icon/Icon.cs
  src/FluentCMS.Web.UI.Components/Components/Icon/IconResource.resx
  src/FluentCMS.Web.UI.Components/wwwroot/css/app.min.css
  src/FluentCMS.Web.UI.Components/wwwroot/css/app.min.css.map
  src/FluentCMS.Web.UI/Plugins/ContentTypeManagement/Components/ContentTypeFieldCreate.razor
  src/FluentCMS.Web.UI/Plugins/ContentTypeManagement/Components/ContentTypeFieldCreate.razor.cs
  src/FluentCMS.Web.UI/Plugins/ContentTypeManagement/Components/ContentTypeFieldSelector.razor
  src/FluentCMS.Web.UI/Plugins/ContentTypeManagement/Components/ContentTypeFieldSelector.razor.cs
  src/FluentCMS.Web.UI/Plugins/ContentTypeManagement/Components/ContentTypeFieldUpdate.razor
  src/FluentCMS.Web.UI/Plugins/ContentTypeManagement/Components/ContentTypeFieldUpdate.razor.cs
  src/FluentCMS.Web.UI/Plugins/ContentTypeManagement/Components/ContentTypeFieldsList.razor
  src/FluentCMS.Web.UI/Plugins/ContentTypeManagement/Components/ContentTypeFieldsList.razor.cs
  src/FluentCMS.Web.UI/Plugins/ContentTypeManagement/ContentTypeDetailPlugin.razor
  src/FluentCMS.Web.UI/Plugins/ContentTypeManagement/ContentTypeListPlugin.razor
  src/FluentCMS.Web.UI/Plugins/ContentTypeManagement/FieldType.cs
  src/FluentCMS.Web.UI/Plugins/FileManagement/FileManagementListPlugin.razor
  src/FluentCMS.Web.UI/Plugins/Home/AdminHomeViewPlugin.razor
  src/FluentCMS/Template/manifest.json
Labels: enhancement

#1603 #1602 build styles
  src/Frontend/FluentCMS.Web.UI.Components/wwwroot/css/app.min.css
  src/Frontend/FluentCMS.Web.UI.Components/wwwroot/css/app.min.css.map
Labels: style

#1604 1602 build styles
  src/Frontend/FluentCMS.Web.UI.Components/Styles/tailwind.config.js
Labels: style

#1607 #1606 Add missing Field types
  src/Frontend/FluentCMS.Web.UI/Plugins/ContentTypeManagement/FieldType.cs
Labels: enhancement

#1610 #1575 Update Home page
  src/FluentCMS/Template/DefaultLayout.body.html
  src/Frontend/FluentCMS.Web.UI.Components/wwwroot/css/app.min.css
  src/Frontend/FluentCMS.Web.UI.Components/wwwroot/css/app.min.css.map
Labels: enhancement

#1615 #1613 Cleanup Card component
  src/Frontend/FluentCMS.Web.UI.Components/Components/Card/Card.razor
  src/Frontend/FluentCMS.Web.UI.Components/Components/Card/Card.razor.scss
  src/Frontend/FluentCMS.Web.UI.Components/Components/Card/CardActions.razor
  src/Frontend/FluentCMS.Web.UI.Components/Components/Card/CardBody.razor
  src/Frontend/FluentCMS.Web.UI.Components/Components/Card/CardHeader.razor
  src/Frontend/FluentCMS.Web.UI.Components/Components/Card/CardTitle.razor
  src/Frontend/FluentCMS.Web.UI.Components/wwwroot/css/app.min.css
  src/Frontend/FluentCMS.Web.UI.Components/wwwroot/css/app.min.css.map
Labels: enhancement, component

#1618 #1491 delete unused Helper class
  src/Frontend/FluentCMS.Web.UI/Helper.cs
Labels: enhancement

#1620 #1619 moving MappingProfile to ApiClient project
  src/Frontend/FluentCMS.Web.ApiClients/ApiClientServiceExtensions.cs
  src/Frontend/FluentCMS.Web.ApiClients/FluentCMS.Web.ApiClients.csproj
  src/Frontend/FluentCMS.Web.ApiClients/MappingProfile.cs
  src/Frontend/FluentCMS.Web.Plugins/FluentCMS.Web.Plugins.csproj
  src/Frontend/FluentCMS.Web.UI/CmsServiceExtensions.cs
  src/Frontend/FluentCMS.Web.UI/FluentCMS.Web.UI.csproj
Labels: enhancement

#1622 #162 update Nuget packages
  src/Backend/FluentCMS.Entities/FluentCMS.Entities.csproj
  src/Backend/FluentCMS.Services/FluentCMS.Services.csproj
  src/Backend/Repositories/FluentCMS.Repositories.LiteDb/FluentCMS.Repositories.LiteDb.csproj
  src/Frontend/FluentCMS.Web.Plugins/FluentCMS.Web.Plugins.csproj
  src/Frontend/FluentCMS.Web.UI.Components/FluentCMS.Web.UI.Components.csproj
  src/Frontend/FluentCMS.Web.UI/FluentCMS.Web.UI.csproj
Labels: enhancement

#1624 Update FluentCMS.Web.Plugins.Admin.LayoutManagement.csproj
  src/Frontend/Plugins/FluentCMS.Web.Plugins.Admin.LayoutManagement/FluentCMS.Web.Plugins.Admin.LayoutManagement.csproj
Labels: enhancement

#1609 #1576 add Data property to FormSelect
  src/Frontend/FluentCMS.Web.UI.Components/Components/Form/FormSelect/FormSelect.razor
  src/Frontend/FluentCMS.Web.UI.Components/Components/Form/FormSelect/FormSelect.razor.cs
  src/Frontend/Plugins/FluentCMS.Web.Plugins.Admin.SiteManagement/SiteCreatePlugin.razor
  src/Frontend/Plugins/FluentCMS.Web.Plugins.Admin.SiteManagement/SiteUpdatePlugin.razor
Labels: enhancement, component

#1625 #1617 add Plugins project in tailwind watch list and build styles
  src/Frontend/FluentCMS.Web.UI.Components/Styles/tailwind.config.js
  src/Frontend/FluentCMS.Web.UI.Components/wwwroot/css/app.min.css
  src/Frontend/FluentCMS.Web.UI.Components/wwwroot/css/app.min.css.map
Labels: bug

#1626 #1616 Add Indicator component
  src/Frontend/FluentCMS.Web.UI.Components/Components/Indicator/Indicator.razor
  src/Frontend/FluentCMS.Web.UI.Components/Components/Indicator/Indicator.razor.cs
  src/Frontend/FluentCMS.Web.UI.Components/Components/Indicator/Indicator.razor.scss
  src/Frontend/FluentCMS.Web.UI.Components/Styles/App.scss
  src/Frontend/FluentCMS.Web.UI.Components/wwwroot/css/app.min.css
  src/Frontend/FluentCMS.Web.UI.Components/wwwroot/css/app.min.css.map
  src/Frontend/Plugins/FluentCMS.Web.Plugins.Admin.UserManagement/UserListPlugin.razor
Labels: component

#1628 #1627 remove ui component dependency to web ui
  src/FluentCMS/Program.cs
  src/Frontend/FluentCMS.Web.UI/CmsServiceExtensions.cs
  src/Frontend/FluentCMS.Web.UI/FluentCMS.Web.UI.csproj
  src/Frontend/FluentCMS.Web.UI/PluginsSection.razor
Labels: enhancement

#1630 #1629 Web.UI project code review and cleanup
  src/Frontend/FluentCMS.Web.UI/Default.razor.cs
  src/Frontend/FluentCMS.Web.UI/DynamicRendering/LayoutProcessor.cs
  src/Frontend/FluentCMS.Web.UI/PluginContainer.razor.cs
  src/Frontend/FluentCMS.Web.UI/PluginLoader/PluginLoadContext.cs
  src/Frontend/FluentCMS.Web.UI/PluginLoader/PluginLoader.cs
  src/Frontend/FluentCMS.Web.UI/PluginsSection.razor.cs
  src/Frontend/FluentCMS.Web.UI/Services/CmsServiceExtensions.cs
  src/Frontend/FluentCMS.Web.UI/_GlobalUsings.cs
  src/Frontend/FluentCMS.Web.UI/_Imports.razor
Labels: enhancement

#1631 #1259 delete unused Home plugin
  src/FluentCMS/Template/manifest.json
  src/Frontend/Plugins/FluentCMS.Web.Plugins.Admin.Home/AdminHomeViewPlugin.razor
  src/Frontend/Plugins/FluentCMS.Web.Plugins.Admin.Home/HomeViewPlugin.razor
  src/Frontend/Plugins/FluentCMS.Web.Plugins.Admin.Home/_GlobalUsings.cs
Labels: enhancement

#1632 Test publish
  src/FluentCMS/FluentCMS.csproj
  src/Frontend/FluentCMS.Web.UI.Components/FluentCMS.Web.UI.Components.csproj
  src/Frontend/FluentCMS.Web.UI/Services/CmsServiceExtensions.cs
Labels: enhancement

#1645 1644 content type plugin UI enhancement
  src/Backend/FluentCMS.Services/ContentTypeService.cs
  src/FluentCMS/Template/AdminLayout.body.html
  src/FluentCMS/Template/manifest.json
  src/Frontend/Plugins/FluentCMS.Web.Plugins.Admin.ContentTypeManagement/Components/BaseContentTypeFieldComponent.cs
  src/Frontend/Plugins/FluentCMS.Web.Plugins.Admin.ContentTypeManagement/Components/BaseFieldSettingViewComponent.cs
  src/Frontend/Plugins/FluentCMS.Web.Plugins.Admin.ContentTypeManagement/Components/Boolean/BooleanFieldSettings.razor
  src/Frontend/Plugins/FluentCMS.Web.Plugins.Admin.ContentTypeManagement/Components/ContentTypeFieldCreate.razor
  src/Frontend/Plugins/FluentCMS.Web.Plugins.Admin.ContentTypeManagement/Components/ContentTypeFieldCreate.razor.cs
  src/Frontend/Plugins/FluentCMS.Web.Plugins.Admin.ContentTypeManagement/Components/ContentTypeFieldDelete.razor
  src/Frontend/Plugins/FluentCMS.Web.Plugins.Admin.ContentTypeManagement/Components/ContentTypeFieldSettingSelector.razor
  src/Frontend/Plugins/FluentCMS.Web.Plugins.Admin.ContentTypeManagement/Components/ContentTypeFieldSettingSelector.razor.cs
  src/Frontend/Plugins/FluentCMS.Web.Plugins.Admin.ContentTypeManagement/Components/ContentTypeFieldUpdate.razor
  src/Frontend/Plugins/FluentCMS.Web.Plugins.Admin.ContentTypeManagement/Components/ContentTypeFieldUpdate.razor.cs
  src/Frontend/Plugins/FluentCMS.Web.Plugins.Admin.ContentTypeManagement/Components/Number/NumberFieldSettings.razor
  src/Frontend/Plugins/FluentCMS.Web.Plugins.Admin.ContentTypeManagement/Components/String/StringFieldSettings.razor
  src/Frontend/Plugins/FluentCMS.Web.Plugins.Admin.ContentTypeManagement/ContentTypeCreatePlugin.razor
  src/Frontend/Plugins/FluentCMS.Web.Plugins.Admin.ContentTypeManagement/ContentTypeDetailPlugin.razor
  src/Frontend/Plugins/FluentCMS.Web.Plugins.Admin.ContentTypeManagement/ContentTypeDetailPlugin.razor.cs
  src/Frontend/Plugins/FluentCMS.Web.Plugins.Admin.ContentTypeManagement/ContentTypeListPlugin.razor
  src/Frontend/Plugins/FluentCMS.Web.Plugins.Admin.ContentTypeManagement/ContentTypeUpdatePlugin.razor
  src/Frontend/Plugins/FluentCMS.Web.Plugins.Admin.ContentTypeManagement/FieldTypes.cs
Labels: enhancement, component

#1647 #1646 refactor form for field settings
  src/Frontend/Plugins/FluentCMS.Web.Plugins.Admin.ContentTypeManagement/Components/Boolean/BooleanFieldSettings.razor
  src/Frontend/Plugins/FluentCMS.Web.Plugins.Admin.ContentTypeManagement/Components/FieldSettingForm.razor
  src/Frontend/Plugins/FluentCMS.Web.Plugins.Admin.ContentTypeManagement/Components/FieldSettingForm.razor.cs
  src/Frontend/Plugins/FluentCMS.Web.Plugins.Admin.ContentTypeManagement/Components/Number/NumberFieldSettings.razor
  src/Frontend/Plugins/FluentCMS.Web.Plugins.Admin.ContentTypeManagement/Components/String/StringFieldSettings.razor
Labels: enhancement

#1649 1648 add initial sample contents to manifestjson and update setup process
  src/Backend/FluentCMS.Web.Api/Setup/Models/AdminTemplate.cs
  src/Backend/FluentCMS.Web.Api/Setup/Models/ContentTypeTemplate.cs
  src/Backend/FluentCMS.Web.Api/Setup/SetupManager.cs
  src/FluentCMS/Template/manifest.json
Labels: enhancement

#1651 1650 develop initial version for content management plugin
  src/FluentCMS/Template/manifest.json
  src/Frontend/FluentCMS.Web.Plugins/BasePlugin.cs
  src/Frontend/Plugins/FluentCMS.Web.Plugins.Admin.ContentTypeManagement/Content/BaseContentPlugin.cs
  src/Frontend/Plugins/FluentCMS.Web.Plugins.Admin.ContentTypeManagement/Content/ContentCreatePlugin.razor
  src/Frontend/Plugins/FluentCMS.Web.Plugins.Admin.ContentTypeManagement/Content/ContentCreatePlugin.razor.cs
  src/Frontend/Plugins/FluentCMS.Web.Plugins.Admin.ContentTypeManagement/Content/ContentListPlugin.razor
  src/Frontend/Plugins/FluentCMS.Web.Plugins.Admin.ContentTypeManagement/Content/ContentListPlugin.razor.cs
  src/Frontend/Plugins/FluentCMS.Web.Plugins.Admin.ContentTypeManagement/Content/ContentUpdatePlugin.razor
  src/Frontend/Plugins/FluentCMS.Web.Plugins.Admin.ContentTypeManagement/Content/ContentUpdatePlugin.razor.cs
  src/Frontend/Plugins/FluentCMS.Web.Plugins.Admin.ContentTypeManagement/ContentTypeListPlugin.razor
  src/Frontend/Plugins/FluentCMS.Web.Plugins.Admin.ContentTypeManagement/ContentTypeListPlugin.razor.cs
Labels: enhancement, component

#1654 1652 add view features to all content fields
  src/FluentCMS/Template/manifest.json
  src/Frontend/FluentCMS.Web.Plugins/BasePlugin.cs
  src/Frontend/Plugins/FluentCMS.Web.Plugins.Admin.ContentTypeManagement/Components/Boolean/BooleanFieldDataTableView.razor
  src/Frontend/Plugins/FluentCMS.Web.Plugins.Admin.ContentTypeManagement/Components/Boolean/BooleanFieldDataTableView.razor.cs
  src/Frontend/Plugins/FluentCMS.Web.Plugins.Admin.ContentTypeManagement/Components/Boolean/BooleanFieldModel.cs
  src/Frontend/Plugins/FluentCMS.Web.Plugins.Admin.ContentTypeManagement/Components/Boolean/BooleanFieldSettings.razor
  src/Frontend/Plugins/FluentCMS.Web.Plugins.Admin.ContentTypeManagement/Components/IFieldModel.cs
  src/Frontend/Plugins/FluentCMS.Web.Plugins.Admin.ContentTypeManagement/Components/Number/NumberFieldDataTableView.razor
  src/Frontend/Plugins/FluentCMS.Web.Plugins.Admin.ContentTypeManagement/Components/Number/NumberFieldDataTableView.razor.cs
  src/Frontend/Plugins/FluentCMS.Web.Plugins.Admin.ContentTypeManagement/Components/Number/NumberFieldModel.cs
  src/Frontend/Plugins/FluentCMS.Web.Plugins.Admin.ContentTypeManagement/Components/Number/NumberFieldSettings.razor
  src/Frontend/Plugins/FluentCMS.Web.Plugins.Admin.ContentTypeManagement/Components/String/StringFieldDataTableView.razor
  src/Frontend/Plugins/FluentCMS.Web.Plugins.Admin.ContentTypeManagement/Components/String/StringFieldDataTableView.razor.cs
  src/Frontend/Plugins/FluentCMS.Web.Plugins.Admin.ContentTypeManagement/Components/String/StringFieldModel.cs
  src/Frontend/Plugins/FluentCMS.Web.Plugins.Admin.ContentTypeManagement/Components/String/StringFieldSettings.razor
  src/Frontend/Plugins/FluentCMS.Web.Plugins.Admin.ContentTypeManagement/Content/ContentListPlugin.razor
  src/Frontend/Plugins/FluentCMS.Web.Plugins.Admin.ContentTypeManagement/Content/ContentListPlugin.razor.cs
  src/Frontend/Plugins/FluentCMS.Web.Plugins.Admin.ContentTypeManagement/ContentTypeDetailPlugin.razor
  src/Frontend/Plugins/FluentCMS.Web.Plugins.Admin.ContentTypeManagement/ContentTypeDetailPlugin.razor.cs
  src/Frontend/Plugins/FluentCMS.Web.Plugins.Admin.ContentTypeManagement/ContentTypeFieldHelper.cs
Labels: enhancement

#1656 #1655 add create content functionality
  src/FluentCMS/Template/manifest.json
  src/Frontend/Plugins/FluentCMS.Web.Plugins.Admin.ContentTypeManagement/Components/Boolean/BooleanFieldFormCheckbox.razor
  src/Frontend/Plugins/FluentCMS.Web.Plugins.Admin.ContentTypeManagement/Components/Boolean/BooleanFieldFormCheckbox.razor.cs
  src/Frontend/Plugins/FluentCMS.Web.Plugins.Admin.ContentTypeManagement/Components/Boolean/BooleanFieldModel.cs
  src/Frontend/Plugins/FluentCMS.Web.Plugins.Admin.ContentTypeManagement/Components/Boolean/BooleanFieldSettings.razor
  src/Frontend/Plugins/FluentCMS.Web.Plugins.Admin.ContentTypeManagement/Components/IFieldModel.cs
  src/Frontend/Plugins/FluentCMS.Web.Plugins.Admin.ContentTypeManagement/Components/Number/NumberFieldFormInput.razor
  src/Frontend/Plugins/FluentCMS.Web.Plugins.Admin.ContentTypeManagement/Components/Number/NumberFieldFormInput.razor.cs
  src/Frontend/Plugins/FluentCMS.Web.Plugins.Admin.ContentTypeManagement/Components/Number/NumberFieldModel.cs
  src/Frontend/Plugins/FluentCMS.Web.Plugins.Admin.ContentTypeManagement/Components/Number/NumberFieldSettings.razor
  src/Frontend/Plugins/FluentCMS.Web.Plugins.Admin.ContentTypeManagement/Components/String/StringFieldFormText.razor
  src/Frontend/Plugins/FluentCMS.Web.Plugins.Admin.ContentTypeManagement/Components/String/StringFieldFormText.razor.cs
  src/Frontend/Plugins/FluentCMS.Web.Plugins.Admin.ContentTypeManagement/Components/String/StringFieldFormTextArea.razor
  src/Frontend/Plugins/FluentCMS.Web.Plugins.Admin.ContentTypeManagement/Components/String/StringFieldFormTextArea.razor.cs
  src/Frontend/Plugins/FluentCMS.Web.Plugins.Admin.ContentTypeManagement/Components/String/StringFieldModel.cs
  src/Frontend/Plugins/FluentCMS.Web.Plugins.Admin.ContentTypeManagement/Components/String/StringFieldSettings.razor
  src/Frontend/Plugins/FluentCMS.Web.Plugins.Admin.ContentTypeManagement/Content/BaseContentPlugin.cs
  src/Frontend/Plugins/FluentCMS.Web.Plugins.Admin.ContentTypeManagement/Content/ContentCreatePlugin.razor
  src/Frontend/Plugins/FluentCMS.Web.Plugins.Admin.ContentTypeManagement/Content/ContentCreatePlugin.razor.cs
  src/Frontend/Plugins/FluentCMS.Web.Plugins.Admin.ContentTypeManagement/Content/ContentListPlugin.razor.cs
Labels: enhancement

#1657 #1643 #1636 review css for button component and use stack component for action buttons
  src/Frontend/FluentCMS.Web.Plugins/PluginBody.razor
  src/Frontend/FluentCMS.Web.UI.Components/Components/Button/Button.razor.cs
  src/Frontend/FluentCMS.Web.UI.Components/Components/Button/Button.razor.scss
  src/Frontend/FluentCMS.Web.UI.Components/wwwroot/css/app.min.css
  src/Frontend/FluentCMS.Web.UI.Components/wwwroot/css/app.min.css.map
  src/Frontend/Plugins/FluentCMS.Web.Plugins.Admin.RoleManagement/RoleListPlugin.razor
  src/Frontend/Plugins/FluentCMS.Web.Plugins.Admin.SiteManagement/SiteListPlugin.razor
Labels: enhancement

#1659 #1595 review layout and add delete feature
  src/FluentCMS/Template/AdminLayout.body.html
  src/Frontend/Plugins/FluentCMS.Web.Plugins.Admin.LayoutManagement/LayoutCreatePlugin.razor
  src/Frontend/Plugins/FluentCMS.Web.Plugins.Admin.LayoutManagement/LayoutCreatePlugin.razor.cs
  src/Frontend/Plugins/FluentCMS.Web.Plugins.Admin.LayoutManagement/LayoutListPlugin.razor
  src/Frontend/Plugins/FluentCMS.Web.Plugins.Admin.LayoutManagement/LayoutListPlugin.razor.cs
  src/Frontend/Plugins/FluentCMS.Web.Plugins.Admin.LayoutManagement/LayoutUpdatePlugin.razor
  src/Frontend/Plugins/FluentCMS.Web.Plugins.Admin.LayoutManagement/LayoutUpdatePlugin.razor.cs
Labels: enhancement

#1660 1653 numbers are stored as decimal in mongodb for content and content type
  src/Backend/Repositories/FluentCMS.Repositories.MongoDB/MongoDBServiceExtensions.cs
  src/Frontend/Plugins/FluentCMS.Web.Plugins.Admin.ContentTypeManagement/Components/IFieldModel.cs
  src/Frontend/Plugins/FluentCMS.Web.Plugins.Admin.LayoutManagement/LayoutListPlugin.razor.cs
Labels: enhancement

#1668 #1667 Delete unused `EmptyState` component
  src/Frontend/FluentCMS.Web.Plugins/EmptyState.razor
  src/Frontend/FluentCMS.Web.Plugins/EmptyState.razor.cs
Labels: enhancement, component

#1672 #1664 use ComponentTypeOption class for selects
  src/Frontend/Plugins/FluentCMS.Web.Plugins.Admin.ContentTypeManagement/Components/Boolean/BooleanFieldSettings.razor
  src/Frontend/Plugins/FluentCMS.Web.Plugins.Admin.ContentTypeManagement/Components/Boolean/BooleanFieldSettings.razor.cs
  src/Frontend/Plugins/FluentCMS.Web.Plugins.Admin.ContentTypeManagement/Components/Number/NumberFieldSettings.razor
  src/Frontend/Plugins/FluentCMS.Web.Plugins.Admin.ContentTypeManagement/Components/Number/NumberFieldSettings.razor.cs
  src/Frontend/Plugins/FluentCMS.Web.Plugins.Admin.ContentTypeManagement/Components/String/StringFieldSettings.razor
  src/Frontend/Plugins/FluentCMS.Web.Plugins.Admin.ContentTypeManagement/Components/String/StringFieldSettings.razor.cs
Labels: enhancement

#1685 #1683 fix content type field CRUD after refactor
  src/Frontend/FluentCMS.Web.UI.Components/Components/Form/FormSelect/FormSelect.razor.cs
  src/Frontend/Plugins/FluentCMS.Web.Plugins.Admin.ContentTypeManagement/Components/Boolean/BooleanFieldSettings.razor
  src/Frontend/Plugins/FluentCMS.Web.Plugins.Admin.ContentTypeManagement/Components/Date/DateFieldSettings.razor
  src/Frontend/Plugins/FluentCMS.Web.Plugins.Admin.ContentTypeManagement/Components/FieldSettingForm.razor.cs
  src/Frontend/Plugins/FluentCMS.Web.Plugins.Admin.ContentTypeManagement/Components/Number/NumberFieldSettings.razor
  src/Frontend/Plugins/FluentCMS.Web.Plugins.Admin.ContentTypeManagement/Components/String/StringFieldSettings.razor
  src/Frontend/Plugins/FluentCMS.Web.Plugins.Admin.ContentTypeManagement/ContentType/Components/ContentTypeFieldCreate.razor.cs
  src/Frontend/Plugins/FluentCMS.Web.Plugins.Admin.ContentTypeManagement/ContentType/Components/ContentTypeFieldUpdate.razor.cs
  src/Frontend/Plugins/FluentCMS.Web.Plugins.Admin.ContentTypeManagement/ContentType/ContentTypeDetailPlugin.razor
Labels: enhancement

#1687 #1661 Feat update content form and add update content page
  src/Backend/FluentCMS.Services/ContentService.cs
  src/Backend/FluentCMS.Web.Api/Controllers/ContentController.cs
  src/Frontend/FluentCMS.Web.ApiClients/DictionaryJsonConverter.cs
  src/Frontend/FluentCMS.Web.ApiClients/GeneratedApiClients.cs
  src/Frontend/FluentCMS.Web.ApiClients/config.nswag
  src/Frontend/FluentCMS.Web.UI.Components/Components/Form/FormSelect/FormSelect.razor.cs
  src/Frontend/Plugins/FluentCMS.Web.Plugins.Admin.ContentTypeManagement/Content/ContentCreatePlugin.razor
  src/Frontend/Plugins/FluentCMS.Web.Plugins.Admin.ContentTypeManagement/Content/ContentCreatePlugin.razor.cs
  src/Frontend/Plugins/FluentCMS.Web.Plugins.Admin.ContentTypeManagement/Content/ContentListPlugin.razor
  src/Frontend/Plugins/FluentCMS.Web.Plugins.Admin.ContentTypeManagement/Content/ContentUpdatePlugin.razor
  src/Frontend/Plugins/FluentCMS.Web.Plugins.Admin.ContentTypeManagement/Content/ContentUpdatePlugin.razor.cs
Labels: enhancement

#1689 Update README.md
  README.md
Labels: documentation

#1677 #1665 Add Multi select field type
  src/FluentCMS/Template/manifest.json
  src/Frontend/FluentCMS.Web.ApiClients/DictionaryJsonConverter.cs
  src/Frontend/FluentCMS.Web.UI.Components/Components/Form/FormCheckboxGroup/FormCheckboxGroup.razor.cs
  src/Frontend/Plugins/FluentCMS.Web.Plugins.Admin.ContentTypeManagement/Components/MultiSelect/MultiSelectFieldDataTableBadges.razor
  src/Frontend/Plugins/FluentCMS.Web.Plugins.Admin.ContentTypeManagement/Components/MultiSelect/MultiSelectFieldFormCheckboxes.razor
  src/Frontend/Plugins/FluentCMS.Web.Plugins.Admin.ContentTypeManagement/Components/MultiSelect/MultiSelectFieldFormCheckboxes.razor.cs
  src/Frontend/Plugins/FluentCMS.Web.Plugins.Admin.ContentTypeManagement/Components/MultiSelect/MultiSelectFieldModel.cs
  src/Frontend/Plugins/FluentCMS.Web.Plugins.Admin.ContentTypeManagement/Components/MultiSelect/MultiSelectFieldSettings.razor
  src/Frontend/Plugins/FluentCMS.Web.Plugins.Admin.ContentTypeManagement/Components/MultiSelect/MultiSelectFieldSettings.razor.cs
  src/Frontend/Plugins/FluentCMS.Web.Plugins.Admin.ContentTypeManagement/Content/ContentCreatePlugin.razor.cs
  src/Frontend/Plugins/FluentCMS.Web.Plugins.Admin.ContentTypeManagement/Models/FieldTypes.cs
  src/Frontend/Plugins/FluentCMS.Web.Plugins.Admin.ContentTypeManagement/Models/ModelHelpers.cs
Labels: enhancement

#1690 #1680 Add RadioGroup component
  src/Frontend/FluentCMS.Web.UI.Components/Components/Form/FormCheckboxGroup/FormCheckboxGroup.razor.cs
  src/Frontend/FluentCMS.Web.UI.Components/Components/Form/FormRadioGroup/FormRadioGroup.razor
  src/Frontend/FluentCMS.Web.UI.Components/Components/Form/FormRadioGroup/FormRadioGroup.razor.cs
  src/Frontend/FluentCMS.Web.UI.Components/Components/Form/FormRadioGroup/FormRadioGroup.razor.scss
  src/Frontend/FluentCMS.Web.UI.Components/Styles/App.scss
  src/Frontend/Plugins/FluentCMS.Web.Plugins.Admin.ContentTypeManagement/Components/MultiSelect/MultiSelectFieldFormCheckboxes.razor.cs
  src/Frontend/Plugins/FluentCMS.Web.Plugins.Admin.ContentTypeManagement/Components/MultiSelect/MultiSelectFieldSettings.razor.cs
Labels: enhancement

#1691 #1679 cleanup Markdown editor
  src/FluentCMS/Template/manifest.json
  src/Frontend/FluentCMS.Web.UI.Components/Components/Form/FormMarkdownEditor/FormMarkdownEditor.core.css
  src/Frontend/FluentCMS.Web.UI.Components/Components/Form/FormMarkdownEditor/FormMarkdownEditor.razor
  src/Frontend/FluentCMS.Web.UI.Components/Components/Form/FormMarkdownEditor/FormMarkdownEditor.razor.cs
  src/Frontend/FluentCMS.Web.UI.Components/Components/Form/FormMarkdownEditor/FormMarkdownEditor.razor.js
  src/Frontend/FluentCMS.Web.UI.Components/Components/Form/FormMarkdownEditor/FormMarkdownEditor.razor.scss
  src/Frontend/FluentCMS.Web.UI.Components/Styles/App.scss
  src/Frontend/Plugins/FluentCMS.Web.Plugins.Admin.ContentTypeManagement/Components/String/StringFieldFormMarkdownText.razor
Labels: enhancement

#1676 #1669 use select component for date formats
  src/Frontend/Plugins/FluentCMS.Web.Plugins.Admin.ContentTypeManagement/Components/Date/DateFieldSettings.razor
  src/Frontend/Plugins/FluentCMS.Web.Plugins.Admin.ContentTypeManagement/Components/Date/DateFieldSettings.razor.cs
  src/Frontend/Plugins/FluentCMS.Web.Plugins.Admin.ContentTypeManagement/Components/Date/DateFormatOptions.cs
Labels: enhancement

#1697 #1696 Apply UI Changes
  src/FluentCMS/Template/manifest.json
  src/Frontend/FluentCMS.Web.UI.Components/Components/Form/FormMarkdownEditor/FormMarkdownEditor.razor.core.css
  src/Frontend/FluentCMS.Web.UI.Components/Components/Form/FormMarkdownEditor/FormMarkdownEditor.razor.cs
  src/Frontend/FluentCMS.Web.UI.Components/Components/Form/FormMarkdownEditor/FormMarkdownEditor.razor.js
  src/Frontend/FluentCMS.Web.UI.Components/Components/Form/FormMarkdownEditor/README.md
  src/Frontend/FluentCMS.Web.UI.Components/Components/Form/FormRichTextEditor/FormRichTextEditor.razor.js
  src/Frontend/FluentCMS.Web.UI.Components/Components/Form/FormRichTextEditor/README.md
  src/Frontend/FluentCMS.Web.UI.Components/Components/FormBackup/MarkdownEditor/MarkdownEditor.Core.css
  src/Frontend/FluentCMS.Web.UI.Components/Components/FormBackup/MarkdownEditor/MarkdownEditor.razor
  src/Frontend/FluentCMS.Web.UI.Components/Components/FormBackup/MarkdownEditor/MarkdownEditor.razor.cs
  src/Frontend/FluentCMS.Web.UI.Components/Components/FormBackup/MarkdownEditor/MarkdownEditor.scss
  src/Frontend/FluentCMS.Web.UI.Components/Styles/App.scss
  src/Frontend/FluentCMS.Web.UI.Components/wwwroot/js/helpers.js
  src/Frontend/Plugins/FluentCMS.Web.Plugins.Admin.ContentTypeManagement/Components/Boolean/BooleanFieldFormCheckbox.razor
  src/Frontend/Plugins/FluentCMS.Web.Plugins.Admin.ContentTypeManagement/Components/Boolean/BooleanFieldFormSwitch.razor
  src/Frontend/Plugins/FluentCMS.Web.Plugins.Admin.ContentTypeManagement/Components/Boolean/BooleanFieldSettings.razor
  src/Frontend/Plugins/FluentCMS.Web.Plugins.Admin.ContentTypeManagement/Components/Date/DateFieldFormDate.razor
  src/Frontend/Plugins/FluentCMS.Web.Plugins.Admin.ContentTypeManagement/Components/Date/DateFieldFormDateTime.razor
  src/Frontend/Plugins/FluentCMS.Web.Plugins.Admin.ContentTypeManagement/Components/Date/DateFieldFormInput.razor
  src/Frontend/Plugins/FluentCMS.Web.Plugins.Admin.ContentTypeManagement/Components/Date/DateFieldFormTime.razor
  src/Frontend/Plugins/FluentCMS.Web.Plugins.Admin.ContentTypeManagement/Components/Date/DateFieldSettings.razor
  src/Frontend/Plugins/FluentCMS.Web.Plugins.Admin.ContentTypeManagement/Components/MultiSelect/MultiSelectFieldSettings.razor
  src/Frontend/Plugins/FluentCMS.Web.Plugins.Admin.ContentTypeManagement/Components/Number/NumberFieldFormInput.razor
  src/Frontend/Plugins/FluentCMS.Web.Plugins.Admin.ContentTypeManagement/Components/Number/NumberFieldSettings.razor
  src/Frontend/Plugins/FluentCMS.Web.Plugins.Admin.ContentTypeManagement/Components/Select/SelectFieldFormRadioGroup.razor
  src/Frontend/Plugins/FluentCMS.Web.Plugins.Admin.ContentTypeManagement/Components/Select/SelectFieldFormSelect.razor
  src/Frontend/Plugins/FluentCMS.Web.Plugins.Admin.ContentTypeManagement/Components/Select/SelectFieldModel.cs
  src/Frontend/Plugins/FluentCMS.Web.Plugins.Admin.ContentTypeManagement/Components/Select/SelectFieldSettings.razor
  src/Frontend/Plugins/FluentCMS.Web.Plugins.Admin.ContentTypeManagement/Components/String/StringFieldFormMarkdownText.razor
  src/Frontend/Plugins/FluentCMS.Web.Plugins.Admin.ContentTypeManagement/Components/String/StringFieldFormRichText.razor
  src/Frontend/Plugins/FluentCMS.Web.Plugins.Admin.ContentTypeManagement/Components/String/StringFieldFormText.razor
  src/Frontend/Plugins/FluentCMS.Web.Plugins.Admin.ContentTypeManagement/Components/String/StringFieldFormTextArea.razor
  src/Frontend/Plugins/FluentCMS.Web.Plugins.Admin.ContentTypeManagement/Components/String/StringFieldSettings.razor
  src/Frontend/Plugins/FluentCMS.Web.Plugins.Admin.ContentTypeManagement/Content/ContentListPlugin.razor
  src/Frontend/Plugins/FluentCMS.Web.Plugins.Admin.ContentTypeManagement/Models/FieldTypes.cs
  src/Frontend/Plugins/FluentCMS.Web.Plugins.Admin.ContentTypeManagement/Models/ModelHelpers.cs
Labels: enhancement

#1700 #1699 add more content types and fix some minor bugs
  src/FluentCMS/Template/manifest.json
  src/Frontend/FluentCMS.Web.UI.Components/Components/Form/FormRichTextEditor/FormRichTextEditor.razor.scss
  src/Frontend/FluentCMS.Web.UI.Components/wwwroot/css/app.min.css
  src/Frontend/FluentCMS.Web.UI.Components/wwwroot/css/app.min.css.map
  src/Frontend/Plugins/FluentCMS.Web.Plugins.Admin.ContentTypeManagement/Components/Date/DateFieldSettings.razor.cs
  src/Frontend/Plugins/FluentCMS.Web.Plugins.Admin.ContentTypeManagement/Content/ContentCreatePlugin.razor.cs
  src/Frontend/Plugins/FluentCMS.Web.Plugins.Admin.ContentTypeManagement/Content/ContentUpdatePlugin.razor.cs
  src/Frontend/Plugins/FluentCMS.Web.Plugins.Admin.ContentTypeManagement/ContentType/ContentTypeDetailPlugin.razor
Labels: enhancement

#1701 #1698 Use int instead of decimal for FieldModel
  src/Frontend/Plugins/FluentCMS.Web.Plugins.Admin.ContentTypeManagement/Components/Boolean/BooleanFieldFormCheckbox.razor
  src/Frontend/Plugins/FluentCMS.Web.Plugins.Admin.ContentTypeManagement/Components/Boolean/BooleanFieldFormSwitch.razor
  src/Frontend/Plugins/FluentCMS.Web.Plugins.Admin.ContentTypeManagement/Components/Date/DateFieldFormDate.razor
  src/Frontend/Plugins/FluentCMS.Web.Plugins.Admin.ContentTypeManagement/Components/Date/DateFieldFormDateTime.razor
  src/Frontend/Plugins/FluentCMS.Web.Plugins.Admin.ContentTypeManagement/Components/Date/DateFieldFormTime.razor
  src/Frontend/Plugins/FluentCMS.Web.Plugins.Admin.ContentTypeManagement/Components/MultiSelect/MultiSelectFieldModel.cs
  src/Frontend/Plugins/FluentCMS.Web.Plugins.Admin.ContentTypeManagement/Components/Number/NumberFieldFormInput.razor
  src/Frontend/Plugins/FluentCMS.Web.Plugins.Admin.ContentTypeManagement/Components/Select/SelectFieldFormRadioGroup.razor
  src/Frontend/Plugins/FluentCMS.Web.Plugins.Admin.ContentTypeManagement/Components/Select/SelectFieldFormSelect.razor
  src/Frontend/Plugins/FluentCMS.Web.Plugins.Admin.ContentTypeManagement/Components/String/StringFieldFormMarkdownText.razor
  src/Frontend/Plugins/FluentCMS.Web.Plugins.Admin.ContentTypeManagement/Components/String/StringFieldFormRichText.razor
  src/Frontend/Plugins/FluentCMS.Web.Plugins.Admin.ContentTypeManagement/Components/String/StringFieldFormText.razor
  src/Frontend/Plugins/FluentCMS.Web.Plugins.Admin.ContentTypeManagement/Components/String/StringFieldFormTextArea.razor
  src/Frontend/Plugins/FluentCMS.Web.Plugins.Admin.ContentTypeManagement/Models/FieldModel.cs
  src/Frontend/Plugins/FluentCMS.Web.Plugins.Admin.ContentTypeManagement/Models/ModelHelpers.cs
Labels: enhancement

#1708 Update PluginLoader.cs
  src/Frontend/FluentCMS.Web.UI/PluginLoader/PluginLoader.cs
Labels: bug

#1709 Update README.md
  README.md
Labels: documentation

#1711 #1710 run code analyzer
  src/Frontend/FluentCMS.Web.UI/PluginLoader/PluginLoader.cs
  src/Frontend/Plugins/FluentCMS.Web.Plugins.Admin.ContentTypeManagement/Models/ModelHelpers.cs
Labels: enhancement

#1713 1703 develop UI of file and folder management
  src/Backend/FluentCMS.Services/FolderService.cs
  src/Backend/FluentCMS.Web.Api/Controllers/FolderController.cs
  src/FluentCMS.sln
  src/FluentCMS/FluentCMS.csproj
  src/FluentCMS/Template/AdminLayout.body.html
  src/FluentCMS/Template/manifest.json
  src/Frontend/FluentCMS.Web.ApiClients/GeneratedApiClients.cs
  src/Frontend/FluentCMS.Web.ApiClients/MappingProfile.cs
  src/Frontend/FluentCMS.Web.UI.Components/Components/DataTable/DataTable.razor.scss
  src/Frontend/FluentCMS.Web.UI.Components/Components/Icon/Icon.cs
  src/Frontend/FluentCMS.Web.UI.Components/Components/Icon/IconResource.resx
  src/Frontend/Plugins/FluentCMS.Web.Plugins.Admin.FileManagement/FileCreatePlugin.razor
  src/Frontend/Plugins/FluentCMS.Web.Plugins.Admin.FileManagement/FileCreatePlugin.razor.cs
  src/Frontend/Plugins/FluentCMS.Web.Plugins.Admin.FileManagement/FileDetailPlugin.razor
  src/Frontend/Plugins/FluentCMS.Web.Plugins.Admin.FileManagement/FileDetailPlugin.razor.cs
  src/Frontend/Plugins/FluentCMS.Web.Plugins.Admin.FileManagement/FileListPlugin.razor
  src/Frontend/Plugins/FluentCMS.Web.Plugins.Admin.FileManagement/FileListPlugin.razor.cs
  src/Frontend/Plugins/FluentCMS.Web.Plugins.Admin.FileManagement/FileUpdatePlugin.razor
  src/Frontend/Plugins/FluentCMS.Web.Plugins.Admin.FileManagement/FileUpdatePlugin.razor.cs
  src/Frontend/Plugins/FluentCMS.Web.Plugins.Admin.FileManagement/FluentCMS.Web.Plugins.Admin.FileManagement.csproj
  src/Frontend/Plugins/FluentCMS.Web.Plugins.Admin.FileManagement/FolderCreatePlugin.razor
  src/Frontend/Plugins/FluentCMS.Web.Plugins.Admin.FileManagement/FolderCreatePlugin.razor.cs
  src/Frontend/Plugins/FluentCMS.Web.Plugins.Admin.FileManagement/FolderUpdatePlugin.razor
  src/Frontend/Plugins/FluentCMS.Web.Plugins.Admin.FileManagement/FolderUpdatePlugin.razor.cs
  src/Frontend/Plugins/FluentCMS.Web.Plugins.Admin.FileManagement/_GlobalUsings.cs
  src/Frontend/Plugins/FluentCMS.Web.Plugins.Admin.FileManagement/_Imports.razor
Labels: enhancement

#1715 1714 run code analyzer
  src/Backend/Repositories/FluentCMS.Repositories.Abstractions/_GlobalUsings.cs
  src/Frontend/FluentCMS.Web.UI.Components/wwwroot/css/app.min.css
  src/Frontend/FluentCMS.Web.UI.Components/wwwroot/css/app.min.css.map
  src/Frontend/Plugins/FluentCMS.Web.Plugins.Admin.FileManagement/FileCreatePlugin.razor.cs
Labels: enhancement

#1716 Update SlugAttribute.cs
  src/Backend/FluentCMS.Web.Api/Validation/SlugAttribute.cs
Labels: enhancement

#1717 Update IPluginDefinitionRepository.cs
  src/Backend/Repositories/FluentCMS.Repositories.Abstractions/IPluginDefinitionRepository.cs
  src/Backend/Repositories/FluentCMS.Repositories.Abstractions/_GlobalUsings.cs
Labels: enhancement

#1719 Update README.md
  README.md
Labels: documentation

#1721 #1720 action buttons change in fields modal
  src/Backend/Repositories/FluentCMS.Repositories.Abstractions/_GlobalUsings.cs
  src/Frontend/Plugins/FluentCMS.Web.Plugins.Admin.ContentTypeManagement/Components/FieldSettingForm.razor
Labels: enhancement

#1723 #1718 UI enhancements for datatable header etc
  src/Backend/FluentCMS.Web.Api/Controllers/FolderController.cs
  src/Frontend/Plugins/FluentCMS.Web.Plugins.Admin.FileManagement/AssetDetail.cs
  src/Frontend/Plugins/FluentCMS.Web.Plugins.Admin.FileManagement/FileCreatePlugin.razor
  src/Frontend/Plugins/FluentCMS.Web.Plugins.Admin.FileManagement/FileCreatePlugin.razor.cs
  src/Frontend/Plugins/FluentCMS.Web.Plugins.Admin.FileManagement/FileDetailPlugin.razor
  src/Frontend/Plugins/FluentCMS.Web.Plugins.Admin.FileManagement/FileDetailPlugin.razor.cs
  src/Frontend/Plugins/FluentCMS.Web.Plugins.Admin.FileManagement/FileListPlugin.razor
  src/Frontend/Plugins/FluentCMS.Web.Plugins.Admin.FileManagement/FileListPlugin.razor.cs
  src/Frontend/Plugins/FluentCMS.Web.Plugins.Admin.FileManagement/FileUpdatePlugin.razor
  src/Frontend/Plugins/FluentCMS.Web.Plugins.Admin.FileManagement/FileUpdatePlugin.razor.cs
  src/Frontend/Plugins/FluentCMS.Web.Plugins.Admin.FileManagement/Files/FileUpdateModal.razor
  src/Frontend/Plugins/FluentCMS.Web.Plugins.Admin.FileManagement/Files/FileUpdateModal.razor.cs
  src/Frontend/Plugins/FluentCMS.Web.Plugins.Admin.FileManagement/Files/FileUploadModal.razor
  src/Frontend/Plugins/FluentCMS.Web.Plugins.Admin.FileManagement/Files/FileUploadModal.razor.cs
  src/Frontend/Plugins/FluentCMS.Web.Plugins.Admin.FileManagement/FolderCreatePlugin.razor
  src/Frontend/Plugins/FluentCMS.Web.Plugins.Admin.FileManagement/FolderCreatePlugin.razor.cs
  src/Frontend/Plugins/FluentCMS.Web.Plugins.Admin.FileManagement/FolderSelectOption.cs
  src/Frontend/Plugins/FluentCMS.Web.Plugins.Admin.FileManagement/FolderUpdatePlugin.razor
  src/Frontend/Plugins/FluentCMS.Web.Plugins.Admin.FileManagement/FolderUpdatePlugin.razor.cs
  src/Frontend/Plugins/FluentCMS.Web.Plugins.Admin.FileManagement/Folders/FolderCreateModal.razor
  src/Frontend/Plugins/FluentCMS.Web.Plugins.Admin.FileManagement/Folders/FolderCreateModal.razor.cs
  src/Frontend/Plugins/FluentCMS.Web.Plugins.Admin.FileManagement/Folders/FolderUpdateModal.razor
  src/Frontend/Plugins/FluentCMS.Web.Plugins.Admin.FileManagement/Folders/FolderUpdateModal.razor.cs
Labels: enhancement

#1726 #1725 update Nuget packages
  src/Backend/Repositories/FluentCMS.Repositories.LiteDb/FluentCMS.Repositories.LiteDb.csproj
  src/Backend/Repositories/FluentCMS.Repositories.MongoDB/FluentCMS.Repositories.MongoDB.csproj
Labels: enhancement

#1727 Update manifest.json
  src/FluentCMS/Template/manifest.json
Labels: enhancement

#1734 #1732 Add Action Buttons
  src/Frontend/FluentCMS.Web.Plugins/ActionButton.razor
  src/Frontend/FluentCMS.Web.Plugins/ActionButton.razor.cs
  src/Frontend/FluentCMS.Web.Plugins/ActionButtonBack.razor
  src/Frontend/FluentCMS.Web.Plugins/ActionButtonCreate.razor
  src/Frontend/FluentCMS.Web.Plugins/ActionButtonDelete.razor
  src/Frontend/FluentCMS.Web.Plugins/ActionButtonEdit.razor
  src/Frontend/FluentCMS.Web.Plugins/ActionButtonOpen.razor
  src/Frontend/FluentCMS.Web.Plugins/ActionButtons.razor
  src/Frontend/FluentCMS.Web.Plugins/ActionButtons.razor.cs
  src/Frontend/FluentCMS.Web.Plugins/PluginBody.razor
  src/Frontend/FluentCMS.Web.UI.Components/Components/Icon/Icon.cs
  src/Frontend/FluentCMS.Web.UI.Components/Components/Icon/IconResource.resx
  src/Frontend/FluentCMS.Web.UI.Components/wwwroot/css/app.min.css
  src/Frontend/FluentCMS.Web.UI.Components/wwwroot/css/app.min.css.map
  src/Frontend/Plugins/FluentCMS.Web.Plugins.Admin.ApiTokenManagement/ApiTokenListPlugin.razor
  src/Frontend/Plugins/FluentCMS.Web.Plugins.Admin.ContentTypeManagement/Content/ContentListPlugin.razor
  src/Frontend/Plugins/FluentCMS.Web.Plugins.Admin.ContentTypeManagement/ContentType/ContentTypeDetailPlugin.razor
  src/Frontend/Plugins/FluentCMS.Web.Plugins.Admin.ContentTypeManagement/ContentType/ContentTypeListPlugin.razor
  src/Frontend/Plugins/FluentCMS.Web.Plugins.Admin.FileManagement/FileListPlugin.razor
  src/Frontend/Plugins/FluentCMS.Web.Plugins.Admin.FileManagement/FileListPlugin.razor.cs
  src/Frontend/Plugins/FluentCMS.Web.Plugins.Admin.FileManagement/Folders/FolderCreateModal.razor
  src/Frontend/Plugins/FluentCMS.Web.Plugins.Admin.Home/AdminHomeViewPlugin.razor
  src/Frontend/Plugins/FluentCMS.Web.Plugins.Admin.LayoutManagement/LayoutListPlugin.razor
  src/Frontend/Plugins/FluentCMS.Web.Plugins.Admin.RoleManagement/RoleListPlugin.razor
  src/Frontend/Plugins/FluentCMS.Web.Plugins.Admin.SiteManagement/SiteListPlugin.razor
  src/Frontend/Plugins/FluentCMS.Web.Plugins.Admin.UserManagement/UserListPlugin.razor
Labels: enhancement

#1736 1728 pagecontroller has many bugs specially in dynamic mode
  src/Backend/FluentCMS.Web.Api/Controllers/PageController.cs
  src/Backend/Repositories/FluentCMS.Repositories.Abstractions/IQueryableRepository.cs
  src/Backend/Repositories/FluentCMS.Repositories.Abstractions/_GlobalUsings.cs
  src/Frontend/FluentCMS.Web.Plugins/BasePlugin.cs
  src/Frontend/FluentCMS.Web.UI/Default.razor
  src/Frontend/FluentCMS.Web.UI/Default.razor.cs
  src/Frontend/FluentCMS.Web.UI/PluginContainer.razor.cs
  src/Frontend/FluentCMS.Web.UI/PluginsSection.razor
  src/Frontend/FluentCMS.Web.UI/PluginsSection.razor.cs
  src/Frontend/FluentCMS.Web.UI/ServiceExtensions.cs
  src/Frontend/FluentCMS.Web.UI/ViewContext.cs
Labels: bug

#1746 1745 refactor contenttype and content plugins
  src/Backend/FluentCMS.Entities/Content.cs
  src/Backend/FluentCMS.Entities/ContentTypeField.cs
  src/Backend/FluentCMS.Entities/FluentCMS.Entities.csproj
  src/Backend/FluentCMS.Services/ContentService.cs
  src/Backend/FluentCMS.Services/ContentTypeService.cs
  src/Backend/FluentCMS.Web.Api/Controllers/ContentController.cs
  src/Backend/FluentCMS.Web.Api/MappingProfile.cs
  src/Backend/FluentCMS.Web.Api/Models/Content/ContentCreateRequest.cs
  src/Backend/FluentCMS.Web.Api/Models/Content/ContentDetailResponse.cs
  src/Backend/FluentCMS.Web.Api/Models/Content/ContentUpdateRequest.cs
  src/Backend/FluentCMS.Web.Api/Setup/SetupManager.cs
  src/FluentCMS.sln
  src/FluentCMS/Template/manifest.json
  src/Frontend/FluentCMS.Web.ApiClients/DictionaryJsonConverter.cs
  src/Frontend/FluentCMS.Web.ApiClients/FluentCMS.Web.ApiClients.csproj
  src/Frontend/FluentCMS.Web.ApiClients/GeneratedApiClients.cs
  src/Frontend/FluentCMS.Web.ApiClients/config.nswag
  src/Frontend/FluentCMS.Web.UI/PluginContainer.razor.cs
  src/Frontend/FluentCMS.Web.UI/ServiceExtensions.cs
  src/Frontend/Plugins/FluentCMS.Web.Plugins.Admin.ContentTypeManagement/Components/BaseFieldViewComponent.cs
  src/Frontend/Plugins/FluentCMS.Web.Plugins.Admin.ContentTypeManagement/Components/Boolean/BooleanFieldFormCheckbox.razor
  src/Frontend/Plugins/FluentCMS.Web.Plugins.Admin.ContentTypeManagement/Components/Boolean/BooleanFieldFormSwitch.razor
  src/Frontend/Plugins/FluentCMS.Web.Plugins.Admin.ContentTypeManagement/Components/Boolean/BooleanFieldModel.cs
  src/Frontend/Plugins/FluentCMS.Web.Plugins.Admin.ContentTypeManagement/Components/Date/DateFieldFormDate.razor
  src/Frontend/Plugins/FluentCMS.Web.Plugins.Admin.ContentTypeManagement/Components/Date/DateFieldFormDateTime.razor
  src/Frontend/Plugins/FluentCMS.Web.Plugins.Admin.ContentTypeManagement/Components/Date/DateFieldFormTime.razor
  src/Frontend/Plugins/FluentCMS.Web.Plugins.Admin.ContentTypeManagement/Components/Date/DateFieldModel.cs
  src/Frontend/Plugins/FluentCMS.Web.Plugins.Admin.ContentTypeManagement/Components/Date/DateFieldSettings.razor
  src/Frontend/Plugins/FluentCMS.Web.Plugins.Admin.ContentTypeManagement/Components/MultiSelect/MultiSelectFieldFormCheckboxes.razor
  src/Frontend/Plugins/FluentCMS.Web.Plugins.Admin.ContentTypeManagement/Components/MultiSelect/MultiSelectFieldModel.cs
  src/Frontend/Plugins/FluentCMS.Web.Plugins.Admin.ContentTypeManagement/Components/MultiSelect/MultiSelectFieldSettings.razor
  src/Frontend/Plugins/FluentCMS.Web.Plugins.Admin.ContentTypeManagement/Components/Number/NumberFieldDataTableView.razor
  src/Frontend/Plugins/FluentCMS.Web.Plugins.Admin.ContentTypeManagement/Components/Number/NumberFieldFormInput.razor
  src/Frontend/Plugins/FluentCMS.Web.Plugins.Admin.ContentTypeManagement/Components/Number/NumberFieldFormRange.razor
  src/Frontend/Plugins/FluentCMS.Web.Plugins.Admin.ContentTypeManagement/Components/Number/NumberFieldModel.cs
  src/Frontend/Plugins/FluentCMS.Web.Plugins.Admin.ContentTypeManagement/Components/Number/NumberFieldSettings.razor
  src/Frontend/Plugins/FluentCMS.Web.Plugins.Admin.ContentTypeManagement/Components/Select/SelectFieldFormRadioGroup.razor
  src/Frontend/Plugins/FluentCMS.Web.Plugins.Admin.ContentTypeManagement/Components/Select/SelectFieldFormSelect.razor
  src/Frontend/Plugins/FluentCMS.Web.Plugins.Admin.ContentTypeManagement/Components/Select/SelectFieldModel.cs
  src/Frontend/Plugins/FluentCMS.Web.Plugins.Admin.ContentTypeManagement/Components/Select/SelectFieldSettings.razor
  src/Frontend/Plugins/FluentCMS.Web.Plugins.Admin.ContentTypeManagement/Components/String/StringFieldFormMarkdownText.razor
  src/Frontend/Plugins/FluentCMS.Web.Plugins.Admin.ContentTypeManagement/Components/String/StringFieldFormRichText.razor
  src/Frontend/Plugins/FluentCMS.Web.Plugins.Admin.ContentTypeManagement/Components/String/StringFieldFormText.razor
  src/Frontend/Plugins/FluentCMS.Web.Plugins.Admin.ContentTypeManagement/Components/String/StringFieldFormTextArea.razor
  src/Frontend/Plugins/FluentCMS.Web.Plugins.Admin.ContentTypeManagement/Components/String/StringFieldModel.cs
  src/Frontend/Plugins/FluentCMS.Web.Plugins.Admin.ContentTypeManagement/Components/String/StringFieldSettings.razor
  src/Frontend/Plugins/FluentCMS.Web.Plugins.Admin.ContentTypeManagement/Content/ContentCreatePlugin.razor.cs
  src/Frontend/Plugins/FluentCMS.Web.Plugins.Admin.ContentTypeManagement/Content/ContentListPlugin.razor.cs
  src/Frontend/Plugins/FluentCMS.Web.Plugins.Admin.ContentTypeManagement/Content/ContentUpdatePlugin.razor.cs
  src/Frontend/Plugins/FluentCMS.Web.Plugins.Admin.ContentTypeManagement/ContentType/ContentTypeDetailPlugin.razor
  src/Frontend/Plugins/FluentCMS.Web.Plugins.Admin.ContentTypeManagement/ContentType/ContentTypeFieldHelper.cs
  src/Frontend/Plugins/FluentCMS.Web.Plugins.Admin.ContentTypeManagement/Models/FieldModel.cs
  src/Frontend/Plugins/FluentCMS.Web.Plugins.Admin.ContentTypeManagement/Models/FieldTypes.cs
  src/Frontend/Plugins/FluentCMS.Web.Plugins.Admin.ContentTypeManagement/Models/ModelHelpers.cs
  src/Shared/DictionaryJsonConverter.cs
  src/Shared/Shared.csproj
Labels: enhancement

#1738 #1735 add initial ui of site builder
  src/Backend/FluentCMS.Web.Api/Controllers/PluginController.cs
  src/Frontend/FluentCMS.Web.UI/Default.razor
  src/Frontend/FluentCMS.Web.UI/Default.razor.cs
  src/Frontend/FluentCMS.Web.UI/DynamicRendering/LayoutProcessor.cs
  src/Frontend/FluentCMS.Web.UI/FluentCMS.Web.UI.csproj
  src/Frontend/FluentCMS.Web.UI/PageEditorForms.razor
  src/Frontend/FluentCMS.Web.UI/PageEditorForms.razor.cs
  src/Frontend/FluentCMS.Web.UI/PageEditorHeader.razor
  src/Frontend/FluentCMS.Web.UI/PageEditorSidebar.razor
  src/Frontend/FluentCMS.Web.UI/PageEditorSidebar.razor.cs
  src/Frontend/FluentCMS.Web.UI/PageEditorToggler.razor
  src/Frontend/FluentCMS.Web.UI/PluginContainer.razor
  src/Frontend/FluentCMS.Web.UI/PluginContainer.razor.cs
  src/Frontend/FluentCMS.Web.UI/PluginContainerActions.razor
  src/Frontend/FluentCMS.Web.UI/PluginsSection.razor
  src/Frontend/FluentCMS.Web.UI/PluginsSection.razor.cs
  src/Frontend/FluentCMS.Web.UI/ServiceExtensions.cs
  src/Frontend/FluentCMS.Web.UI/ViewContext.cs
  src/Frontend/FluentCMS.Web.UI/_GlobalUsings.cs
  src/Frontend/FluentCMS.Web.UI/wwwroot/css/sitebuilder.css
  src/Frontend/FluentCMS.Web.UI/wwwroot/css/sitebuilder.default.css
  src/Frontend/FluentCMS.Web.UI/wwwroot/css/sitebuilder.preview.css
  src/Frontend/FluentCMS.Web.UI/wwwroot/js/sitebuilder.default.js
  src/Frontend/FluentCMS.Web.UI/wwwroot/js/sitebuilder.js
  src/Frontend/FluentCMS.Web.UI/wwwroot/js/sortable.js
Labels: enhancement

#1750 Update styles of site builder
  src/Frontend/FluentCMS.Web.UI/Default.razor
  src/Frontend/FluentCMS.Web.UI/PageEditorHeader.razor
  src/Frontend/FluentCMS.Web.UI/wwwroot/css/sitebuilder.css
  src/Frontend/FluentCMS.Web.UI/wwwroot/css/sitebuilder.default.css
Labels: enhancement

#1753 #1752 build styles
  src/Frontend/FluentCMS.Web.UI.Components/wwwroot/css/app.min.css
  src/Frontend/FluentCMS.Web.UI.Components/wwwroot/css/app.min.css.map
Labels: enhancement

#1756 Major restructuring in FluentCMS project
  src/Backend/FluentCMS.Common/FluentCMS.Common.csproj
  src/Backend/Repositories/FluentCMS.Repositories.Abstractions/FluentCMS.Repositories.Abstractions.csproj
  src/Backend/Repositories/FluentCMS.Repositories.Abstractions/IAuthContext.cs
  src/FluentCMS.sln
  src/Shared/Exceptions/AppApiClientException.cs
  src/Shared/Exceptions/AppError.cs
  src/Shared/Exceptions/AppException.cs
  src/Shared/Exceptions/ExceptionCodes.cs
Labels: enhancement
