Repository fluentcms/FluentCMS, pull requests merged in 2024-10, with the labels that each got.

#2081 Fix navigation problem when navigate to interactive pages
  src/Frontend/FluentCMS.Web.UI/Components/PluginContainerActions.razor
  src/Frontend/FluentCMS.Web.UI/Components/PluginsSection.razor.cs
  src/Frontend/FluentCMS.Web.UI/Default.razor
  src/Frontend/FluentCMS.Web.UI/Default.razor.cs
  src/Frontend/FluentCMS.Web.UI/ServiceExtensions.cs
  src/Shared/ViewState.cs
  src/Shared/ViewStateExtensions.cs
Labels: bug

#2089 2088 thread safe issue in pluginloader
  src/Frontend/FluentCMS.Web.UI/Components/PluginContainerActions.razor.cs
  src/Frontend/FluentCMS.Web.UI/PluginLoader/PluginLoadContext.cs
  src/Frontend/FluentCMS.Web.UI/PluginLoader/PluginLoader.cs
Labels: bug

#2091 #2084 Update design of blocks Modal
  src/Frontend/FluentCMS.Web.UI.Components/Styles/Flowbite/Components/Modal.scss
  src/Frontend/FluentCMS.Web.UI.Components/Styles/Flowbite/Plugins/Block.scss
  src/Frontend/FluentCMS.Web.UI.Components/wwwroot/css/flowbite.min.css
  src/Frontend/FluentCMS.Web.UI.Components/wwwroot/css/flowbite.min.css.map
  src/Frontend/Plugins/FluentCMS.Web.Plugins.Contents.Block/Components/BlockEmptyView.razor
Labels: enhancement

#2092 #2082 replace fab icon in website builder pages with persist admin toolbar
  src/FluentCMS/Templates/Blank/DefaultLayout.body.html
  src/FluentCMS/Templates/Blank/SingleLayout.body.html
  src/FluentCMS/Templates/Default/DefaultLayout.body.html
  src/FluentCMS/Templates/Default/SingleLayout.body.html
  src/Frontend/FluentCMS.Web.UI/Components/SiteBuilder.razor
  src/Frontend/FluentCMS.Web.UI/Components/SiteBuilderDefaultToolbar.razor
  src/Frontend/FluentCMS.Web.UI/Components/SiteBuilderDefaultToolbar.razor.cs
  src/Frontend/FluentCMS.Web.UI/Components/SiteBuilderFloatingButtons.razor
  src/Frontend/FluentCMS.Web.UI/Components/SiteBuilderFloatingButtons.razor.js
  src/Frontend/FluentCMS.Web.UI/Default.razor
  src/Frontend/FluentCMS.Web.UI/ServiceExtensions.cs
  src/Frontend/FluentCMS.Web.UI/wwwroot/css/floating.css
  src/Frontend/FluentCMS.Web.UI/wwwroot/css/sitebuilder.default.css
Labels: enhancement

#2094 Use Dropdown in plugin toolbar
  src/Frontend/FluentCMS.Web.UI/Components/PluginContainerActions.razor
  src/Frontend/FluentCMS.Web.UI/wwwroot/css/plugin-container.css
Labels: enhancement

#2109 Enable inline edit for text html plugin
  src/FluentCMS/Templates/Default/site.json
  src/Frontend/Plugins/FluentCMS.Web.Plugins.Contents.TextHTML/TextHTMLEditPlugin.razor
  src/Frontend/Plugins/FluentCMS.Web.Plugins.Contents.TextHTML/TextHTMLViewPlugin.razor
  src/Frontend/Plugins/FluentCMS.Web.Plugins.Contents.TextHTML/TextHTMLViewPlugin.razor.cs
Labels: enhancement

#2067 Refactor PageController and add PageDetail class
  src/Backend/FluentCMS.Entities/Settings.cs
  src/Backend/FluentCMS.Entities/SiteAssociatedEntities/Plugin.cs
  src/Backend/FluentCMS.Entities/SiteAssociatedEntities/SiteAssociatedEntity.cs
  src/Backend/FluentCMS.Services/ActionNames.cs
  src/Backend/FluentCMS.Services/FluentCMS.Services.csproj
  src/Backend/FluentCMS.Services/MappingProfile.cs
  src/Backend/FluentCMS.Services/MessageHandlers/BlockMessageHandler.cs
  src/Backend/FluentCMS.Services/MessageHandlers/PluginMessageHandler.cs
  src/Backend/FluentCMS.Services/MessageHandlers/SettingsMessageHandler.cs
  src/Backend/FluentCMS.Services/Models/Helpers.cs
  src/Backend/FluentCMS.Services/Models/SiteTemplate.cs
  src/Backend/FluentCMS.Services/PluginService.cs
  src/Backend/FluentCMS.Services/ServiceConstants.cs
  src/Backend/FluentCMS.Services/ServiceExtensions.cs
  src/Backend/FluentCMS.Services/SettingsService.cs
  src/Backend/FluentCMS.Services/SetupService.cs
  src/Backend/FluentCMS.Services/SiteService.cs
  src/Backend/FluentCMS.Web.Api/Controllers/PageController.cs
  src/Backend/FluentCMS.Web.Api/Controllers/PluginController.cs
  src/Backend/FluentCMS.Web.Api/Controllers/SettingsController.cs
  src/Backend/FluentCMS.Web.Api/Controllers/SetupController.cs
  src/Backend/FluentCMS.Web.Api/Controllers/SiteController.cs
  src/Backend/FluentCMS.Web.Api/Models/BaseAuditableResponse.cs
  src/Backend/FluentCMS.Web.Api/Models/Plugin/PluginDetailResponse.cs
  src/Backend/FluentCMS.Web.Api/Models/Settings/SettingsUpdateRequest.cs
  src/Backend/FluentCMS.Web.Api/Models/Setup/SetupRequest.cs
  src/Backend/FluentCMS.Web.Api/Models/Site/SiteCreateRequest.cs
  src/Backend/FluentCMS.Web.Api/Models/Site/SiteDetailResponse.cs
  src/Backend/FluentCMS.Web.Api/Validation/DomainNameAttribute.cs
  src/Backend/Repositories/FluentCMS.Repositories.Abstractions/IPermissionRepository.cs
  src/Backend/Repositories/FluentCMS.Repositories.Abstractions/IPluginRepository.cs
  src/Backend/Repositories/FluentCMS.Repositories.Abstractions/ISettingsRepository.cs
  src/Backend/Repositories/FluentCMS.Repositories.Abstractions/ISiteAssociatedRepository.cs
  src/Backend/Repositories/FluentCMS.Repositories.Caching/FluentCMS.Repositories.Caching.csproj
  src/Backend/Repositories/FluentCMS.Repositories.Caching/MappingProfile.cs
  src/Backend/Repositories/FluentCMS.Repositories.Caching/PluginRepository.cs
  src/Backend/Repositories/FluentCMS.Repositories.Caching/ServiceExtensions.cs
  src/Backend/Repositories/FluentCMS.Repositories.Caching/SettingsRepository.cs
  src/Backend/Repositories/FluentCMS.Repositories.Caching/SiteAssociatedRepository.cs
  src/Backend/Repositories/FluentCMS.Repositories.LiteDb/LiteDbServiceExtensions.cs
  src/Backend/Repositories/FluentCMS.Repositories.LiteDb/PluginRepository.cs
  src/Backend/Repositories/FluentCMS.Repositories.LiteDb/SettingsRepository.cs
  src/Backend/Repositories/FluentCMS.Repositories.LiteDb/SiteAssociatedRepository.cs
  src/Backend/Repositories/FluentCMS.Repositories.MongoDB/MongoDBServiceExtensions.cs
  src/Backend/Repositories/FluentCMS.Repositories.MongoDB/PluginRepository.cs
  src/Backend/Repositories/FluentCMS.Repositories.MongoDB/SettingsRepository.cs
  src/Backend/Repositories/FluentCMS.Repositories.MongoDB/SiteAssociatedRepository.cs
  src/FluentCMS/Templates/Default/site.json
  src/Frontend/FluentCMS.Web.ApiClients/ApiClientFactory.cs
  src/Frontend/FluentCMS.Web.ApiClients/GeneratedApiClients.cs
  src/Frontend/FluentCMS.Web.ApiClients/MappingProfile.cs
  src/Frontend/FluentCMS.Web.ApiClients/config.nswag
  src/Frontend/Plugins/FluentCMS.Web.Plugins.Admin/SiteManagement/SiteCreateModel.cs
  src/Frontend/Plugins/FluentCMS.Web.Plugins.Admin/SiteManagement/SiteCreatePlugin.razor
  src/Frontend/Plugins/FluentCMS.Web.Plugins.Admin/SiteManagement/SiteCreatePlugin.razor.cs
  src/Frontend/Plugins/FluentCMS.Web.Plugins.Admin/SiteManagement/SiteUpdateModel.cs
  src/Frontend/Plugins/FluentCMS.Web.Plugins.Admin/SiteManagement/SiteUpdatePlugin.razor
  src/Frontend/Plugins/FluentCMS.Web.Plugins.Admin/SiteManagement/SiteUpdatePlugin.razor.cs
  src/Frontend/Plugins/FluentCMS.Web.Plugins.Contents.ContentViewer/ContentListSettingsPlugin.razor.cs
  src/Shared/Exceptions/ExceptionCodes.cs
Labels: enhancement

#2118 #2116 fix page Update plugin after form submit
  src/Frontend/Plugins/FluentCMS.Web.Plugins.Admin/PageManagement/PageUpdatePlugin.razor.cs
Labels: bug

#2120 Fix create plugin error
  src/Backend/FluentCMS.Services/PluginService.cs
Labels: bug

#2117 #2114 Add Hint for some form elements
  src/Frontend/FluentCMS.Web.UI.Components/Styles/Flowbite/Components/Form/FormField.scss
  src/Frontend/FluentCMS.Web.UI.Components/wwwroot/css/flowbite.min.css
  src/Frontend/FluentCMS.Web.UI.Components/wwwroot/css/flowbite.min.css.map
  src/Frontend/Plugins/FluentCMS.Web.Plugins.Admin/LayoutManagement/LayoutCreatePlugin.razor
  src/Frontend/Plugins/FluentCMS.Web.Plugins.Admin/LayoutManagement/LayoutUpdatePlugin.razor
  src/Frontend/Plugins/FluentCMS.Web.Plugins.Admin/PageManagement/PageCreatePlugin.razor
  src/Frontend/Plugins/FluentCMS.Web.Plugins.Admin/PageManagement/PageUpdatePlugin.razor
  src/Frontend/Plugins/FluentCMS.Web.Plugins.Admin/SiteManagement/SiteCreatePlugin.razor
  src/Frontend/Plugins/FluentCMS.Web.Plugins.Admin/SiteManagement/SiteUpdatePlugin.razor
Labels: enhancement

#2125 #2124 add plugin settings modal
  src/Backend/FluentCMS.Web.Api/Controllers/PluginController.cs
  src/FluentCMS/Templates/Blank/manifest.json
  src/FluentCMS/Templates/Default/manifest.json
  src/Frontend/FluentCMS.Web.UI/Components/PluginContainer.razor
  src/Frontend/FluentCMS.Web.UI/Components/PluginContainer.razor.cs
  src/Frontend/FluentCMS.Web.UI/Components/PluginContainerActions.razor
  src/Frontend/FluentCMS.Web.UI/Components/PluginContainerActions.razor.cs
  src/Frontend/FluentCMS.Web.UI/PluginSettingsModel.cs
  src/Frontend/Plugins/FluentCMS.Web.Plugins.Contents.ContentViewer/ContentListEditPlugin.razor
  src/Frontend/Plugins/FluentCMS.Web.Plugins.Contents.ContentViewer/ContentListEditPlugin.razor.cs
Labels: enhancement

#2127 Fix response of settings.Update api
  src/Backend/FluentCMS.Web.Api/Controllers/SettingsController.cs
  src/Backend/FluentCMS.Web.Api/Models/Settings/SettingsDetailResponse.cs
  src/Frontend/FluentCMS.Web.ApiClients/GeneratedApiClients.cs
  src/Frontend/FluentCMS.Web.UI/Components/PluginContainerActions.razor.cs
Labels: enhancement

#2126 #2129 Move edit of plugins to modal
  src/Frontend/FluentCMS.Web.UI/Components/PluginContainer.razor
  src/Frontend/FluentCMS.Web.UI/Components/PluginContainer.razor.cs
  src/Frontend/FluentCMS.Web.UI/Components/PluginContainerActions.razor
  src/Frontend/FluentCMS.Web.UI/Components/PluginContainerActions.razor.cs
  src/Frontend/Plugins/FluentCMS.Web.Plugins.Base/BaseEditPlugin.cs
  src/Frontend/Plugins/FluentCMS.Web.Plugins.Base/Components/PluginModalForm.razor
  src/Frontend/Plugins/FluentCMS.Web.Plugins.Base/Components/PluginModalForm.razor.cs
  src/Frontend/Plugins/FluentCMS.Web.Plugins.Contents.Block/BlockEditPlugin.razor
  src/Frontend/Plugins/FluentCMS.Web.Plugins.Contents.Block/BlockEditPlugin.razor.cs
  src/Frontend/Plugins/FluentCMS.Web.Plugins.Contents.ContentViewer/ContentListEditPlugin.razor
  src/Frontend/Plugins/FluentCMS.Web.Plugins.Contents.ContentViewer/ContentListEditPlugin.razor.cs
  src/Frontend/Plugins/FluentCMS.Web.Plugins.Contents.RichText/RichTextEditPlugin.razor
  src/Frontend/Plugins/FluentCMS.Web.Plugins.Contents.RichText/RichTextEditPlugin.razor.cs
  src/Frontend/Plugins/FluentCMS.Web.Plugins.Contents.TextHTML/TextHTMLEditPlugin.razor
  src/Frontend/Plugins/FluentCMS.Web.Plugins.Contents.TextHTML/TextHTMLEditPlugin.razor.cs
Labels: enhancement

#2134 #2133 fix null reference on inline editor dispose
  src/Frontend/FluentCMS.Web.UI.Components/Components/InlineEditor/InlineEditor.razor.js
Labels: bug

#2138 Refactor cache provider and remove AutoMapper dependency
  src/Backend/Repositories/FluentCMS.Repositories.Caching/EntityRepository.cs
  src/Backend/Repositories/FluentCMS.Repositories.Caching/SiteAssociatedRepository.cs
  src/Backend/Repositories/FluentCMS.Repositories.LiteDb/SiteAssociatedRepository.cs
  src/Providers/CacheProviders/FluentCMS.Providers.CacheProviders.Abstractions/ICacheProvider.cs
  src/Providers/CacheProviders/FluentCMS.Providers.CacheProviders/FluentCMS.Providers.CacheProviders.csproj
  src/Providers/CacheProviders/FluentCMS.Providers.CacheProviders/InMemoryCacheProvider.cs
Labels: enhancement

#2140 #2139 add PageHead component
  src/FluentCMS/Templates/Blank/AdminLayout.head.html
  src/FluentCMS/Templates/Blank/DefaultLayout.head.html
  src/FluentCMS/Templates/Blank/EditLayout.head.html
  src/FluentCMS/Templates/Blank/SingleLayout.head.html
  src/FluentCMS/Templates/Default/AdminLayout.head.html
  src/FluentCMS/Templates/Default/DefaultLayout.head.html
  src/FluentCMS/Templates/Default/EditLayout.head.html
  src/FluentCMS/Templates/Default/SingleLayout.head.html
  src/Frontend/FluentCMS.Web.UI/Components/PageHead.razor
  src/Frontend/FluentCMS.Web.UI/Components/PageHead.razor.cs
  src/Shared/ViewState.cs
Labels: enhancement

#2142 #2101 add more blocks
  src/FluentCMS/Templates/Blank/Blocks/CTA/Image and Button.html
  src/FluentCMS/Templates/Blank/Blocks/CTA/Mobile App.html
  src/FluentCMS/Templates/Blank/Blocks/Content/With Gallery.html
  src/FluentCMS/Templates/Blank/Blocks/Customer Logos/Default.html
  src/FluentCMS/Templates/Blank/Blocks/FAQ/Default.html
  src/FluentCMS/Templates/Blank/Blocks/Schedule/Default.html
  src/FluentCMS/Templates/Blank/Blocks/Social Proof/Card Statistics.html
  src/FluentCMS/Templates/Blank/Blocks/Social Proof/Icon Statistics.html
  src/FluentCMS/Templates/Blank/Blocks/Testimonials/Cards.html
  src/FluentCMS/Templates/Blank/Blocks/Testimonials/Default.html
  src/FluentCMS/Templates/Blank/site.json
  src/FluentCMS/Templates/Default/Blocks/CTA/Image and Button.html
  src/FluentCMS/Templates/Default/Blocks/CTA/Mobile App.html
  src/FluentCMS/Templates/Default/Blocks/Content/With Gallery.html
  src/FluentCMS/Templates/Default/Blocks/Customer Logos/Default.html
  src/FluentCMS/Templates/Default/Blocks/FAQ/Default.html
  src/FluentCMS/Templates/Default/Blocks/Schedule/Default.html
  src/FluentCMS/Templates/Default/Blocks/Social Proof/Card Statistics.html
  src/FluentCMS/Templates/Default/Blocks/Social Proof/Icon Statistics.html
  src/FluentCMS/Templates/Default/Blocks/Testimonials/Cards.html
  src/FluentCMS/Templates/Default/Blocks/Testimonials/Default.html
  src/FluentCMS/Templates/Default/site.json
  src/FluentCMS/wwwroot/images/cta-dashboard-mockup-dark.svg
  src/FluentCMS/wwwroot/images/cta-dashboard-mockup.svg
  src/FluentCMS/wwwroot/images/jese-leos.png
  src/FluentCMS/wwwroot/images/karen-nelson.png
  src/FluentCMS/wwwroot/images/michael-gouch.png
  src/FluentCMS/wwwroot/images/phone-mockup.png
  src/FluentCMS/wwwroot/images/roberta-casas.png
Labels: enhancement

#2149 add validation for page settings modal
  src/Frontend/FluentCMS.Web.UI.Components/Components/Form/FormSelect/FormSelect.razor
  src/Frontend/FluentCMS.Web.UI.Components/Styles/Flowbite/Components/Modal.scss
  src/Frontend/FluentCMS.Web.UI.Components/wwwroot/css/flowbite.min.css
  src/Frontend/FluentCMS.Web.UI/Components/PageSettingsModal.razor
  src/Frontend/FluentCMS.Web.UI/Components/PageSettingsModal.razor.cs
  src/Frontend/FluentCMS.Web.UI/PageSettingsModel.cs
  src/Frontend/Plugins/FluentCMS.Web.Plugins.Admin/PageManagement/PageSettingsModel.cs
  src/Frontend/Plugins/FluentCMS.Web.Plugins.Admin/PageManagement/PageUpdatePlugin.razor.cs
Labels: enhancement

#2154 Update various package versions across multiple projects
  src/Backend/FluentCMS.Entities/FluentCMS.Entities.csproj
  src/Backend/FluentCMS.Services/FluentCMS.Services.csproj
  src/Backend/FluentCMS.Web.Api/FluentCMS.Web.Api.csproj
  src/Backend/Repositories/FluentCMS.Repositories.Caching/FluentCMS.Repositories.Caching.csproj
  src/Backend/Repositories/FluentCMS.Repositories.MongoDB/FluentCMS.Repositories.MongoDB.csproj
  src/Backend/Repositories/FluentCMS.Repositories.MongoDB/MongoDBServiceExtensions.cs
  src/Frontend/FluentCMS.Web.ApiClients/FluentCMS.Web.ApiClients.csproj
  src/Frontend/FluentCMS.Web.UI.Components/FluentCMS.Web.UI.Components.csproj
  src/Frontend/FluentCMS.Web.UI/FluentCMS.Web.UI.csproj
  src/Frontend/Plugins/FluentCMS.Web.Plugins.Admin/FluentCMS.Web.Plugins.Admin.csproj
  src/Providers/ApiTokenProviders/FluentCMS.Providers.ApiTokenProviders/FluentCMS.Providers.ApiTokenProviders.csproj
  src/Providers/CacheProviders/FluentCMS.Providers.CacheProviders/FluentCMS.Providers.CacheProviders.csproj
  src/Providers/MessageBusProviders/FluentCMS.Providers.MessageBusProviders/FluentCMS.Providers.MessageBusProviders.csproj
  src/Providers/TemplateRenderingProviders/FluentCMS.Providers.TemplateRenderingProviders/FluentCMS.Providers.TemplateRenderingProviders.csproj
Labels: enhancement

#2158 #1425 add Definition list plugin and update order of admin sidebar items
  src/Backend/FluentCMS.Entities/PluginDefinition.cs
  src/Backend/FluentCMS.Web.Api/Models/PluginDefinition/PluginDefinitionDetailResponse.cs
  src/FluentCMS/Templates/Blank/manifest.json
  src/FluentCMS/Templates/Blank/site.json
  src/FluentCMS/Templates/Default/manifest.json
  src/FluentCMS/Templates/Default/site.json
  src/Frontend/FluentCMS.Web.ApiClients/GeneratedApiClients.cs
  src/Frontend/FluentCMS.Web.UI/Components/AdminSidebar.razor
  src/Frontend/FluentCMS.Web.UI/Components/SiteBuilderPreview.razor
  src/Frontend/Plugins/FluentCMS.Web.Plugins.Admin/PluginDefinitionManagement/DefinitionListPlugin.razor
  src/Frontend/Plugins/FluentCMS.Web.Plugins.Admin/PluginDefinitionManagement/DefinitionListPlugin.razor.cs
Labels: enhancement

#2156 #2155 add roles for Site update
  src/Backend/FluentCMS.Web.Api/Controllers/SiteController.cs
  src/Backend/FluentCMS.Web.Api/Models/Site/SiteDetailResponse.cs
  src/Backend/FluentCMS.Web.Api/Models/Site/SiteUpdateRequest.cs
  src/Frontend/FluentCMS.Web.ApiClients/GeneratedApiClients.cs
  src/Frontend/FluentCMS.Web.ApiClients/config.nswag
  src/Frontend/Plugins/FluentCMS.Web.Plugins.Admin/SiteManagement/SiteUpdateModel.cs
  src/Frontend/Plugins/FluentCMS.Web.Plugins.Admin/SiteManagement/SiteUpdatePlugin.razor
  src/Frontend/Plugins/FluentCMS.Web.Plugins.Admin/SiteManagement/SiteUpdatePlugin.razor.cs
Labels: enhancement

#2163 #2162 Show All pages in page List plugin
  src/Frontend/Plugins/FluentCMS.Web.Plugins.Admin/PageManagement/PageListPlugin.razor
  src/Frontend/Plugins/FluentCMS.Web.Plugins.Admin/PageManagement/PageListPlugin.razor.cs
Labels: enhancement

#2177 #2176 fix scrollbar and modal problems
  src/Frontend/FluentCMS.Web.UI.Components/Components/Modal/Modal.cs
  src/Frontend/FluentCMS.Web.UI.Components/Components/Modal/Modal.razor.cs
  src/Frontend/FluentCMS.Web.UI.Components/Styles/Flowbite/Components/Modal.scss
  src/Frontend/FluentCMS.Web.UI.Components/wwwroot/css/flowbite.min.css
  src/Frontend/FluentCMS.Web.UI.Components/wwwroot/css/flowbite.min.css.map
  src/Frontend/FluentCMS.Web.UI/Components/PageSettingsModal.razor
  src/Frontend/FluentCMS.Web.UI/Components/SiteBuilder.razor.js
  src/Frontend/FluentCMS.Web.UI/wwwroot/css/sitebuilder.editor.css
Labels: enhancement

#2188 #2187 Fix logout problem
  src/Frontend/FluentCMS.Web.UI/Components/SiteBuilder.razor
  src/Frontend/FluentCMS.Web.UI/Components/SiteBuilderDefaultToolbar.razor
  src/Frontend/Plugins/FluentCMS.Web.Plugins.Admin/Auth/LogoutViewPlugin.razor.cs
Labels: bug

#2194 #2190 allow single component in layouts.
  src/Frontend/FluentCMS.Web.UI/DynamicRendering/LayoutProcessor.cs
Labels: bug

#2196 #2111 Run formatter for Scss files
  src/Frontend/FluentCMS.Web.UI.Components/Styles/Flowbite/Components/Accordion.scss
  src/Frontend/FluentCMS.Web.UI.Components/Styles/Flowbite/Components/Alert.scss
  src/Frontend/FluentCMS.Web.UI.Components/Styles/Flowbite/Components/Avatar.scss
  src/Frontend/FluentCMS.Web.UI.Components/Styles/Flowbite/Components/Badge.scss
  src/Frontend/FluentCMS.Web.UI.Components/Styles/Flowbite/Components/Breadcrumb.scss
  src/Frontend/FluentCMS.Web.UI.Components/Styles/Flowbite/Components/Card.scss
  src/Frontend/FluentCMS.Web.UI.Components/Styles/Flowbite/Components/CloseButton.scss
  src/Frontend/FluentCMS.Web.UI.Components/Styles/Flowbite/Components/Confirm.scss
  src/Frontend/FluentCMS.Web.UI.Components/Styles/Flowbite/Components/DataTable.scss
  src/Frontend/FluentCMS.Web.UI.Components/Styles/Flowbite/Components/Dropdown.scss
  src/Frontend/FluentCMS.Web.UI.Components/Styles/Flowbite/Components/Form/FormAutocomplete.scss
  src/Frontend/FluentCMS.Web.UI.Components/Styles/Flowbite/Components/Form/FormCheckbox.scss
  src/Frontend/FluentCMS.Web.UI.Components/Styles/Flowbite/Components/Form/FormField.scss
  src/Frontend/FluentCMS.Web.UI.Components/Styles/Flowbite/Components/Form/FormFileUpload.scss
  src/Frontend/FluentCMS.Web.UI.Components/Styles/Flowbite/Components/Form/FormMarkdownEditor.scss
  src/Frontend/FluentCMS.Web.UI.Components/Styles/Flowbite/Components/Form/FormRadioGroup.scss
  src/Frontend/FluentCMS.Web.UI.Components/Styles/Flowbite/Components/Form/FormRichTextEditor.scss
  src/Frontend/FluentCMS.Web.UI.Components/Styles/Flowbite/Components/Form/FormSelect.scss
  src/Frontend/FluentCMS.Web.UI.Components/Styles/Flowbite/Components/Form/FormSwitch.scss
  src/Frontend/FluentCMS.Web.UI.Components/Styles/Flowbite/Components/Form/FormTreeSelector.scss
  src/Frontend/FluentCMS.Web.UI.Components/Styles/Flowbite/Components/Grid.scss
  src/Frontend/FluentCMS.Web.UI.Components/Styles/Flowbite/Components/Icon.scss
  src/Frontend/FluentCMS.Web.UI.Components/Styles/Flowbite/Components/Indicator.scss
  src/Frontend/FluentCMS.Web.UI.Components/Styles/Flowbite/Components/InlineEditor.scss
  src/Frontend/FluentCMS.Web.UI.Components/Styles/Flowbite/Components/Modal.scss
  src/Frontend/FluentCMS.Web.UI.Components/Styles/Flowbite/Components/Pagination.scss
  src/Frontend/FluentCMS.Web.UI.Components/Styles/Flowbite/Components/Spacer.scss
  src/Frontend/FluentCMS.Web.UI.Components/Styles/Flowbite/Components/Spinner.scss
  src/Frontend/FluentCMS.Web.UI.Components/Styles/Flowbite/Components/Stack.scss
  src/Frontend/FluentCMS.Web.UI.Components/Styles/Flowbite/Components/Stepper.scss
  src/Frontend/FluentCMS.Web.UI.Components/Styles/Flowbite/Components/Tabs.scss
  src/Frontend/FluentCMS.Web.UI.Components/Styles/Flowbite/Components/Toast.scss
  src/Frontend/FluentCMS.Web.UI.Components/Styles/Flowbite/Components/Tooltip.scss
  src/Frontend/FluentCMS.Web.UI.Components/Styles/Flowbite/Components/Typography.scss
  src/Frontend/FluentCMS.Web.UI.Components/Styles/Flowbite/Plugins/Block.scss
  src/Frontend/FluentCMS.Web.UI.Components/wwwroot/css/flowbite.min.css
  src/Frontend/FluentCMS.Web.UI.Components/wwwroot/css/flowbite.min.css.map
Labels: enhancement

#2195 #2192 run formatter for Blocks and review data-inline-editable props
  src/FluentCMS/Templates/Blank/Blocks/CTA/Default.html
  src/FluentCMS/Templates/Blank/Blocks/CTA/Image and Button.html
  src/FluentCMS/Templates/Blank/Blocks/CTA/Mobile App.html
  src/FluentCMS/Templates/Blank/Blocks/CTA/With Heading.html
  src/FluentCMS/Templates/Blank/Blocks/CTA/With Image.html
  src/FluentCMS/Templates/Blank/Blocks/Content/Simple.html
  src/FluentCMS/Templates/Blank/Blocks/Content/With Gallery.html
  src/FluentCMS/Templates/Blank/Blocks/Content/With Image.html
  src/FluentCMS/Templates/Blank/Blocks/Customer Logos/Default.html
  src/FluentCMS/Templates/Blank/Blocks/FAQ/Default.html
  src/FluentCMS/Templates/Blank/Blocks/Feature/Default.html
  src/FluentCMS/Templates/Blank/Blocks/Footer/Default.html
  src/FluentCMS/Templates/Blank/Blocks/Footer/With Sitemap & Social.html
  src/FluentCMS/Templates/Blank/Blocks/Headers/Header.html
  src/FluentCMS/Templates/Blank/Blocks/Hero/Default.html
  src/FluentCMS/Templates/Blank/Blocks/Hero/Visual Image.html
  src/FluentCMS/Templates/Blank/Blocks/Pricing/Default.html
  src/FluentCMS/Templates/Blank/Blocks/Schedule/Default.html
  src/FluentCMS/Templates/Blank/Blocks/Social Proof/Card Statistics.html
  src/FluentCMS/Templates/Blank/Blocks/Social Proof/Default.html
  src/FluentCMS/Templates/Blank/Blocks/Social Proof/Icon Statistics.html
  src/FluentCMS/Templates/Blank/Blocks/Teams/Card.html
  src/FluentCMS/Templates/Blank/Blocks/Teams/Clean.html
  src/FluentCMS/Templates/Blank/Blocks/Testimonials/Cards.html
  src/FluentCMS/Templates/Blank/Blocks/Testimonials/Default.html
  src/FluentCMS/Templates/Default/Blocks/CTA/Default.html
  src/FluentCMS/Templates/Default/Blocks/CTA/Image and Button.html
  src/FluentCMS/Templates/Default/Blocks/CTA/Mobile App.html
  src/FluentCMS/Templates/Default/Blocks/CTA/With Heading.html
  src/FluentCMS/Templates/Default/Blocks/CTA/With Image.html
  src/FluentCMS/Templates/Default/Blocks/Content/Simple.html
  src/FluentCMS/Templates/Default/Blocks/Content/With Gallery.html
  src/FluentCMS/Templates/Default/Blocks/Content/With Image.html
  src/FluentCMS/Templates/Default/Blocks/Customer Logos/Default.html
  src/FluentCMS/Templates/Default/Blocks/FAQ/Default.html
  src/FluentCMS/Templates/Default/Blocks/Feature/Default.html
  src/FluentCMS/Templates/Default/Blocks/Footer/Default.html
  src/FluentCMS/Templates/Default/Blocks/Footer/With Sitemap & Social.html
  src/FluentCMS/Templates/Default/Blocks/Headers/Header.html
  src/FluentCMS/Templates/Default/Blocks/Hero/Default.html
  src/FluentCMS/Templates/Default/Blocks/Hero/Visual Image.html
  src/FluentCMS/Templates/Default/Blocks/Pricing/Default.html
  src/FluentCMS/Templates/Default/Blocks/Schedule/Default.html
  src/FluentCMS/Templates/Default/Blocks/Social Proof/Card Statistics.html
  src/FluentCMS/Templates/Default/Blocks/Social Proof/Default.html
  src/FluentCMS/Templates/Default/Blocks/Social Proof/Icon Statistics.html
  src/FluentCMS/Templates/Default/Blocks/Teams/Card.html
  src/FluentCMS/Templates/Default/Blocks/Teams/Clean.html
  src/FluentCMS/Templates/Default/Blocks/Testimonials/Cards.html
  src/FluentCMS/Templates/Default/Blocks/Testimonials/Default.html
Labels: enhancement

#2193 #2175 Show block selector instead of edit modal when block is empty
  src/Frontend/Plugins/FluentCMS.Web.Plugins.Contents.Block/BlockEditPlugin.razor
  src/Frontend/Plugins/FluentCMS.Web.Plugins.Contents.Block/BlockEditPlugin.razor.cs
  src/Frontend/Plugins/FluentCMS.Web.Plugins.Contents.Block/Components/BlockEmptyView.razor
  src/Frontend/Plugins/FluentCMS.Web.Plugins.Contents.Block/Components/BlockEmptyView.razor.cs
  src/Frontend/Plugins/FluentCMS.Web.Plugins.Contents.Block/Components/BlockSelectModal.razor
  src/Frontend/Plugins/FluentCMS.Web.Plugins.Contents.Block/Components/BlockSelectModal.razor.cs
Labels: bug, enhancement

#2189 #2182 Add Iframe plugin
  src/FluentCMS.sln
  src/FluentCMS/FluentCMS.csproj
  src/FluentCMS/Templates/Blank/manifest.json
  src/FluentCMS/Templates/Default/manifest.json
  src/Frontend/FluentCMS.Web.UI.Components/Styles/Flowbite/App.scss
  src/Frontend/FluentCMS.Web.UI.Components/Styles/Flowbite/Plugins/IFrame.scss
  src/Frontend/FluentCMS.Web.UI.Components/wwwroot/css/flowbite.min.css
  src/Frontend/FluentCMS.Web.UI.Components/wwwroot/css/flowbite.min.css.map
  src/Frontend/Plugins/FluentCMS.Web.Plugins.Base/Components/PluginModalForm.razor
  src/Frontend/Plugins/FluentCMS.Web.Plugins.Contents.IFrame/FluentCMS.Web.Plugins.Contents.IFrame.csproj
  src/Frontend/Plugins/FluentCMS.Web.Plugins.Contents.IFrame/IFrameEditPlugin.razor
  src/Frontend/Plugins/FluentCMS.Web.Plugins.Contents.IFrame/IFrameEditPlugin.razor.cs
  src/Frontend/Plugins/FluentCMS.Web.Plugins.Contents.IFrame/IFrameViewPlugin.razor
  src/Frontend/Plugins/FluentCMS.Web.Plugins.Contents.IFrame/IFrameViewPlugin.razor.cs
  src/Frontend/Plugins/FluentCMS.Web.Plugins.Contents.IFrame/_GlobalUsings.cs
  src/Frontend/Plugins/FluentCMS.Web.Plugins.Contents.IFrame/_Imports.razor
Labels: enhancement

#2207 #2205 Fix ux of iframe edit
  src/Frontend/Plugins/FluentCMS.Web.Plugins.Contents.IFrame/IFrameEditPlugin.razor.cs
  src/Frontend/Plugins/FluentCMS.Web.Plugins.Contents.IFrame/IFrameViewPlugin.razor.cs
Labels: enhancement

#2208 #2206 apply design changes and add dropdown
  src/Frontend/FluentCMS.Web.UI.Components/Styles/Flowbite/Components/InlineEditor.scss
  src/Frontend/FluentCMS.Web.UI.Components/wwwroot/css/flowbite.min.css
  src/Frontend/FluentCMS.Web.UI.Components/wwwroot/css/flowbite.min.css.map
  src/Frontend/FluentCMS.Web.UI/Components/SiteBuilder.razor
  src/Frontend/FluentCMS.Web.UI/Components/SiteBuilder.razor.js
  src/Frontend/FluentCMS.Web.UI/Components/SiteBuilderDefaultToolbar.razor
  src/Frontend/FluentCMS.Web.UI/Components/SiteBuilderToolbarDropdown.razor
  src/Frontend/FluentCMS.Web.UI/Components/SiteBuilderToolbarDropdown.razor.cs
  src/Frontend/FluentCMS.Web.UI/Components/SiteBuilderToolbarDropdown.razor.js
  src/Frontend/FluentCMS.Web.UI/wwwroot/css/plugin-container.css
  src/Frontend/FluentCMS.Web.UI/wwwroot/css/sitebuilder.default.css
  src/Frontend/FluentCMS.Web.UI/wwwroot/css/sitebuilder.editor.css
  src/Frontend/FluentCMS.Web.UI/wwwroot/css/toolbar.css
Labels: enhancement

#2211 #2210 Add validation for content type field settings
  src/Frontend/Plugins/FluentCMS.Web.Plugins.Admin/ContentTypeManagement/Components/Boolean/BooleanFieldSettings.razor
  src/Frontend/Plugins/FluentCMS.Web.Plugins.Admin/ContentTypeManagement/Components/Date/DateFieldSettings.razor
  src/Frontend/Plugins/FluentCMS.Web.Plugins.Admin/ContentTypeManagement/Components/FieldSettingForm.razor
  src/Frontend/Plugins/FluentCMS.Web.Plugins.Admin/ContentTypeManagement/Components/FieldSettingForm.razor.cs
  src/Frontend/Plugins/FluentCMS.Web.Plugins.Admin/ContentTypeManagement/Components/MultiSelect/MultiSelectFieldSettings.razor
  src/Frontend/Plugins/FluentCMS.Web.Plugins.Admin/ContentTypeManagement/Components/Number/NumberFieldSettings.razor
  src/Frontend/Plugins/FluentCMS.Web.Plugins.Admin/ContentTypeManagement/Components/Select/SelectFieldSettings.razor
  src/Frontend/Plugins/FluentCMS.Web.Plugins.Admin/ContentTypeManagement/Components/SingleFile/SingleFileFieldSettings.razor
  src/Frontend/Plugins/FluentCMS.Web.Plugins.Admin/ContentTypeManagement/Components/String/StringFieldSettings.razor
  src/Frontend/Plugins/FluentCMS.Web.Plugins.Admin/ContentTypeManagement/Models/FieldModel.cs
  src/Frontend/Plugins/FluentCMS.Web.Plugins.Admin/_GlobalUsings.cs
Labels: enhancement

#2215 #2204 add Title and favicon for page editor
  src/Frontend/FluentCMS.Web.UI/Components/SiteBuilder.razor
  src/Frontend/FluentCMS.Web.UI/wwwroot/images/android-chrome-192x192.png
  src/Frontend/FluentCMS.Web.UI/wwwroot/images/apple-touch-icon.png
  src/Frontend/FluentCMS.Web.UI/wwwroot/images/favicon-16x16.png
  src/Frontend/FluentCMS.Web.UI/wwwroot/images/favicon-32x32.png
  src/Frontend/FluentCMS.Web.UI/wwwroot/images/safari-pinned-tab.svg
Labels: enhancement
