Repository fluentcms/FluentCMS, pull requests merged in 2024-05, with the labels that each got.

#1205 #1204 add RoleController's policy attributes
  src/FluentCMS.Web.Api/Controllers/RoleController.cs
Labels: enhancement

#1211 1210 revert setupreset api
  src/FluentCMS.Shared/Exceptions/ExceptionCodes.cs
  src/FluentCMS.Web.Api/Controllers/SetupController.cs
  src/FluentCMS.Web.ApiClients/GeneratedApiClients.cs
  src/FluentCMS.Web.ApiClients/config.nswag
  src/FluentCMS/Properties/launchSettings.json
Labels: test

#1214 revert: moving of `ApiClientServiceExtensions` to `Web.UI`
  src/FluentCMS.Web.ApiClients/ApiClientServiceExtensions.cs
  src/FluentCMS.Web.ApiClients/HttpClientFactoryHelper.cs
Labels: enhancement

#1221 #1196 remove Shared project's dependency from UI.Components project
  src/FluentCMS.Web.UI.Components/FluentCMS.Web.UI.Components.csproj
  src/FluentCMS.Web.UI.Components/StringExtensions.cs
Labels: enhancement

#1223 #1222 add policies to User response model
  src/FluentCMS.Web.Api/Controllers/UserController.cs
  src/FluentCMS.Web.Api/MappingProfile.cs
  src/FluentCMS.Web.Api/Models/Roles/RoleSimpleResponse.cs
  src/FluentCMS.Web.Api/Models/Users/UserDetailResponse.cs
  src/FluentCMS.Web.ApiClients/ApiClientServiceExtensions.cs
  src/FluentCMS.Web.ApiClients/GeneratedApiClients.cs
  src/FluentCMS.Web.ApiClients/config.nswag
Labels: enhancement

#1226 #1206 Role policies list enhancement
  src/FluentCMS.Web.Api/Controllers/RoleController.cs
  src/FluentCMS.Web.ApiClients/GeneratedApiClients.cs
  src/FluentCMS.Web.ApiClients/config.nswag
Labels: enhancement

#1202 1150 remove layouts from plugin view 3
  src/FluentCMS.Web.UI.Components/wwwroot/css/app.min.css
  src/FluentCMS.Web.UI.Components/wwwroot/css/app.min.css.map
  src/FluentCMS.Web.UI/Components/BasePlugin.razor
  src/FluentCMS.Web.UI/Components/BasePlugin.razor.cs
  src/FluentCMS.Web.UI/Components/EmptyState.razor
  src/FluentCMS.Web.UI/Components/EmptyState.razor.cs
  src/FluentCMS.Web.UI/Components/Form/PluginBody.razor
  src/FluentCMS.Web.UI/Components/Form/PluginBody.razor.cs
  src/FluentCMS.Web.UI/Components/Form/PluginForm.razor
  src/FluentCMS.Web.UI/Components/Form/PluginForm.razor.cs
  src/FluentCMS.Web.UI/Components/Form/PluginFormActions.razor
  src/FluentCMS.Web.UI/Components/Form/PluginFormActions.razor.cs
  src/FluentCMS.Web.UI/Components/Form/PluginFormCheckbox.razor
  src/FluentCMS.Web.UI/Components/Form/PluginFormCheckbox.razor.cs
  src/FluentCMS.Web.UI/Components/Form/PluginFormField.razor
  src/FluentCMS.Web.UI/Components/Form/PluginFormField.razor.cs
  src/FluentCMS.Web.UI/Components/Form/PluginFormInput.razor
  src/FluentCMS.Web.UI/Components/Layout/AdminSidebar.razor
  src/FluentCMS.Web.UI/Components/Layout/ExtendedFocusOnNavigate.razor
  src/FluentCMS.Web.UI/Components/Layout/SecondarySidebarWrapper.razor
  src/FluentCMS.Web.UI/Components/Layout/UserInfo.razor
  src/FluentCMS.Web.UI/Components/Layout/Version.razor
  src/FluentCMS.Web.UI/Components/PluginContainer.razor
  src/FluentCMS.Web.UI/Components/PluginContainer.razor.cs
  src/FluentCMS.Web.UI/Components/Section.razor
  src/FluentCMS.Web.UI/Components/Section.razor.cs
  src/FluentCMS.Web.UI/Default.razor.cs
  src/FluentCMS.Web.UI/Plugins/BasePlugin.razor
  src/FluentCMS.Web.UI/Plugins/Home/HomeViewPlugin.razor
  src/FluentCMS.Web.UI/Plugins/PluginFormActions.razor
  src/FluentCMS.Web.UI/Plugins/PluginView.razor
  src/FluentCMS.Web.UI/Plugins/PluginView.razor.cs
  src/FluentCMS.Web.UI/Plugins/UserManagement/UserCreatePlugin.razor
  src/FluentCMS.Web.UI/Plugins/UserManagement/UserDetailPlugin.razor
  src/FluentCMS.Web.UI/Plugins/UserManagement/UserListPlugin.razor
  src/FluentCMS.Web.UI/Plugins/UserManagement/UserUpdatePlugin.razor
  src/FluentCMS.Web.UI/_Imports.razor
Labels: enhancement, plugin

#1239 #1218 develop ApiToken feature
  src/FluentCMS.Entities/ApiToken.cs
  src/FluentCMS.Repositories.Abstractions/IApiTokenRepository.cs
  src/FluentCMS.Repositories.MongoDB/ApiTokenRepository.cs
  src/FluentCMS.Services/ApiTokenService.cs
  src/FluentCMS.Shared/Exceptions/ExceptionCodes.cs
  src/FluentCMS.Web.Api/Controllers/ApiTokenController.cs
  src/FluentCMS.Web.Api/MappingProfile.cs
  src/FluentCMS.Web.Api/Models/ApiToken/ApiTokenCreateRequest.cs
  src/FluentCMS.Web.Api/Models/ApiToken/ApiTokenDetailResponse.cs
  src/FluentCMS.Web.Api/Models/ApiToken/ApiTokenUpdateRequest.cs
  src/FluentCMS.Web.ApiClients/GeneratedApiClients.cs
  src/FluentCMS.Web.ApiClients/config.nswag
Labels: enhancement

#1240 1209 review apiclient tests
  src/Tests/FluentCMS.E2eTests/Features/AccountClient.feature
  src/Tests/FluentCMS.E2eTests/Features/AccountClient.feature.cs
  src/Tests/FluentCMS.E2eTests/Features/ContentTypeClient.feature.cs
  src/Tests/FluentCMS.E2eTests/Features/RoleClient.feature.cs
  src/Tests/FluentCMS.E2eTests/Features/SetupClient.feature
  src/Tests/FluentCMS.E2eTests/Features/SetupClient.feature.cs
  src/Tests/FluentCMS.E2eTests/Features/UserClient.feature.cs
  src/Tests/FluentCMS.E2eTests/StepDefinitions/Given/GivenIHaveADto.cs
  src/Tests/FluentCMS.E2eTests/StepDefinitions/Given/GivenIHaveAService.cs
  src/Tests/FluentCMS.E2eTests/StepDefinitions/Tags/RequiresAuthenticatedAdmin.cs
  src/Tests/FluentCMS.E2eTests/StepDefinitions/Tags/RequiresFreshSetup.cs
  src/Tests/FluentCMS.E2eTests/StepDefinitions/Then/ThenIShouldHaveAToken.cs
  src/Tests/FluentCMS.E2eTests/StepDefinitions/When/WhenIAuthenticateAsync.cs
  src/Tests/FluentCMS.E2eTests/StepDefinitions/When/WhenIChangePassword.cs
  src/Tests/FluentCMS.E2eTests/StepDefinitions/When/WhenIRegister.cs
Labels: test

#1238 340 develop litedb repository from new abstracts 1
  src/FluentCMS.Repositories.LiteDb/ApiTokenRepository.cs
  src/FluentCMS.Repositories.LiteDb/AppTemplateRepository.cs
  src/FluentCMS.Repositories.LiteDb/AuditableEntityRepository.cs
  src/FluentCMS.Repositories.LiteDb/ContentRepository.cs
  src/FluentCMS.Repositories.LiteDb/ContentTypeRepository.cs
  src/FluentCMS.Repositories.LiteDb/EntityRepository.cs
  src/FluentCMS.Repositories.LiteDb/FluentCMS.Repositories.LiteDb.csproj
  src/FluentCMS.Repositories.LiteDb/GlobalSettingsRepository.cs
  src/FluentCMS.Repositories.LiteDb/LayoutRepository.cs
  src/FluentCMS.Repositories.LiteDb/LiteDBContext.cs
  src/FluentCMS.Repositories.LiteDb/LiteDBOptions.cs
  src/FluentCMS.Repositories.LiteDb/LiteDbServiceExtensions.cs
  src/FluentCMS.Repositories.LiteDb/PageRepository.cs
  src/FluentCMS.Repositories.LiteDb/PluginDefinitionRepository.cs
  src/FluentCMS.Repositories.LiteDb/PluginRepository.cs
  src/FluentCMS.Repositories.LiteDb/RoleRepository.cs
  src/FluentCMS.Repositories.LiteDb/SiteAssociatedRepository.cs
  src/FluentCMS.Repositories.LiteDb/SiteRepository.cs
  src/FluentCMS.Repositories.LiteDb/UserRepository.cs
  src/FluentCMS.sln
Labels: enhancement

#1246 #1189 develop CSS name overriding feature
  src/FluentCMS.Web.UI.Components/Base/BaseComponent.cs
  src/FluentCMS.Web.UI.Components/Base/BaseComponentHelpers.cs
Labels: enhancement

#1254 #1249 resolve ApiTokenService issue
  src/FluentCMS.Services/ApiTokenService.cs
Labels: bug

#1257 #1256 revert visible functionality in base
  src/FluentCMS.Web.UI.Components/Base/BaseComponent.cs
  src/FluentCMS.Web.UI.Components/Components/Alert/Alert.razor
  src/FluentCMS.Web.UI.Components/Components/Badge/Badge.razor
  src/FluentCMS.Web.UI.Components/Components/Badge/Badge.razor.cs
  src/FluentCMS.Web.UI.Components/Components/Button/Button.razor
  src/FluentCMS.Web.UI.Components/Components/Card/Card.razor
  src/FluentCMS.Web.UI.Components/Components/Grid/Grid.razor
  src/FluentCMS.Web.UI.Components/Components/Grid/GridItem.razor
  src/FluentCMS.Web.UI.Components/Components/Spacer/Spacer.razor
Labels: bug

#1269 chore: remove `Counter` from `PluginDefinitions`
  src/FluentCMS/Templates/Admin/manifest.json
  src/FluentCMS/Templates/Site/Blank/manifest.json
Labels: enhancement

#1268 1263 review controller policies
  src/FluentCMS.Web.Api/Controllers/ApiTokenController.cs
  src/FluentCMS.Web.Api/Controllers/ContentController.cs
  src/FluentCMS.Web.Api/Controllers/ContentTypeController.cs
  src/FluentCMS.Web.Api/Controllers/PageController.cs
  src/FluentCMS.Web.Api/Controllers/PluginController.cs
  src/FluentCMS.Web.Api/Controllers/PluginDefinitionController.cs
  src/FluentCMS.Web.Api/Controllers/RoleController.cs
  src/FluentCMS.Web.Api/Controllers/SiteController.cs
  src/FluentCMS.Web.Api/Controllers/UserController.cs
Labels: enhancement

#1274 1261 api token generate token
  src/FluentCMS.Services/ApiTokenProvider.cs
  src/FluentCMS.Services/ApiTokenService.cs
  src/FluentCMS.Services/ServiceExtensions.cs
  src/FluentCMS.Shared/IAuthContext.cs
  src/FluentCMS.Web.Api/Attributes/PolicyAttribute.cs
  src/FluentCMS.Web.Api/AuthContext.cs
Labels: enhancement

#1278 feat: implement dispose for js components
  src/FluentCMS.Web.UI.Components/Components/Accordion/Accordion.razor
  src/FluentCMS.Web.UI.Components/Components/Accordion/Accordion.razor.cs
  src/FluentCMS.Web.UI.Components/Components/Browse/Browse.razor
  src/FluentCMS.Web.UI.Components/Components/Browse/Browse.razor.cs
  src/FluentCMS.Web.UI.Components/Components/Confirm/Confirm.razor
  src/FluentCMS.Web.UI.Components/Components/Confirm/Confirm.razor.cs
  src/FluentCMS.Web.UI.Components/Components/Dropdown/Dropdown.razor
  src/FluentCMS.Web.UI.Components/Components/Dropdown/Dropdown.razor.cs
  src/FluentCMS.Web.UI.Components/Components/Form/Autocomplete/Autocomplete.razor
  src/FluentCMS.Web.UI.Components/Components/Form/Autocomplete/Autocomplete.razor.cs
  src/FluentCMS.Web.UI.Components/Components/Form/FormField/FormField.razor
  src/FluentCMS.Web.UI.Components/Components/Form/FormField/FormField.razor.cs
  src/FluentCMS.Web.UI.Components/Components/Form/MarkdownEditor/MarkdownEditor.razor
  src/FluentCMS.Web.UI.Components/Components/Form/MarkdownEditor/MarkdownEditor.razor.cs
  src/FluentCMS.Web.UI.Components/Components/Form/MarkdownEditor/MarkdownEditor.razor.js
  src/FluentCMS.Web.UI.Components/Components/Modal/Modal.razor
  src/FluentCMS.Web.UI.Components/Components/Modal/Modal.razor.cs
  src/FluentCMS.Web.UI.Components/Components/Sidebar/Sidebar.scss
  src/FluentCMS.Web.UI.Components/Components/Sidebar/SidebarToggler.razor
  src/FluentCMS.Web.UI.Components/Components/Sidebar/SidebarToggler.razor.cs
  src/FluentCMS.Web.UI.Components/Components/Sidebar/SidebarToggler.razor.js
  src/FluentCMS.Web.UI.Components/Components/ThemeSwitcher/ThemeSwitcher.razor
  src/FluentCMS.Web.UI.Components/Components/ThemeSwitcher/ThemeSwitcher.razor.cs
  src/FluentCMS.Web.UI.Components/Components/ThemeSwitcher/ThemeSwitcher.razor.js
  src/FluentCMS.Web.UI.Components/Components/ThemeSwitcher/ThemeSwitcher.scss
  src/FluentCMS.Web.UI.Components/Components/Tooltip/Tooltip.razor
  src/FluentCMS.Web.UI.Components/Components/Tooltip/Tooltip.razor.cs
  src/FluentCMS.Web.UI.Components/Layouts/PanelLayout.razor
  src/FluentCMS.Web.UI.Components/Styles/App.scss
  src/FluentCMS.Web.UI.ComponentsDocs/Layouts/RootLayout.razor
  src/FluentCMS.Web.UI/Components/Layout/AdminSidebar.razor
Labels: component

#1290 Update HomePage plugin and inherit it from BasePlugin
  src/FluentCMS.Web.UI/Plugins/Home/HomeViewPlugin.razor
Labels: plugin

#1292 #1291 remove duplicated title attributes
  src/FluentCMS.Web.UI.Components/Components/Page/PageHeader.razor
  src/FluentCMS.Web.UI/App.razor
Labels: bug

#1297 feat: add Html of User List
  src/FluentCMS.Web.UI/Plugins/UserManagement/UserListPlugin.razor
  src/FluentCMS.Web.UI/Plugins/UserManagement/UserListPlugin.razor.cs
Labels: enhancement

#1294 feat: Update Admin Layout
  src/FluentCMS.Web.UI/App.razor
  src/FluentCMS/Templates/Admin/AdminLayout.body.html
  src/FluentCMS/Templates/Admin/AdminLayout.head.html
  src/FluentCMS/wwwroot/css/app.css
  src/FluentCMS/wwwroot/js/app.bundle.js
Labels: enhancement

#1308 feat: Add PluginFormTextarea component
  src/FluentCMS.Web.UI/Components/Form/PluginFormTextarea.razor
  src/FluentCMS.Web.UI/Components/Form/PluginFormTextarea.razor.cs
Labels: enhancement, plugin, component

#1310 fix: Fix link of Edit User button in table
  src/FluentCMS.Web.UI/Plugins/UserManagement/UserListPlugin.razor
Labels: bug

#1302 fix: Resolve the PluginFormActions layout.
  src/FluentCMS.Web.UI/Components/Form/PluginFormActions.razor
Labels: bug, plugin, component

#1316 fix: remove custom css and js of admin Layout
  src/FluentCMS.Web.UI/App.razor
  src/FluentCMS/Templates/Admin/AdminLayout.body.html
  src/FluentCMS/Templates/Admin/AdminLayout.head.html
  src/FluentCMS/wwwroot/css/app.css
  src/FluentCMS/wwwroot/js/app.bundle.js
Labels: bug

#1320 feat: Add TextEdit and NumericEdit component.
  src/FluentCMS.Web.UI.Components/Base/BaseComponentHelpers.cs
  src/FluentCMS.Web.UI.Components/Components/Form/FormField/FormField.razor
  src/FluentCMS.Web.UI.Components/Components/Form/FormField/FormField.razor.cs
  src/FluentCMS.Web.UI.Components/Components/Form/NumericEdit/NumericEdit.cs
  src/FluentCMS.Web.UI.Components/Components/Form/NumericEdit/NumericEdit.razor
  src/FluentCMS.Web.UI.Components/Components/Form/NumericEdit/NumericEdit.razor.cs
  src/FluentCMS.Web.UI.Components/Components/Form/NumericEdit/NumericEdit.scss
  src/FluentCMS.Web.UI.Components/Components/Form/TextEdit/TextEdit.cs
  src/FluentCMS.Web.UI.Components/Components/Form/TextEdit/TextEdit.razor
  src/FluentCMS.Web.UI.Components/Components/Form/TextEdit/TextEdit.razor.cs
  src/FluentCMS.Web.UI.Components/Components/Form/TextEdit/TextEdit.scss
  src/FluentCMS.Web.UI.Components/Styles/App.scss
Labels: enhancement, component

#1325 #1324 change default render mode to SSR
  src/FluentCMS.Web.UI/App.razor
Labels: enhancement

#1327 #1312 update csproj file
  src/FluentCMS/FluentCMS.csproj
Labels: enhancement

#1339 clean: remove console.logs from FluentCMS.Web.UI.Components project
  src/FluentCMS.Web.UI.Components/Components/Accordion/Accordion.razor.js
Labels: component

#1334 refactor: remove Loading prop from Button
  src/FluentCMS.Web.UI.Components/Components/Button/Button.razor
  src/FluentCMS.Web.UI.Components/Components/Button/Button.razor.cs
  src/FluentCMS.Web.UI.Components/Components/Button/Button.scss
  src/FluentCMS.Web.UI.Components/Components/Dropdown/DropdownButton.razor
Labels: component

#1330 1329 cleanup card component
  src/FluentCMS.Web.UI.Components/Components/Card/Card.razor.cs
  src/FluentCMS.Web.UI.Components/Components/Card/Card.scss
  src/FluentCMS.Web.UI.Components/Components/Card/CardFooter.razor
  src/FluentCMS.Web.UI.Components/Components/Card/CardFooter.razor.cs
  src/FluentCMS.Web.UI/Plugins/FileManagement/FileManagementTile.razor
Labels: component

#1333 refactor: remove Show property from Alert
  src/FluentCMS.Web.UI.Components/Components/Alert/Alert.razor
  src/FluentCMS.Web.UI.Components/Components/Alert/Alert.razor.cs
Labels: component

#1341 #1340 build css
  src/FluentCMS.Web.UI.Components/wwwroot/css/app.min.css
  src/FluentCMS.Web.UI.Components/wwwroot/css/app.min.css.map
Labels: bug

#1345 feat: Update Admin and Auth Layouts and add FluentCMS logo
  src/FluentCMS.Web.Api/Setup/SetupManager.cs
  src/FluentCMS.Web.UI.Components/Components/Logo.razor
  src/FluentCMS.Web.UI.Components/Layouts/AuthLayout.razor
  src/FluentCMS.Web.UI.Components/Styles/App.scss
  src/FluentCMS.Web.UI.Components/Styles/Sidebar.scss
  src/FluentCMS.Web.UI.Components/Styles/tailwind.config.js
  src/FluentCMS.Web.UI.Components/wwwroot/css/app.min.css
  src/FluentCMS.Web.UI.Components/wwwroot/css/app.min.css.map
  src/FluentCMS.Web.UI.Components/wwwroot/img/logo.svg
  src/FluentCMS.Web.UI.ComponentsDocs/Components/Sidebar/Sidebar.razor
  src/FluentCMS.Web.UI.ComponentsDocs/Components/Sidebar/Sidebar.razor.cs
  src/FluentCMS.Web.UI.ComponentsDocs/Components/Sidebar/SidebarItem.razor
  src/FluentCMS.Web.UI.ComponentsDocs/Components/Sidebar/SidebarItem.razor.cs
  src/FluentCMS.Web.UI.ComponentsDocs/Layouts/PanelLayout.razor
  src/FluentCMS.Web.UI.ComponentsDocs/Layouts/RootLayout.razor
  src/FluentCMS.Web.UI.ComponentsDocs/_GlobalUsings.cs
  src/FluentCMS.Web.UI.ComponentsDocs/_Imports.razor
  src/FluentCMS.Web.UI.ComponentsDocs/wwwroot/images/logo-shape-dark.svg
  src/FluentCMS.Web.UI.ComponentsDocs/wwwroot/images/logo-shape.svg
  src/FluentCMS.Web.UI/App.razor
  src/FluentCMS.Web.UI/Components/Layout/AdminSidebar.razor
  src/FluentCMS/Templates/Admin/AdminLayout.body.html
  src/FluentCMS/Templates/Admin/AdminLayout.head.html
  src/FluentCMS/Templates/Admin/AuthLayout.body.html
  src/FluentCMS/Templates/Admin/AuthLayout.head.html
  src/FluentCMS/Templates/Admin/SetupLayout.body.html
  src/FluentCMS/Templates/Admin/SetupLayout.head.html
  src/FluentCMS/Templates/Admin/SetupLayout.html
  src/FluentCMS/wwwroot/css/app.css
  src/FluentCMS/wwwroot/favicon.png
  src/FluentCMS/wwwroot/images/favicon-32x32.png
  src/FluentCMS/wwwroot/images/logo-shape-dark.svg
  src/FluentCMS/wwwroot/images/logo-shape.svg
  src/FluentCMS/wwwroot/js/app.head.js
  src/FluentCMS/wwwroot/js/app.js
  src/FluentCMS/wwwroot/js/before-render.js
Labels: enhancement

#1354 fix: use Logo.svg instead of Logo-shape.svg
  src/FluentCMS.Web.UI.ComponentsDocs/Layouts/PanelLayout.razor
  src/FluentCMS.Web.UI.ComponentsDocs/Layouts/RootLayout.razor
  src/FluentCMS/Templates/Admin/AdminLayout.body.html
  src/FluentCMS/Templates/Admin/AuthLayout.body.html
  src/FluentCMS/wwwroot/images/logo-dark.svg
  src/FluentCMS/wwwroot/images/logo.svg
Labels: enhancement

#1353 remove Providers from AuthLayout and change its size to fit in larger screens
  src/FluentCMS/Templates/Admin/AuthLayout.body.html
Labels: enhancement

#1358 #1357 css file generated
  src/FluentCMS.Web.UI.Components/wwwroot/css/app.min.css
  src/FluentCMS.Web.UI.Components/wwwroot/css/app.min.css.map
Labels: bug

#1359 #1251 add loading bar using enhanced navigation
  src/FluentCMS.Web.UI.Components/wwwroot/css/app.min.css
  src/FluentCMS.Web.UI.Components/wwwroot/css/app.min.css.map
  src/FluentCMS.Web.UI/App.razor
  src/FluentCMS/Templates/Admin/AdminLayout.body.html
  src/FluentCMS/Templates/Admin/AdminLayout.head.html
  src/FluentCMS/Templates/Admin/AuthLayout.body.html
  src/FluentCMS/Templates/Admin/AuthLayout.head.html
  src/FluentCMS/wwwroot/css/app.css
  src/FluentCMS/wwwroot/js/loadingbar.js
Labels: documentation

#1361 feat: add Theme button and sidebar toggler for admin panel
  src/FluentCMS.Web.UI.Components/wwwroot/css/app.min.css
  src/FluentCMS.Web.UI.Components/wwwroot/css/app.min.css.map
  src/FluentCMS.Web.UI/App.razor
  src/FluentCMS/Templates/Admin/AuthLayout.body.html
  src/FluentCMS/wwwroot/js/app.js
Labels: bug

#1365 fix flowbite componets after navigate and cleanup js file
  src/FluentCMS/wwwroot/js/app.js
Labels: bug

#1369 1366 remove todos and cleanup layouts
  src/FluentCMS/Templates/Admin/AdminLayout.body.html
  src/FluentCMS/wwwroot/js/app.js
Labels: enhancement

#1385 1376 develop a datatable component to automatically render the table tr td with an items property
  src/FluentCMS.Web.UI.Components/Base/BaseComponentHelpers.cs
  src/FluentCMS.Web.UI.Components/Components/DataTable/DataTable.razor
  src/FluentCMS.Web.UI.Components/Components/DataTable/DataTable.razor.cs
  src/FluentCMS.Web.UI.Components/Components/DataTable/DataTable.scss
  src/FluentCMS.Web.UI.Components/Components/DataTable/DataTableItem.razor
  src/FluentCMS.Web.UI.Components/Components/DataTable/DataTableItem.razor.cs
  src/FluentCMS.Web.UI.Components/Styles/App.scss
  src/FluentCMS.Web.UI.Components/wwwroot/css/app.min.css
  src/FluentCMS.Web.UI.Components/wwwroot/css/app.min.css.map
  src/FluentCMS.Web.UI/Plugins/UserManagement/UserListPlugin.razor
  src/FluentCMS.sln
Labels: enhancement

#1387 #1386 run code analyzer
  src/FluentCMS.Web.UI.Components/Base/BaseComponentHelpers.cs
  src/FluentCMS.Web.UI.Components/Components/Card/Card.razor.cs
  src/FluentCMS.Web.UI.ComponentsDocs/_GlobalUsings.cs
  src/FluentCMS.Web.UI/Components/Form/PluginFormCheckboxGroup.razor.cs
  src/FluentCMS.Web.UI/Components/Form/PluginFormDateInput.razor.cs
  src/FluentCMS.Web.UI/Components/Form/PluginFormField.razor.cs
  src/FluentCMS.Web.UI/Components/Form/PluginFormNumberInput.razor.cs
Labels: enhancement

#1389 1388 users lastloginat is always null
  src/FluentCMS.E2E.UI/package-lock.json
  src/FluentCMS.Web.Api/Models/Users/UserCreateRequest.cs
  src/FluentCMS.Web.Api/Models/Users/UserDetailResponse.cs
  src/FluentCMS.Web.Api/Models/Users/UserUpdateRequest.cs
  src/FluentCMS.Web.ApiClients/GeneratedApiClients.cs
  src/FluentCMS.Web.ApiClients/config.nswag
  src/FluentCMS.Web.UI/Plugins/UserManagement/UserListPlugin.razor
Labels: enhancement

#1367 feat: add meta tags from favicon project & update content of Setup page
  src/FluentCMS/Templates/Admin/AdminLayout.head.html
  src/FluentCMS/Templates/Admin/AuthLayout.body.html
  src/FluentCMS/Templates/Admin/AuthLayout.head.html
  src/FluentCMS/wwwroot/images/android-chrome-144x144.png
  src/FluentCMS/wwwroot/images/android-chrome-192x192.png
  src/FluentCMS/wwwroot/images/android-chrome-256x256.png
  src/FluentCMS/wwwroot/images/android-chrome-36x36.png
  src/FluentCMS/wwwroot/images/android-chrome-48x48.png
  src/FluentCMS/wwwroot/images/android-chrome-72x72.png
  src/FluentCMS/wwwroot/images/android-chrome-96x96.png
  src/FluentCMS/wwwroot/images/apple-touch-icon.png
  src/FluentCMS/wwwroot/images/favicon-16x16.png
  src/FluentCMS/wwwroot/images/mstile-150x150.png
  src/FluentCMS/wwwroot/images/safari-pinned-tab.svg
Labels: enhancement

#1393 feat: use generic image instead of 'A' text for User profile
  src/FluentCMS/Templates/Admin/AdminLayout.body.html
Labels: enhancement

#1394 feat: make logo smaller
  src/FluentCMS.Web.UI.Components/wwwroot/css/app.min.css
  src/FluentCMS.Web.UI.Components/wwwroot/css/app.min.css.map
  src/FluentCMS/Templates/Admin/AdminLayout.body.html
Labels: enhancement

#1397 1391 revise setupmanager and setup process
  src/FluentCMS.Shared/Exceptions/ExceptionCodes.cs
  src/FluentCMS.Web.Api/Controllers/PageController.cs
  src/FluentCMS.Web.Api/Controllers/SetupController.cs
  src/FluentCMS.Web.Api/Models/Setup/SetupRequest.cs
  src/FluentCMS.Web.Api/Setup/SetupConfig.cs
  src/FluentCMS.Web.Api/Setup/SetupManager.cs
  src/FluentCMS.Web.ApiClients/GeneratedApiClients.cs
  src/FluentCMS.Web.ApiClients/config.nswag
  src/FluentCMS.Web.UI/Default.razor.cs
  src/FluentCMS.Web.UI/Plugins/Setup/SetupViewPlugin.razor
  src/FluentCMS.Web.UI/Plugins/Setup/SetupViewPlugin.razor.cs
  src/FluentCMS.Web.UI/Services/SetupManager.cs
  src/FluentCMS/Config/setup.json
Labels: enhancement

#1400 #1275 login plugin rendering issue resolved
  src/FluentCMS.Web.UI/Plugins/Auth/LoginViewPlugin.razor
  src/FluentCMS.Web.UI/Plugins/Auth/LoginViewPlugin.razor.cs
Labels: bug

#1403 chore: Remove NumericEdit and TextEdit components.
  src/FluentCMS.Web.UI.Components/Base/BaseComponentHelpers.cs
  src/FluentCMS.Web.UI.Components/Components/Form/NumericEdit/NumericEdit.cs
  src/FluentCMS.Web.UI.Components/Components/Form/NumericEdit/NumericEdit.razor
  src/FluentCMS.Web.UI.Components/Components/Form/NumericEdit/NumericEdit.razor.cs
  src/FluentCMS.Web.UI.Components/Components/Form/NumericEdit/NumericEdit.scss
  src/FluentCMS.Web.UI.Components/Components/Form/TextEdit/TextEdit.cs
  src/FluentCMS.Web.UI.Components/Components/Form/TextEdit/TextEdit.razor
  src/FluentCMS.Web.UI.Components/Components/Form/TextEdit/TextEdit.razor.cs
  src/FluentCMS.Web.UI.Components/Components/Form/TextEdit/TextEdit.scss
  src/FluentCMS.Web.UI.Components/Styles/App.scss
  src/FluentCMS.Web.UI.Components/wwwroot/css/app.min.css
  src/FluentCMS.Web.UI.Components/wwwroot/css/app.min.css.map
Labels: enhancement, component

#1413 chore: Remove griding system from checkbox group
  src/FluentCMS.Web.UI/Components/Form/PluginFormCheckboxGroup.razor
Labels: enhancement, component

#1404 feat: Add padding prop to the PluginBody
  src/FluentCMS.Web.UI/Components/Form/PluginBody.razor
  src/FluentCMS.Web.UI/Components/Form/PluginForm.razor
  src/FluentCMS.Web.UI/Plugins/Home/AdminHomeViewPlugin.razor
Labels: enhancement, plugin, component

#1417 #1416 build styles
  src/FluentCMS.Web.UI.Components/wwwroot/css/app.min.css
  src/FluentCMS.Web.UI.Components/wwwroot/css/app.min.css.map
Labels: enhancement, component

#1420 #419 redirect to route after logout
  src/FluentCMS.Web.UI/Services/AuthService.cs
Labels: enhancement

#1422 #1421 NavigationManager issue
  src/FluentCMS.Web.UI/Components/BasePlugin.razor.cs
  src/FluentCMS.Web.UI/Plugins/Auth/LoginViewPlugin.razor.cs
  src/FluentCMS.Web.UI/Plugins/Auth/LogoutViewPlugin.razor.cs
  src/FluentCMS.Web.UI/Plugins/Auth/RegisterViewPlugin.razor.cs
  src/FluentCMS.Web.UI/Plugins/Setup/SetupViewPlugin.razor.cs
  src/FluentCMS.Web.UI/Services/AuthService.cs
Labels: bug

#1405 fix: Remove required from roles selector in create user.
  src/FluentCMS.Web.UI/Plugins/UserManagement/UserCreatePlugin.razor
  src/FluentCMS.Web.UI/Plugins/UserManagement/UserCreatePlugin.razor.cs
  src/FluentCMS.Web.UI/Plugins/UserManagement/UserUpdatePlugin.razor
  src/FluentCMS.Web.UI/Plugins/UserManagement/UserUpdatePlugin.razor.cs
Labels: bug, plugin

#1418 feat: Update checkbox group to support primitive types
  src/FluentCMS.Web.UI/Components/Form/PluginFormCheckboxGroup.razor
  src/FluentCMS.Web.UI/Components/Form/PluginFormCheckboxGroup.razor.cs
Labels: enhancement, component

#1423 #1411 use Scriban for dynamic layout rendering
  src/FluentCMS.Web.UI/Default.razor
  src/FluentCMS.Web.UI/Default.razor.cs
  src/FluentCMS.Web.UI/FluentCMS.Web.UI.csproj
  src/FluentCMS/Templates/Admin/AdminLayout.body.html
Labels: enhancement

#1438 #1436 add default layout id to site entity
  src/FluentCMS.Entities/Sites/Layout.cs
  src/FluentCMS.Entities/Sites/Site.cs
  src/FluentCMS.Web.Api/Controllers/PageController.cs
  src/FluentCMS.Web.Api/Controllers/SiteController.cs
  src/FluentCMS.Web.Api/MappingProfile.cs
  src/FluentCMS.Web.Api/Models/Layout/LayoutCreateRequest.cs
  src/FluentCMS.Web.Api/Models/Layout/LayoutDetailResponse.cs
  src/FluentCMS.Web.Api/Models/Site/SiteCreateRequest.cs
  src/FluentCMS.Web.Api/Models/Site/SiteDetailResponse.cs
  src/FluentCMS.Web.Api/Models/Site/SiteFullDetailResponse.cs
  src/FluentCMS.Web.Api/Setup/SetupManager.cs
  src/FluentCMS.Web.ApiClients/GeneratedApiClients.cs
  src/FluentCMS.Web.ApiClients/config.nswag
  src/FluentCMS.Web.UI/Plugins/LayoutManagement/LayoutCreatePlugin.razor
  src/FluentCMS.Web.UI/Plugins/LayoutManagement/LayoutListPlugin.razor
  src/FluentCMS.Web.UI/Plugins/LayoutManagement/LayoutUpdatePlugin.razor
  src/FluentCMS.Web.UI/Plugins/LayoutManagement/LayoutUpdatePlugin.razor.cs
Labels: enhancement

#1440 #1435 enable AutoMapper in admin ui
  src/FluentCMS.Web.UI/Components/BasePlugin.razor.cs
  src/FluentCMS.Web.UI/FluentCMS.Web.UI.csproj
  src/FluentCMS.Web.UI/MappingProfile.cs
  src/FluentCMS.Web.UI/Plugins/LayoutManagement/LayoutUpdatePlugin.razor.cs
  src/FluentCMS.Web.UI/Plugins/UserManagement/UserUpdatePlugin.razor.cs
  src/FluentCMS.Web.UI/Services/AdminUIServiceExtensions.cs
Labels: enhancement

#1443 #1442 update Nuget packages
  src/FluentCMS.Entities/FluentCMS.Entities.csproj
  src/FluentCMS.Repositories.MongoDB/FluentCMS.Repositories.MongoDB.csproj
  src/FluentCMS.Services/FluentCMS.Services.csproj
  src/FluentCMS.Web.Api/FluentCMS.Web.Api.csproj
  src/FluentCMS.Web.UI.Components/FluentCMS.Web.UI.Components.csproj
  src/FluentCMS.Web.UI/FluentCMS.Web.UI.csproj
  src/Tests/FluentCMS.E2eTests/FluentCMS.E2eTests.csproj
Labels: enhancement

#1451 1437 remove htmlagilitypack to increase dynamic page rendering performance
  src/FluentCMS.Web.UI/Components/Section.razor
  src/FluentCMS.Web.UI/Components/Section.razor.cs
  src/FluentCMS.Web.UI/Default.razor
  src/FluentCMS.Web.UI/Default.razor.cs
  src/FluentCMS.Web.UI/DynamicRendering/ComponentSegment.cs
  src/FluentCMS.Web.UI/DynamicRendering/HtmlSegment.cs
  src/FluentCMS.Web.UI/DynamicRendering/LayoutProcessor.cs
  src/FluentCMS.Web.UI/DynamicRendering/Segment.cs
  src/FluentCMS.Web.UI/FluentCMS.Web.UI.csproj
Labels: enhancement

#1447 #1409 Add plugin form switch
  src/FluentCMS.Web.UI/Components/Form/PluginFormSwitch.razor
  src/FluentCMS.Web.UI/Components/Form/PluginFormSwitch.razor.cs
Labels: enhancement, component

#1450 #1448 Add text property to the checkbox
  src/FluentCMS.Web.UI/Components/Form/PluginFormCheckbox.razor
  src/FluentCMS.Web.UI/Components/Form/PluginFormCheckbox.razor.cs
Labels: enhancement, component

#1445 #1444 Fix settings plugin
  src/FluentCMS.Web.UI/Plugins/Settings/SettingsViewPlugin.razor
  src/FluentCMS.Web.UI/Plugins/Settings/SettingsViewPlugin.razor.cs
Labels: enhancement, plugin

#1461 #1460 disable policy authorization for API
  src/FluentCMS.Web.Api/Attributes/PolicyAttribute.cs
  src/FluentCMS/Templates/Admin/AdminLayout.body.html
Labels: enhancement

#1457 chore: Update user management plugin.
  src/FluentCMS.Web.UI/Plugins/UserManagement/UserCreatePlugin.razor
  src/FluentCMS.Web.UI/Plugins/UserManagement/UserCreatePlugin.razor.cs
  src/FluentCMS.Web.UI/Plugins/UserManagement/UserListPlugin.razor
  src/FluentCMS.Web.UI/Plugins/UserManagement/UserUpdatePlugin.razor
  src/FluentCMS.Web.UI/Plugins/UserManagement/UserUpdatePlugin.razor.cs
Labels: enhancement, plugin

#1458 Add default landing page
  src/FluentCMS.Web.UI.Components/wwwroot/css/app.min.css
  src/FluentCMS.Web.UI.Components/wwwroot/css/app.min.css.map
  src/FluentCMS/Templates/Admin/DefaultLayout.body.html
Labels: enhancement

#1459 #1410 Add plugin form select
  src/FluentCMS.Web.UI/Components/Form/PluginFormSelect.razor
  src/FluentCMS.Web.UI/Components/Form/PluginFormSelect.razor.cs
Labels: plugin, component

#1464 #1460 disabling API authorization
  src/FluentCMS.Web.Api/Controllers/BaseController.cs
Labels: bug

#1477 fix: Add default id for the checkbox
  src/FluentCMS.Web.UI/Components/Form/PluginFormCheckbox.razor.cs
  src/FluentCMS.Web.UI/Components/Form/PluginFormCheckboxGroup.razor
Labels: enhancement, component

#1478 #1384 Remove OnClick and StopPropagation from Button component
  src/FluentCMS.Web.UI.Components/Components/Button/Button.razor
  src/FluentCMS.Web.UI.Components/Components/Button/Button.razor.cs
  src/FluentCMS.Web.UI.Components/Components/Confirm/Confirm.razor
  src/FluentCMS.Web.UI.Components/Components/Page/PageBackButton.razor
  src/FluentCMS.Web.UI.Components/Components/Pagination/Pagination.razor
  src/FluentCMS.Web.UI.Components/Components/Pagination/PaginationItem.razor
  src/FluentCMS.Web.UI.Components/Components/Table/TableRow.razor
  src/FluentCMS.Web.UI.Components/Components/Table/TableRow.razor.cs
  src/FluentCMS.Web.UI/Plugins/ApiTokenManagement/ApiTokenCreatePlugin.razor
  src/FluentCMS.Web.UI/Plugins/ApiTokenManagement/ApiTokenListPlugin.razor
  src/FluentCMS.Web.UI/Plugins/ApiTokenManagement/ApiTokenUpdatePlugin.razor
  src/FluentCMS.Web.UI/Plugins/Auth/ProfileUpdatePlugin.razor
  src/FluentCMS.Web.UI/Plugins/ContentManagement/ContentCreatePlugin.razor
  src/FluentCMS.Web.UI/Plugins/ContentManagement/ContentDetailPlugin.razor
  src/FluentCMS.Web.UI/Plugins/ContentManagement/ContentListPlugin.razor
  src/FluentCMS.Web.UI/Plugins/ContentManagement/ContentUpdatePlugin.razor
  src/FluentCMS.Web.UI/Plugins/ContentTypeManagement/ContentTypeCreatePlugin.razor
  src/FluentCMS.Web.UI/Plugins/ContentTypeManagement/ContentTypeDetailPlugin.razor
  src/FluentCMS.Web.UI/Plugins/ContentTypeManagement/ContentTypeFields/ContentTypeFieldModal.razor
  src/FluentCMS.Web.UI/Plugins/ContentTypeManagement/ContentTypeFields/ContentTypeFieldSelector.razor
  src/FluentCMS.Web.UI/Plugins/ContentTypeManagement/ContentTypeListPlugin.razor
  src/FluentCMS.Web.UI/Plugins/ContentTypeManagement/ContentTypeUpdatePlugin.razor
  src/FluentCMS.Web.UI/Plugins/FileManagement/FileManagementEditModal.razor
  src/FluentCMS.Web.UI/Plugins/FileManagement/FileManagementListPlugin.razor
  src/FluentCMS.Web.UI/Plugins/FileManagement/FileManagementTile.razor
  src/FluentCMS.Web.UI/Plugins/FileManagement/FileManagementUploadModal.razor
  src/FluentCMS.Web.UI/Plugins/Home/AdminHomeViewPlugin.razor
Labels: enhancement

#1465 #1234 review and complete user management plugin
  src/FluentCMS.Web.Api/Models/Users/UserDetailResponse.cs
  src/FluentCMS.Web.Api/Models/Users/UserUpdateRequest.cs
  src/FluentCMS.Web.ApiClients/GeneratedApiClients.cs
  src/FluentCMS.Web.UI.Components/Components/Button/Button.scss
  src/FluentCMS.Web.UI.Components/Components/Icon/Icon.cs
  src/FluentCMS.Web.UI.Components/Components/Icon/IconResource.resx
  src/FluentCMS.Web.UI.Components/Styles/App.scss
  src/FluentCMS.Web.UI/Plugins/UserManagement/UserListPlugin.razor
  src/FluentCMS.Web.UI/Plugins/UserManagement/UserUpdatePlugin.razor
  src/FluentCMS.Web.UI/Plugins/UserManagement/UserUpdatePlugin.razor.cs
Labels: enhancement, plugin

#1484 #1483 api client generation
  src/FluentCMS.Web.ApiClients/GeneratedApiClients.cs
  src/FluentCMS.Web.ApiClients/config.nswag
  src/FluentCMS.Web.UI/Plugins/RoleManagement/RoleCreatePlugin.razor
  src/FluentCMS.Web.UI/Plugins/RoleManagement/RoleDetailPlugin.razor
  src/FluentCMS.Web.UI/Plugins/RoleManagement/RoleListPlugin.razor
  src/FluentCMS.Web.UI/Plugins/RoleManagement/RoleUpdatePlugin.razor
Labels: enhancement

#1485 #1441 add default roles while setup
  src/FluentCMS.Web.Api/Setup/Models/AdminTemplate.cs
  src/FluentCMS.Web.Api/Setup/SetupManager.cs
  src/FluentCMS/Templates/Admin/manifest.json
  src/FluentCMS/Templates/Site/Blank/AdminLayout.body.html
  src/FluentCMS/Templates/Site/Blank/AdminLayout.head.html
  src/FluentCMS/Templates/Site/Blank/AdminLayout.html
  src/FluentCMS/Templates/Site/Blank/AuthLayout.body.html
  src/FluentCMS/Templates/Site/Blank/AuthLayout.head.html
  src/FluentCMS/Templates/Site/Blank/AuthLayout.html
  src/FluentCMS/Templates/Site/Blank/SiteLayout.body.html
  src/FluentCMS/Templates/Site/Blank/SiteLayout.head.html
  src/FluentCMS/Templates/Site/Blank/SiteLayout.html
  src/FluentCMS/Templates/Site/Blank/manifest.json
Labels: enhancement

#1492 1466 review refactor client side authentication process and integration with api calls jwt header
  src/FluentCMS.Repositories.LiteDb/LayoutRepository.cs
  src/FluentCMS.Web.Api/Attributes/PolicyAttribute.cs
  src/FluentCMS.Web.Api/Controllers/BaseController.cs
  src/FluentCMS.Web.UI/Components/BasePlugin.razor.cs
  src/FluentCMS.Web.UI/Default.razor.cs
  src/FluentCMS.Web.UI/Plugins/Auth/LoginViewPlugin.razor.cs
  src/FluentCMS.Web.UI/Plugins/Auth/LogoutViewPlugin.razor.cs
  src/FluentCMS.Web.UI/Plugins/ContentManagement/ContentIndexPlugin.razor
  src/FluentCMS.Web.UI/Plugins/ContentManagement/ContentLayout.razor
  src/FluentCMS.Web.UI/Plugins/ContentTypeManagement/ContentTypeListPlugin.razor
  src/FluentCMS.Web.UI/Plugins/Setup/SetupViewPlugin.razor.cs
  src/FluentCMS.Web.UI/Plugins/UserManagement/UserCreatePlugin.razor.cs
  src/FluentCMS.Web.UI/Plugins/UserManagement/UserListPlugin.razor.cs
  src/FluentCMS.Web.UI/Plugins/UserManagement/UserUpdatePlugin.razor.cs
  src/FluentCMS.Web.UI/Services/AdminUIServiceExtensions.cs
  src/FluentCMS.Web.UI/Services/AuthManager.cs
  src/FluentCMS.Web.UI/Services/Cookies/BrowserCookieService.cs
  src/FluentCMS.Web.UI/Services/Cookies/Cookie.cs
  src/FluentCMS.Web.UI/Services/Cookies/CookiesServiceCollectionExtension.cs
  src/FluentCMS.Web.UI/Services/Cookies/HttpContextCookieService.cs
  src/FluentCMS.Web.UI/Services/Cookies/ICookieService.cs
  src/FluentCMS.Web.UI/Services/LocalStorage/BrowserStorageDisabledException.cs
  src/FluentCMS.Web.UI/Services/LocalStorage/BrowserStorageProvider.cs
  src/FluentCMS.Web.UI/Services/LocalStorage/ChangedEventArgs.cs
  src/FluentCMS.Web.UI/Services/LocalStorage/ChangingEventArgs.cs
  src/FluentCMS.Web.UI/Services/LocalStorage/IStorageProvider.cs
  src/FluentCMS.Web.UI/Services/LocalStorage/ISyncLocalStorageService.cs
  src/FluentCMS.Web.UI/Services/LocalStorage/LocalStorageKeys.cs
  src/FluentCMS.Web.UI/Services/LocalStorage/LocalStorageOptions.cs
  src/FluentCMS.Web.UI/Services/LocalStorage/LocalStorageService.cs
  src/FluentCMS.Web.UI/Services/LocalStorage/LocalStorageServiceCollectionExtensions.cs
  src/FluentCMS.Web.UI/Services/LocalStorage/SystemTextJsonSerializer.cs
Labels: enhancement

#1407 Update Role List/Create/Update Plugins
  src/FluentCMS.Services/RoleService.cs
  src/FluentCMS.Web.Api/Controllers/RoleController.cs
  src/FluentCMS.Web.ApiClients/GeneratedApiClients.cs
  src/FluentCMS.Web.ApiClients/config.nswag
  src/FluentCMS.Web.UI/Components/BasePlugin.razor.cs
  src/FluentCMS.Web.UI/Components/Form/PluginFormCheckboxGroup.razor
  src/FluentCMS.Web.UI/Components/Form/PluginFormCheckboxGroup.razor.cs
  src/FluentCMS.Web.UI/MappingProfile.cs
  src/FluentCMS.Web.UI/Plugins/RoleManagement/PluginFormPolicies.razor
  src/FluentCMS.Web.UI/Plugins/RoleManagement/PluginFormPolicies.razor.cs
  src/FluentCMS.Web.UI/Plugins/RoleManagement/RoleCreatePlugin.razor
  src/FluentCMS.Web.UI/Plugins/RoleManagement/RoleCreatePlugin.razor.cs
  src/FluentCMS.Web.UI/Plugins/RoleManagement/RoleDetailPlugin.razor
  src/FluentCMS.Web.UI/Plugins/RoleManagement/RoleListPlugin.razor
  src/FluentCMS.Web.UI/Plugins/RoleManagement/RoleListPlugin.razor.cs
  src/FluentCMS.Web.UI/Plugins/RoleManagement/RoleUpdatePlugin.razor
  src/FluentCMS.Web.UI/Plugins/RoleManagement/RoleUpdatePlugin.razor.cs
Labels: enhancement

#1497 #1496 Cleanup ApiToken plugins
  src/FluentCMS.Web.UI/Components/Form/PluginFormPolicies.razor
  src/FluentCMS.Web.UI/Components/Form/PluginFormPolicies.razor.cs
  src/FluentCMS.Web.UI/MappingProfile.cs
  src/FluentCMS.Web.UI/Plugins/ApiTokenManagement/ApiTokenCreatePlugin.razor
  src/FluentCMS.Web.UI/Plugins/ApiTokenManagement/ApiTokenCreatePlugin.razor.cs
  src/FluentCMS.Web.UI/Plugins/ApiTokenManagement/ApiTokenListPlugin.razor
  src/FluentCMS.Web.UI/Plugins/ApiTokenManagement/ApiTokenListPlugin.razor.cs
  src/FluentCMS.Web.UI/Plugins/ApiTokenManagement/ApiTokenUpdatePlugin.razor
  src/FluentCMS.Web.UI/Plugins/ApiTokenManagement/ApiTokenUpdatePlugin.razor.cs
Labels: enhancement, plugin

#1495 #1383 Deprecate table, its related components and Refactor its usages
  src/FluentCMS.Web.UI.Components/Components/Table/Table.cs
  src/FluentCMS.Web.UI.Components/Components/Table/Table.razor
  src/FluentCMS.Web.UI.Components/Components/Table/Table.razor.cs
  src/FluentCMS.Web.UI.Components/Components/Table/Table.scss
  src/FluentCMS.Web.UI.Components/Components/Table/TableBody.razor
  src/FluentCMS.Web.UI.Components/Components/Table/TableBody.razor.cs
  src/FluentCMS.Web.UI.Components/Components/Table/TableCell.razor
  src/FluentCMS.Web.UI.Components/Components/Table/TableCell.razor.cs
  src/FluentCMS.Web.UI.Components/Components/Table/TableFoot.razor
  src/FluentCMS.Web.UI.Components/Components/Table/TableFoot.razor.cs
  src/FluentCMS.Web.UI.Components/Components/Table/TableHead.razor
  src/FluentCMS.Web.UI.Components/Components/Table/TableHead.razor.cs
  src/FluentCMS.Web.UI.Components/Components/Table/TableRow.razor
  src/FluentCMS.Web.UI.Components/Components/Table/TableRow.razor.cs
  src/FluentCMS.Web.UI.Components/Styles/App.scss
  src/FluentCMS.Web.UI/Plugins/ApiTokenManagement/ApiTokenListPlugin.razor.cs
  src/FluentCMS.Web.UI/Plugins/ContentManagement/ContentListPlugin.razor
  src/FluentCMS.Web.UI/Plugins/ContentTypeManagement/ContentTypeDetailPlugin.razor
  src/FluentCMS.Web.UI/Plugins/ContentTypeManagement/ContentTypeListPlugin.razor
  src/FluentCMS.Web.UI/Plugins/ContentTypeManagement/ContentTypeListPlugin.razor.cs
  src/FluentCMS.Web.UI/Plugins/ContentTypeManagement/ContentTypeUpdatePlugin.razor
Labels: enhancement

#1502 #1469 Deprecate Page component and refactor it's usage
  src/FluentCMS.Web.UI.Components/Components/Page/Page.razor
  src/FluentCMS.Web.UI.Components/Components/Page/Page.razor.cs
  src/FluentCMS.Web.UI.Components/Components/Page/Page.scss
  src/FluentCMS.Web.UI.Components/Components/Page/PageBackButton.razor
  src/FluentCMS.Web.UI.Components/Components/Page/PageBackButton.razor.cs
  src/FluentCMS.Web.UI.Components/Components/Page/PageBody.razor
  src/FluentCMS.Web.UI.Components/Components/Page/PageBody.razor.cs
  src/FluentCMS.Web.UI.Components/Components/Page/PageHeader.razor
  src/FluentCMS.Web.UI.Components/Components/Page/PageHeader.razor.cs
  src/FluentCMS.Web.UI.Components/Styles/App.scss
  src/FluentCMS.Web.UI/Plugins/Auth/ProfileUpdatePlugin.razor
  src/FluentCMS.Web.UI/Plugins/Auth/ProfileViewPlugin.razor
  src/FluentCMS.Web.UI/Plugins/ContentManagement/ContentCreatePlugin.razor
  src/FluentCMS.Web.UI/Plugins/ContentManagement/ContentDetailPlugin.razor
  src/FluentCMS.Web.UI/Plugins/ContentManagement/ContentIndexPlugin.razor
  src/FluentCMS.Web.UI/Plugins/ContentManagement/ContentLayout.razor
  src/FluentCMS.Web.UI/Plugins/ContentManagement/ContentUpdatePlugin.razor
  src/FluentCMS.Web.UI/Plugins/ContentTypeManagement/ContentTypeCreatePlugin.razor
  src/FluentCMS.Web.UI/Plugins/ContentTypeManagement/ContentTypeDetailPlugin.razor
  src/FluentCMS.Web.UI/Plugins/ContentTypeManagement/ContentTypeListPlugin.razor
  src/FluentCMS.Web.UI/Plugins/ContentTypeManagement/ContentTypeUpdatePlugin.razor
  src/FluentCMS.Web.UI/Plugins/FileManagement/FileManagementListPlugin.razor
Labels: enhancement

#1481 #1401 review auth plugin and apply new input components changes
  src/FluentCMS.Web.Api/Controllers/AccountController.cs
  src/FluentCMS.Web.UI.Components/Components/Button/Button.scss
  src/FluentCMS.Web.UI.Components/wwwroot/css/app.min.css
  src/FluentCMS.Web.UI.Components/wwwroot/css/app.min.css.map
  src/FluentCMS.Web.UI/Components/Form/PluginFormCheckbox.razor
  src/FluentCMS.Web.UI/Components/Form/PluginFormCheckbox.razor.cs
  src/FluentCMS.Web.UI/Components/Form/PluginFormDateInput.razor
  src/FluentCMS.Web.UI/Components/Form/PluginFormInputBase.cs
  src/FluentCMS.Web.UI/Components/Form/PluginFormNumberInput.razor
  src/FluentCMS.Web.UI/Components/Form/PluginFormTextInput.razor
  src/FluentCMS.Web.UI/Components/Form/PluginFormTextarea.razor
  src/FluentCMS.Web.UI/Plugins/Auth/AuthPluginForm.razor
  src/FluentCMS.Web.UI/Plugins/Auth/AuthPluginForm.razor.cs
  src/FluentCMS.Web.UI/Plugins/Auth/ForgotPasswordViewPlugin.razor
  src/FluentCMS.Web.UI/Plugins/Auth/ForgotPasswordViewPlugin.razor.cs
  src/FluentCMS.Web.UI/Plugins/Auth/LoginViewPlugin.razor
  src/FluentCMS.Web.UI/Plugins/Auth/LoginViewPlugin.razor.cs
  src/FluentCMS.Web.UI/Plugins/Auth/ProfileUpdatePlugin.razor
  src/FluentCMS.Web.UI/Plugins/Auth/ProfileUpdatePlugin.razor.cs
  src/FluentCMS.Web.UI/Plugins/Auth/ProfileViewPlugin.razor
  src/FluentCMS.Web.UI/Plugins/Auth/ProfileViewPlugin.razor.cs
  src/FluentCMS.Web.UI/Plugins/Auth/RegisterViewPlugin.razor
  src/FluentCMS.Web.UI/Plugins/Auth/ResetPasswordViewPlugin.razor
  src/FluentCMS.Web.UI/Plugins/Auth/ResetPasswordViewPlugin.razor.cs
  src/FluentCMS.Web.UI/Plugins/Setup/SetupViewPlugin.razor
  src/FluentCMS.Web.UI/Plugins/Setup/SetupViewPlugin.razor.cs
  src/FluentCMS/Templates/Admin/AuthLayout.body.html
  src/FluentCMS/Templates/Admin/manifest.json
Labels: enhancement, plugin

#1506 #1501 initial commit for cascading issue in mixing SSR and interactiv…
  src/FluentCMS.Web.Api/Controllers/PageController.cs
  src/FluentCMS.Web.UI/Components/BasePlugin.cs
  src/FluentCMS.Web.UI/Components/BasePlugin.razor
  src/FluentCMS.Web.UI/Components/Form/PluginFormPolicies.razor.cs
  src/FluentCMS.Web.UI/Components/PluginContainer.razor
  src/FluentCMS.Web.UI/Components/PluginContainer.razor.cs
  src/FluentCMS.Web.UI/Components/Section.razor
  src/FluentCMS.Web.UI/Components/Section.razor.cs
  src/FluentCMS.Web.UI/Default.razor
  src/FluentCMS.Web.UI/Default.razor.cs
  src/FluentCMS.Web.UI/Plugins/ApiTokenManagement/ApiTokenCreatePlugin.razor.cs
  src/FluentCMS.Web.UI/Plugins/ApiTokenManagement/ApiTokenListPlugin.razor.cs
  src/FluentCMS.Web.UI/Plugins/ApiTokenManagement/ApiTokenUpdatePlugin.razor.cs
  src/FluentCMS.Web.UI/Plugins/RoleManagement/RoleCreatePlugin.razor.cs
  src/FluentCMS.Web.UI/Plugins/RoleManagement/RoleListPlugin.razor
  src/FluentCMS.Web.UI/Plugins/RoleManagement/RoleListPlugin.razor.cs
  src/FluentCMS.Web.UI/Plugins/RoleManagement/RoleUpdatePlugin.razor.cs
  src/FluentCMS.Web.UI/Plugins/Setup/SetupViewPlugin.razor.cs
  src/FluentCMS.Web.UI/Plugins/UserManagement/UserCreatePlugin.razor.cs
  src/FluentCMS.Web.UI/Plugins/UserManagement/UserListPlugin.razor.cs
  src/FluentCMS.Web.UI/Plugins/UserManagement/UserUpdatePlugin.razor.cs
  src/FluentCMS.Web.UI/Services/AdminUIServiceExtensions.cs
  src/FluentCMS.Web.UI/Services/AuthenticationStateHelper.cs
Labels: bug

#1511 #1337 Cleanup Icons and fix style of icon inside button
  src/FluentCMS.Web.UI.Components/Components/Button/Button.scss
  src/FluentCMS.Web.UI.Components/Components/Icon/Icon.cs
  src/FluentCMS.Web.UI.Components/Components/Icon/Icon.scss
  src/FluentCMS.Web.UI.Components/Components/Icon/IconResource.resx
  src/FluentCMS.Web.UI/Plugins/RoleManagement/RoleListPlugin.razor
  src/FluentCMS.Web.UI/Plugins/UserManagement/UserListPlugin.razor
Labels: enhancement

#1513 #1512 Add FormLabel component and refactor PluginForm components
  src/FluentCMS.Web.UI.Components/Components/TempForm/FormLabel/FormLabel.razor
  src/FluentCMS.Web.UI.Components/Components/TempForm/FormLabel/FormLabel.razor.cs
  src/FluentCMS.Web.UI.Components/Components/TempForm/FormLabel/FormLabel.scss
  src/FluentCMS.Web.UI.Components/Styles/App.scss
  src/FluentCMS.Web.UI/Components/Form/PluginFormCheckbox.razor
  src/FluentCMS.Web.UI/Components/Form/PluginFormCheckbox.razor.cs
  src/FluentCMS.Web.UI/Components/Form/PluginFormCheckboxGroup.razor
  src/FluentCMS.Web.UI/Components/Form/PluginFormDateInput.razor
  src/FluentCMS.Web.UI/Components/Form/PluginFormField.razor
  src/FluentCMS.Web.UI/Components/Form/PluginFormField.razor.cs
  src/FluentCMS.Web.UI/Components/Form/PluginFormInputBase.cs
  src/FluentCMS.Web.UI/Components/Form/PluginFormNumberInput.razor
  src/FluentCMS.Web.UI/Components/Form/PluginFormPolicies.razor
  src/FluentCMS.Web.UI/Components/Form/PluginFormSelect.razor
  src/FluentCMS.Web.UI/Components/Form/PluginFormSwitch.razor
  src/FluentCMS.Web.UI/Components/Form/PluginFormTextInput.razor
  src/FluentCMS.Web.UI/Components/Form/PluginFormTextarea.razor
Labels: enhancement

#1515 #1514 build css
  src/FluentCMS.Web.UI.Components/wwwroot/css/app.min.css
  src/FluentCMS.Web.UI.Components/wwwroot/css/app.min.css.map
Labels: enhancement

#1518 1258 supporting multiple policy attribute to api controllers
  src/FluentCMS.Entities/GlobalSettings.cs
  src/FluentCMS.Entities/Policy.cs
  src/FluentCMS.Entities/Role.cs
  src/FluentCMS.Services/GlobalSettingsService.cs
  src/FluentCMS.Shared/Exceptions/ExceptionCodes.cs
  src/FluentCMS.Shared/IAuthContext.cs
  src/FluentCMS.Web.Api/Attributes/JwtAuthorizeAttribute.cs
  src/FluentCMS.Web.Api/Attributes/PolicyAttribute.cs
  src/FluentCMS.Web.Api/AuthContext.cs
  src/FluentCMS.Web.Api/Controllers/AccountController.cs
  src/FluentCMS.Web.Api/Controllers/ApiTokenController.cs
  src/FluentCMS.Web.Api/Controllers/BaseController.cs
  src/FluentCMS.Web.Api/Controllers/ContentController.cs
  src/FluentCMS.Web.Api/Controllers/ContentTypeController.cs
  src/FluentCMS.Web.Api/Controllers/GlobalSettingsController.cs
  src/FluentCMS.Web.Api/Controllers/LayoutController.cs
  src/FluentCMS.Web.Api/Controllers/PageController.cs
  src/FluentCMS.Web.Api/Controllers/PluginController.cs
  src/FluentCMS.Web.Api/Controllers/PluginDefinitionController.cs
  src/FluentCMS.Web.Api/Controllers/RoleController.cs
  src/FluentCMS.Web.Api/Controllers/SetupController.cs
  src/FluentCMS.Web.Api/Controllers/SiteController.cs
  src/FluentCMS.Web.Api/Controllers/UserController.cs
  src/FluentCMS.Web.Api/Filters/PolicyAuthorizeFiler.cs
  src/FluentCMS.Web.Api/Models/GlobalSettings/GlobalSettingsUpdateRequest.cs
  src/FluentCMS.Web.Api/Setup/SetupManager.cs
  src/FluentCMS.Web.Api/Validation/SlugAttribute.cs
  src/FluentCMS.Web.ApiClients/GeneratedApiClients.cs
  src/FluentCMS.Web.ApiClients/config.nswag
  src/FluentCMS.Web.UI/Plugins/Settings/SettingsViewPlugin.razor
  src/FluentCMS/Templates/Admin/manifest.json
Labels: enhancement

#1522 #1520 delete global setting plugin
  src/FluentCMS.Web.UI/Plugins/Settings/SettingsViewPlugin.razor
  src/FluentCMS.Web.UI/Plugins/Settings/SettingsViewPlugin.razor.cs
  src/FluentCMS/Templates/Admin/AdminLayout.body.html
  src/FluentCMS/Templates/Admin/manifest.json
Labels: bug

#1526 #1525 hiding global policies!
  src/FluentCMS.Web.Api/Controllers/RoleController.cs
Labels: enhancement

#1524 1517 refactor FormField component
  src/FluentCMS.Web.UI.Components/Components/Form/Checkbox/Checkbox.razor
  src/FluentCMS.Web.UI.Components/Components/Form/FormField2/FormField2.cs
  src/FluentCMS.Web.UI.Components/Components/Form/FormField2/FormField2.razor
  src/FluentCMS.Web.UI.Components/Components/Form/FormField2/FormField2.razor.cs
  src/FluentCMS.Web.UI.Components/Components/Form/FormField2/FormField2.scss
  src/FluentCMS.Web.UI.Components/Components/Form/Input/Input.razor
  src/FluentCMS.Web.UI.Components/Components/Form/MarkdownEditor/MarkdownEditor.razor
  src/FluentCMS.Web.UI.Components/Components/Form/Radio/Radio.razor
  src/FluentCMS.Web.UI.Components/Components/Form/Select/Select.razor
  src/FluentCMS.Web.UI.Components/Components/Form/Switch/Switch.razor
  src/FluentCMS.Web.UI.Components/Components/Form/Textarea/Textarea.razor
  src/FluentCMS.Web.UI.Components/Components/TempForm/FormField/FormField.razor
  src/FluentCMS.Web.UI.Components/Components/TempForm/FormField/FormField.razor.cs
  src/FluentCMS.Web.UI.Components/Styles/App.scss
  src/FluentCMS.Web.UI/Components/Form/PluginFormCheckbox.razor
  src/FluentCMS.Web.UI/Components/Form/PluginFormCheckbox.razor.cs
  src/FluentCMS.Web.UI/Components/Form/PluginFormCheckboxGroup.razor
  src/FluentCMS.Web.UI/Components/Form/PluginFormDateInput.razor
  src/FluentCMS.Web.UI/Components/Form/PluginFormInputBase.cs
  src/FluentCMS.Web.UI/Components/Form/PluginFormNumberInput.razor
  src/FluentCMS.Web.UI/Components/Form/PluginFormPolicies.razor
  src/FluentCMS.Web.UI/Components/Form/PluginFormSelect.razor
  src/FluentCMS.Web.UI/Components/Form/PluginFormSwitch.razor
  src/FluentCMS.Web.UI/Components/Form/PluginFormTextInput.razor
  src/FluentCMS.Web.UI/Components/Form/PluginFormTextarea.razor
  src/FluentCMS.Web.UI/Plugins/Auth/ForgotPasswordViewPlugin.razor
  src/FluentCMS.Web.UI/Plugins/Auth/LoginViewPlugin.razor
  src/FluentCMS.Web.UI/Plugins/Auth/ProfileUpdatePlugin.razor
  src/FluentCMS.Web.UI/Plugins/Auth/RegisterViewPlugin.razor
  src/FluentCMS.Web.UI/Plugins/Auth/ResetPasswordViewPlugin.razor
  src/FluentCMS.Web.UI/Plugins/ContentManagement/ContentCreatePlugin.razor
  src/FluentCMS.Web.UI/Plugins/ContentManagement/ContentUpdatePlugin.razor
  src/FluentCMS.Web.UI/Plugins/ContentTypeManagement/ContentTypeCreatePlugin.razor
  src/FluentCMS.Web.UI/Plugins/ContentTypeManagement/ContentTypeFields/ContentTypeFieldModal.razor
  src/FluentCMS.Web.UI/Plugins/ContentTypeManagement/ContentTypeUpdatePlugin.razor
Labels: enhancement

#1529 #1507 fix js sourcemap related error
  src/FluentCMS/wwwroot/js/flowbite.min.js
Labels: enhancement

#1528 #1523 Fix checkboxGroup label issue
  src/FluentCMS.Web.UI/Components/Form/PluginFormCheckboxGroup.razor
Labels: enhancement

#1532 #252 rename `Section` component to `PluginsSection`
  src/FluentCMS.Web.UI/Components/PluginContainer.razor.cs
  src/FluentCMS.Web.UI/Components/PluginsSection.razor
  src/FluentCMS.Web.UI/Components/PluginsSection.razor.cs
  src/FluentCMS/Templates/Admin/AdminLayout.body.html
  src/FluentCMS/Templates/Admin/AuthLayout.body.html
  src/FluentCMS/Templates/Admin/DefaultLayout.body.html
Labels: enhancement

#1536 #1535 comment deprecated sidebar menus
  src/FluentCMS/Templates/Admin/AdminLayout.body.html
Labels: bug

#1537 1533 develop initial content type management plugin
  src/FluentCMS.Entities/AppTemplates/AppTemplate.cs
  src/FluentCMS.Entities/AppTemplates/ContentTemplate.cs
  src/FluentCMS.Entities/AppTemplates/ContentTypeFieldTemplate.cs
  src/FluentCMS.Entities/AppTemplates/ContentTypeTemplate.cs
  src/FluentCMS.Entities/ContentTypeField.cs
  src/FluentCMS.Repositories.Abstractions/IAppTemplateRepository.cs
  src/FluentCMS.Repositories.LiteDb/AppTemplateRepository.cs
  src/FluentCMS.Repositories.MongoDB/AppTemplateRepository.cs
  src/FluentCMS.Services/AppTemplateService.cs
  src/FluentCMS.Shared/Exceptions/ExceptionCodes.cs
  src/FluentCMS.Web.Api/Setup/Models/AdminTemplate.cs
  src/FluentCMS.Web.Api/Setup/SetupManager.cs
  src/FluentCMS.Web.ApiClients/GeneratedApiClients.cs
  src/FluentCMS.Web.ApiClients/config.nswag
  src/FluentCMS.Web.UI/MappingProfile.cs
  src/FluentCMS.Web.UI/Plugins/ContentManagement/ContentCreatePlugin.razor
  src/FluentCMS.Web.UI/Plugins/ContentManagement/ContentDetailPlugin.razor
  src/FluentCMS.Web.UI/Plugins/ContentManagement/ContentUpdatePlugin.razor
  src/FluentCMS.Web.UI/Plugins/ContentTypeManagement/ContentTypeCreatePlugin.razor
  src/FluentCMS.Web.UI/Plugins/ContentTypeManagement/ContentTypeCreatePlugin.razor.cs
  src/FluentCMS.Web.UI/Plugins/ContentTypeManagement/ContentTypeDetailPlugin.razor
  src/FluentCMS.Web.UI/Plugins/ContentTypeManagement/ContentTypeFields/Boolean/BooleanAdvancedSettings.razor
  src/FluentCMS.Web.UI/Plugins/ContentTypeManagement/ContentTypeFields/ContentTypeFieldModal.razor
  src/FluentCMS.Web.UI/Plugins/ContentTypeManagement/ContentTypeFields/Date/DateAdvancedSettings.razor
  src/FluentCMS.Web.UI/Plugins/ContentTypeManagement/ContentTypeFields/Email/EmailAdvancedSettings.razor
  src/FluentCMS.Web.UI/Plugins/ContentTypeManagement/ContentTypeFields/Enumeration/EnumerationAdvancedSettings.razor
  src/FluentCMS.Web.UI/Plugins/ContentTypeManagement/ContentTypeFields/Number/NumberAdvancedSettings.razor
  src/FluentCMS.Web.UI/Plugins/ContentTypeManagement/ContentTypeFields/Password/PasswordAdvancedSettings.razor
  src/FluentCMS.Web.UI/Plugins/ContentTypeManagement/ContentTypeFields/RichText/RichTextAdvancedSettings.razor
  src/FluentCMS.Web.UI/Plugins/ContentTypeManagement/ContentTypeFields/Text/TextAdvancedSettings.razor
  src/FluentCMS.Web.UI/Plugins/ContentTypeManagement/ContentTypeListPlugin.razor
  src/FluentCMS.Web.UI/Plugins/ContentTypeManagement/ContentTypeUpdatePlugin.razor
  src/FluentCMS.Web.UI/Plugins/ContentTypeManagement/ContentTypeUpdatePlugin.razor.cs
  src/FluentCMS/Template/AdminLayout.body.html
  src/FluentCMS/Template/AdminLayout.head.html
  src/FluentCMS/Template/AdminLayout.html
  src/FluentCMS/Template/AuthLayout.body.html
  src/FluentCMS/Template/AuthLayout.head.html
  src/FluentCMS/Template/AuthLayout.html
  src/FluentCMS/Template/DefaultLayout.body.html
  src/FluentCMS/Template/DefaultLayout.head.html
  src/FluentCMS/Template/DefaultLayout.html
  src/FluentCMS/Template/manifest.json
  src/FluentCMS/Templates/App/Blank/manifest.json
  src/FluentCMS/Templates/App/Blog/manifest.json
Labels: enhancement

#1540 1538 develop content type field management plugins
  src/FluentCMS.Entities/ContentTypeField.cs
  src/FluentCMS.Services/ContentTypeService.cs
  src/FluentCMS.Web.ApiClients/GeneratedApiClients.cs
  src/FluentCMS.Web.ApiClients/config.nswag
  src/FluentCMS.Web.UI/Components/Form/PluginBody.razor
  src/FluentCMS.Web.UI/Components/Form/PluginBody.razor.cs
  src/FluentCMS.Web.UI/Plugins/ContentManagement/ContentCreatePlugin.razor
  src/FluentCMS.Web.UI/Plugins/ContentManagement/ContentDetailPlugin.razor
  src/FluentCMS.Web.UI/Plugins/ContentManagement/ContentIndexPlugin.razor
  src/FluentCMS.Web.UI/Plugins/ContentManagement/ContentLayout.razor
  src/FluentCMS.Web.UI/Plugins/ContentManagement/ContentListPlugin.razor
  src/FluentCMS.Web.UI/Plugins/ContentManagement/ContentUpdatePlugin.razor
  src/FluentCMS.Web.UI/Plugins/ContentTypeManagement/ContentTypeDetailPlugin.razor
  src/FluentCMS.Web.UI/Plugins/ContentTypeManagement/ContentTypeDetailPlugin.razor.cs
  src/FluentCMS.Web.UI/Plugins/ContentTypeManagement/ContentTypeFields/Base/Base.cs
  src/FluentCMS.Web.UI/Plugins/ContentTypeManagement/ContentTypeFields/Base/FieldAdvancedSettings.razor
  src/FluentCMS.Web.UI/Plugins/ContentTypeManagement/ContentTypeFields/Base/FieldBasicSettings.razor
  src/FluentCMS.Web.UI/Plugins/ContentTypeManagement/ContentTypeFields/Base/FieldName.razor
  src/FluentCMS.Web.UI/Plugins/ContentTypeManagement/ContentTypeFields/Boolean/Boolean.cs
  src/FluentCMS.Web.UI/Plugins/ContentTypeManagement/ContentTypeFields/Boolean/BooleanAdvancedSettings.razor
  src/FluentCMS.Web.UI/Plugins/ContentTypeManagement/ContentTypeFields/Boolean/BooleanBasicSettings.razor
  src/FluentCMS.Web.UI/Plugins/ContentTypeManagement/ContentTypeFields/ContentTypeFieldExplorer.cs
  src/FluentCMS.Web.UI/Plugins/ContentTypeManagement/ContentTypeFields/ContentTypeFieldModal.razor
  src/FluentCMS.Web.UI/Plugins/ContentTypeManagement/ContentTypeFields/ContentTypeFieldSelector.razor
  src/FluentCMS.Web.UI/Plugins/ContentTypeManagement/ContentTypeFields/Date/Date.cs
  src/FluentCMS.Web.UI/Plugins/ContentTypeManagement/ContentTypeFields/Date/DateAdvancedSettings.razor
  src/FluentCMS.Web.UI/Plugins/ContentTypeManagement/ContentTypeFields/Date/DateBasicSettings.razor
  src/FluentCMS.Web.UI/Plugins/ContentTypeManagement/ContentTypeFields/Email/Email.cs
  src/FluentCMS.Web.UI/Plugins/ContentTypeManagement/ContentTypeFields/Email/EmailAdvancedSettings.razor
  src/FluentCMS.Web.UI/Plugins/ContentTypeManagement/ContentTypeFields/Enumeration/Enumeration.cs
  src/FluentCMS.Web.UI/Plugins/ContentTypeManagement/ContentTypeFields/Enumeration/EnumerationAdvancedSettings.razor
  src/FluentCMS.Web.UI/Plugins/ContentTypeManagement/ContentTypeFields/Enumeration/EnumerationBasicSettings.razor
  src/FluentCMS.Web.UI/Plugins/ContentTypeManagement/ContentTypeFields/Media/Media.cs
  src/FluentCMS.Web.UI/Plugins/ContentTypeManagement/ContentTypeFields/Media/MediaAdvancedSettings.razor
  src/FluentCMS.Web.UI/Plugins/ContentTypeManagement/ContentTypeFields/Media/MediaBasicSettings.razor
  src/FluentCMS.Web.UI/Plugins/ContentTypeManagement/ContentTypeFields/Number/Number.cs
  src/FluentCMS.Web.UI/Plugins/ContentTypeManagement/ContentTypeFields/Number/NumberAdvancedSettings.razor
  src/FluentCMS.Web.UI/Plugins/ContentTypeManagement/ContentTypeFields/Number/NumberBasicSettings.razor
  src/FluentCMS.Web.UI/Plugins/ContentTypeManagement/ContentTypeFields/Password/Password.cs
  src/FluentCMS.Web.UI/Plugins/ContentTypeManagement/ContentTypeFields/Password/PasswordAdvancedSettings.razor
  src/FluentCMS.Web.UI/Plugins/ContentTypeManagement/ContentTypeFields/RichText/RichText.cs
  src/FluentCMS.Web.UI/Plugins/ContentTypeManagement/ContentTypeFields/RichText/RichTextAdvancedSettings.razor
  src/FluentCMS.Web.UI/Plugins/ContentTypeManagement/ContentTypeFields/Text/Text.cs
  src/FluentCMS.Web.UI/Plugins/ContentTypeManagement/ContentTypeFields/Text/TextAdvancedSettings.razor
  src/FluentCMS.Web.UI/Plugins/ContentTypeManagement/ContentTypeFields/Text/TextBasicSettings.razor
  src/FluentCMS.Web.UI/Plugins/ContentTypeManagement/ContentTypeListPlugin.razor
  src/FluentCMS.Web.UI/Plugins/ContentTypeManagement/ContentTypeListPlugin.razor.cs
  src/FluentCMS/Template/manifest.json
Labels: enhancement

#1541 #1531 Refactor BaseInput and cleanup FormInput component
  src/FluentCMS.Web.UI.Components/Base/BaseComponent.cs
  src/FluentCMS.Web.UI.Components/Base/BaseComponentHelpers.cs
  src/FluentCMS.Web.UI.Components/Base/IBaseComponent.cs
  src/FluentCMS.Web.UI.Components/Components/TempForm/BaseInput/BaseInput.cs
  src/FluentCMS.Web.UI.Components/Components/TempForm/FormCheckboxGroup/FormCheckboxGroup.razor
  src/FluentCMS.Web.UI.Components/Components/TempForm/FormCheckboxGroup/FormCheckboxGroup.razor.cs
  src/FluentCMS.Web.UI.Components/Components/TempForm/FormInput/FormInput.razor
  src/FluentCMS.Web.UI.Components/Components/TempForm/FormInput/FormInput.razor.cs
  src/FluentCMS.Web.UI.Components/Components/TempForm/FormInput/FormInput.scss
  src/FluentCMS.Web.UI.Components/Styles/App.scss
  src/FluentCMS.Web.UI.Components/wwwroot/css/app.min.css
  src/FluentCMS.Web.UI.Components/wwwroot/css/app.min.css.map
  src/FluentCMS.Web.UI/Components/Form/PluginFormPolicies.razor
  src/FluentCMS.Web.UI/Components/Form/PluginFormTextInput.razor
  src/FluentCMS.Web.UI/Plugins/ApiTokenManagement/ApiTokenCreatePlugin.razor
  src/FluentCMS.Web.UI/Plugins/ApiTokenManagement/ApiTokenUpdatePlugin.razor
  src/FluentCMS.Web.UI/Plugins/Auth/ForgotPasswordViewPlugin.razor
  src/FluentCMS.Web.UI/Plugins/Auth/LoginViewPlugin.razor
  src/FluentCMS.Web.UI/Plugins/Auth/ProfileUpdatePlugin.razor
  src/FluentCMS.Web.UI/Plugins/Auth/RegisterViewPlugin.razor
  src/FluentCMS.Web.UI/Plugins/Auth/ResetPasswordViewPlugin.razor
  src/FluentCMS.Web.UI/Plugins/ContentTypeManagement/ContentTypeCreatePlugin.razor
  src/FluentCMS.Web.UI/Plugins/ContentTypeManagement/ContentTypeUpdatePlugin.razor
  src/FluentCMS.Web.UI/Plugins/LayoutManagement/LayoutCreatePlugin.razor
  src/FluentCMS.Web.UI/Plugins/LayoutManagement/LayoutUpdatePlugin.razor
  src/FluentCMS.Web.UI/Plugins/RoleManagement/RoleCreatePlugin.razor
  src/FluentCMS.Web.UI/Plugins/RoleManagement/RoleUpdatePlugin.razor
  src/FluentCMS.Web.UI/Plugins/Setup/SetupViewPlugin.razor
  src/FluentCMS.Web.UI/Plugins/UserManagement/UserCreatePlugin.razor
  src/FluentCMS.Web.UI/Plugins/UserManagement/UserUpdatePlugin.razor
Labels: enhancement

#1544 #1472 remove unused components in UI
  src/FluentCMS.Web.UI/Components/Layout/SecondarySidebarWrapper.razor
  src/FluentCMS.Web.UI/Components/Layout/UserInfo.razor
  src/FluentCMS.Web.UI/Components/Layout/Version.razor
  src/FluentCMS.Web.UI/Plugins/Home/AdminHomeViewPlugin.razor
Labels: enhancement

#1546 1542 develop content type fields
  src/FluentCMS.Web.UI/Plugins/ContentTypeManagement/Components/ContentTypeFieldCreate.razor
  src/FluentCMS.Web.UI/Plugins/ContentTypeManagement/Components/ContentTypeFieldCreate.razor.cs
  src/FluentCMS.Web.UI/Plugins/ContentTypeManagement/Components/ContentTypeFieldSelector.razor
  src/FluentCMS.Web.UI/Plugins/ContentTypeManagement/Components/ContentTypeFieldSelector.razor.cs
  src/FluentCMS.Web.UI/Plugins/ContentTypeManagement/Components/ContentTypeFieldUpdate.razor
  src/FluentCMS.Web.UI/Plugins/ContentTypeManagement/Components/ContentTypeFieldUpdate.razor.cs
  src/FluentCMS.Web.UI/Plugins/ContentTypeManagement/Components/ContentTypeFieldsList.razor
  src/FluentCMS.Web.UI/Plugins/ContentTypeManagement/Components/ContentTypeFieldsList.razor.cs
  src/FluentCMS.Web.UI/Plugins/ContentTypeManagement/ContentTypeDetailPlugin.razor
  src/FluentCMS.Web.UI/Plugins/ContentTypeManagement/ContentTypeDetailPlugin.razor.cs
Labels: enhancement

#1547 #5139 `FormActions` enhancement
  src/FluentCMS.Web.UI/Components/Form/FormActions.razor
Labels: enhancement

#1553 1551 update readme on GitHub and remove invalid section
  LICENSE
  README.md
Labels: documentation
