Repository fluentcms/FluentCMS, pull requests merged in 2024-02, with the labels that each got.

#733 Add `App` and `ContentType` CRUD
  src/FluentCMS.Web.UI.Components/Components/Form/Form.razor.cs
  src/FluentCMS.Web.UI.Components/Components/Form/Select.razor
  src/FluentCMS.Web.UI/Helper.cs
  src/FluentCMS.Web.UI/Plugins/AppManagement/AppCreatePlugin.razor
  src/FluentCMS.Web.UI/Plugins/AppManagement/AppDetailPlugin.razor
  src/FluentCMS.Web.UI/Plugins/AppManagement/AppListPlugin.razor
  src/FluentCMS.Web.UI/Plugins/AppManagement/AppUpdatePlugin.razor
  src/FluentCMS.Web.UI/Plugins/ContentTypeManagement/ContentTypeCreatePlugin.razor
  src/FluentCMS.Web.UI/Plugins/ContentTypeManagement/ContentTypeDetailPlugin.razor
  src/FluentCMS.Web.UI/Plugins/ContentTypeManagement/ContentTypeFieldModal.razor
  src/FluentCMS.Web.UI/Plugins/ContentTypeManagement/ContentTypeListPlugin.razor
  src/FluentCMS.Web.UI/Plugins/ContentTypeManagement/ContentTypeUpdatePlugin.razor
  src/FluentCMS/Templates/Admin/AdminLayout.body.html
  src/FluentCMS/Templates/Admin/manifest.json
Labels: panel

#738 fix: implement missing APIs for `ContentType`
  src/FluentCMS.Services/ContentTypeService.cs
  src/FluentCMS.Web.Api/Controllers/ContentTypeController.cs
Labels: enhancement

#741 Add content crud
  src/FluentCMS.Web.UI/Helper.cs
  src/FluentCMS.Web.UI/Plugins/ContentManagement/ContentCreatePlugin.razor
  src/FluentCMS.Web.UI/Plugins/ContentManagement/ContentIndexPlugin.razor
  src/FluentCMS.Web.UI/Plugins/ContentManagement/ContentLayout.razor
  src/FluentCMS.Web.UI/Plugins/ContentManagement/ContentListPlugin.razor
  src/FluentCMS.Web.UI/Plugins/ContentManagement/ContentUpdatePlugin.razor
  src/FluentCMS/Templates/Admin/AdminLayout.body.html
  src/FluentCMS/Templates/Admin/manifest.json
Labels: panel

#743 feat: make admin panel responsive
  src/FluentCMS.Web.UI.Components/Components/Sidebar/Sidebar.razor
  src/FluentCMS.Web.UI.Components/Static/scss/components/_sidebar.scss
  src/FluentCMS/Templates/Admin/AdminLayout.body.html
Labels: panel

#752 740 cannot create content from api
  src/FluentCMS.Web.Api/Controllers/ContentController.cs
  src/FluentCMS.Web.Api/MappingProfile.cs
  src/FluentCMS.Web.Api/Models/Content/ContentDetailResponse.cs
  src/FluentCMS.Web.ApiClients/GeneratedApiClients.cs
  src/FluentCMS.Web.UI/Plugins/ContentManagement/ContentListPlugin.razor
  src/FluentCMS.Web.UI/Plugins/ContentManagement/ContentUpdatePlugin.razor
Labels: enhancement

#751 update: add naming convention to GUIDELINE.md
  src/GUIDELINE.md
Labels: documentation

#758 757 mapping value property of content results in an exception
  src/FluentCMS.Web.Api/MappingProfile.cs
  src/FluentCMS.Web.Api/ValueConverters/ObjectDictionaryValueConverter.cs
Labels: bug

#762 feat: #748 add UI of media library section
  src/FluentCMS.Web.UI/Plugins/MediaLibrary/MediaDetailModal.razor
  src/FluentCMS.Web.UI/Plugins/MediaLibrary/MediaFolderModal.razor
  src/FluentCMS.Web.UI/Plugins/MediaLibrary/MediaListPlugin.razor
  src/FluentCMS.Web.UI/Plugins/MediaLibrary/MediaUploadModal.razor
  src/FluentCMS/Templates/Admin/AdminLayout.body.html
  src/FluentCMS/Templates/Admin/manifest.json
Labels: panel

#765 fix: call `OnChange` event
  src/FluentCMS.Web.UI.Components/Components/Form/Form.razor.cs
Labels: bug

#768 feat: Use components for Setup and Auth layouts
  src/FluentCMS.Web.UI.Components/Layouts/AuthLayout.razor
  src/FluentCMS/Templates/Admin/AuthLayout.body.html
  src/FluentCMS/Templates/Admin/SetupLayout.body.html
Labels: panel

#769 style: reduce opacity of input in disabled state
  src/FluentCMS.Web.UI.Components/Static/scss/components/_input.scss
Labels: component

#770 fix: use Disabled instead on Readonly for inputs
  src/FluentCMS.Web.UI/Plugins/AppManagement/AppUpdatePlugin.razor
  src/FluentCMS.Web.UI/Plugins/ContentTypeManagement/ContentTypeCreatePlugin.razor
  src/FluentCMS.Web.UI/Plugins/UserManagement/UserUpdatePlugin.razor
Labels: component, style

#774 773 update naming conventions
  src/GUIDELINE.md
Labels: documentation

#775 759 content crud functionality
  src/FluentCMS.Web.Api/Controllers/ContentTypeController.cs
  src/FluentCMS.Web.ApiClients/GeneratedApiClients.cs
  src/FluentCMS.Web.ApiClients/config.nswag
  src/FluentCMS.Web.UI/Plugins/ContentManagement/ContentListPlugin.razor
  src/FluentCMS.Web.UI/Plugins/ContentManagement/ContentUpdatePlugin.razor
Labels: enhancement

#777 755 setup e2e test
  src/FluentCMS.E2E.UI/FluentCMS.E2E.UI.esproj
  src/FluentCMS.E2E.UI/config.js
  src/FluentCMS.E2E.UI/cypress.config.js
  src/FluentCMS.E2E.UI/cypress/commands/admin-layout.js
  src/FluentCMS.E2E.UI/cypress/commands/apps.js
  src/FluentCMS.E2E.UI/cypress/commands/auth.js
  src/FluentCMS.E2E.UI/cypress/commands/content-type.js
  src/FluentCMS.E2E.UI/cypress/commands/content.js
  src/FluentCMS.E2E.UI/cypress/commands/index.js
  src/FluentCMS.E2E.UI/cypress/commands/setup.js
  src/FluentCMS.E2E.UI/cypress/e2e/admin-layout.e2e.js
  src/FluentCMS.E2E.UI/cypress/e2e/apps.e2e.js
  src/FluentCMS.E2E.UI/cypress/e2e/basic.e2e.js
  src/FluentCMS.E2E.UI/cypress/e2e/content-type.e2e.js
  src/FluentCMS.E2E.UI/cypress/e2e/content.e2e.js
  src/FluentCMS.E2E.UI/cypress/fixtures/example.json
  src/FluentCMS.E2E.UI/cypress/support/commands.js
  src/FluentCMS.E2E.UI/cypress/support/e2e.js
  src/FluentCMS.E2E.UI/package-lock.json
  src/FluentCMS.E2E.UI/package.json
  src/FluentCMS.Web.UI.Components/Components/Form/FormField.razor
  src/FluentCMS.Web.UI.Components/Static/dist/app.css
  src/FluentCMS.Web.UI.Components/Static/dist/app.css.map
  src/FluentCMS.Web.UI.Components/Static/scss/App.scss
  src/FluentCMS.Web.UI.Components/Static/scss/components/_sidebar.scss
  src/FluentCMS.Web.UI.Components/wwwroot/css/app.min.css
  src/FluentCMS.Web.UI.Components/wwwroot/css/app.min.css.map
  src/FluentCMS.Web.UI/Plugins/AppManagement/AppCreatePlugin.razor
  src/FluentCMS.Web.UI/Plugins/AppManagement/AppListPlugin.razor
  src/FluentCMS.Web.UI/Plugins/AppManagement/AppUpdatePlugin.razor
  src/FluentCMS.Web.UI/Plugins/Auth/ForgotPasswordViewPlugin.razor
  src/FluentCMS.Web.UI/Plugins/Auth/LoginViewPlugin.razor
  src/FluentCMS.Web.UI/Plugins/Auth/RegisterViewPlugin.razor
  src/FluentCMS.Web.UI/Plugins/Auth/ResetPasswordViewPlugin.razor
  src/FluentCMS.Web.UI/Plugins/ContentManagement/ContentCreatePlugin.razor
  src/FluentCMS.Web.UI/Plugins/ContentManagement/ContentLayout.razor
  src/FluentCMS.Web.UI/Plugins/ContentManagement/ContentListPlugin.razor
  src/FluentCMS.Web.UI/Plugins/ContentManagement/ContentUpdatePlugin.razor
  src/FluentCMS.Web.UI/Plugins/ContentTypeManagement/ContentTypeCreatePlugin.razor
  src/FluentCMS.Web.UI/Plugins/ContentTypeManagement/ContentTypeFieldModal.razor
  src/FluentCMS.Web.UI/Plugins/ContentTypeManagement/ContentTypeListPlugin.razor
  src/FluentCMS.Web.UI/Plugins/ContentTypeManagement/ContentTypeUpdatePlugin.razor
  src/FluentCMS.Web.UI/Plugins/Setup/SetupViewPlugin.razor
  src/FluentCMS.sln
  src/FluentCMS/FluentCMS.csproj
  src/FluentCMS/Templates/Admin/AdminLayout.body.html
  src/FluentCMS/wwwroot/js/admin-sidebar.js
Labels: test

#784 783 implement error handling UI
  src/FluentCMS.Web.UI.Components/Components/ExtendedErrorBoundary.razor
  src/FluentCMS.Web.UI.Components/Components/Toast/ToastProvider.razor
  src/FluentCMS.Web.UI/Default.razor
  src/FluentCMS.Web.UI/Default.razor.cs
  src/FluentCMS.Web.UI/Services/AdminUIServiceExtensions.cs
  src/FluentCMS.Web.UI/Services/ErrorMessageExtension.cs
  src/FluentCMS.Web.UI/_Imports.razor
Labels: enhancement

#780 fix: remove unused sidebar items
  src/FluentCMS/Templates/Admin/AdminLayout.body.html
  src/FluentCMS/Templates/Admin/manifest.json
Labels: panel

#788 787-fix-input-refactor-impacts-on-content-type
  src/FluentCMS.Web.UI/Plugins/ContentManagement/ContentCreatePlugin.razor
  src/FluentCMS.Web.UI/Plugins/ContentManagement/ContentUpdatePlugin.razor
Labels: bug

#791 789 fix tests after merge with dev
  src/FluentCMS.E2E.UI/cypress/commands/apps.js
  src/FluentCMS.E2E.UI/cypress/commands/auth.js
  src/FluentCMS.E2E.UI/cypress/commands/content-type.js
  src/FluentCMS.E2E.UI/cypress/commands/content.js
  src/FluentCMS.E2E.UI/cypress/e2e/content.e2e.js
Labels: test

#793 feat: add validation attributes for models
  src/FluentCMS.Web.Api/Models/App/AppCreateRequest.cs
  src/FluentCMS.Web.Api/Models/App/AppUpdateRequest.cs
  src/FluentCMS.Web.Api/Models/Content/ContentCreateRequest.cs
  src/FluentCMS.Web.Api/Models/Content/ContentDetailResponse.cs
  src/FluentCMS.Web.Api/Models/ContentType/ContentTypeCreateRequest.cs
  src/FluentCMS.Web.Api/Models/ContentType/ContentTypeUpdateRequest.cs
  src/FluentCMS.Web.Api/Models/Setup/SetupRequest.cs
  src/FluentCMS.Web.Api/Models/Users/UserCreateRequest.cs
  src/FluentCMS.Web.Api/Models/Users/UserLoginRequest.cs
  src/FluentCMS.Web.Api/Models/Users/UserRegisterRequest.cs
  src/FluentCMS.Web.Api/Models/Users/UserUpdateRequest.cs
  src/FluentCMS.Web.Api/Validation/SlugAttribute.cs
  src/FluentCMS.Web.ApiClients/GeneratedApiClients.cs
  src/FluentCMS.Web.ApiClients/config.nswag
Labels: enhancement

#807 style: update styles of Table pages and sidebar
  src/FluentCMS.Web.UI.Components/Components/Page/PageHeader.razor
  src/FluentCMS.Web.UI.Components/Components/Table/Table.razor.cs
  src/FluentCMS.Web.UI.Components/Components/Table/TableCell.razor
  src/FluentCMS.Web.UI.Components/Static/scss/components/_page.scss
  src/FluentCMS.Web.UI.Components/Static/scss/components/_sidebar.scss
  src/FluentCMS.Web.UI.Components/Static/scss/components/_table.scss
  src/FluentCMS.Web.UI.ComponentsDocs/Pages/Examples/ListPage.razor
  src/FluentCMS.Web.UI.ComponentsDocs/Pages/Examples/MediaPage.razor
  src/FluentCMS.Web.UI/Plugins/AppManagement/AppListPlugin.razor
  src/FluentCMS.Web.UI/Plugins/ContentManagement/ContentListPlugin.razor
  src/FluentCMS.Web.UI/Plugins/ContentTypeManagement/ContentTypeListPlugin.razor
  src/FluentCMS.Web.UI/Plugins/ContentTypeManagement/ContentTypeUpdatePlugin.razor
  src/FluentCMS.Web.UI/Plugins/MediaLibrary/MediaListPlugin.razor
  src/FluentCMS.Web.UI/Plugins/UserManagement/UserListPlugin.razor
  src/FluentCMS/Templates/Admin/AdminLayout.body.html
Labels: style
