Repository fluentcms/FluentCMS, pull requests merged in 2024-09, with the labels that each got.

#1961 #1960 Applying PermissionManager for Page and Plugin
  src/Backend/FluentCMS.Services/PageService.cs
  src/Backend/FluentCMS.Services/Permissions/IPermissionManager.cs
  src/Backend/FluentCMS.Services/Permissions/PermissionManager.cs
  src/Backend/FluentCMS.Services/PluginService.cs
  src/Backend/FluentCMS.Services/SiteService.cs
Labels: enhancement

#1969 #1968 add AdminSidebar and secondary sidebar for content types
  src/FluentCMS/Template/AdminLayout.body.html
  src/FluentCMS/Template/manifest.json
  src/Frontend/FluentCMS.Web.UI/Components/AdminSidebar.razor
  src/Frontend/FluentCMS.Web.UI/Components/AdminSidebar.razor.cs
  src/Frontend/Plugins/FluentCMS.Web.Plugins.Admin/ContentTypeManagement/Content/ContentListPlugin.razor
  src/Frontend/Plugins/FluentCMS.Web.Plugins.Admin/ContentTypeManagement/Content/ContentListPlugin.razor.cs
Labels: enhancement

#1970 #1968 Remove nested sidebar from admin panel
  src/FluentCMS/Template/manifest.json
  src/Frontend/FluentCMS.Web.UI/Components/AdminSidebar.razor
  src/Frontend/Plugins/FluentCMS.Web.Plugins.Admin/ContentTypeManagement/Content/ContentListPlugin.razor
  src/Frontend/Plugins/FluentCMS.Web.Plugins.Admin/ContentTypeManagement/Content/ContentListPlugin.razor.cs
Labels: enhancement

#1963 #1962 refactoring setup manager
  src/Backend/FluentCMS.Services/ServiceExtensions.cs
  src/Backend/FluentCMS.Services/Setup/BaseSetupHandler.cs
  src/Backend/FluentCMS.Services/Setup/Handlers/ApiTokenHandler.cs
  src/Backend/FluentCMS.Services/Setup/Handlers/ContentTypeHandler.cs
  src/Backend/FluentCMS.Services/Setup/Handlers/GlobalSettingsHandler.cs
  src/Backend/FluentCMS.Services/Setup/Handlers/LayoutHandler.cs
  src/Backend/FluentCMS.Services/Setup/Handlers/PageHandler.cs
  src/Backend/FluentCMS.Services/Setup/Handlers/PluginHandler.cs
  src/Backend/FluentCMS.Services/Setup/Handlers/SiteHandler.cs
  src/Backend/FluentCMS.Services/Setup/Handlers/SuperAdminHandler.cs
  src/Backend/FluentCMS.Services/Setup/ISetupHandler.cs
  src/Backend/FluentCMS.Services/Setup/SetupContext.cs
  src/Backend/FluentCMS.Services/Setup/SetupManager.cs
  src/Backend/FluentCMS.Services/Setup/SetupServiceExtensions.cs
  src/Backend/FluentCMS.Services/Setup/SetupSteps.cs
Labels: enhancement

#1978 Refactor JWT auth and middleware, update access levels
  src/Backend/FluentCMS.Web.Api/Attributes/JwtAuthorizeAttribute.cs
  src/Backend/FluentCMS.Web.Api/Controllers/BaseController.cs
  src/Backend/FluentCMS.Web.Api/Controllers/PageController.cs
  src/Backend/FluentCMS.Web.Api/Extentions/ApiServiceExtensions.cs
  src/Backend/FluentCMS.Web.Api/Middleware/ApplicationExecutionContextMiddleware.cs
  src/Backend/FluentCMS.Web.Api/Middleware/JwtAuthorizationMiddleware.cs
  src/Backend/FluentCMS.Web.Api/Middlware/ApplicationExecutionContextMiddleware.cs
Labels: enhancement

#1976 #1975 Implement Blocks API
  src/Backend/FluentCMS.Entities/SiteAssociatedEntities/Block.cs
  src/Backend/FluentCMS.Services/BlockService.cs
  src/Backend/FluentCMS.Web.Api/Controllers/BlockController.cs
  src/Backend/FluentCMS.Web.Api/MappingProfile.cs
  src/Backend/FluentCMS.Web.Api/Models/Block/BlockCreateRequest.cs
  src/Backend/FluentCMS.Web.Api/Models/Block/BlockDetailResponse.cs
  src/Backend/FluentCMS.Web.Api/Models/Block/BlockUpdateRequest.cs
  src/Backend/Repositories/FluentCMS.Repositories.Abstractions/IBlockRepository.cs
  src/Backend/Repositories/FluentCMS.Repositories.LiteDb/BlockRepository.cs
  src/Backend/Repositories/FluentCMS.Repositories.MongoDB/BlockRepository.cs
  src/FluentCMS/Template/manifest.json
  src/Frontend/FluentCMS.Web.ApiClients/ApiClientFactory.cs
  src/Frontend/FluentCMS.Web.ApiClients/GeneratedApiClients.cs
  src/Frontend/FluentCMS.Web.ApiClients/MappingProfile.cs
  src/Frontend/FluentCMS.Web.ApiClients/config.nswag
  src/Frontend/FluentCMS.Web.UI/Components/AdminSidebar.razor
  src/Frontend/Plugins/FluentCMS.Web.Plugins.Admin/BlockManagement/BlockCreatePlugin.razor
  src/Frontend/Plugins/FluentCMS.Web.Plugins.Admin/BlockManagement/BlockCreatePlugin.razor.cs
  src/Frontend/Plugins/FluentCMS.Web.Plugins.Admin/BlockManagement/BlockListPlugin.razor
  src/Frontend/Plugins/FluentCMS.Web.Plugins.Admin/BlockManagement/BlockListPlugin.razor.cs
  src/Frontend/Plugins/FluentCMS.Web.Plugins.Admin/BlockManagement/BlockUpdatePlugin.razor
  src/Frontend/Plugins/FluentCMS.Web.Plugins.Admin/BlockManagement/BlockUpdatePlugin.razor.cs
  src/Shared/Exceptions/ExceptionCodes.cs
Labels: enhancement

#1985 Refactor AuthContext to ApiExecutionContext
  src/Backend/FluentCMS.Services/GlobalSettingsService.cs
  src/Backend/FluentCMS.Services/Permissions/PermissionManager.cs
  src/Backend/FluentCMS.Services/UserRoleService.cs
  src/Backend/FluentCMS.Services/UserService.cs
  src/Backend/FluentCMS.Web.Api/ApiExecutionContext.cs
  src/Backend/FluentCMS.Web.Api/AuthContext.cs
  src/Backend/FluentCMS.Web.Api/Controllers/AccountController.cs
  src/Backend/FluentCMS.Web.Api/Controllers/PageController.cs
  src/Backend/FluentCMS.Web.Api/Extentions/ApiServiceExtensions.cs
  src/Backend/FluentCMS.Web.Api/Filters/ApiResultActionFilter.cs
  src/Backend/FluentCMS.Web.Api/Filters/ApiResultExceptionFilter.cs
  src/Backend/FluentCMS.Web.Api/MappingProfile.cs
  src/Backend/FluentCMS.Web.Api/Middleware/ApplicationExecutionContextMiddleware.cs
  src/Backend/FluentCMS.Web.Api/Middleware/JwtAuthorizationMiddleware.cs
  src/Backend/Repositories/FluentCMS.Repositories.Abstractions/IApiExecutionContext.cs
  src/Backend/Repositories/FluentCMS.Repositories.Abstractions/IAuthContext.cs
  src/Backend/Repositories/FluentCMS.Repositories.LiteDb/ApiTokenRepository.cs
  src/Backend/Repositories/FluentCMS.Repositories.LiteDb/AuditableEntityRepository.cs
  src/Backend/Repositories/FluentCMS.Repositories.LiteDb/BlockRepository.cs
  src/Backend/Repositories/FluentCMS.Repositories.LiteDb/ContentRepository.cs
  src/Backend/Repositories/FluentCMS.Repositories.LiteDb/ContentTypeRepository.cs
  src/Backend/Repositories/FluentCMS.Repositories.LiteDb/FileRepository.cs
  src/Backend/Repositories/FluentCMS.Repositories.LiteDb/FolderRepository.cs
  src/Backend/Repositories/FluentCMS.Repositories.LiteDb/GlobalSettingsRepository.cs
  src/Backend/Repositories/FluentCMS.Repositories.LiteDb/LayoutRepository.cs
  src/Backend/Repositories/FluentCMS.Repositories.LiteDb/PageRepository.cs
  src/Backend/Repositories/FluentCMS.Repositories.LiteDb/PermissionRepository.cs
  src/Backend/Repositories/FluentCMS.Repositories.LiteDb/PluginContentRepository.cs
  src/Backend/Repositories/FluentCMS.Repositories.LiteDb/PluginDefinitionRepository.cs
  src/Backend/Repositories/FluentCMS.Repositories.LiteDb/PluginRepository.cs
  src/Backend/Repositories/FluentCMS.Repositories.LiteDb/RoleRepository.cs
  src/Backend/Repositories/FluentCMS.Repositories.LiteDb/SiteAssociatedRepository.cs
  src/Backend/Repositories/FluentCMS.Repositories.LiteDb/SiteRepository.cs
  src/Backend/Repositories/FluentCMS.Repositories.LiteDb/UserRepository.cs
  src/Backend/Repositories/FluentCMS.Repositories.LiteDb/UserRoleRepository.cs
  src/Backend/Repositories/FluentCMS.Repositories.MongoDB/ApiTokenRepository.cs
  src/Backend/Repositories/FluentCMS.Repositories.MongoDB/AuditableEntityRepository.cs
  src/Backend/Repositories/FluentCMS.Repositories.MongoDB/BlockRepository.cs
  src/Backend/Repositories/FluentCMS.Repositories.MongoDB/ContentRepository.cs
  src/Backend/Repositories/FluentCMS.Repositories.MongoDB/ContentTypeRepository.cs
  src/Backend/Repositories/FluentCMS.Repositories.MongoDB/FileRepository.cs
  src/Backend/Repositories/FluentCMS.Repositories.MongoDB/FolderRepository.cs
  src/Backend/Repositories/FluentCMS.Repositories.MongoDB/GlobalSettingsRepository.cs
  src/Backend/Repositories/FluentCMS.Repositories.MongoDB/LayoutRepository.cs
  src/Backend/Repositories/FluentCMS.Repositories.MongoDB/PageRepository.cs
  src/Backend/Repositories/FluentCMS.Repositories.MongoDB/PermissionRepository.cs
  src/Backend/Repositories/FluentCMS.Repositories.MongoDB/PluginContentRepository.cs
  src/Backend/Repositories/FluentCMS.Repositories.MongoDB/PluginDefinitionRepository.cs
  src/Backend/Repositories/FluentCMS.Repositories.MongoDB/PluginRepository.cs
  src/Backend/Repositories/FluentCMS.Repositories.MongoDB/RoleRepository.cs
  src/Backend/Repositories/FluentCMS.Repositories.MongoDB/SiteAssociatedRepository.cs
  src/Backend/Repositories/FluentCMS.Repositories.MongoDB/SiteRepository.cs
  src/Backend/Repositories/FluentCMS.Repositories.MongoDB/UserRepository.cs
  src/Backend/Repositories/FluentCMS.Repositories.MongoDB/UserRoleRepository.cs
Labels: enhancement

#1993 #1984 Superadmin is added to GlobalSettings in setup process
  src/Backend/FluentCMS.Services/Setup/Handlers/GlobalSettingsHandler.cs
Labels: bug

#1996 #1995 add logout button and theme switcher to default layout
  src/FluentCMS/Template/DefaultLayout.body.html
Labels: enhancement

#1994 #1965 ApiSettings is renamed to ClientSettings
  src/Backend/FluentCMS.Services/Setup/Handlers/ApiTokenHandler.cs
  src/FluentCMS/appsettings.Development.json
  src/FluentCMS/appsettings.json
  src/Frontend/FluentCMS.Web.ApiClients/ApiClientServiceExtensions.cs
  src/Frontend/FluentCMS.Web.ApiClients/ApiSettings.cs
Labels: enhancement

#2002 #1997 Hide Admin Toolbar and Admin Panel button from unauthenticated users
  src/FluentCMS/Template/DefaultLayout.body.html
  src/Frontend/FluentCMS.Web.UI/Default.razor
Labels: enhancement

#2001 #1998 add "Add page" button to toolbar. and update layout styles
  src/FluentCMS/Template/DefaultLayout.body.html
  src/FluentCMS/Template/SingleLayout.body.html
  src/Frontend/FluentCMS.Web.UI/Default.razor
  src/Frontend/FluentCMS.Web.UI/Default.razor.cs
  src/Frontend/FluentCMS.Web.UI/wwwroot/css/html.css
  src/Frontend/FluentCMS.Web.UI/wwwroot/css/toolbar.css
  src/Frontend/Plugins/FluentCMS.Web.Plugins.Admin/PageManagement/PageCreatePlugin.razor.cs
  src/Frontend/Plugins/FluentCMS.Web.Plugins.Admin/PageManagement/PageListPlugin.razor.cs
Labels: enhancement

#2011 fix page layouts & parentId, and fix site create mapping error
  src/Backend/FluentCMS.Web.Api/MappingProfile.cs
  src/Frontend/Plugins/FluentCMS.Web.Plugins.Admin/PageManagement/PageCreatePlugin.razor.cs
  src/Frontend/Plugins/FluentCMS.Web.Plugins.Admin/PageManagement/PageUpdatePlugin.razor.cs
Labels: bug

#2015 Refactor user role fetching and remove message handlers
  src/Backend/FluentCMS.Services/Permissions/PermissionManager.cs
  src/Backend/FluentCMS.Services/UserRoleService.cs
  src/Backend/Repositories/FluentCMS.Repositories.Abstractions/IUserRoleRepository.cs
  src/Backend/Repositories/FluentCMS.Repositories.LiteDb/UserRoleRepository.cs
  src/Backend/Repositories/FluentCMS.Repositories.MongoDB/UserRoleRepository.cs
Labels: enhancement

#2018 #2017 Make layout plugins site based
  src/Backend/FluentCMS.Web.Api/Controllers/LayoutController.cs
  src/Backend/FluentCMS.Web.Api/Models/Layout/LayoutCreateRequest.cs
  src/Backend/FluentCMS.Web.Api/Models/Layout/LayoutDetailResponse.cs
  src/Frontend/FluentCMS.Web.ApiClients/GeneratedApiClients.cs
  src/Frontend/Plugins/FluentCMS.Web.Plugins.Admin/LayoutManagement/LayoutCreatePlugin.razor.cs
  src/Frontend/Plugins/FluentCMS.Web.Plugins.Admin/LayoutManagement/LayoutListPlugin.razor.cs
  src/Frontend/Plugins/FluentCMS.Web.Plugins.Admin/PageManagement/PageCreatePlugin.razor.cs
  src/Frontend/Plugins/FluentCMS.Web.Plugins.Admin/PageManagement/PageListPlugin.razor.cs
  src/Frontend/Plugins/FluentCMS.Web.Plugins.Admin/PageManagement/PageUpdatePlugin.razor.cs
  src/Frontend/Plugins/FluentCMS.Web.Plugins.Admin/SiteManagement/SiteListPlugin.razor.cs
  src/Frontend/Plugins/FluentCMS.Web.Plugins.Admin/SiteManagement/SiteUpdatePlugin.razor.cs
Labels: bug

#2013 #1972 implement tree view component and use for Page update/create plugins
  src/Frontend/FluentCMS.Web.UI.Components/Components/Form/FormTreeSelector/FormTreeSelector.cs
  src/Frontend/FluentCMS.Web.UI.Components/Components/Form/FormTreeSelector/FormTreeSelector.razor
  src/Frontend/FluentCMS.Web.UI.Components/Components/Form/FormTreeSelector/FormTreeSelector.razor.cs
  src/Frontend/FluentCMS.Web.UI.Components/Components/Form/FormTreeSelector/FormTreeSelector.razor.js
  src/Frontend/FluentCMS.Web.UI.Components/Styles/Flowbite/App.scss
  src/Frontend/FluentCMS.Web.UI.Components/Styles/Flowbite/Components/Form/FormTreeSelector.scss
  src/Frontend/FluentCMS.Web.UI.Components/wwwroot/css/flowbite.min.css
  src/Frontend/FluentCMS.Web.UI.Components/wwwroot/css/flowbite.min.css.map
  src/Frontend/FluentCMS.Web.UI.Components/wwwroot/js/tree-selector.js
  src/Frontend/Plugins/FluentCMS.Web.Plugins.Admin/PageManagement/PageCreatePlugin.razor
  src/Frontend/Plugins/FluentCMS.Web.Plugins.Admin/PageManagement/PageCreatePlugin.razor.cs
  src/Frontend/Plugins/FluentCMS.Web.Plugins.Admin/PageManagement/PageUpdatePlugin.razor
  src/Frontend/Plugins/FluentCMS.Web.Plugins.Admin/PageManagement/PageUpdatePlugin.razor.cs
  src/Frontend/Plugins/FluentCMS.Web.Plugins.Admin/PageManagement/ParentPageSelector.razor
  src/Frontend/Plugins/FluentCMS.Web.Plugins.Admin/PageManagement/ParentPageSelector.razor.cs
  src/Frontend/Plugins/FluentCMS.Web.Plugins.Admin/_GlobalUsings.cs
Labels: enhancement, component

#2022 #2021 Fix layout update problem
  src/Backend/FluentCMS.Web.Api/Models/Layout/LayoutCreateRequest.cs
  src/Backend/FluentCMS.Web.Api/Models/Layout/LayoutUpdateRequest.cs
  src/Backend/Repositories/FluentCMS.Repositories.LiteDb/AuditableEntityRepository.cs
  src/Backend/Repositories/FluentCMS.Repositories.LiteDb/SiteAssociatedRepository.cs
  src/Backend/Repositories/FluentCMS.Repositories.MongoDB/AuditableEntityRepository.cs
  src/Backend/Repositories/FluentCMS.Repositories.MongoDB/SiteAssociatedRepository.cs
Labels: bug

#2025 Refactor API token handling and UI improvements
  src/Backend/FluentCMS.Services/ActionNames.cs
  src/Backend/FluentCMS.Services/ApiTokenService.cs
  src/Frontend/Plugins/FluentCMS.Web.Plugins.Admin/ApiTokenManagement/ApiTokenCreatePlugin.razor
  src/Frontend/Plugins/FluentCMS.Web.Plugins.Admin/ApiTokenManagement/ApiTokenListPlugin.razor
  src/Frontend/Plugins/FluentCMS.Web.Plugins.Admin/ApiTokenManagement/ApiTokenListPlugin.razor.cs
Labels: enhancement

#2030 Code cleanup and minor improvements
  src/Backend/FluentCMS.Services/UserRoleService.cs
  src/Backend/Repositories/FluentCMS.Repositories.LiteDb/SiteAssociatedRepository.cs
  src/Backend/Repositories/FluentCMS.Repositories.MongoDB/SiteAssociatedRepository.cs
  src/Frontend/FluentCMS.Web.UI.Components/Components/Form/FormTreeSelector/FormTreeSelector.razor.cs
  src/Frontend/Plugins/FluentCMS.Web.Plugins.Admin/ContentTypeManagement/ContentType/Components/BaseContentTypeFieldComponent.cs
  src/Frontend/Plugins/FluentCMS.Web.Plugins.Admin/ContentTypeManagement/Models/FieldType.cs
  src/Frontend/Plugins/FluentCMS.Web.Plugins.Admin/ContentTypeManagement/Models/FieldTypes.cs
  src/Frontend/Plugins/FluentCMS.Web.Plugins.Admin/ContentTypeManagement/Models/ModelHelpers.cs
  src/Frontend/Plugins/FluentCMS.Web.Plugins.Admin/FileManagement/FileListPlugin.razor.cs
  src/Frontend/Plugins/FluentCMS.Web.Plugins.Admin/FileManagement/FolderBreadcrumbItemType.cs
  src/Frontend/Plugins/FluentCMS.Web.Plugins.Admin/PageManagement/PageCreatePlugin.razor.cs
  src/Frontend/Plugins/FluentCMS.Web.Plugins.Admin/PageManagement/PageUpdatePlugin.razor.cs
  src/Frontend/Plugins/FluentCMS.Web.Plugins.Admin/_GlobalUsings.cs
Labels: enhancement

#2032 Refactor authentication to use JWT token retrieval
  src/Frontend/FluentCMS.Web.ApiClients/ApiClientServiceExtensions.cs
  src/Frontend/FluentCMS.Web.UI/MappingProfile.cs
  src/Frontend/FluentCMS.Web.UI/ServiceExtensions.cs
Labels: enhancement

#2027 #2026 implement onChange for ViewState
  src/Frontend/FluentCMS.Web.UI/Components/PluginContainer.razor.cs
  src/Frontend/FluentCMS.Web.UI/Components/PluginContainerActions.razor.cs
  src/Frontend/FluentCMS.Web.UI/Components/SiteBuilder.razor.cs
  src/Frontend/FluentCMS.Web.UI/Components/SiteBuilderForms.razor.cs
  src/Frontend/FluentCMS.Web.UI/Default.razor.cs
  src/Frontend/FluentCMS.Web.UI/PluginsSection.razor.cs
  src/Frontend/FluentCMS.Web.UI/ServiceExtensions.cs
  src/Frontend/Plugins/FluentCMS.Web.Plugins.Base/BasePlugin.cs
  src/Shared/ViewState.cs
Labels: enhancement

#2042 Add DeleteBySiteId method and permission checks
  src/Backend/FluentCMS.Services/LayoutService.cs
  src/Backend/FluentCMS.Services/MessageHandlers/LayoutMessageHandler.cs
  src/Frontend/Plugins/FluentCMS.Web.Plugins.Admin/LayoutManagement/LayoutCreatePlugin.razor.cs
  src/Frontend/Plugins/FluentCMS.Web.Plugins.Admin/LayoutManagement/LayoutUpdatePlugin.razor
  src/Frontend/Plugins/FluentCMS.Web.Plugins.Admin/LayoutManagement/LayoutUpdatePlugin.razor.cs
Labels: enhancement

#2046 Prevent deletion of default layouts and update dependencies
  src/Backend/FluentCMS.Services/LayoutService.cs
  src/Backend/FluentCMS.Services/MessageHandlers/PageMessageHandler.cs
  src/Frontend/Plugins/FluentCMS.Web.Plugins.Admin/LayoutManagement/LayoutListPlugin.razor
  src/Shared/Exceptions/ExceptionCodes.cs
Labels: enhancement

#2048 2047 final review for mongodb repository and litedb repository
  src/Backend/FluentCMS.Services/LayoutService.cs
  src/Backend/Repositories/FluentCMS.Repositories.Abstractions/IEntityRepository.cs
  src/Backend/Repositories/FluentCMS.Repositories.LiteDb/EntityRepository.cs
  src/Backend/Repositories/FluentCMS.Repositories.MongoDB/EntityRepository.cs
  src/Backend/Repositories/FluentCMS.Repositories.MongoDB/PermissionRepository.cs
Labels: enhancement

#2028 #1889 remove ApiClients dependency from Web.UI.Components project
  src/Frontend/FluentCMS.Web.UI.Components/FluentCMS.Web.UI.Components.csproj
  src/Frontend/FluentCMS.Web.UI.Components/_GlobalUsings.cs
  src/Frontend/Plugins/FluentCMS.Web.Plugins.Base/Components/FormRichTextEditor/FormRichTextEditor.razor
  src/Frontend/Plugins/FluentCMS.Web.Plugins.Base/Components/FormRichTextEditor/FormRichTextEditor.razor.cs
  src/Frontend/Plugins/FluentCMS.Web.Plugins.Base/Components/FormRichTextEditor/FormRichTextEditor.razor.js
  src/Frontend/Plugins/FluentCMS.Web.Plugins.Base/Components/FormRichTextEditor/README.md
  src/Frontend/Plugins/FluentCMS.Web.Plugins.Base/_GlobalUsings.cs
  src/Frontend/Plugins/FluentCMS.Web.Plugins.Base/wwwroot/js/quill-image-resize.min.js
  src/Frontend/Plugins/FluentCMS.Web.Plugins.Base/wwwroot/js/quill.min.js
Labels: enhancement

#2050 #2035 sitebuilder should use interactive render mode
  src/Backend/FluentCMS.Services/MessageHandlers/PluginMessageHandler.cs
  src/Frontend/FluentCMS.Web.UI/Components/PluginContainer.razor
  src/Frontend/FluentCMS.Web.UI/Components/PluginContainer.razor.cs
  src/Frontend/FluentCMS.Web.UI/Components/PluginContainerActions.razor
  src/Frontend/FluentCMS.Web.UI/Components/PluginContainerActions.razor.cs
  src/Frontend/FluentCMS.Web.UI/Components/SiteBuilder.razor
  src/Frontend/FluentCMS.Web.UI/Components/SiteBuilder.razor.cs
  src/Frontend/FluentCMS.Web.UI/Components/SiteBuilder.razor.js
  src/Frontend/FluentCMS.Web.UI/Components/SiteBuilderFloatingButtons.razor
  src/Frontend/FluentCMS.Web.UI/Components/SiteBuilderFloatingButtons.razor.cs
  src/Frontend/FluentCMS.Web.UI/Components/SiteBuilderFloatingButtons.razor.js
  src/Frontend/FluentCMS.Web.UI/Components/SiteBuilderPreview.razor
  src/Frontend/FluentCMS.Web.UI/Components/SiteBuilderPreview.razor.cs
  src/Frontend/FluentCMS.Web.UI/Components/SiteBuilderPreviewScript.razor
  src/Frontend/FluentCMS.Web.UI/Components/SiteBuilderPreviewScript.razor.cs
  src/Frontend/FluentCMS.Web.UI/Components/SiteBuilderPreviewScript.razor.js
  src/Frontend/FluentCMS.Web.UI/Default.razor
  src/Frontend/FluentCMS.Web.UI/Default.razor.cs
  src/Frontend/FluentCMS.Web.UI/FluentCMS.Web.UI.csproj
  src/Frontend/FluentCMS.Web.UI/MappingProfile.cs
  src/Frontend/FluentCMS.Web.UI/PluginsSection.razor.cs
  src/Frontend/FluentCMS.Web.UI/_Imports.razor
  src/Frontend/FluentCMS.Web.UI/wwwroot/css/floating.css
  src/Frontend/FluentCMS.Web.UI/wwwroot/css/plugin-container.css
  src/Frontend/FluentCMS.Web.UI/wwwroot/css/sidebar.css
  src/Frontend/FluentCMS.Web.UI/wwwroot/css/sitebuilder.default.css
  src/Frontend/FluentCMS.Web.UI/wwwroot/css/sitebuilder.editor.css
  src/Frontend/FluentCMS.Web.UI/wwwroot/css/sitebuilder.plugin-edit.css
  src/Frontend/FluentCMS.Web.UI/wwwroot/css/sitebuilder.preview.css
  src/Frontend/FluentCMS.Web.UI/wwwroot/js/actions.js
  src/Frontend/FluentCMS.Web.UI/wwwroot/js/api.js
  src/Frontend/FluentCMS.Web.UI/wwwroot/js/columns.js
  src/Frontend/FluentCMS.Web.UI/wwwroot/js/request.js
  src/Frontend/FluentCMS.Web.UI/wwwroot/js/responsive.js
  src/Frontend/FluentCMS.Web.UI/wwwroot/js/sitebuilder.default.js
  src/Frontend/FluentCMS.Web.UI/wwwroot/js/sitebuilder.editor.js
  src/Frontend/FluentCMS.Web.UI/wwwroot/js/sitebuilder.preview.js
  src/Frontend/Plugins/FluentCMS.Web.Plugins.Base/BasePlugin.cs
  src/Frontend/Plugins/FluentCMS.Web.Plugins.Contents.TextHTML/TextHTMLViewPlugin.razor.cs
Labels: enhancement

#2063 Refactor UserRoleService and simplify DeleteByRoleId
  src/Backend/FluentCMS.Services/UserRoleService.cs
Labels: bug

#2064 Set Description and Name in SiteController.Create
  src/Backend/FluentCMS.Web.Api/Controllers/SiteController.cs
Labels: bug

#2072 Fix some small UI issues
  src/FluentCMS/Templates/Blank/AdminLayout.body.html
  src/FluentCMS/Templates/Blank/manifest.json
  src/FluentCMS/Templates/Default/AdminLayout.body.html
  src/Frontend/FluentCMS.Web.UI.Components/Components/Confirm/Confirm.razor
  src/Frontend/Plugins/FluentCMS.Web.Plugins.Admin/Auth/AuthPluginForm.razor
  src/Frontend/Plugins/FluentCMS.Web.Plugins.Admin/Auth/AuthPluginForm.razor.cs
  src/Frontend/Plugins/FluentCMS.Web.Plugins.Admin/Auth/ForgotPasswordViewPlugin.razor
  src/Frontend/Plugins/FluentCMS.Web.Plugins.Admin/Auth/LoginViewPlugin.razor
  src/Frontend/Plugins/FluentCMS.Web.Plugins.Admin/Auth/RegisterViewPlugin.razor
  src/Frontend/Plugins/FluentCMS.Web.Plugins.Admin/Auth/ResetPasswordViewPlugin.razor
  src/Frontend/Plugins/FluentCMS.Web.Plugins.Admin/Auth/SetupViewPlugin.razor
  src/Frontend/Plugins/FluentCMS.Web.Plugins.Base/Components/PluginForm.razor
  src/Frontend/Plugins/FluentCMS.Web.Plugins.Base/Components/PluginForm.razor.cs
Labels: bug

#2073 #1787 Cleanup Interactive components and add dispose functionality
  src/Frontend/FluentCMS.Web.UI.Components/Components/Accordion/Accordion.razor.cs
  src/Frontend/FluentCMS.Web.UI.Components/Components/Dropdown/Dropdown.razor.cs
  src/Frontend/FluentCMS.Web.UI.Components/Components/Form/FormAutocomplete/FormAutocomplete.razor.cs
  src/Frontend/FluentCMS.Web.UI.Components/Components/Form/FormAutocomplete/FormAutocompleteMultiple.razor.cs
  src/Frontend/FluentCMS.Web.UI.Components/Components/Form/FormCheckboxGroup/FormCheckboxGroup.razor.cs
  src/Frontend/FluentCMS.Web.UI.Components/Components/Form/FormField/FormField.razor.cs
  src/Frontend/FluentCMS.Web.UI.Components/Components/Form/FormFileUpload/FormFileUpload.razor.cs
  src/Frontend/FluentCMS.Web.UI.Components/Components/Form/FormMarkdownEditor/FormMarkdownEditor.razor
  src/Frontend/FluentCMS.Web.UI.Components/Components/Form/FormMarkdownEditor/FormMarkdownEditor.razor.cs
  src/Frontend/FluentCMS.Web.UI.Components/Components/Form/FormRadioGroup/FormRadioGroup.razor.cs
  src/Frontend/FluentCMS.Web.UI.Components/Components/Form/FormSelect/FormSelect.razor.cs
  src/Frontend/FluentCMS.Web.UI.Components/Components/Form/FormTreeSelector/FormTreeSelector.razor
  src/Frontend/FluentCMS.Web.UI.Components/Components/Form/FormTreeSelector/FormTreeSelector.razor.cs
  src/Frontend/FluentCMS.Web.UI.Components/Components/Tooltip/Tooltip.razor
  src/Frontend/FluentCMS.Web.UI.Components/Components/Tooltip/Tooltip.razor.cs
Labels: enhancement

#2076 #2074 resolve warnings of admin plugins
  src/Frontend/Plugins/FluentCMS.Web.Plugins.Admin/ApiTokenManagement/ApiTokenListPlugin.razor.cs
  src/Frontend/Plugins/FluentCMS.Web.Plugins.Admin/ContentTypeManagement/Components/SingleFile/SingleFileFieldFormFilePicker.razor.cs
  src/Frontend/Plugins/FluentCMS.Web.Plugins.Admin/ContentTypeManagement/Content/ContentCreatePlugin.razor.cs
  src/Frontend/Plugins/FluentCMS.Web.Plugins.Admin/ContentTypeManagement/Content/ContentListPlugin.razor.cs
  src/Frontend/Plugins/FluentCMS.Web.Plugins.Admin/ContentTypeManagement/Content/ContentUpdatePlugin.razor.cs
  src/Frontend/Plugins/FluentCMS.Web.Plugins.Admin/ContentTypeManagement/Models/ModelHelpers.cs
  src/Frontend/Plugins/FluentCMS.Web.Plugins.Admin/FileManagement/Files/FileUpdateModal.razor.cs
  src/Frontend/Plugins/FluentCMS.Web.Plugins.Admin/PageManagement/PageCreatePlugin.razor.cs
  src/Frontend/Plugins/FluentCMS.Web.Plugins.Admin/PageManagement/PageListPlugin.razor.cs
  src/Frontend/Plugins/FluentCMS.Web.Plugins.Admin/PageManagement/PageUpdatePlugin.razor.cs
  src/Frontend/Plugins/FluentCMS.Web.Plugins.Admin/RoleManagement/RoleCreatePlugin.razor
Labels: enhancement

#2077 Fix plugin order after create, delete confirm and add Edit content bu…
  src/Frontend/FluentCMS.Web.UI/Components/PluginContainerActions.razor
  src/Frontend/FluentCMS.Web.UI/Components/PluginContainerActions.razor.cs
  src/Frontend/FluentCMS.Web.UI/Components/SiteBuilderPreviewScript.razor.js
  src/Frontend/Plugins/FluentCMS.Web.Plugins.Admin/ContentTypeManagement/Content/ContentListPlugin.razor
  src/Frontend/Plugins/FluentCMS.Web.Plugins.Admin/ContentTypeManagement/ContentType/ContentTypeDetailPlugin.razor
  src/Frontend/Plugins/FluentCMS.Web.Plugins.Base/BasePlugin.cs
  src/Frontend/Plugins/FluentCMS.Web.Plugins.Contents.Block/BlockEditPlugin.razor.cs
  src/Frontend/Plugins/FluentCMS.Web.Plugins.Contents.ContentViewer/ContentListSettingsPlugin.razor.cs
  src/Frontend/Plugins/FluentCMS.Web.Plugins.Contents.RichText/RichTextEditPlugin.razor.cs
  src/Frontend/Plugins/FluentCMS.Web.Plugins.Contents.TextHTML/TextHTMLEditPlugin.razor.cs
Labels: bug, enhancement
