Repository fluentcms/FluentCMS, pull requests merged in 2024-01, with the labels that each got.

#582 #571 Change ApiClients namespace
  src/New/FluentCMS.Web.ApiClients/ClientServiceExtensions.cs
  src/New/FluentCMS.Web.ApiClients/GeneratedApiClients.cs
  src/New/FluentCMS.Web.ApiClients/IApiClient.cs
  src/New/FluentCMS.Web.ApiClients/config.nswag
  src/New/FluentCMS.Web.UI/_GlobalUsings.cs
Labels: enhancement

#584 #583 rename Code property to Status in IApiResult
  src/New/FluentCMS.Web.Api/Filters/ApiResultActionFilter.cs
  src/New/FluentCMS.Web.Api/Filters/ApiResultExceptionFilter.cs
  src/New/FluentCMS.Web.Api/Models/ApiResult.cs
  src/New/FluentCMS.Web.ApiClients/GeneratedApiClients.cs
  src/New/FluentCMS.Web.ApiClients/config.nswag
Labels: enhancement

#587 #585 Setup plugin revision
  src/New/FluentCMS.Web.UI/Plugins/Setup/SetupViewPlugin.razor
Labels: enhancement

#579 fix: add mappings for app
  src/New/FluentCMS.Web.Api/Controllers/AppController.cs
  src/New/FluentCMS.Web.Api/MappingProfile.cs
  src/New/FluentCMS.Web.Api/Models/App/AppDetailResponse.cs
  src/New/FluentCMS.Web.ApiClients/GeneratedApiClients.cs
  src/New/FluentCMS.Web.UI/Services/SetupManager.cs
Labels: enhancement

#574 573 nswag is using incorrect types with datetime fields
  src/New/FluentCMS.Web.ApiClients/GeneratedApiClients.cs
  src/New/FluentCMS.Web.ApiClients/config.nswag
Labels: enhancement

#595 fix: we dont need to check the id for update appservice
  src/New/FluentCMS.Services/AppService.cs
Labels: enhancement

#557 543 pageheader should support moving back
  src/FluentCMS.Web.UI/Components/Core/PageBackButton.razor
  src/FluentCMS.Web.UI/Components/Core/PageHeader.razor
  src/FluentCMS.Web.UI/Layouts/ComponentsLayout.razor
  src/FluentCMS.Web.UI/Previews/Pages/Components/PageHeaderPage.razor
  src/FluentCMS.Web.UI/static/scss/components/_page.scss
Labels: documentation, panel

#591 feat: #592 Add Tab component
  src/FluentCMS.Web.UI/Components/Core/Tab/TabContent.razor
  src/FluentCMS.Web.UI/Components/Core/Tab/TabItem.razor
  src/FluentCMS.Web.UI/Components/Core/Tab/TabList.razor
  src/FluentCMS.Web.UI/Components/Core/Tab/TabPanel.razor
  src/FluentCMS.Web.UI/Components/Core/Tab/Tabs.razor
  src/FluentCMS.Web.UI/Components/Core/TabItem.razor
  src/FluentCMS.Web.UI/Components/Core/Tabs.razor
  src/FluentCMS.Web.UI/Layouts/ComponentsLayout.razor
  src/FluentCMS.Web.UI/Previews/Pages/Components/TabPage.razor
  src/FluentCMS.Web.UI/_Imports.razor
  src/FluentCMS.Web.UI/static/scss/components/_tabs.scss
Labels: panel, component

#599 #589 remove PageTitle
  src/New/FluentCMS.Web.UI/Plugins/Setup/SetupViewPlugin.razor
Labels: enhancement

#600 468 develop e2e test for rolecontroller
  src/New/Tests/FluentCMS.E2eTests/Features/RoleClient.feature
  src/New/Tests/FluentCMS.E2eTests/StepDefinitions/Given/GivenIHaveARole.cs
  src/New/Tests/FluentCMS.E2eTests/StepDefinitions/Given/GivenIHaveRoles.cs
  src/New/Tests/FluentCMS.E2eTests/StepDefinitions/Tags/RequiresTestRole.cs
  src/New/Tests/FluentCMS.E2eTests/StepDefinitions/Then/ThenIShouldGetRoles.cs
  src/New/Tests/FluentCMS.E2eTests/StepDefinitions/Then/ThenRoleCreationResultShouldBeSuccess.cs
  src/New/Tests/FluentCMS.E2eTests/StepDefinitions/Then/ThenRoleDeletionResultShouldBeSuccess.cs
  src/New/Tests/FluentCMS.E2eTests/StepDefinitions/Then/ThenRoleUpdateResultShouldBeSuccess.cs
  src/New/Tests/FluentCMS.E2eTests/StepDefinitions/When/WhenICreateRole.cs
  src/New/Tests/FluentCMS.E2eTests/StepDefinitions/When/WhenIDeleteRole.cs
  src/New/Tests/FluentCMS.E2eTests/StepDefinitions/When/WhenIGetAllRoles.cs
  src/New/Tests/FluentCMS.E2eTests/StepDefinitions/When/WhenIUpdateRoleTo.cs
Labels: enhancement

#570 feat: #562 add tooltip component
  src/FluentCMS.Web.UI/Components/Core/Button.razor
  src/FluentCMS.Web.UI/Components/Core/Tooltip/Tooltip.razor
  src/FluentCMS.Web.UI/Components/Core/Tooltip/Tooltip.razor.js
  src/FluentCMS.Web.UI/Components/Enums/TooltipPlacementEnum.cs
  src/FluentCMS.Web.UI/Layouts/ComponentsLayout.razor
  src/FluentCMS.Web.UI/Previews/Pages/Components/TooltipPage.razor
  src/FluentCMS.Web.UI/_Imports.razor
  src/FluentCMS.Web.UI/static/scss/App.scss
  src/FluentCMS.Web.UI/static/scss/components/_tooltip.scss
  src/FluentCMS.Web.UI/wwwroot/js/floating-ui-dom.min.js
  src/FluentCMS.Web.UI/wwwroot/js/tooltip.blazor.js
Labels: component

#609 feat: fix styles of formField
  src/FluentCMS.Web.UI/Components/Core/Form/Checkbox.razor
  src/FluentCMS.Web.UI/Components/Core/Form/FormField.razor
  src/FluentCMS.Web.UI/Components/Core/Form/Input.razor
  src/FluentCMS.Web.UI/Components/Core/Form/Radio.razor
  src/FluentCMS.Web.UI/Components/Core/Form/Select.razor
  src/FluentCMS.Web.UI/Components/Core/Form/Switch.razor
  src/FluentCMS.Web.UI/Components/Core/Form/Textarea.razor
  src/FluentCMS.Web.UI/Previews/Pages/ContentManager.razor
  src/FluentCMS.Web.UI/static/scss/components/_form.scss
Labels: bug

#610 feat: #593 Add Sample CRUD page
  src/FluentCMS.Web.UI/Layouts/ComponentsLayout.razor
  src/FluentCMS.Web.UI/Previews/Pages/CRUD2/List.razor
Labels: panel

#608 feature: add missing mappings for role
  src/New/FluentCMS.Web.Api/MappingProfile.cs
Labels: enhancement

#614 fix: refactor controller to depend on interface not implementation
  src/New/FluentCMS.Web.Api/Controllers/RoleController.cs
Labels: enhancement

#616 fix: update GivenIHaveRoles to accually create the roles
  src/New/Tests/FluentCMS.E2eTests/StepDefinitions/Given/GivenIHaveRoles.cs
Labels: enhancement

#620 598 add plugindeginition controller and loading module by definition name in dynamic rendering
  src/New/FluentCMS.Entities/Sites/PluginDefinition.cs
  src/New/FluentCMS.Entities/Sites/PluginDefinitionType.cs
  src/New/FluentCMS.Web.Api/Controllers/BaseController.cs
  src/New/FluentCMS.Web.Api/Controllers/PageController.cs
  src/New/FluentCMS.Web.Api/Controllers/PluginDefinitionController.cs
  src/New/FluentCMS.Web.Api/Controllers/SiteController.cs
  src/New/FluentCMS.Web.Api/Models/PluginDefinition/PluginDefinitionDetailResponse.cs
  src/New/FluentCMS.Web.Api/Models/Users/UserCreateRequest.cs
  src/New/FluentCMS.Web.Api/Models/Users/UserDetailResponse.cs
  src/New/FluentCMS.Web.Api/Models/Users/UserUpdateRequest.cs
  src/New/FluentCMS.Web.Api/Setup/Models/PluginDefinitionTemplate.cs
  src/New/FluentCMS.Web.Api/Setup/SetupManager.cs
  src/New/FluentCMS.Web.ApiClients/GeneratedApiClients.cs
  src/New/FluentCMS.Web.ApiClients/config.nswag
  src/New/FluentCMS.Web.UI/Components/Section.razor
  src/New/FluentCMS.Web.UI/Default.razor.cs
  src/New/FluentCMS.Web.UI/Helper.cs
  src/New/FluentCMS.Web.UI/Plugins/UserManagement/UserCreatePlugin.razor
  src/New/FluentCMS.Web.UI/Plugins/UserManagement/UserListPlugin.razor
  src/New/FluentCMS.Web.UI/Plugins/UserManagement/UserUpdatePlugin.razor
  src/New/FluentCMS.Web.UI/Services/SetupManager.cs
  src/New/FluentCMS.Web.UI/_Imports.razor
  src/New/FluentCMS/Templates/Admin/AdminLayout.body.html
  src/New/FluentCMS/Templates/Admin/manifest.json
  src/New/Tests/FluentCMS.E2eTests/ImplicitUsings.cs
  src/New/Tests/FluentCMS.E2eTests/StepDefinitions/Given/GivenIHaveAService.cs
  src/New/Tests/FluentCMS.E2eTests/StepDefinitions/Tags/RequiresFreshSetup.cs
  src/New/Tests/FluentCMS.E2eTests/StepDefinitions/Then/ThenResponseErrorsShouldNotBeEmpty.cs
  src/New/Tests/FluentCMS.E2eTests/StepDefinitions/When/WhenIAuthenticateAsync.cs
  src/New/Tests/FluentCMS.E2eTests/StepDefinitions/When/WhenIUpdateAUser.cs
  src/New/Tests/FluentCMS.E2eTests/StepDefinitions/When/WhenIUpdateApp.cs
Labels: enhancement, plugin

#626 fix: update ContentTypeController
  src/New/FluentCMS.Web.Api/Controllers/ContentTypeController.cs
Labels: enhancement

#624 fix: update mapping profile
  src/New/FluentCMS.Web.Api/Controllers/ContentTypeController.cs
  src/New/FluentCMS.Web.Api/MappingProfile.cs
  src/New/FluentCMS.Web.Api/Models/ContentType/ContentTypeDetailResponse.cs
  src/New/FluentCMS.Web.ApiClients/GeneratedApiClients.cs
  src/New/FluentCMS.Web.ApiClients/config.nswag
  src/New/Tests/FluentCMS.E2eTests/StepDefinitions/Given/GivenIHaveAContentType.cs
  src/New/Tests/FluentCMS.E2eTests/StepDefinitions/Given/GivenIHaveAContentTypeUpdateRequest.cs
  src/New/Tests/FluentCMS.E2eTests/StepDefinitions/Then/ThenIShouldNotSeeTheContentType.cs
  src/New/Tests/FluentCMS.E2eTests/StepDefinitions/Then/ThenIShouldNotSeeTheField.cs
  src/New/Tests/FluentCMS.E2eTests/StepDefinitions/Then/ThenIShouldSeeContentTypes.cs
  src/New/Tests/FluentCMS.E2eTests/StepDefinitions/Then/ThenIShouldSeeTheContentType.cs
  src/New/Tests/FluentCMS.E2eTests/StepDefinitions/Then/ThenIShouldSeeTheField.cs
  src/New/Tests/FluentCMS.E2eTests/StepDefinitions/Then/ThenIShouldSeeTheUpdatedContentType.cs
  src/New/Tests/FluentCMS.E2eTests/StepDefinitions/When/WhenIDeleteAContentType.cs
  src/New/Tests/FluentCMS.E2eTests/StepDefinitions/When/WhenIDeleteAField.cs
  src/New/Tests/FluentCMS.E2eTests/StepDefinitions/When/WhenISetAField.cs
Labels: enhancement

#629 627 contenttypes deletefield api is broken
  src/New/FluentCMS.Services/ContentTypeService.cs
  src/New/Tests/FluentCMS.E2eTests/StepDefinitions/When/WhenIDeleteAField.cs
Labels: enhancement

#635 docs: #634 use Page component in component examples
  src/FluentCMS.Web.UI/Previews/Pages/Components/AlertPage.razor
  src/FluentCMS.Web.UI/Previews/Pages/Components/AutocompletePage.razor
  src/FluentCMS.Web.UI/Previews/Pages/Components/BadgePage.razor
  src/FluentCMS.Web.UI/Previews/Pages/Components/ButtonPage.razor
  src/FluentCMS.Web.UI/Previews/Pages/Components/CardPage.razor
  src/FluentCMS.Web.UI/Previews/Pages/Components/CheckboxPage.razor
  src/FluentCMS.Web.UI/Previews/Pages/Components/ConfirmPage.razor
  src/FluentCMS.Web.UI/Previews/Pages/Components/DropdownPage.razor
  src/FluentCMS.Web.UI/Previews/Pages/Components/GridPage.razor
  src/FluentCMS.Web.UI/Previews/Pages/Components/IconPage.razor
  src/FluentCMS.Web.UI/Previews/Pages/Components/IndexPage.razor
  src/FluentCMS.Web.UI/Previews/Pages/Components/InputPage.razor
  src/FluentCMS.Web.UI/Previews/Pages/Components/ModalPage.razor
  src/FluentCMS.Web.UI/Previews/Pages/Components/PageHeaderPage.razor
  src/FluentCMS.Web.UI/Previews/Pages/Components/PaginationPage.razor
  src/FluentCMS.Web.UI/Previews/Pages/Components/RadioPage.razor
  src/FluentCMS.Web.UI/Previews/Pages/Components/SelectPage.razor
  src/FluentCMS.Web.UI/Previews/Pages/Components/SpinnerPage.razor
  src/FluentCMS.Web.UI/Previews/Pages/Components/SwitchPage.razor
  src/FluentCMS.Web.UI/Previews/Pages/Components/TabPage.razor
  src/FluentCMS.Web.UI/Previews/Pages/Components/TablePage.razor
  src/FluentCMS.Web.UI/Previews/Pages/Components/TextareaPage.razor
  src/FluentCMS.Web.UI/Previews/Pages/Components/TooltipPage.razor
Labels: documentation, component

#648 style: #647 cleanup scss files
  src/FluentCMS.Web.UI/App.razor
  src/FluentCMS.Web.UI/Components/Core/Base/InputBaseComponent.cs
  src/FluentCMS.Web.UI/static/scss/App.scss
  src/FluentCMS.Web.UI/static/scss/components/_alert.scss
  src/FluentCMS.Web.UI/static/scss/components/_autocomplete.scss
  src/FluentCMS.Web.UI/static/scss/components/_badge.scss
  src/FluentCMS.Web.UI/static/scss/components/_button.scss
  src/FluentCMS.Web.UI/static/scss/components/_card.scss
  src/FluentCMS.Web.UI/static/scss/components/_checkbox.scss
  src/FluentCMS.Web.UI/static/scss/components/_close-button.scss
  src/FluentCMS.Web.UI/static/scss/components/_confirm.scss
  src/FluentCMS.Web.UI/static/scss/components/_dropdown.scss
  src/FluentCMS.Web.UI/static/scss/components/_form-check.scss
  src/FluentCMS.Web.UI/static/scss/components/_form.scss
  src/FluentCMS.Web.UI/static/scss/components/_grid.scss
  src/FluentCMS.Web.UI/static/scss/components/_icon.scss
  src/FluentCMS.Web.UI/static/scss/components/_input.scss
  src/FluentCMS.Web.UI/static/scss/components/_layout.scss
  src/FluentCMS.Web.UI/static/scss/components/_logo.scss
  src/FluentCMS.Web.UI/static/scss/components/_modal.scss
  src/FluentCMS.Web.UI/static/scss/components/_page.scss
  src/FluentCMS.Web.UI/static/scss/components/_pagination.scss
  src/FluentCMS.Web.UI/static/scss/components/_radio.scss
  src/FluentCMS.Web.UI/static/scss/components/_select.scss
  src/FluentCMS.Web.UI/static/scss/components/_sidebar.scss
  src/FluentCMS.Web.UI/static/scss/components/_spinner.scss
  src/FluentCMS.Web.UI/static/scss/components/_switch.scss
  src/FluentCMS.Web.UI/static/scss/components/_table.scss
  src/FluentCMS.Web.UI/static/scss/components/_tabs.scss
  src/FluentCMS.Web.UI/static/scss/components/_textarea.scss
  src/FluentCMS.Web.UI/static/scss/components/_tooltip.scss
  src/FluentCMS.Web.UI/static/scss/pages/_login.scss
  src/FluentCMS.Web.UI/static/scss/pages/_sites.scss
Labels: component, style

#662 #654 add Api Client Exception handling
  src/New/FluentCMS.Web.ApiClients/ApiClientException.cs
  src/New/FluentCMS.Web.ApiClients/ApiExceptionResult.cs
  src/New/FluentCMS.Web.ApiClients/GeneratedApiClients.cs
  src/New/FluentCMS.Web.ApiClients/config.nswag
  src/New/FluentCMS.Web.UI/Plugins/UserManagement/UserCreatePlugin.razor
Labels: enhancement

#680 #679 add base url
  src/FluentCMS.Web.UI/App.razor
Labels: enhancement

#681 677 add link styles for button
  src/FluentCMS.Web.UI.Components/Components/Button/Button.razor
  src/FluentCMS.Web.UI.Components/Static/scss/components/_button.scss
  src/FluentCMS.Web.UI.ComponentsDocs/Pages/Components/ButtonPage.razor
  src/FluentCMS.Web.UI.ComponentsDocs/Pages/Examples/LoginPage.razor
Labels: enhancement, component

#687 #684 add styles for spacer component
  src/FluentCMS.Web.UI.Components/Components/Spacer.razor
  src/FluentCMS.Web.UI.Components/Components/Spacer.razor.cs
  src/FluentCMS.Web.UI.Components/Static/scss/components/_spacer.scss
Labels: component

#688 #686 reduce padding of CardBody
  src/FluentCMS.Web.UI.Components/Static/scss/components/_card.scss
Labels: component

#703 style: #702 fix admin sidebar
  src/FluentCMS/Templates/Admin/AdminLayout.body.html
Labels: panel

#722 #721 apply coding convention
  src/FluentCMS.Web.Api/MappingProfile.cs
  src/FluentCMS.Web.ApiClients/ClientServiceExtensions.cs
  src/FluentCMS.Web.UI.Components/Components/Card/Card.razor.cs
  src/Tests/FluentCMS.E2eTests/StepDefinitions/Given/GivenIHaveAContentTypeUpdateRequest.cs
  src/Tests/FluentCMS.E2eTests/StepDefinitions/Then/ThenIShouldSeeTheContentType.cs
Labels: enhancement

#724 #723 Update Nuget packages
  src/FluentCMS.Entities/FluentCMS.Entities.csproj
  src/FluentCMS.Services/FluentCMS.Services.csproj
  src/FluentCMS.Web.UI.Components/FluentCMS.Web.UI.Components.csproj
  src/FluentCMS.Web.UI/FluentCMS.Web.UI.csproj
  src/Tests/FluentCMS.E2eTests/FluentCMS.E2eTests.csproj
Labels: enhancement

#727 #726 add local storage service
  src/FluentCMS.Web.UI/Services/AdminUIServiceExtensions.cs
  src/FluentCMS.Web.UI/Services/LocalStorage/BrowserStorageDisabledException.cs
  src/FluentCMS.Web.UI/Services/LocalStorage/BrowserStorageProvider.cs
  src/FluentCMS.Web.UI/Services/LocalStorage/ChangedEventArgs.cs
  src/FluentCMS.Web.UI/Services/LocalStorage/ChangingEventArgs.cs
  src/FluentCMS.Web.UI/Services/LocalStorage/IStorageProvider.cs
  src/FluentCMS.Web.UI/Services/LocalStorage/ISyncLocalStorageService.cs
  src/FluentCMS.Web.UI/Services/LocalStorage/LocalStorageOptions.cs
  src/FluentCMS.Web.UI/Services/LocalStorage/LocalStorageService.cs
  src/FluentCMS.Web.UI/Services/LocalStorage/LocalStorageServiceCollectionExtensions.cs
  src/FluentCMS.Web.UI/Services/LocalStorage/SystemTextJsonSerializer.cs
  src/FluentCMS.Web.UI/_Imports.razor
Labels: enhancement

#730 fix: remove icons from sidebar
  src/FluentCMS/Templates/Admin/AdminLayout.body.html
Labels: panel

#705 700 add logout page definition
  src/FluentCMS/Templates/Admin/manifest.json
Labels: enhancement

#707 feat: implement Login page functionality
  src/FluentCMS.Web.UI/Plugins/Auth/LoginViewPlugin.razor
Labels: enhancement

#711 fix: setup page password binding
  src/FluentCMS.Web.UI/Plugins/Setup/SetupViewPlugin.razor
Labels: enhancement
