Repository fluentcms/FluentCMS, pull requests merged in 2024-07, with the labels that each got.

#1762 Refactor DI and update `Default.razor.cs`
  src/Frontend/FluentCMS.Web.UI/Default.razor.cs
  src/Frontend/FluentCMS.Web.UI/ServiceExtensions.cs
Labels: enhancement

#1765 Implement ILayoutProcessor interface
  src/Frontend/FluentCMS.Web.UI/Default.razor.cs
  src/Frontend/FluentCMS.Web.UI/DynamicRendering/LayoutProcessor.cs
  src/Frontend/FluentCMS.Web.UI/ServiceExtensions.cs
Labels: enhancement

#1767 #1766 extract interface for SetupManager
  src/Backend/FluentCMS.Web.Api/Controllers/PageController.cs
  src/Backend/FluentCMS.Web.Api/Controllers/SetupController.cs
  src/Backend/FluentCMS.Web.Api/Extentions/ApiServiceExtensions.cs
  src/Backend/FluentCMS.Web.Api/Setup/SetupManager.cs
  src/FluentCMS/Program.cs
Labels: enhancement

#1769 Refactor API client access and management
  src/Frontend/FluentCMS.Web.ApiClients/ApiClientException.cs
  src/Frontend/FluentCMS.Web.ApiClients/ApiClientFactory.cs
  src/Frontend/FluentCMS.Web.ApiClients/ApiClientServiceExtensions.cs
  src/Frontend/FluentCMS.Web.ApiClients/HttpClientFactoryHelper.cs
  src/Frontend/FluentCMS.Web.ApiClients/IApiClient.cs
  src/Frontend/FluentCMS.Web.ApiClients/MappingProfile.cs
  src/Frontend/FluentCMS.Web.ApiClients/Services/SetupManager.cs
  src/Frontend/FluentCMS.Web.Plugins/BasePlugin.cs
  src/Frontend/FluentCMS.Web.UI/PageEditorForms.razor.cs
  src/Frontend/FluentCMS.Web.UI/PageEditorSidebar.razor.cs
  src/Frontend/FluentCMS.Web.UI/ServiceExtensions.cs
  src/Frontend/Plugins/FluentCMS.Web.Plugins.Admin/ApiTokenManagement/ApiTokenCreatePlugin.razor.cs
  src/Frontend/Plugins/FluentCMS.Web.Plugins.Admin/ApiTokenManagement/ApiTokenListPlugin.razor.cs
  src/Frontend/Plugins/FluentCMS.Web.Plugins.Admin/ApiTokenManagement/ApiTokenUpdatePlugin.razor.cs
  src/Frontend/Plugins/FluentCMS.Web.Plugins.Admin/Auth/ForgotPasswordViewPlugin.razor.cs
  src/Frontend/Plugins/FluentCMS.Web.Plugins.Admin/Auth/ProfileUpdatePlugin.razor.cs
  src/Frontend/Plugins/FluentCMS.Web.Plugins.Admin/Auth/RegisterViewPlugin.razor.cs
  src/Frontend/Plugins/FluentCMS.Web.Plugins.Admin/Auth/ResetPasswordViewPlugin.razor.cs
  src/Frontend/Plugins/FluentCMS.Web.Plugins.Admin/ContentTypeManagement/Content/BaseContentPlugin.cs
  src/Frontend/Plugins/FluentCMS.Web.Plugins.Admin/ContentTypeManagement/Content/ContentCreatePlugin.razor.cs
  src/Frontend/Plugins/FluentCMS.Web.Plugins.Admin/ContentTypeManagement/Content/ContentListPlugin.razor.cs
  src/Frontend/Plugins/FluentCMS.Web.Plugins.Admin/ContentTypeManagement/Content/ContentUpdatePlugin.razor.cs
  src/Frontend/Plugins/FluentCMS.Web.Plugins.Admin/ContentTypeManagement/ContentType/Components/BaseContentTypeFieldComponent.cs
  src/Frontend/Plugins/FluentCMS.Web.Plugins.Admin/ContentTypeManagement/ContentType/Components/ContentTypeFieldCreate.razor.cs
  src/Frontend/Plugins/FluentCMS.Web.Plugins.Admin/ContentTypeManagement/ContentType/Components/ContentTypeFieldDelete.razor.cs
  src/Frontend/Plugins/FluentCMS.Web.Plugins.Admin/ContentTypeManagement/ContentType/Components/ContentTypeFieldUpdate.razor.cs
  src/Frontend/Plugins/FluentCMS.Web.Plugins.Admin/ContentTypeManagement/ContentType/ContentTypeCreatePlugin.razor.cs
  src/Frontend/Plugins/FluentCMS.Web.Plugins.Admin/ContentTypeManagement/ContentType/ContentTypeDetailPlugin.razor.cs
  src/Frontend/Plugins/FluentCMS.Web.Plugins.Admin/ContentTypeManagement/ContentType/ContentTypeListPlugin.razor.cs
  src/Frontend/Plugins/FluentCMS.Web.Plugins.Admin/ContentTypeManagement/ContentType/ContentTypeUpdatePlugin.razor.cs
  src/Frontend/Plugins/FluentCMS.Web.Plugins.Admin/FileManagement/FileListPlugin.razor.cs
  src/Frontend/Plugins/FluentCMS.Web.Plugins.Admin/LayoutManagement/LayoutCreatePlugin.razor.cs
  src/Frontend/Plugins/FluentCMS.Web.Plugins.Admin/LayoutManagement/LayoutListPlugin.razor.cs
  src/Frontend/Plugins/FluentCMS.Web.Plugins.Admin/LayoutManagement/LayoutUpdatePlugin.razor.cs
  src/Frontend/Plugins/FluentCMS.Web.Plugins.Admin/RoleManagement/RoleCreatePlugin.razor.cs
  src/Frontend/Plugins/FluentCMS.Web.Plugins.Admin/RoleManagement/RoleListPlugin.razor.cs
  src/Frontend/Plugins/FluentCMS.Web.Plugins.Admin/RoleManagement/RoleUpdatePlugin.razor.cs
  src/Frontend/Plugins/FluentCMS.Web.Plugins.Admin/SiteManagement/SiteCreatePlugin.razor.cs
  src/Frontend/Plugins/FluentCMS.Web.Plugins.Admin/SiteManagement/SiteListPlugin.razor.cs
  src/Frontend/Plugins/FluentCMS.Web.Plugins.Admin/SiteManagement/SiteUpdatePlugin.razor.cs
  src/Frontend/Plugins/FluentCMS.Web.Plugins.Admin/UserManagement/UserCreatePlugin.razor.cs
  src/Frontend/Plugins/FluentCMS.Web.Plugins.Admin/UserManagement/UserListPlugin.razor.cs
  src/Frontend/Plugins/FluentCMS.Web.Plugins.Admin/UserManagement/UserUpdatePlugin.razor.cs
Labels: enhancement

#1771 1770 configure and run analyzer
  src/Backend/FluentCMS.Identity/UserStore_IUserAuthenticationTokenStore.cs
  src/Backend/FluentCMS.Identity/UserStore_IUserLoginStore.cs
  src/Frontend/FluentCMS.Web.UI.Components/Components/Toast/ToastProvider.razor.cs
  src/Frontend/FluentCMS.Web.UI/PageEditorSidebar.razor.cs
  src/Frontend/Plugins/FluentCMS.Web.Plugins.Admin/ContentTypeManagement/ContentType/ContentTypeDetailPlugin.razor.cs
Labels: enhancement

#1773 Refactor AuthManager for ApiClientFactory
  src/Frontend/FluentCMS.Web.ApiClients/Services/AuthManager.cs
Labels: enhancement

#1774 Implement Container system without using any library
  src/Backend/FluentCMS.Entities/Sites/Plugin.cs
  src/Backend/FluentCMS.Web.Api/Controllers/PluginController.cs
  src/Backend/FluentCMS.Web.Api/Models/Plugin/PluginCreateRequest.cs
  src/Backend/FluentCMS.Web.Api/Models/Plugin/PluginDetailResponse.cs
  src/Backend/FluentCMS.Web.Api/Models/Plugin/PluginUpdateRequest.cs
  src/Frontend/FluentCMS.Web.ApiClients/GeneratedApiClients.cs
  src/Frontend/FluentCMS.Web.ApiClients/config.nswag
  src/Frontend/FluentCMS.Web.UI/Default.razor
  src/Frontend/FluentCMS.Web.UI/PluginContainer.razor
  src/Frontend/FluentCMS.Web.UI/PluginsSection.razor
  src/Frontend/FluentCMS.Web.UI/wwwroot/css/columns.css
  src/Frontend/FluentCMS.Web.UI/wwwroot/css/columns.editor.css
  src/Frontend/FluentCMS.Web.UI/wwwroot/css/sitebuilder.css
  src/Frontend/FluentCMS.Web.UI/wwwroot/js/columns.js
  src/Frontend/FluentCMS.Web.UI/wwwroot/js/sitebuilder.js
  src/Frontend/FluentCMS.Web.UI/wwwroot/js/sitebuilder.preview.js
Labels: enhancement

#1776 Delete PageEditorToggler.razor
  src/Frontend/FluentCMS.Web.UI/PageEditorToggler.razor
Labels: enhancement

#1783 1777 refactor viewcontext and develope viewstate avoid pageplugin editing for admin
  src/Backend/FluentCMS.Entities/Sites/Page.cs
  src/Backend/FluentCMS.Entities/Sites/Plugin.cs
  src/Backend/FluentCMS.Entities/Sites/PluginDefinition.cs
  src/Backend/FluentCMS.Web.Api/Controllers/PageController.cs
  src/Backend/FluentCMS.Web.Api/Models/Pages/PageDetailResponse.cs
  src/Backend/FluentCMS.Web.Api/Models/Pages/PageFullDetailResponse.cs
  src/Backend/FluentCMS.Web.Api/Models/Plugin/PluginDetailResponse.cs
  src/Backend/FluentCMS.Web.Api/Models/PluginDefinition/PluginDefinitionCreateRequest.cs
  src/Backend/FluentCMS.Web.Api/Models/PluginDefinition/PluginDefinitionDetailResponse.cs
  src/Backend/FluentCMS.Web.Api/Setup/Models/PageTemplate.cs
  src/Backend/FluentCMS.Web.Api/Setup/Models/PluginDefinitionTemplate.cs
  src/Backend/FluentCMS.Web.Api/Setup/Models/PluginTemplate.cs
  src/Backend/FluentCMS.Web.Api/Setup/SetupManager.cs
  src/FluentCMS/Template/AdminLayout.body.html
  src/FluentCMS/Template/manifest.json
  src/Frontend/FluentCMS.Web.ApiClients/GeneratedApiClients.cs
  src/Frontend/FluentCMS.Web.ApiClients/config.nswag
  src/Frontend/FluentCMS.Web.UI/Default.razor
  src/Frontend/FluentCMS.Web.UI/Default.razor.cs
  src/Frontend/FluentCMS.Web.UI/DynamicRendering/LayoutProcessor.cs
  src/Frontend/FluentCMS.Web.UI/MappingProfile.cs
  src/Frontend/FluentCMS.Web.UI/PageEditorForms.razor.cs
  src/Frontend/FluentCMS.Web.UI/PageEditorSidebar.razor
  src/Frontend/FluentCMS.Web.UI/PluginContainer.razor
  src/Frontend/FluentCMS.Web.UI/PluginContainer.razor.cs
  src/Frontend/FluentCMS.Web.UI/PluginsSection.razor
  src/Frontend/FluentCMS.Web.UI/PluginsSection.razor.cs
  src/Frontend/FluentCMS.Web.UI/ServiceExtensions.cs
  src/Frontend/FluentCMS.Web.UI/ViewContext.cs
  src/Frontend/Plugins/FluentCMS.Web.Plugins.Admin/Componenets/BasePlugin.cs
  src/Shared/ViewState.cs
Labels: enhancement

#1780 #1778 use tailwind cdn
  src/FluentCMS/Template/AdminLayout.body.html
  src/FluentCMS/Template/AuthLayout.body.html
  src/FluentCMS/Template/DefaultLayout.body.html
  src/FluentCMS/wwwroot/js/tailwind.cdn.js
  src/Frontend/FluentCMS.Web.UI.Components/Styles/tailwind.config.js
  src/Frontend/FluentCMS.Web.UI.Components/wwwroot/css/app.min.css
  src/Frontend/FluentCMS.Web.UI.Components/wwwroot/css/app.min.css.map
Labels: enhancement

#1786 Update MongoDB.Driver to 2.27.0 in FluentCMS project
  src/Backend/Repositories/FluentCMS.Repositories.MongoDB/FluentCMS.Repositories.MongoDB.csproj
Labels: enhancement

#1788 #1754 Fix edit user button
  src/Frontend/Plugins/FluentCMS.Web.Plugins.Admin/UserManagement/UserListPlugin.razor
Labels: bug

#1791 #1790 add crud actions for TextHTML Plugin
  src/Frontend/FluentCMS.Web.UI/Default.razor
  src/Frontend/FluentCMS.Web.UI/PageEditorForms.razor.cs
  src/Frontend/FluentCMS.Web.UI/PluginActionsForms.razor
  src/Frontend/FluentCMS.Web.UI/PluginActionsForms.razor.cs
  src/Frontend/FluentCMS.Web.UI/PluginContainerActions.razor
  src/Frontend/FluentCMS.Web.UI/PluginContainerActions.razor.cs
  src/Frontend/FluentCMS.Web.UI/wwwroot/css/plugin-actions.css
  src/Frontend/FluentCMS.Web.UI/wwwroot/js/plugin-actions.js
  src/Frontend/FluentCMS.Web.UI/wwwroot/js/sitebuilder.default.js
  src/Frontend/FluentCMS.Web.UI/wwwroot/js/sitebuilder.js
  src/Frontend/Plugins/FluentCMS.Web.Plugins.Contents.TextHTML/TextHTMLEditPlugin.razor.cs
  src/Frontend/Plugins/FluentCMS.Web.Plugins.Contents.TextHTML/TextHTMLViewPlugin.razor
  src/Frontend/Plugins/FluentCMS.Web.Plugins.Contents.TextHTML/TextHTMLViewPlugin.razor.cs
Labels: enhancement, plugin

#1794 #1793 Add Page and External links for rich text editor
  src/Frontend/FluentCMS.Web.UI.Components/Components/Form/FormRichTextEditor/FormRichTextEditor.razor
  src/Frontend/FluentCMS.Web.UI.Components/Components/Form/FormRichTextEditor/FormRichTextEditor.razor.cs
  src/Frontend/FluentCMS.Web.UI.Components/Components/Form/FormRichTextEditor/FormRichTextEditor.razor.js
  src/Frontend/FluentCMS.Web.UI.Components/Components/Form/FormRichTextEditor/FormRichTextEditor.razor.scss
  src/Frontend/FluentCMS.Web.UI.Components/Components/Modal/Modal.razor.scss
  src/Frontend/FluentCMS.Web.UI.Components/FluentCMS.Web.UI.Components.csproj
  src/Frontend/FluentCMS.Web.UI.Components/_GlobalUsings.cs
  src/Frontend/FluentCMS.Web.UI.Components/wwwroot/css/app.min.css
  src/Frontend/FluentCMS.Web.UI.Components/wwwroot/css/app.min.css.map
  src/Frontend/FluentCMS.Web.UI.Components/wwwroot/js/quill-image-resize.min.js
  src/Frontend/Plugins/FluentCMS.Web.Plugins.Contents.TextHTML/TextHTMLContent.cs
  src/Frontend/Plugins/FluentCMS.Web.Plugins.Contents.TextHTML/TextHTMLEditPlugin.razor
  src/Frontend/Plugins/FluentCMS.Web.Plugins.Contents.TextHTML/TextHTMLEditPlugin.razor.cs
Labels: enhancement

#1795 #1793 [RichTextEditor] add link to file and fix edit/delete link features
  src/Backend/FluentCMS.Web.Api/Controllers/FileController.cs
  src/Frontend/FluentCMS.Web.UI.Components/Components/Form/FormRichTextEditor/FormRichTextEditor.razor
  src/Frontend/FluentCMS.Web.UI.Components/Components/Form/FormRichTextEditor/FormRichTextEditor.razor.cs
  src/Frontend/FluentCMS.Web.UI.Components/Components/Form/FormRichTextEditor/FormRichTextEditor.razor.js
  src/Frontend/FluentCMS.Web.UI.Components/Components/Form/FormRichTextEditor/FormRichTextEditor.razor.scss
  src/Frontend/FluentCMS.Web.UI.Components/wwwroot/css/app.min.css
  src/Frontend/FluentCMS.Web.UI.Components/wwwroot/css/app.min.css.map
  src/Shared/AssetDetail.cs
Labels: enhancement

#1796 #1792 make column resizer wider and update responsive system
  src/Backend/FluentCMS.Entities/Sites/Plugin.cs
  src/Frontend/FluentCMS.Web.UI/wwwroot/css/columns.editor.css
  src/Frontend/FluentCMS.Web.UI/wwwroot/css/sitebuilder.css
  src/Frontend/FluentCMS.Web.UI/wwwroot/js/columns.js
Labels: enhancement

#1740 #1705 file selector UI
  src/.gitignore
  src/Backend/FluentCMS.Web.Api/Setup/SetupManager.cs
  src/FluentCMS/Template/manifest.json
  src/Frontend/FluentCMS.Web.UI.Components/Components/Form/FormRichTextEditor/FormRichTextEditor.razor.cs
  src/Frontend/FluentCMS.Web.UI.Components/_GlobalUsings.cs
  src/Frontend/FluentCMS.Web.UI/PluginActionsForms.razor.cs
  src/Frontend/Plugins/FluentCMS.Web.Plugins.Admin/ContentTypeManagement/Components/SingleFile/SingleFileFieldDataTableFile.razor
  src/Frontend/Plugins/FluentCMS.Web.Plugins.Admin/ContentTypeManagement/Components/SingleFile/SingleFileFieldDataTableFile.razor.cs
  src/Frontend/Plugins/FluentCMS.Web.Plugins.Admin/ContentTypeManagement/Components/SingleFile/SingleFileFieldFormFilePicker.razor
  src/Frontend/Plugins/FluentCMS.Web.Plugins.Admin/ContentTypeManagement/Components/SingleFile/SingleFileFieldFormFilePicker.razor.cs
  src/Frontend/Plugins/FluentCMS.Web.Plugins.Admin/ContentTypeManagement/Components/SingleFile/SingleFileFieldModel.cs
  src/Frontend/Plugins/FluentCMS.Web.Plugins.Admin/ContentTypeManagement/Components/SingleFile/SingleFileFieldSettings.razor
  src/Frontend/Plugins/FluentCMS.Web.Plugins.Admin/ContentTypeManagement/Components/SingleFile/SingleFilePickerModal.razor
  src/Frontend/Plugins/FluentCMS.Web.Plugins.Admin/ContentTypeManagement/Components/SingleFile/SingleFilePickerModal.razor.cs
  src/Frontend/Plugins/FluentCMS.Web.Plugins.Admin/ContentTypeManagement/Components/SingleFile/SingleFileTypeOptions.cs
  src/Frontend/Plugins/FluentCMS.Web.Plugins.Admin/ContentTypeManagement/Content/ContentUpdatePlugin.razor.cs
  src/Frontend/Plugins/FluentCMS.Web.Plugins.Admin/ContentTypeManagement/Models/FieldTypes.cs
  src/Frontend/Plugins/FluentCMS.Web.Plugins.Admin/ContentTypeManagement/Models/ModelHelpers.cs
  src/Frontend/Plugins/FluentCMS.Web.Plugins.Admin/FileManagement/AssetDetail.cs
  src/Frontend/Plugins/FluentCMS.Web.Plugins.Admin/FileManagement/FileListPlugin.razor
  src/Frontend/Plugins/FluentCMS.Web.Plugins.Contents.TextHTML/TextHTMLContent.cs
  src/Frontend/Plugins/FluentCMS.Web.Plugins.Contents.TextHTML/TextHTMLEditPlugin.razor.cs
  src/Frontend/Plugins/FluentCMS.Web.Plugins.Contents.TextHTML/TextHTMLViewPlugin.razor.cs
  src/Frontend/Plugins/FluentCMS.Web.Plugins.Contents.TextHTML/_GlobalUsings.cs
  src/Shared/AssetDetail.cs
  src/Shared/DictionaryJsonConverter.cs
Labels: enhancement

#1800 Refactor AuditableEntity inheritance
  src/Backend/FluentCMS.Entities/AuditableEntity.cs
Labels: enhancement

#1797 #1743 implement breadcrumbs and use in file list plugin
  src/Frontend/FluentCMS.Web.UI.Components/Components/Breadcrumb/Breadcrumb.razor
  src/Frontend/FluentCMS.Web.UI.Components/Components/Breadcrumb/Breadcrumb.razor.scss
  src/Frontend/FluentCMS.Web.UI.Components/Components/Breadcrumb/BreadcrumbItem.razor
  src/Frontend/FluentCMS.Web.UI.Components/Components/Breadcrumb/BreadcrumbItem.razor.cs
  src/Frontend/FluentCMS.Web.UI.Components/Components/Form/FormRichTextEditor/FormRichTextEditor.razor
  src/Frontend/FluentCMS.Web.UI.Components/Components/Form/FormRichTextEditor/FormRichTextEditor.razor.cs
  src/Frontend/FluentCMS.Web.UI.Components/Styles/App.scss
  src/Frontend/FluentCMS.Web.UI.Components/wwwroot/css/app.min.css
  src/Frontend/FluentCMS.Web.UI.Components/wwwroot/css/app.min.css.map
  src/Frontend/Plugins/FluentCMS.Web.Plugins.Admin/Componenets/Buttons/ActionButton.razor.cs
  src/Frontend/Plugins/FluentCMS.Web.Plugins.Admin/ContentTypeManagement/Components/MultiSelect/MultiSelectFieldDataTableBadges.razor
  src/Frontend/Plugins/FluentCMS.Web.Plugins.Admin/ContentTypeManagement/Components/MultiSelect/MultiSelectFieldFormAutocomplete.razor
  src/Frontend/Plugins/FluentCMS.Web.Plugins.Admin/ContentTypeManagement/Components/MultiSelect/MultiSelectFieldFormAutocomplete.razor.cs
  src/Frontend/Plugins/FluentCMS.Web.Plugins.Admin/ContentTypeManagement/Components/MultiSelect/MultiSelectFieldFormCheckboxes.razor
  src/Frontend/Plugins/FluentCMS.Web.Plugins.Admin/ContentTypeManagement/Components/MultiSelect/MultiSelectFieldFormCheckboxes.razor.cs
  src/Frontend/Plugins/FluentCMS.Web.Plugins.Admin/ContentTypeManagement/Components/MultiSelect/MultiSelectFieldSettings.razor
  src/Frontend/Plugins/FluentCMS.Web.Plugins.Admin/ContentTypeManagement/Components/Select/SelectFieldFormAutocomplete.razor
  src/Frontend/Plugins/FluentCMS.Web.Plugins.Admin/ContentTypeManagement/Components/Select/SelectFieldFormAutocomplete.razor.cs
  src/Frontend/Plugins/FluentCMS.Web.Plugins.Admin/ContentTypeManagement/Components/Select/SelectFieldFormRadioGroup.razor
  src/Frontend/Plugins/FluentCMS.Web.Plugins.Admin/ContentTypeManagement/Components/Select/SelectFieldFormRadioGroup.razor.cs
  src/Frontend/Plugins/FluentCMS.Web.Plugins.Admin/ContentTypeManagement/Components/Select/SelectFieldFormSelect.razor
  src/Frontend/Plugins/FluentCMS.Web.Plugins.Admin/ContentTypeManagement/Components/Select/SelectFieldFormSelect.razor.cs
  src/Frontend/Plugins/FluentCMS.Web.Plugins.Admin/ContentTypeManagement/Components/Select/SelectFieldModel.cs
  src/Frontend/Plugins/FluentCMS.Web.Plugins.Admin/ContentTypeManagement/Components/SingleFile/SingleFileFieldFormFilePicker.razor.cs
  src/Frontend/Plugins/FluentCMS.Web.Plugins.Admin/ContentTypeManagement/Components/SingleFile/SingleFilePickerModal.razor
  src/Frontend/Plugins/FluentCMS.Web.Plugins.Admin/ContentTypeManagement/Components/SingleFile/SingleFilePickerModal.razor.cs
  src/Frontend/Plugins/FluentCMS.Web.Plugins.Admin/ContentTypeManagement/Content/ContentListPlugin.razor.cs
  src/Frontend/Plugins/FluentCMS.Web.Plugins.Admin/ContentTypeManagement/Content/ContentUpdatePlugin.razor.cs
  src/Frontend/Plugins/FluentCMS.Web.Plugins.Admin/ContentTypeManagement/Models/ModelHelpers.cs
  src/Frontend/Plugins/FluentCMS.Web.Plugins.Admin/FileManagement/FileListPlugin.razor
  src/Frontend/Plugins/FluentCMS.Web.Plugins.Admin/FileManagement/FileListPlugin.razor.cs
  src/Frontend/Plugins/FluentCMS.Web.Plugins.Admin/FileManagement/Files/FileUpdateModal.razor.cs
  src/Frontend/Plugins/FluentCMS.Web.Plugins.Admin/FileManagement/Files/FileUploadModal.razor.cs
  src/Frontend/Plugins/FluentCMS.Web.Plugins.Admin/FileManagement/FolderBreadcrumbItemType.cs
  src/Frontend/Plugins/FluentCMS.Web.Plugins.Admin/FileManagement/FolderSelectOption.cs
  src/Frontend/Plugins/FluentCMS.Web.Plugins.Admin/FileManagement/Folders/FolderCreateModal.razor.cs
  src/Frontend/Plugins/FluentCMS.Web.Plugins.Admin/FileManagement/Folders/FolderUpdateModal.razor.cs
  src/Frontend/Plugins/FluentCMS.Web.Plugins.Admin/SiteManagement/SiteUpdatePlugin.razor
  src/Shared/AssetDetail.cs
Labels: enhancement

#1809 #1808 fix link of logo
  src/FluentCMS/Template/DefaultLayout.body.html
Labels: bug

#1807 Some Improvements
  src/Backend/FluentCMS.Services/ContentTypeService.cs
  src/Backend/FluentCMS.Services/UserService.cs
  src/Backend/FluentCMS.Web.Api/AuthContext.cs
  src/Backend/FluentCMS.Web.Api/Extentions/SwaggerServiceExtensions.cs
  src/Backend/FluentCMS.Web.Api/Models/ApiPagingResult.cs
  src/Backend/FluentCMS.Web.Api/Validation/SlugAttribute.cs
  src/Backend/Repositories/FluentCMS.Repositories.LiteDb/EntityRepository.cs
  src/Backend/Repositories/FluentCMS.Repositories.MongoDB/AuditableEntityRepository.cs
  src/Backend/Repositories/FluentCMS.Repositories.MongoDB/EntityRepository.cs
  src/FluentCMS/Program.cs
  src/Frontend/FluentCMS.Web.ApiClients/ApiClientException.cs
  src/Frontend/FluentCMS.Web.ApiClients/Services/AuthManager.cs
  src/Frontend/FluentCMS.Web.UI.Components/Base/BaseComponentHelpers.cs
  src/Frontend/FluentCMS.Web.UI.Components/Components/Accordion/Accordion.razor.cs
  src/Frontend/FluentCMS.Web.UI.Components/Components/Accordion/Accordion.razor.scss
  src/Frontend/FluentCMS.Web.UI.Components/Components/Confirm/Confirm.razor.cs
  src/Frontend/FluentCMS.Web.UI.Components/Components/Dropdown/Dropdown.razor.cs
  src/Frontend/FluentCMS.Web.UI.Components/Components/Modal/Modal.razor.cs
  src/Frontend/FluentCMS.Web.UI/PluginLoader/PluginLoader.cs
  src/Frontend/Plugins/FluentCMS.Web.Plugins.Admin/ContentTypeManagement/Content/ContentListPlugin.razor.cs
  src/Frontend/Plugins/FluentCMS.Web.Plugins.Admin/ContentTypeManagement/Models/FieldTypes.cs
  src/Shared/Exceptions/ExceptionCodes.cs
Labels: enhancement

#1817 Refactor and clean up Razor component files
  src/Frontend/FluentCMS.Web.UI.Components/Components/Form/FormAutocomplete/FormAutocompleteMultiple.razor.cs
  src/Frontend/Plugins/FluentCMS.Web.Plugins.Admin/FileManagement/FileListPlugin.razor.cs
Labels: enhancement

#1815 #1814 fix some admin panel issues
  src/FluentCMS/Template/AdminLayout.body.html
  src/FluentCMS/Template/DefaultLayout.body.html
  src/FluentCMS/Template/manifest.json
  src/Frontend/FluentCMS.Web.UI.Components/wwwroot/css/app.min.css.map
  src/Frontend/Plugins/FluentCMS.Web.Plugins.Admin/ApiTokenManagement/ApiTokenCreatePlugin.razor
  src/Frontend/Plugins/FluentCMS.Web.Plugins.Admin/ApiTokenManagement/ApiTokenListPlugin.razor
  src/Frontend/Plugins/FluentCMS.Web.Plugins.Admin/ApiTokenManagement/ApiTokenUpdatePlugin.razor
  src/Frontend/Plugins/FluentCMS.Web.Plugins.Admin/Componenets/PluginBody.razor
  src/Frontend/Plugins/FluentCMS.Web.Plugins.Admin/Componenets/PluginBody.razor.cs
  src/Frontend/Plugins/FluentCMS.Web.Plugins.Admin/ContentTypeManagement/Content/ContentListPlugin.razor
  src/Frontend/Plugins/FluentCMS.Web.Plugins.Admin/ContentTypeManagement/ContentType/Components/ContentTypeFieldDelete.razor
  src/Frontend/Plugins/FluentCMS.Web.Plugins.Admin/ContentTypeManagement/ContentType/ContentTypeListPlugin.razor
  src/Frontend/Plugins/FluentCMS.Web.Plugins.Admin/FileManagement/FileListPlugin.razor
  src/Frontend/Plugins/FluentCMS.Web.Plugins.Admin/LayoutManagement/LayoutListPlugin.razor
  src/Frontend/Plugins/FluentCMS.Web.Plugins.Admin/RoleManagement/RoleCreatePlugin.razor
  src/Frontend/Plugins/FluentCMS.Web.Plugins.Admin/RoleManagement/RoleListPlugin.razor
  src/Frontend/Plugins/FluentCMS.Web.Plugins.Admin/RoleManagement/RoleUpdatePlugin.razor
  src/Frontend/Plugins/FluentCMS.Web.Plugins.Admin/SiteManagement/SiteListPlugin.razor
  src/Frontend/Plugins/FluentCMS.Web.Plugins.Admin/SiteManagement/SiteUpdatePlugin.razor
Labels: enhancement

#1825 Update README.md
  README.md
Labels: documentation

#1832 #1831 make litedb as default database provider
  src/.gitignore
  src/FluentCMS/Config/appsettings.json
  src/FluentCMS/FluentCMS.csproj
  src/FluentCMS/Program.cs
Labels: enhancement

#1833 Update README.md
  README.md
Labels: documentation

#1827 #1826 Remove login button from DefaultLayout when user is logged in
  src/FluentCMS/Template/AdminLayout.body.html
  src/FluentCMS/Template/AuthLayout.body.html
  src/FluentCMS/Template/DefaultLayout.body.html
  src/FluentCMS/wwwroot/images/logo-dark.svg
  src/FluentCMS/wwwroot/images/logo.svg
Labels: enhancement

#1835 #1830 add Hint property for Form elements
  src/Frontend/FluentCMS.Web.UI.Components/Components/Form/BaseInput/BaseInput.cs
  src/Frontend/FluentCMS.Web.UI.Components/Components/Form/FormAutocomplete/FormAutocomplete.razor
  src/Frontend/FluentCMS.Web.UI.Components/Components/Form/FormAutocomplete/FormAutocompleteMultiple.razor
  src/Frontend/FluentCMS.Web.UI.Components/Components/Form/FormCheckbox/FormCheckbox.razor
  src/Frontend/FluentCMS.Web.UI.Components/Components/Form/FormCheckboxGroup/FormCheckboxGroup.razor
  src/Frontend/FluentCMS.Web.UI.Components/Components/Form/FormDateInput/FormDateInput.razor
  src/Frontend/FluentCMS.Web.UI.Components/Components/Form/FormField/FormField.razor
  src/Frontend/FluentCMS.Web.UI.Components/Components/Form/FormField/FormField.razor.cs
  src/Frontend/FluentCMS.Web.UI.Components/Components/Form/FormField/FormField.razor.scss
  src/Frontend/FluentCMS.Web.UI.Components/Components/Form/FormFileUpload/FormFileUpload.razor
  src/Frontend/FluentCMS.Web.UI.Components/Components/Form/FormFileUpload/FormFileUpload.razor.cs
  src/Frontend/FluentCMS.Web.UI.Components/Components/Form/FormInput/FormInput.razor
  src/Frontend/FluentCMS.Web.UI.Components/Components/Form/FormMarkdownEditor/FormMarkdownEditor.razor
  src/Frontend/FluentCMS.Web.UI.Components/Components/Form/FormNumberInput/FormNumberInput.razor
  src/Frontend/FluentCMS.Web.UI.Components/Components/Form/FormRadioGroup/FormRadioGroup.razor
  src/Frontend/FluentCMS.Web.UI.Components/Components/Form/FormRichTextEditor/FormRichTextEditor.razor
  src/Frontend/FluentCMS.Web.UI.Components/Components/Form/FormSelect/FormSelect.razor
  src/Frontend/FluentCMS.Web.UI.Components/Components/Form/FormSwitch/FormSwitch.razor
  src/Frontend/FluentCMS.Web.UI.Components/Components/Form/FormTextarea/FormTextarea.razor
  src/Frontend/FluentCMS.Web.UI.Components/Styles/App.scss
  src/Frontend/FluentCMS.Web.UI.Components/wwwroot/css/app.min.css
  src/Frontend/FluentCMS.Web.UI.Components/wwwroot/css/app.min.css.map
Labels: enhancement, component
