Repository fluentcms/FluentCMS, pull requests merged in 2024-04, with the labels that each got.

#974 930 remove app from UI
  src/FluentCMS.Web.UI/Helper.cs
  src/FluentCMS.Web.UI/Plugins/ContentManagement/ContentCreatePlugin.razor
  src/FluentCMS.Web.UI/Plugins/ContentManagement/ContentDetailPlugin.razor
  src/FluentCMS.Web.UI/Plugins/ContentManagement/ContentIndexPlugin.razor
  src/FluentCMS.Web.UI/Plugins/ContentManagement/ContentLayout.razor
  src/FluentCMS.Web.UI/Plugins/ContentManagement/ContentListPlugin.razor
  src/FluentCMS.Web.UI/Plugins/ContentManagement/ContentUpdatePlugin.razor
  src/FluentCMS.Web.UI/Plugins/ContentTypeManagement/ContentTypeCreatePlugin.razor
  src/FluentCMS.Web.UI/Plugins/ContentTypeManagement/ContentTypeDetailPlugin.razor
  src/FluentCMS.Web.UI/Plugins/ContentTypeManagement/ContentTypeListPlugin.razor
  src/FluentCMS.Web.UI/Plugins/ContentTypeManagement/ContentTypeUpdatePlugin.razor
  src/FluentCMS/Templates/Admin/AdminLayout.body.html
Labels: enhancement

#975 971 remove app from api e2e tests
  src/Tests/FluentCMS.E2eTests/Features/AppClient.feature
  src/Tests/FluentCMS.E2eTests/Features/AppClient.feature.cs
  src/Tests/FluentCMS.E2eTests/Features/ContentTypeClient.feature
  src/Tests/FluentCMS.E2eTests/Features/ContentTypeClient.feature.cs
  src/Tests/FluentCMS.E2eTests/Features/RoleClient.feature
  src/Tests/FluentCMS.E2eTests/Features/RoleClient.feature.cs
  src/Tests/FluentCMS.E2eTests/Features/SetupClient.feature.cs
  src/Tests/FluentCMS.E2eTests/Features/UserClient.feature.cs
  src/Tests/FluentCMS.E2eTests/StepDefinitions/Given/GivenIHaveAContentTypeUpdateRequest.cs
  src/Tests/FluentCMS.E2eTests/StepDefinitions/Given/GivenIHaveAppDetails.cs
  src/Tests/FluentCMS.E2eTests/StepDefinitions/Given/GivenIHaveAppUpdateRequest.cs
  src/Tests/FluentCMS.E2eTests/StepDefinitions/Given/GivenIHaveApps.cs
  src/Tests/FluentCMS.E2eTests/StepDefinitions/Given/GivenIHaveContentTypes.cs
  src/Tests/FluentCMS.E2eTests/StepDefinitions/Given/GivenIHaveRoles.cs
  src/Tests/FluentCMS.E2eTests/StepDefinitions/Tags/RequiresTestApp.cs
  src/Tests/FluentCMS.E2eTests/StepDefinitions/Then/ThenAppCreateResultShouldBeSuccess.cs
  src/Tests/FluentCMS.E2eTests/StepDefinitions/Then/ThenAppDeleteResultShouldBeSuccess.cs
  src/Tests/FluentCMS.E2eTests/StepDefinitions/Then/ThenAppGetAllResultShouldBeSuccess.cs
  src/Tests/FluentCMS.E2eTests/StepDefinitions/Then/ThenAppGetAllResultShouldHaveItems.cs
  src/Tests/FluentCMS.E2eTests/StepDefinitions/Then/ThenAppGetBySlugResultShouldBeSuccess.cs
  src/Tests/FluentCMS.E2eTests/StepDefinitions/Then/ThenAppUpdateResultShouldBeSuccess.cs
  src/Tests/FluentCMS.E2eTests/StepDefinitions/Then/ThenAppUpdateShouldMatchRequest.cs
  src/Tests/FluentCMS.E2eTests/StepDefinitions/Then/ThenIShouldNotSeeTheContentType.cs
  src/Tests/FluentCMS.E2eTests/StepDefinitions/Then/ThenIShouldNotSeeTheField.cs
  src/Tests/FluentCMS.E2eTests/StepDefinitions/Then/ThenIShouldSeeTheContentType.cs
  src/Tests/FluentCMS.E2eTests/StepDefinitions/Then/ThenIShouldSeeTheField.cs
  src/Tests/FluentCMS.E2eTests/StepDefinitions/When/WhenICreateAContentType.cs
  src/Tests/FluentCMS.E2eTests/StepDefinitions/When/WhenICreateApp.cs
  src/Tests/FluentCMS.E2eTests/StepDefinitions/When/WhenICreateRole.cs
  src/Tests/FluentCMS.E2eTests/StepDefinitions/When/WhenIDeleteAContentType.cs
  src/Tests/FluentCMS.E2eTests/StepDefinitions/When/WhenIDeleteAField.cs
  src/Tests/FluentCMS.E2eTests/StepDefinitions/When/WhenIDeleteApp.cs
  src/Tests/FluentCMS.E2eTests/StepDefinitions/When/WhenIDeleteRole.cs
  src/Tests/FluentCMS.E2eTests/StepDefinitions/When/WhenIGetAllApps.cs
  src/Tests/FluentCMS.E2eTests/StepDefinitions/When/WhenIGetAllContentTypes.cs
  src/Tests/FluentCMS.E2eTests/StepDefinitions/When/WhenIGetAllRoles.cs
  src/Tests/FluentCMS.E2eTests/StepDefinitions/When/WhenIGetAppBySlug.cs
  src/Tests/FluentCMS.E2eTests/StepDefinitions/When/WhenISetAField.cs
  src/Tests/FluentCMS.E2eTests/StepDefinitions/When/WhenIUpdateAContentType.cs
  src/Tests/FluentCMS.E2eTests/StepDefinitions/When/WhenIUpdateApp.cs
  src/Tests/FluentCMS.E2eTests/StepDefinitions/When/WhenIUpdateRoleTo.cs
Labels: enhancement

#980 979 remove app reference from `ContentIndexPlugin`
  src/FluentCMS.Web.UI/Plugins/ContentManagement/ContentIndexPlugin.razor
Labels: bug

#1009 #1006 code review & cleanup for base component
  src/FluentCMS.Web.UI.Components/Base/BaseComponent.cs
  src/FluentCMS.Web.UI.Components/Base/BaseComponentHelpers.cs
  src/FluentCMS.Web.UI.Components/Base/UISettings.cs
Labels: enhancement, component

#1011 #1010 Card component cleanup
  src/FluentCMS.Web.UI.Components/Components/Card/Card.cs
  src/FluentCMS.Web.UI.Components/Components/Card/Card.scss
Labels: enhancement, component

#1041 #1014 run code analyzer
  src/FluentCMS.Web.UI/Helper.cs
Labels: enhancement

#1123 feat: Add header for tabs component
  src/FluentCMS.Web.UI.Components/Components/Tabs/Tabs.scss
  src/FluentCMS.Web.UI.Components/Components/Tabs/TabsHeader.razor
  src/FluentCMS.Web.UI.ComponentsDocs/Pages/Components/TabsPage.razor
Labels: enhancement, component

#1121 1116 enable serverinteractive mode and interactive authentication 2
  src/FluentCMS.Web.Api/Controllers/SetupController.cs
  src/FluentCMS.Web.Api/Validation/DomainNameAttribute.cs
  src/FluentCMS.Web.ApiClients/GeneratedApiClients.cs
  src/FluentCMS.Web.ApiClients/config.nswag
  src/FluentCMS.Web.UI/App.razor
  src/FluentCMS.Web.UI/Default.razor
  src/FluentCMS.Web.UI/Default.razor.cs
  src/FluentCMS.Web.UI/Plugins/Auth/LoginViewPlugin.razor.cs
  src/FluentCMS.Web.UI/Plugins/BasePlugin.razor.cs
  src/FluentCMS.Web.UI/Plugins/Settings/SettingsViewPlugin.razor.cs
  src/FluentCMS.Web.UI/Plugins/Setup/SetupViewPlugin.razor.cs
  src/FluentCMS.Web.UI/Plugins/UserManagement/UserCreatePlugin.razor.cs
  src/FluentCMS.Web.UI/Plugins/UserManagement/UserDetailPlugin.razor.cs
  src/FluentCMS.Web.UI/Plugins/UserManagement/UserListPlugin.razor.cs
  src/FluentCMS.Web.UI/Plugins/UserManagement/UserUpdatePlugin.razor.cs
  src/FluentCMS.Web.UI/Routes.razor
  src/FluentCMS.Web.UI/Services/AdminUIServiceExtensions.cs
  src/FluentCMS.Web.UI/Services/ApiClientServiceExtensions.cs
  src/FluentCMS.Web.UI/Services/AuthService.cs
  src/FluentCMS.Web.UI/Services/AuthStateProvider.cs
  src/FluentCMS.Web.UI/Services/AuthenticationStateHelper.cs
  src/FluentCMS.Web.UI/Services/HttpClientFactoryHelper.cs
  src/FluentCMS.Web.UI/Services/SetupManager.cs
  src/FluentCMS/SiteServiceExtensions.cs
Labels: enhancement

#1129 refactor: clean up `Default.razor.cs`
  src/FluentCMS.Web.UI/Default.razor.cs
  src/FluentCMS.Web.UI/Services/AdminUIServiceExtensions.cs
  src/FluentCMS.Web.UI/Services/ErrorMessageExtension.cs
Labels: enhancement

#1108 fix: ensure `cancellationToken` is available on all actions for `UserController`
  src/FluentCMS.Web.Api/Controllers/AccountController.cs
Labels: enhancement

#1160 1159 implement an attribute to simplify authorizing endpoints
  src/FluentCMS.Web.Api/Attributes/JwtAuthorize.cs
  src/FluentCMS.Web.Api/AuthContext.cs
  src/FluentCMS.Web.Api/Controllers/AccountController.cs
  src/FluentCMS.Web.Api/Controllers/ContentController.cs
  src/FluentCMS.Web.Api/Controllers/ContentTypeController.cs
  src/FluentCMS.Web.Api/Controllers/GlobalSettingsController.cs
  src/FluentCMS.Web.Api/Controllers/PageController.cs
  src/FluentCMS.Web.Api/Controllers/PluginController.cs
  src/FluentCMS.Web.Api/Controllers/PluginDefinitionController.cs
  src/FluentCMS.Web.Api/Controllers/RoleController.cs
  src/FluentCMS.Web.Api/Controllers/SiteController.cs
Labels: enhancement

#1174 1042 use another strategy and replace extendederrorboundary
  src/FluentCMS.Web.UI/Components/PluginContainer.razor
  src/FluentCMS.Web.UI/Components/PluginContainer.razor.cs
  src/FluentCMS.Web.UI/Components/Section.razor
  src/FluentCMS.Web.UI/Plugins/ContentManagement/ContentIndexPlugin.razor
  src/FluentCMS.Web.UI/Plugins/ContentManagement/ContentLayout.razor
  src/FluentCMS.Web.UI/Plugins/ContentTypeManagement/ContentTypeListPlugin.razor
  src/FluentCMS.Web.UI/Plugins/PluginForm.razor
  src/FluentCMS.Web.UI/Plugins/PluginForm.razor.cs
  src/FluentCMS.Web.UI/Plugins/UserManagement/UserCreatePlugin.razor
  src/FluentCMS.Web.UI/Plugins/UserManagement/UserCreatePlugin.razor.cs
  src/FluentCMS.Web.UI/_Imports.razor
Labels: enhancement, plugin

#1177 1175 error handling enhancement for api client
  src/FluentCMS.Web.Api/Controllers/AccountController.cs
  src/FluentCMS.Web.Api/Controllers/PluginDefinitionController.cs
  src/FluentCMS.Web.Api/Extentions/ApiServiceExtensions.cs
  src/FluentCMS.Web.ApiClients/ApiClientException.cs
  src/FluentCMS.Web.UI/Plugins/PluginForm.razor
  src/FluentCMS.Web.UI/Plugins/PluginForm.razor.cs
Labels: enhancement

#1131 1130 Review user management plugins
  src/FluentCMS.Web.Api/Controllers/AccountController.cs
  src/FluentCMS.Web.UI/Plugins/UserManagement/UserDetailPlugin.razor
  src/FluentCMS.Web.UI/Plugins/UserManagement/UserListPlugin.razor
  src/FluentCMS.Web.UI/Plugins/UserManagement/UserUpdatePlugin.razor
  src/FluentCMS.Web.UI/Plugins/UserManagement/UserUpdatePlugin.razor.cs
Labels: plugin

#1192 refactor: sync `AuthContext` and `AuthService` claims
  src/FluentCMS.Services/UserService.cs
  src/FluentCMS.Services/UserTokenProvider.cs
  src/FluentCMS.Shared/IAuthContext.cs
  src/FluentCMS.Web.Api/AuthContext.cs
Labels: bug

#1195 1122 implement sample authorization mechanism to account user setup and role controllers
  src/FluentCMS.Entities/Policy.cs
  src/FluentCMS.Entities/Role.cs
  src/FluentCMS.Services/RoleService.cs
  src/FluentCMS.Services/UserService.cs
  src/FluentCMS.Shared/Exceptions/ExceptionCodes.cs
  src/FluentCMS.Shared/FluentCMS.Shared.csproj
  src/FluentCMS.Shared/IAuthContext.cs
  src/FluentCMS.Web.Api/Attributes/PolicyAttribute.cs
  src/FluentCMS.Web.Api/AuthContext.cs
  src/FluentCMS.Web.Api/Controllers/AccountController.cs
  src/FluentCMS.Web.Api/Controllers/BaseController.cs
  src/FluentCMS.Web.Api/Controllers/ContentController.cs
  src/FluentCMS.Web.Api/Controllers/ContentTypeController.cs
  src/FluentCMS.Web.Api/Controllers/GlobalSettingsController.cs
  src/FluentCMS.Web.Api/Controllers/PageController.cs
  src/FluentCMS.Web.Api/Controllers/PluginController.cs
  src/FluentCMS.Web.Api/Controllers/PluginDefinitionController.cs
  src/FluentCMS.Web.Api/Controllers/RoleController.cs
  src/FluentCMS.Web.Api/Controllers/SetupController.cs
  src/FluentCMS.Web.Api/Controllers/SiteController.cs
  src/FluentCMS.Web.Api/Controllers/UserController.cs
  src/FluentCMS.Web.Api/Models/BaseAuditableResponse.cs
  src/FluentCMS.Web.Api/Models/Content/ContentCreateRequest.cs
  src/FluentCMS.Web.Api/Models/Content/ContentDetailResponse.cs
  src/FluentCMS.Web.Api/Models/ContentType/ContentTypeCreateRequest.cs
  src/FluentCMS.Web.Api/Models/ContentType/ContentTypeDetailResponse.cs
  src/FluentCMS.Web.Api/Models/ContentType/ContentTypeUpdateRequest.cs
  src/FluentCMS.Web.Api/Models/Roles/RoleCreateRequest.cs
  src/FluentCMS.Web.Api/Models/Roles/RoleDetailResponse.cs
  src/FluentCMS.Web.Api/Models/Setup/SetupRequest.cs
  src/FluentCMS.Web.Api/Models/Users/UserCreateRequest.cs
  src/FluentCMS.Web.Api/Models/Users/UserLoginRequest.cs
  src/FluentCMS.Web.Api/Models/Users/UserRegisterRequest.cs
  src/FluentCMS.Web.Api/Models/Users/UserSendPasswordResetTokenRequest.cs
  src/FluentCMS.Web.Api/Models/Users/UserUpdateRequest.cs
  src/FluentCMS.Web.Api/Models/Users/UserValidatePasswordResetTokenRequest.cs
  src/FluentCMS.Web.Api/Models/_GlobalUsings.cs
  src/FluentCMS.Web.Api/Validation/DomainNameAttribute.cs
  src/FluentCMS.Web.Api/Validation/SlugAttribute.cs
  src/FluentCMS.Web.ApiClients/GeneratedApiClients.cs
  src/FluentCMS.Web.ApiClients/config.nswag
Labels: enhancement

#1193 1154 review Login & Register
  src/FluentCMS.Web.Api/Models/Users/UserLoginRequest.cs
  src/FluentCMS.Web.ApiClients/GeneratedApiClients.cs
  src/FluentCMS.Web.UI/Plugins/Auth/LoginViewPlugin.razor
  src/FluentCMS.Web.UI/Plugins/Auth/LoginViewPlugin.razor.cs
  src/FluentCMS.Web.UI/Plugins/Auth/RegisterViewPlugin.razor
  src/FluentCMS.Web.UI/Plugins/Auth/RegisterViewPlugin.razor.cs
Labels: plugin

#1194 `ForgotPasswordViewPlugin` & `ResetPasswordViewPlugin` functionality review
  src/FluentCMS.Web.UI/Plugins/Auth/ForgotPasswordViewPlugin.razor
  src/FluentCMS.Web.UI/Plugins/Auth/ForgotPasswordViewPlugin.razor.cs
  src/FluentCMS.Web.UI/Plugins/Auth/ResetPasswordViewPlugin.razor
  src/FluentCMS.Web.UI/Plugins/Auth/ResetPasswordViewPlugin.razor.cs
Labels: plugin

#1198 #1197 ApiClients updated
  src/FluentCMS.Web.ApiClients/GeneratedApiClients.cs
  src/FluentCMS.Web.ApiClients/config.nswag
Labels: enhancement
